import fs from 'node:fs';import path from 'node:path';import {stringifyYaml} from '../core/yaml.mjs';import {validateWorkspace} from '../core/index.mjs';
import { readDistJson } from '../core/runtime-root.mjs';
export function makeExample(root){
 if(fs.existsSync(root))throw Error('Example destination must be new');
 const write=(p,v)=>{const file=path.join(root,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof v==='string'?v:stringifyYaml(v));};
 write('workspace.yaml',{schema:'work/workspace@1',id:'example-expandable-work'});write('.gitignore','_local/\n_workflows/\n');
 for(const [name,source]of [['work.schema','work.schema'],['work-layout','work-layout']])write('_schema/'+name+'.yaml',readDistJson('schemas',source+'.json'));
 const defs=[['vps','business',false],['vps/create','business',false],['vps/create/business','business',false],['vps/create/business/rules','business',true],['vps/create/business/actors','business',true],['vps/create/business/states','business',true],['vps/create/business/flows','business',true],['vps/create/business/acceptance','business',true],['vps/create/architecture','architecture',false],['vps/create/architecture/services','architecture',true],['vps/create/architecture/contracts','architecture',true],['vps/create/architecture/data','architecture',true],['vps/create/architecture/patterns','architecture',true],['vps/create/architecture/security','architecture',true],['vps/create/architecture/recovery','architecture',true],['vps/create/architecture/code','implementation',true],['vps/create/architecture/verification','verification',true]];
 for(const [dir,kind,leaf]of defs){const name=dir.split('/').at(-1).replaceAll('-',' ');const meta={schema:'work/node@2',id:dir.replaceAll('/','.'),kind,required:true,description:name[0].toUpperCase()+name.slice(1)+'. Describe the selected scope, decisions, exclusions, and observable acceptance here. This synthetic example claims no investigation, implementation, or acceptance.'};if(leaf){meta.state='uninvestigate';meta.activity='idle';meta.assertions=['reviewed-scope','verified-outcome'];}write(dir+'/index.yaml',meta);}
 const result=validateWorkspace(root);if(!result.ok)throw Error(JSON.stringify(result.errors));return {ok:true,nodes:result.nodes.length,root,synthetic:true};
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(import.meta.filename))console.log(JSON.stringify(makeExample(path.resolve(process.argv[2]))));
