/** The package's one public entry: everything the apps of the product share, client-safe (server-only readers avoid Node built-ins at module scope). */
export { GlobalErrorBoundary } from "./components/composites/GlobalErrorBoundary"
export { LocaleErrorBoundary } from "./modules/boundaries/LocaleErrorBoundary"
export { LocaleLoading } from "./modules/boundaries/LocaleLoading"
export { LocaleNotFound } from "./modules/boundaries/LocaleNotFound"
export { LocaleShell } from "./components/composites/LocaleShell"
export { SlotView } from "./components/composites/SlotView"
export { CatalogueTile } from "./components/leaves/CatalogueTile"
export { DuckMascot } from "./components/leaves/DuckMascot"
export { StateBlock } from "./components/leaves/StateBlock"
export { formatPrice } from "./modules/money"
export { readProjectedPorts } from "./modules/config/projection"
export { PRODUCT_TIME_ZONE } from "./modules/i18n/config"
export { withCommonMessages } from "./modules/i18n/catalog"
export { usePathname, useRouter } from "./modules/i18n/navigation"
export { routing } from "./modules/i18n/routing"
export { collectionSlot, type Slot } from "./modules/slot"
