// readme-blocks.mjs - the generated blocks of knowledge/hfs/README.md (RT_GENERATED_BLOCK_STALE, rule R194).
// The app map (section 4), the back-end source tree (5.1), the tier matrix (5.2), the front-end source tree (6.1) and the rule catalog (12) are rendered from
// knowledge/hfs/slots.yaml and knowledge/hfs/rules.yaml between the markers
//   <!-- hfs:generated NAME -->  ...  <!-- hfs:generated-end NAME -->
// and compared byte for byte; the README never restates them by hand. `node scripts/hfs/readme-blocks.mjs --write` rewrites the
// blocks, `--check` (the default) lists the stale ones.
import fs from 'node:fs';
import path from 'node:path';
import { skillRoot } from '../../engine/runtime-root.mjs';
import { isMain } from '../lib/is-main.mjs';
import { loadRuleCatalog, loadSlotManifest } from './slots.mjs';

export const README = 'knowledge/hfs/README.md';
export const BLOCKS = Object.freeze(['app-map', 'be-tree', 'be-tiers', 'fe-tree', 'rules']);
const open = (name) => `<!-- hfs:generated ${name} -->`;
const close = (name) => `<!-- hfs:generated-end ${name} -->`;
const PROFILE_ORDER = ['app', 'be', 'fe', 'repo'];
const PROFILE_ROOT = { app: '', be: 'be/', fe: 'fe/', repo: '`be/` and `fe/` ' };

const cell = (text) => String(text).replace(/\|/g, '\\|');
const state = (slot) => [slot.presence, slot.tracked, slot.managedBy ? `generated by hfs sync (${slot.managedBy})` : null, slot.appKind ? `app kind ${slot.appKind}` : null, slot.trigger ? `trigger ${slot.trigger}` : null, slot.minInstances ? `at least ${slot.minInstances}` : null]
  .filter(Boolean).join(', ');
const slotPath = (slot) => `${slot.profiles.length === 1 ? PROFILE_ROOT[slot.profiles[0]] ?? '' : ''}${slot.path}`;

/** The app map: one row per slot, grouped by profile (app root, be, fe, repo = both sides), in manifest order. */
function appMap(manifest) {
  const rows = ['| Path | State | Slot |', '| --- | --- | --- |'];
  const profile = (slot) => PROFILE_ORDER.indexOf(slot.profiles[0]);
  const ordered = manifest.slots.map((slot, index) => ({ slot, index })).sort((a, b) => profile(a.slot) - profile(b.slot) || a.index - b.index);
  for (const { slot } of ordered) {
    const note = slot.goesTo ? `; ${slot.goesTo}` : '';
    rows.push(`| \`${cell(slotPath(slot))}\` | ${cell(state(slot))}${cell(note)} | \`${slot.id}\` |`);
  }
  return rows.join('\n');
}

/** The source tree of one side: the paths of its slots with their presence and slot id, one line each. */
const tree = (side) => (manifest) => {
  const slots = manifest.slots.filter((slot) => slot.profiles.includes(side) && slot.presence !== 'forbidden');
  const width = Math.max(...slots.map((slot) => slot.path.length + side.length + 1)) + 2;
  const lines = slots.map((slot) => `${side}/${slot.path}`.padEnd(width) + `${slot.presence.padEnd(9)} ${slot.id}`);
  return ['```text', ...lines, '```'].join('\n');
};

/** The tier matrix of the back end: from (row) to (column) — `yes`, `yes, acyclic` inside the tier, `no`. */
function beTiers(manifest) {
  const tiers = Object.keys(manifest.tiers.be);
  const rows = [`| From \\ to | ${tiers.join(' | ')} |`, `| --- | ${tiers.map(() => '---').join(' | ')} |`];
  for (const from of tiers) {
    const rule = manifest.tiers.be[from];
    rows.push(`| ${from} | ${tiers.map((to) => (rule.mayImport.includes(to) ? (to === from && rule.acyclic ? 'yes, acyclic' : 'yes') : 'no')).join(' | ')} |`);
  }
  return rows.join('\n');
}

/** The rule catalog: `| id | code | law | scope |` per rule (scope `runtime` for a rule that governs this repository itself). */
function rules(_manifest, catalog) {
  return ['| Id | Code | Law | Scope |', '| --- | --- | --- | --- |', ...catalog.rules.map((rule) => `| ${rule.id} | \`${rule.code}\` | ${cell(rule.law)} | ${rule.scope ?? 'product'} |`)].join('\n');
}

const RENDER = { 'app-map': appMap, 'be-tree': tree('be'), 'be-tiers': beTiers, 'fe-tree': tree('fe'), rules };

/** The rendered text of one block. */
export const renderBlock = (name, manifest, catalog) => RENDER[name](manifest, catalog);

/** The names of the blocks whose text in `readme` is missing, has no markers or differs from the render. */
export function staleBlocks(readme, manifest, catalog) {
  return BLOCKS.filter((name) => {
    const a = readme.indexOf(open(name));
    const b = readme.indexOf(close(name));
    if (a < 0 || b < a) return true;
    return readme.slice(a + open(name).length, b) !== `\n${renderBlock(name, manifest, catalog)}\n`;
  });
}

/** `readme` with every block that has markers rewritten to its render. */
export function writeBlocks(readme, manifest, catalog) {
  let out = readme;
  for (const name of BLOCKS) {
    const a = out.indexOf(open(name));
    const b = out.indexOf(close(name));
    if (a < 0 || b < a) continue;
    out = `${out.slice(0, a + open(name).length)}\n${renderBlock(name, manifest, catalog)}\n${out.slice(b)}`;
  }
  return out;
}

if (isMain(import.meta.url)) {
  const root = skillRoot;
  const manifest = loadSlotManifest({ root });
  const catalog = loadRuleCatalog({ root });
  const file = path.join(root, README);
  const text = fs.readFileSync(file, 'utf8');
  if (process.argv.includes('--write')) { fs.writeFileSync(file, writeBlocks(text, manifest, catalog)); process.stdout.write('README blocks written\n'); }
  else {
    const stale = staleBlocks(text, manifest, catalog);
    process.stdout.write(stale.length ? `stale: ${stale.join(', ')}\n` : 'README blocks current\n');
    process.exitCode = stale.length ? 1 : 0;
  }
}
