export { TaskModule } from './task.module';
export { TaskRepository } from './task.repository';
export { TaskRecord } from './task-record.types';
export { TaskForbiddenException, TaskNotFoundException, TaskTitleRequiredException } from './task.exception';
export { OwnershipGuard } from './ownership.guard';
export { TaskCreationPolicy } from './creation-policy.contracts';
export type { TaskCreationPolicyResult, CreateTaskPrincipalParams, CreateTaskInputParams } from './creation-policy.contracts';
export { TaskCreationPolicyRegistry } from './creation-policy.providers';
export { CompletionAuthority, OwnerOnlyCompletionAuthority } from './completion-authority.contracts';
export type { CompletionAction } from './completion-authority.contracts';
export { CompletionAuthorityRegistry } from './completion-authority.providers';
