import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

/**
 * The app's generated code, the one step behind `npm run codegen` (lint, typecheck, dev and build run it first).
 *
 * Each front-end app keeps its GraphQL documents in `.graphql` files next to the module that owns the call. For every app
 * below, this script reads each document under the app's `src/`, keys it by its operation name and writes the typed table
 * the transport client sends to the app's gitignored `__generated__/` folder.
 */

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const APPS = [{ dir: "fe/apps/shop", output: "src/modules/services/__generated__/documents.ts" }]
const OPERATION = /^\s*(?:query|mutation)\s+([A-Za-z_][A-Za-z0-9_]*)/m

/** Every `.graphql` file under a directory, in a stable order. */
const documentFiles = (directory) =>
    fs
        .readdirSync(directory, { withFileTypes: true })
        .flatMap((entry) => {
            const full = path.join(directory, entry.name)
            if (entry.isDirectory()) return entry.name === "__generated__" ? [] : documentFiles(full)
            return entry.name.endsWith(".graphql") ? [full] : []
        })
        .sort()

/** Writes the document table of the app at `dir` to `output` (relative to the app). */
const generate = ({ dir, output }) => {
    const sourceRoot = path.join(APP_ROOT, dir, "src")
    const documents = new Map()
    for (const file of documentFiles(sourceRoot)) {
        const text = fs.readFileSync(file, "utf8").trim()
        const match = OPERATION.exec(text)
        if (match === null) throw new Error(`${path.relative(sourceRoot, file)} names no query or mutation`)
        if (documents.has(match[1])) throw new Error(`operation ${match[1]} is declared twice`)
        documents.set(match[1], text.replace(/\s+/g, " "))
    }
    const body = [...documents].map(([name, text]) => `    ${name}: ${JSON.stringify(text)},`).join("\n")
    const target = path.join(APP_ROOT, dir, output)
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(
        target,
        `/** Generated by codegen from the \`.graphql\` documents; never edited by hand. */\nexport const DOCUMENTS = {\n${body}\n} as const\n\n/** The operations the client can send. */\nexport type OperationName = keyof typeof DOCUMENTS\n`,
    )
}

for (const app of APPS) generate(app)
