// git-hooks.spec.mjs - the git hooks of the runtime repository (scripts/guards/git-hooks.mjs): the rendered files, their install
// into <git common dir>/hooks, and the push gate they carry, run with `sh` in a temp git repository exactly as git runs it:
// stdin lines `<local ref> <local sha> <remote ref> <remote sha>`; refs/backup/* is allowed; main is allowed fast-forward (every main push starts CI);
// a v* tag only when HEAD carries an annotated v tag and the release cut recorded the full suite of HEAD (<git common dir>/starci-release/<HEAD sha>.l4.json);
// anything else, a non-fast-forward main and a delete, is refused with RIGHTS_PUSH_NOT_RELEASE.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { GIT_HOOKS_MARKER, HOOK_NAMES, installGitHooks, renderRuntimeHooks } from '../../scripts/guards/git-hooks.mjs';
import { WORK_HOOK_MARKER, ensureWorkHook } from '../../scripts/guards/hook-install.mjs';
import { mkdtemp } from '../helpers/tmpdir.mjs';

for (const key of ['GIT_DIR', 'GIT_COMMON_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_OBJECT_DIRECTORY', 'GIT_CONFIG_PARAMETERS', 'GIT_CONFIG_COUNT', 'GIT_PREFIX']) delete process.env[key];

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const ZERO = '0'.repeat(40);
const git = (cwd, args) => spawnSync('git', args, { cwd, encoding: 'utf8' });
const gitOk = (cwd, args) => { const r = git(cwd, args); assert.equal(r.status, 0, `git ${args.join(' ')}: ${r.stderr}`); return r.stdout.trim(); };
const gitExecPath = gitOk(ROOT, ['--exec-path']);
const SH = process.platform === 'win32' && fs.existsSync(path.resolve(gitExecPath, '..', '..', '..', 'bin', 'sh.exe'))
  ? path.resolve(gitExecPath, '..', '..', '..', 'bin', 'sh.exe') : 'sh';

/** A temp repository with one commit, the generated hooks installed, and a bare remote nobody pushes to. */
function repoWithHooks(t) {
  const repo = path.join(mkdtemp(t, 'starci-git-hooks-'), 'repo');
  fs.mkdirSync(repo);
  for (const args of [['init', '-q', '-b', 'main'], ['config', 'user.email', 't@t'], ['config', 'user.name', 't'], ['config', 'commit.gpgsign', 'false'], ['config', 'tag.gpgsign', 'false']]) gitOk(repo, args);
  fs.writeFileSync(path.join(repo, 'a.mjs'), 'export const a = 1;\n');
  gitOk(repo, ['add', '.']);
  gitOk(repo, ['commit', '-q', '-m', 'base']);
  const installed = installGitHooks({ root: repo });
  assert.equal(installed.ok, true);
  return { repo, head: gitOk(repo, ['rev-parse', 'HEAD']), hooksDir: installed.hooksDir };
}

const record = (repo, head, body) => {
  const dir = path.join(repo, '.git', 'starci-release');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, `${head}.l4.json`), typeof body === 'string' ? body : `${JSON.stringify({ schema: 'starci/l4-record@1', head, tag: 'v1.0.0', logs: [], ...body }, null, 2)}\n`);
};

/** Run the generated pre-push hook of `repo` (from `cwd`) with `lines` on stdin the way git does; sh -e like husky's dispatcher. */
const push = (repo, lines, cwd = repo) => {
  const r = spawnSync(SH, ['-e', path.join(repo, '.git', 'hooks', 'pre-push'), 'origin', 'url'], { cwd, encoding: 'utf8', input: lines.map((l) => `${l}\n`).join('') });
  const stderr = r.stderr ?? String(r.error?.message ?? '');
  return { status: r.status, refusals: stderr.split('\n').filter((l) => l.startsWith('RIGHTS_PUSH_NOT_RELEASE')), stderr };
};
const refLine = (remoteRef, local = 'HEAD', sha = 'a'.repeat(40)) => `${local} ${sha} ${remoteRef} ${ZERO}`;

test('renderRuntimeHooks: the push gate is the app template with a generator header, the commit gate is L0 only', () => {
  const hooks = renderRuntimeHooks({ root: ROOT });
  assert.deepEqual(Object.keys(hooks).sort(), [...HOOK_NAMES].sort());
  const template = fs.readFileSync(path.join(ROOT, 'packages', 'hfs', 'templates', 'app', 'hooks', 'husky', 'pre-push'), 'utf8');
  const rest = template.slice(template.indexOf('\n') + 1);
  for (const [name, text] of Object.entries(hooks)) {
    assert.ok(text.startsWith('#!/bin/sh\n# Generated by the StarCi runtime'), name);
    assert.ok(text.includes(GIT_HOOKS_MARKER), name);
    assert.doesNotMatch(text, /\{\{|\r/, `${name}: no placeholder, LF only`);
  }
  const push = hooks['pre-push'];
  assert.ok(push.includes(rest.slice(rest.indexOf('release_gate() {'), rest.indexOf('while read'))), 'the release gate function is the template one');
  assert.ok(push.endsWith(rest.slice(rest.indexOf('      release_gate\n'))), 'the tag branch and the fallback are the template ones');
  assert.ok(push.includes('refs/heads/main)\n') && push.includes('git merge-base --is-ancestor'), 'main is judged by fast-forward');
  assert.match(hooks['pre-commit'], /git diff --cached --check/);
  assert.match(hooks['pre-commit'], /node --check/);
  assert.ok(hooks['pre-commit'].includes(WORK_HOOK_MARKER), 'the generated commit hook chains the work guard');
  assert.doesNotMatch(hooks['pre-commit'], /npm |jest|typecheck|test:/, 'no test run, no typecheck at the commit gate');
});

test('renderRuntimeHooks refuses a push template that lost its header line', (t) => {
  const root = mkdtemp(t, 'starci-git-hooks-root-');
  const dir = path.join(root, 'packages', 'hfs', 'templates', 'app', 'hooks', 'husky');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'pre-push'), 'exit 0\n');
  assert.throws(() => renderRuntimeHooks({ root }), /no \{\{header\}\} line/);
});

test('installGitHooks writes both hooks executable into the git common dir, rewrites a stale generated hook and leaves a foreign one', (t) => {
  const { repo, hooksDir } = repoWithHooks(t);
  const rendered = renderRuntimeHooks({ root: ROOT });
  assert.equal(path.resolve(hooksDir), path.resolve(repo, '.git', 'hooks'));
  for (const name of HOOK_NAMES) {
    assert.equal(fs.readFileSync(path.join(hooksDir, name), 'utf8'), rendered[name], name);
    if (process.platform !== 'win32') assert.equal(fs.statSync(path.join(hooksDir, name)).mode & 0o111, 0o111, `${name} is executable`);
  }
  assert.deepEqual(installGitHooks({ root: repo }).hooks.map((h) => h.state), ['current', 'current']);
  fs.writeFileSync(path.join(hooksDir, 'pre-push'), `#!/bin/sh\n# ${GIT_HOOKS_MARKER} old\nexit 0\n`);
  fs.writeFileSync(path.join(hooksDir, 'pre-commit'), '#!/bin/sh\necho mine\n');
  const again = installGitHooks({ root: repo });
  assert.deepEqual(again.hooks.map((h) => [h.name, h.state]), [['pre-commit', 'foreign'], ['pre-push', 'updated']]);
  assert.equal(fs.readFileSync(path.join(hooksDir, 'pre-commit'), 'utf8'), '#!/bin/sh\necho mine\n', 'a foreign hook is never overwritten');
  assert.equal(git(repo, ['config', '--get', 'core.hooksPath']).status, 1, 'git config is not edited');
});

test('installGitHooks owns the single pre-commit, migrates the work hook, and ensureWorkHook leaves the generated chain unchanged', (t) => {
  const { repo, hooksDir } = repoWithHooks(t);
  const file = path.join(hooksDir, 'pre-commit');
  fs.rmSync(file);
  assert.equal(ensureWorkHook(repo, { skillRoot: ROOT }).changed, true);
  assert.ok(fs.readFileSync(file, 'utf8').includes(WORK_HOOK_MARKER));

  const installed = installGitHooks({ root: repo });
  assert.deepEqual(installed.hooks.map((h) => [h.name, h.state]), [['pre-commit', 'updated'], ['pre-push', 'current']]);
  const chained = fs.readFileSync(file, 'utf8');
  assert.ok(chained.includes(GIT_HOOKS_MARKER));
  assert.ok(chained.includes(WORK_HOOK_MARKER));
  assert.deepEqual(ensureWorkHook(repo, { skillRoot: ROOT }), { installed: true, path: file, changed: false });
  assert.equal(fs.readFileSync(file, 'utf8'), chained, 'the dispatch path never replaces the generated hook');
  assert.equal(installGitHooks({ root: repo }).hooks.find((h) => h.name === 'pre-commit').state, 'current');
});

test('installGitHooks from a linked worktree writes the common hooks dir; outside a checkout it reports', (t) => {
  const { repo } = repoWithHooks(t);
  const wt = path.join(path.dirname(repo), 'wt');
  gitOk(repo, ['worktree', 'add', '-q', '-b', 'side', wt]);
  fs.rmSync(path.join(repo, '.git', 'hooks', 'pre-push'));
  const result = installGitHooks({ root: wt });
  assert.equal(path.resolve(result.hooksDir), path.resolve(repo, '.git', 'hooks'));
  assert.equal(result.hooks.find((h) => h.name === 'pre-push').state, 'installed');
  const plain = mkdtemp(t, 'starci-git-hooks-plain-');
  assert.deepEqual(installGitHooks({ root: plain }), { ok: false, reason: 'not-a-git-checkout', hooksDir: null, hooks: [] });
});

test('installGitHooks takes an injected fs and an explicit hooks dir', () => {
  const written = [];
  const fake = {
    readFileSync: (file, enc) => fs.readFileSync(file, enc),
    existsSync: () => false,
    mkdirSync: () => {},
    writeFileSync: (file, body, opts) => written.push({ file, body, opts }),
    renameSync: (from, to) => written.push({ renamed: to }),
    chmodSync: () => {},
  };
  const result = installGitHooks({ root: ROOT, hooksDir: path.join('virtual', 'hooks'), fs: fake });
  assert.deepEqual(result.hooks.map((h) => h.state), ['installed', 'installed']);
  assert.equal(written.filter((w) => w.renamed).length, 2);
  assert.ok(written.filter((w) => w.body).every((w) => w.opts.mode === 0o755));
});

test('the push gate allows refs/backup/* and an empty push with no release', (t) => {
  const { repo } = repoWithHooks(t);
  assert.deepEqual(push(repo, [refLine('refs/backup/lane-a')]), { status: 0, refusals: [], stderr: '' });
  assert.equal(push(repo, [refLine('refs/backup/lane-a', '(delete)', ZERO)]).status, 0, 'deleting a backup ref is allowed');
  assert.equal(push(repo, []).status, 0, 'no ref lines, nothing to judge');
});

test('the push gate refuses a v tag without an annotated v tag on HEAD, naming the allowed path, and allows main with no tag', (t) => {
  const { repo, head } = repoWithHooks(t);
  record(repo, head, {});
  assert.deepEqual(push(repo, [refLine('refs/heads/main')]), { status: 0, refusals: [], stderr: '' }, 'a first push of main needs no tag');
  const bare = push(repo, [refLine('refs/tags/v1.0.0')]);
  assert.equal(bare.status, 1);
  assert.equal(bare.refusals.length, 1);
  assert.match(bare.refusals[0], /no annotated tag v\[0-9\]\* on HEAD/);
  assert.match(bare.refusals[0], /release cut.*refs\/backup\//);
  gitOk(repo, ['tag', 'v1.0.0']);
  assert.equal(push(repo, [refLine('refs/tags/v1.0.0')]).status, 1, 'a lightweight tag is no release tag');
  gitOk(repo, ['tag', '-d', 'v1.0.0']);
  gitOk(repo, ['tag', '-a', '-m', 'notes', 'rc-1']);
  assert.equal(push(repo, [refLine('refs/tags/v1.0.0')]).status, 1, 'an annotated tag that is not v[0-9]* is no release tag');
});

test('the push gate allows a fast-forward of main and refuses a rewind, a divergence and an unknown remote head', (t) => {
  const { repo, head } = repoWithHooks(t);
  gitOk(repo, ['commit', '-q', '--allow-empty', '-m', 'next']);
  const next = gitOk(repo, ['rev-parse', 'HEAD']);
  gitOk(repo, ['checkout', '-q', '-b', 'side', head]);
  gitOk(repo, ['commit', '-q', '--allow-empty', '-m', 'side']);
  const side = gitOk(repo, ['rev-parse', 'HEAD']);
  const main = (local, remote) => `refs/heads/main ${local} refs/heads/main ${remote}`;
  assert.deepEqual(push(repo, [main(next, head)]), { status: 0, refusals: [], stderr: '' }, 'a fast-forward');
  assert.equal(push(repo, [main(next, next)]).status, 0, 'an up-to-date main');
  for (const [name, local, remote] of [['a rewind', head, next], ['a divergence', side, next], ['a remote head this clone never had', next, 'c'.repeat(40)]]) {
    const refused = push(repo, [main(local, remote)]);
    assert.equal(refused.status, 1, name);
    assert.match(refused.refusals[0], /refs\/heads\/main is not a fast-forward/, name);
  }
});

test('the push gate needs the L4 record of HEAD for a v tag, naming this head and this tag', (t) => {
  const { repo, head } = repoWithHooks(t);
  gitOk(repo, ['tag', '-a', '-m', 'release', 'v1.0.0']);
  const tag = [refLine('refs/tags/v1.0.0')];
  assert.match(push(repo, tag).refusals[0], /no L4 record/);
  assert.equal(push(repo, [refLine('refs/heads/main')]).status, 0, 'main needs no record');
  record(repo, head, { head: 'f'.repeat(40) });
  assert.match(push(repo, tag).refusals[0], /does not name head/);
  record(repo, head, { tag: 'v9.9.9' });
  assert.match(push(repo, tag).refusals[0], /does not name head/);
  record(repo, head, '{not json');
  assert.equal(push(repo, tag).status, 1);
  record(repo, head, {});
  assert.deepEqual(push(repo, tag), { status: 0, refusals: [], stderr: '' });
  assert.equal(push(repo, [refLine('refs/heads/main'), ...tag]).status, 0, 'the release cut pushes main and its tag with the same record');
  record(repo, head, '{"tag":"v1.0.0","head":"' + head + '"}');
  assert.equal(push(repo, tag).status, 0, 'key order and spacing of the record do not matter');
});

test('the push gate refuses every other ref and a delete of main or a release ref, one line each, and still allows the backups of the same push', (t) => {
  const { repo, head } = repoWithHooks(t);
  gitOk(repo, ['tag', '-a', '-m', 'release', 'v1.0.0']);
  record(repo, head, {});
  const result = push(repo, [refLine('refs/heads/feature'), refLine('refs/tags/build-7'), refLine('refs/heads/main', '(delete)', ZERO), refLine('refs/tags/v1.0.0', '(delete)', ZERO), refLine('refs/backup/x'), refLine('refs/heads/main')]);
  assert.equal(result.status, 1);
  assert.equal(result.refusals.length, 4);
  assert.match(result.refusals[0], /refusing to push refs\/heads\/feature/);
  assert.match(result.refusals[1], /refusing to push refs\/tags\/build-7/);
  assert.match(result.refusals[2], /refusing to delete refs\/heads\/main/);
  assert.match(result.refusals[3], /refusing to delete refs\/tags\/v1\.0\.0/);
});

test('the push gate reads the record of the common dir from a linked worktree and from a subdirectory', (t) => {
  const { repo, head } = repoWithHooks(t);
  gitOk(repo, ['tag', '-a', '-m', 'release', 'v1.0.0']);
  record(repo, head, {});
  const wt = path.join(path.dirname(repo), 'wt');
  gitOk(repo, ['worktree', 'add', '-q', '--detach', wt, head]);
  const tag = [refLine('refs/tags/v1.0.0')];
  assert.equal(push(repo, tag, wt).status, 0, 'the record sits in the shared git dir');
  fs.mkdirSync(path.join(repo, 'sub'));
  assert.equal(push(repo, tag, path.join(repo, 'sub')).status, 0);
  gitOk(repo, ['commit', '-q', '--allow-empty', '-m', 'next']);
  assert.match(push(repo, tag).refusals[0], /no annotated tag/, 'a new HEAD carries no release tag');
});

test('the commit gate refuses whitespace errors and a syntax error of a staged .mjs, and passes a clean commit', (t) => {
  const { repo } = repoWithHooks(t);
  const commit = () => spawnSync('git', ['commit', '-q', '-m', 'x'], { cwd: repo, encoding: 'utf8' });
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = ;\n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.notEqual(commit().status, 0, 'a staged .mjs that does not parse');
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = 1; \n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.notEqual(commit().status, 0, 'trailing whitespace');
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = 1;\n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.equal(commit().status, 0);
});
