// git-hooks.spec.mjs - the git hooks of the runtime repository (scripts/guards/git-hooks.mjs): the rendered files and their install
// into <git common dir>/hooks. The push gate they carry is judged by tests/guards/release-push-gate.spec.mjs with a real push to a bare remote.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { GIT_HOOKS_MARKER, HOOK_NAMES, installGitHooks, renderRuntimeHooks } from '../../scripts/guards/git-hooks.mjs';
import { WORK_HOOK_MARKER, ensureWorkHook } from '../../scripts/guards/hook-install.mjs';
import { mkdtemp } from '../helpers/tmpdir.mjs';

for (const key of ['GIT_DIR', 'GIT_COMMON_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_OBJECT_DIRECTORY', 'GIT_CONFIG_PARAMETERS', 'GIT_CONFIG_COUNT', 'GIT_PREFIX']) delete process.env[key];

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const git = (cwd, args) => spawnSync('git', args, { cwd, encoding: 'utf8' });
const gitOk = (cwd, args) => { const r = git(cwd, args); assert.equal(r.status, 0, `git ${args.join(' ')}: ${r.stderr}`); return r.stdout.trim(); };
/** A temp repository with one commit, the generated hooks installed, and no remote. */
function repoWithHooks(t) {
  const repo = path.join(mkdtemp(t, 'starci-git-hooks-'), 'repo');
  fs.mkdirSync(repo);
  for (const args of [['init', '-q', '-b', 'main'], ['config', 'user.email', 't@t'], ['config', 'user.name', 't'], ['config', 'commit.gpgsign', 'false'], ['config', 'tag.gpgsign', 'false']]) gitOk(repo, args);
  fs.writeFileSync(path.join(repo, 'a.mjs'), 'export const a = 1;\n');
  gitOk(repo, ['add', '.']);
  gitOk(repo, ['commit', '-q', '-m', 'base']);
  const installed = installGitHooks({ root: repo });
  assert.equal(installed.ok, true);
  return { repo, head: gitOk(repo, ['rev-parse', 'HEAD']), hooksDir: installed.hooksDir };
}

test('renderRuntimeHooks: the push gate runs the release push gate script, the commit gate is L0 only', () => {
  const hooks = renderRuntimeHooks({ root: ROOT });
  assert.deepEqual(Object.keys(hooks).sort(), [...HOOK_NAMES].sort());
  for (const [name, text] of Object.entries(hooks)) {
    assert.ok(text.startsWith(['#!/bin/sh', '# Generated by the StarCi runtime'].join('\n')), name);
    assert.ok(text.includes(GIT_HOOKS_MARKER), name);
    assert.ok(!text.includes('{{') && !text.includes('\r'), `${name}: no placeholder, LF only`);
  }
  const push = hooks['pre-push'];
  const lastLine = push.trimEnd().split('\n').at(-1);
  assert.match(lastLine, /^exec '[^']+' '[^']*scripts\/guards\/release-push-gate\.mjs'$/, 'the hook hands git stdin to the gate script');
  assert.doesNotMatch(push, /--no-verify|SKIP|bypass|STARCI_/i, 'no switch opens the gate');
  assert.match(hooks['pre-commit'], /git diff --cached --check/);
  assert.match(hooks['pre-commit'], /node --check/);
  assert.ok(hooks['pre-commit'].includes(WORK_HOOK_MARKER), 'the generated commit hook chains the work guard');
  assert.doesNotMatch(hooks['pre-commit'], /npm |jest|typecheck|test:/, 'no test run, no typecheck at the commit gate');
});

test('installGitHooks writes both hooks executable into the git common dir, rewrites a stale generated hook and leaves a foreign one', (t) => {
  const { repo, hooksDir } = repoWithHooks(t);
  const rendered = renderRuntimeHooks({ root: ROOT });
  assert.equal(path.resolve(hooksDir), path.resolve(repo, '.git', 'hooks'));
  for (const name of HOOK_NAMES) {
    assert.equal(fs.readFileSync(path.join(hooksDir, name), 'utf8'), rendered[name], name);
    if (process.platform !== 'win32') assert.equal(fs.statSync(path.join(hooksDir, name)).mode & 0o700, 0o700, `${name} is owner-executable (0o700)`);
  }
  assert.deepEqual(installGitHooks({ root: repo }).hooks.map((h) => h.state), ['current', 'current']);
  fs.writeFileSync(path.join(hooksDir, 'pre-push'), `#!/bin/sh\n# ${GIT_HOOKS_MARKER} old\nexit 0\n`);
  fs.writeFileSync(path.join(hooksDir, 'pre-commit'), '#!/bin/sh\necho mine\n');
  const again = installGitHooks({ root: repo });
  assert.deepEqual(again.hooks.map((h) => [h.name, h.state]), [['pre-commit', 'foreign'], ['pre-push', 'updated']]);
  assert.equal(fs.readFileSync(path.join(hooksDir, 'pre-commit'), 'utf8'), '#!/bin/sh\necho mine\n', 'a foreign hook is never overwritten');
  assert.equal(git(repo, ['config', '--get', 'core.hooksPath']).status, 1, 'git config is not edited');
});

test('installGitHooks owns the single pre-commit, migrates the work hook, and ensureWorkHook leaves the generated chain unchanged', (t) => {
  const { repo, hooksDir } = repoWithHooks(t);
  const file = path.join(hooksDir, 'pre-commit');
  fs.rmSync(file);
  assert.equal(ensureWorkHook(repo, { skillRoot: ROOT }).changed, true);
  assert.ok(fs.readFileSync(file, 'utf8').includes(WORK_HOOK_MARKER));

  const installed = installGitHooks({ root: repo });
  assert.deepEqual(installed.hooks.map((h) => [h.name, h.state]), [['pre-commit', 'updated'], ['pre-push', 'current']]);
  const chained = fs.readFileSync(file, 'utf8');
  assert.ok(chained.includes(GIT_HOOKS_MARKER));
  assert.ok(chained.includes(WORK_HOOK_MARKER));
  assert.deepEqual(ensureWorkHook(repo, { skillRoot: ROOT }), { installed: true, path: file, changed: false });
  assert.equal(fs.readFileSync(file, 'utf8'), chained, 'the dispatch path never replaces the generated hook');
  assert.equal(installGitHooks({ root: repo }).hooks.find((h) => h.name === 'pre-commit').state, 'current');
});

test('installGitHooks from a linked worktree writes the common hooks dir; outside a checkout it reports', (t) => {
  const { repo } = repoWithHooks(t);
  const wt = path.join(path.dirname(repo), 'wt');
  gitOk(repo, ['worktree', 'add', '-q', '-b', 'side', wt]);
  fs.rmSync(path.join(repo, '.git', 'hooks', 'pre-push'));
  const result = installGitHooks({ root: wt });
  assert.equal(path.resolve(result.hooksDir), path.resolve(repo, '.git', 'hooks'));
  assert.equal(result.hooks.find((h) => h.name === 'pre-push').state, 'installed');
  const plain = mkdtemp(t, 'starci-git-hooks-plain-');
  assert.deepEqual(installGitHooks({ root: plain }), { ok: false, reason: 'not-a-git-checkout', hooksDir: null, hooks: [] });
});

test('installGitHooks takes an injected fs and an explicit hooks dir', () => {
  const written = [];
  const fake = {
    readFileSync: (file, enc) => fs.readFileSync(file, enc),
    existsSync: () => false,
    mkdirSync: () => {},
    writeFileSync: (file, body, opts) => written.push({ file, body, opts }),
    renameSync: (from, to) => written.push({ renamed: to }),
    chmodSync: () => {},
  };
  const result = installGitHooks({ root: ROOT, hooksDir: path.join('virtual', 'hooks'), fs: fake });
  assert.deepEqual(result.hooks.map((h) => h.state), ['installed', 'installed']);
  assert.equal(written.filter((w) => w.renamed).length, 2);
  assert.ok(written.filter((w) => w.body).every((w) => w.opts.mode === 0o700));
});

test('the commit gate refuses whitespace errors and a syntax error of a staged .mjs, and passes a clean commit', (t) => {
  const { repo } = repoWithHooks(t);
  const commit = () => spawnSync('git', ['commit', '-q', '-m', 'x'], { cwd: repo, encoding: 'utf8' });
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = ;\n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.notEqual(commit().status, 0, 'a staged .mjs that does not parse');
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = 1; \n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.notEqual(commit().status, 0, 'trailing whitespace');
  fs.writeFileSync(path.join(repo, 'b.mjs'), 'export const b = 1;\n');
  gitOk(repo, ['add', 'b.mjs']);
  assert.equal(commit().status, 0);
});
