import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openSession, confirmSession, cleanupFixtureOwners } from './v23-test-fixture.mjs';
import { openAttempt, acceptAttempt } from './attempt-gate.mjs';
import { editForecast } from './plan-history.mjs';
import { validateStep } from './validate-step.mjs';
import { goalPartitionCoverage, forecastObligations, partitionAdmissionErrors } from './goal-partitions.mjs';
import { retainContext, retainMission } from './mission-history.mjs';
import { scopeHash } from './mission-scope.mjs';
import { goalLedger, provenErrors, threeBranchStopErrors, v22SessionErrors } from './validate-session.mjs';
import { createHash } from 'node:crypto';
const sha = value => 'sha256:'+createHash('sha256').update(value).digest('hex');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('nineteen current accepted seed partitions close one goal only after every required unit passes', async t => {
  const owner = await mkdtemp(path.join(os.tmpdir(), 'starci-plan-expand-'));
  t.after(async()=> { cleanupFixtureOwners(owner); await rm(owner,{recursive:true,force:true}); });
  const opened = await openSession(path.join(owner,'.worktrees/sessions'), { project:'expansion', hostBinding:{kind:'codex-task',hostId:`native-${path.basename(owner)}`,worktree:owner,sourcePromptRef:'user:opening'},mission:{language:'en',goal:'Plan two independently attributable fixture units.',target:'Declared seed plan',includes:['Seed planning'],excludes:[],outputs:['Seed plan'],doneWhen:[{evidence:'Nineteen attributable seed units are planned.',producedBy:'data.plan'},{evidence:'Every planned fixture unit has been placed and read back.',producedBy:'data.seed'}],verification:'Validate the plan and units.',sourceRef:'user:opening'} });
  await confirmSession(opened.session,{selected:'as-stated',selectedBy:'user',sourceRef:'user:approved'});
  const session=opened.session, branch=path.join(session,'step-1/parallel-1'), file=path.join(session,'state.json');
  await mkdir(path.join(branch,'request'),{recursive:true});
  const contexts=[{alias:'@workspaces/be',head:null},{alias:'@worktrees/_templates',head:null},{alias:'@worktrees/uat/items',head:null}];
  const request={contractVersion:'starci/v2.2',schemaVersion:9,operatorId:'data.plan',sessionId:opened.sessionId,step:1,parallel:1,contexts,requirements:{goal:'Two fixture units support the declared journey.',feature:'items',env:'dev'},inputs:{},resume:null,goal:{doneWhen:0},attempt:{id:'1/1:a1',number:1,kind:'initial',previous:null},expected:{version:1,goalVersion:1,sourceRef:'state.json#mission:v1/doneWhen:0',criteria:[{id:'units',required:true,expected:'Two attributable units are planned.',verification:'Validate the plan and units.'}]},environment:{isolationId:'1/1:a1',mode:'isolated',workspace:null,reads:contexts.map(c=>c.alias),writes:[],exclusive:[],outputRoot:'response'},frozenInputs:[]};
  let state=JSON.parse(await readFile(file));state.chain=[['1/1']];state.steps={'1/1':'data.plan'};state.current='1/1';await writeFile(file,JSON.stringify(state));
  await writeFile(path.join(branch,'request/request.json'),JSON.stringify(request));
  await openAttempt(branch);
  const units=Array.from({length:19},(_,i)=>({id:`unit-${i+1}`,kind:'table',goal:`Owned fixture ${i+1} is available.`,inputs:[],dependsOn:[]}));
  const table=(head,rows)=>`\n## ${head[0]}\n\n| ${head[1].join(' | ')} |\n| ${head[1].map(()=> '---').join(' | ')} |\n${rows.map(row=>`| ${row.join(' | ')} |`).join('\n')}\n`;
  const quote=value=>'`'+value+'`';
  const receipt='# seed-plan — items\n'+table(['Units',['Unit','Serves','Namespace','Goal']],units.map(u=>[quote(u.id),`flow ${quote(u.id)}`,quote(`uat-${u.id}`),u.goal]))+table(['Targets',['Unit','Store','Attribution','Volume','Rollback']],units.map(u=>[quote(u.id),quote('items'),'owner','2','Remove every record owned by the unit account.']))+table(['Fixtures',['Unit','State','Action','JSON','SQL','Expected','Creates outcome']],units.map(u=>[quote(u.id),'valid','reuse',quote(`.worktrees/uat/items/${u.id}/seed/records.json`),'—','Two owned records read back.','false']))+table(['Fallbacks taken',['Code','Action']],[]);
  await mkdir(path.join(branch,'response/data'),{recursive:true});
  await writeFile(path.join(branch,'response/response.md'),receipt);
  await writeFile(path.join(branch,'response/data/units.json'),JSON.stringify({schemaVersion:9,producedBy:'data.plan',units}));
  const evidence=['response/response.md','response/data/units.json'];
  const response={contractVersion:'starci/v2.2',schemaVersion:9,operatorId:'data.plan',step:1,parallel:1,status:'done',fields:{'seed-plan':evidence[0],units:evidence[1]},fallbacks:[],commits:[],next:['data.seed'],boundProfile:'sol-reviewer',ranProfile:'sol-reviewer',attempt:{id:'1/1:a1',number:1,expectedVersion:1},actual:{expectedVersion:1,observedAt:new Date().toISOString(),observations:[{criterionId:'units',observed:'Both attributable units are declared.',evidence}]},comparison:{expectedVersion:1,verdict:'matched',criteria:[{criterionId:'units',verdict:'matched',evidence,note:'Both units and their targets validate.'}],next:'advance'},goalCheck:{achieved:true,evidence}};
  response.outcome={summary:'Two attributable fixture units are planned.',primary:{kind:'document',label:'Seed plan',ref:'response/response.md'}};
  await writeFile(path.join(branch,'response/response.json'),JSON.stringify(response));
  assert.equal((await acceptAttempt(branch)).state,'matched');
  state=JSON.parse(await readFile(file));
  const forecast={chain:[['1/1'],['2/1']],steps:{'1/1':'data.plan','2/1':'data.seed'},goals:{'1/1':{doneWhen:0},'2/1':{doneWhen:1}},reasons:{},presets:{},dependencies:{'1/1':[],'2/1':['1/1']},evidenceDependencies:{'1/1':[],'2/1':['1/1']},nodes:{'1/1':'data.plan','2/1':'data.seed'},fanout:{'2/1':'units'},handoffs:{},imports:{}};
  const expanded=await editForecast(root,session,state,forecast,{kind:'expand',cell:'2/1',producer:'1/1'},2);
  assert.equal(Object.keys(expanded.units).length,19);
  assert.equal(Object.values(expanded.obligations)[0].members.length,19);
  state.chain=expanded.chain;state.steps=expanded.steps;state.planned={};state.budget.units=19;
  const mission=await retainMission(session,state,{root});
  const record={version:1,sessionId:state.id,mission,missionVersion:state.mission.version,scopeHash:scopeHash(state.mission),previous:null,forecast:expanded,planned:{},retained:{steps:{},attempts:{},requestHashes:{},choices:{},inventoryCells:[],files:{}},mappings:[]};
  const address=await retainContext(session,'plans',record);
  state.planHistory={active:address,revisions:[address]};await writeFile(file,JSON.stringify(state));
  const stack=path.join(path.dirname(root),'.stacks','partition-fixture');await mkdir(stack,{recursive:true});
  const declaration=JSON.stringify({schemaVersion:9,env:'partition-fixture',production:false});await writeFile(path.join(stack,'environment.json'),declaration);
  t.after(()=>rm(stack,{recursive:true,force:true}));
  const approval=`.stacks/partition-fixture/environment.json#${sha(declaration)}`;
  let coverage=await goalPartitionCoverage(root,session,state);
  assert.deepEqual(coverage.errors,[]);assert.equal(coverage.goals.get(1).complete,false);assert.equal(coverage.goals.get(1).proven.size,0);
  async function seed(cell){
    const unit=expanded.units[cell].id,[step,parallel]=cell.split('/').map(Number),dir=path.join(session,`step-${step}`,`parallel-${parallel}`);
    await mkdir(path.join(dir,'request'),{recursive:true});await mkdir(path.join(dir,'response/artifacts'),{recursive:true});
    const ctx=[{alias:`@worktrees/uat/${unit}`,head:null},{alias:'@worktrees/sessions/central-runtime',head:null},{alias:'@workspaces/device-state',head:null}];
    const req={...structuredClone(request),operatorId:'data.seed',step,parallel,contexts:ctx,unit,requirements:{flow:unit,routeKey:state.project+'/be',env:'partition-fixture',approval,operation:'apply',resume:null},inputs:{'seed-plan':'step-1/parallel-1/response/response.md',units:'step-1/parallel-1/response/data/units.json'},goal:{doneWhen:1},attempt:{id:`${cell}:a1`,number:1,kind:'initial',previous:null},expected:{version:1,goalVersion:1,sourceRef:'state.json#mission:v1/doneWhen:1',criteria:[{id:'placed',required:true,expected:`Fixture ${unit} is placed and read back.`,verification:'Read the isolated JSON store and compare its owned ids.'}]},environment:{isolationId:`${cell}:a1`,mode:'inline',workspace:null,reads:ctx.map(c=>c.alias),writes:[],exclusive:[],outputRoot:'response'}};
    await writeFile(path.join(dir,'request/request.json'),JSON.stringify(req));
    await openAttempt(dir);
    // Real, isolated JSON fixture storage; no product database or UAT claim.
    const records=[{id:`uat-${unit}-record`,store:'fixture',value:unit}];
    await writeFile(path.join(dir,'response/artifacts/seed.json'),JSON.stringify(records));
    const observed=JSON.parse(await readFile(path.join(dir,'response/artifacts/seed.json')));assert.deepEqual(observed,records);
    const text=`# seed-receipt — ${unit}\n`+table(['Binding',['Field','Value']],[['Operator',quote('data.seed')],['Step',quote(`step-${step}/parallel-${parallel}`)],['Flow',quote(unit)],['Environment',quote('partition-fixture')],['Route',quote(state.project+'/be')],['Account',quote(`uat-${unit}-owner`)],['Operation','apply'],['Approval',approval],['Namespace',quote(`uat-${unit}`)],['Seed fingerprint',quote(sha(JSON.stringify(observed)))],['Drafted','no']])+table(['Records',['Id','Store','Attribution','Rollback']],observed.map(row=>[quote(row.id),quote(row.store),'prefix','yes']))+table(['Checks',['Check','Status','Evidence']],['store-reachable','rows-attributable','expected-state','rollback-listed'].map(id=>[quote(id),'passed',quote('response/artifacts/seed.json')]))+table(['Findings',['Code','Statement']],[]);
    await writeFile(path.join(dir,'response/response.md'),text);
    const res={...structuredClone(response),operatorId:req.operatorId,step,parallel,fields:{'seed-receipt':'response/response.md'},next:[],boundProfile:'sol-fresh',ranProfile:'sol-fresh',attempt:{id:req.attempt.id,number:1,expectedVersion:1},actual:{expectedVersion:1,observedAt:new Date().toISOString(),observations:[{criterionId:'placed',observed:`${observed.length} owned row read back.`,evidence:['response/response.md']}]},comparison:{expectedVersion:1,verdict:'matched',criteria:[{criterionId:'placed',verdict:'matched',evidence:['response/response.md'],note:'The isolated store matches its expected fixture.'}],next:'advance'},goalCheck:{achieved:true,evidence:['response/response.md']},outcome:{summary:`Fixture ${unit} placed.`,primary:{kind:'document',label:'Seed receipt',ref:'response/response.md'}}};
    await writeFile(path.join(dir,'response/response.json'),JSON.stringify(res));
    assert.equal((await acceptAttempt(dir)).state,'matched');state=JSON.parse(await readFile(file));
  }
  const cells=Object.keys(expanded.units);
  const consumerForecast=structuredClone(expanded);consumerForecast.steps['21/1']='uat.verify';consumerForecast.dependencies['21/1']=[cells[0]];
  const consumer={operatorId:'uat.verify',step:21,parallel:1};
  await seed(cells[0]);coverage=await goalPartitionCoverage(root,session,state);
  assert.deepEqual(coverage.errors,[]);assert.equal(coverage.goals.get(1).proven.size,1);assert.equal(coverage.goals.get(1).complete,false);
  let ledger=await goalLedger(session,state,root);assert.equal(ledger.find(row=>row.branch===cells[0]).partitionAchieved,true);assert.equal(ledger.find(row=>row.branch===cells[0]).achieved,false);
  assert.ok(provenErrors({...state,brief:{...state.brief,proven:['doneWhen:1 all fixtures placed']}},ledger,{root}).length);
  assert.match((await v22SessionErrors(session,{...state,status:'done'},root)).join(),/missing required partition/);
  assert.match((await partitionAdmissionErrors(root,session,state,consumer,consumerForecast)).join(),/GOAL_PARTITION_PENDING/,'a dependency on one member consumes the complete registered set');
  for(const cell of cells.slice(1))await seed(cell);
  coverage=await goalPartitionCoverage(root,session,state);assert.deepEqual(coverage.errors,[]);assert.equal(coverage.goals.get(1).complete,true);
  ledger=await goalLedger(session,state,root);assert.deepEqual(threeBranchStopErrors(state,ledger),[]);assert.deepEqual(provenErrors({...state,brief:{...state.brief,proven:['doneWhen:1 every fixture proved']}},ledger,{root}),[]);
  assert.deepEqual(await v22SessionErrors(session,{...state,status:'done'},root),[]);
  assert.deepEqual(await partitionAdmissionErrors(root,session,state,consumer,consumerForecast),[]);
  const unsealed=structuredClone(state);delete unsealed.attempts[cells.at(-1)].evidenceManifest;assert.equal((await goalPartitionCoverage(root,session,unsealed)).goals.get(1).complete,false);
  for(const mutate of [s=>{s.attempts[cells.at(-1)].status='blocked';},s=>{s.attempts[cells.at(-1)].expected.goalVersion=2;},s=>{s.chain=s.chain.filter(step=>!step.includes(cells.at(-1)));}]){const bad=structuredClone(state);mutate(bad);assert.equal((await goalPartitionCoverage(root,session,bad)).goals.get(1).complete,false);}
  const proofPath=path.join(session,'step-20/parallel-1/response/artifacts/seed.json'),bytes=await readFile(proofPath);await writeFile(proofPath,'[]');assert.equal((await goalPartitionCoverage(root,session,state)).goals.get(1).complete,false);await writeFile(proofPath,bytes);
  const changed=structuredClone(expanded);Object.values(changed.obligations)[0].members.pop();assert.match((await forecastObligations(root,session,state,changed)).errors.join(),/members|source|authority/);
  // The immutable unit producer, not the number of scheduled cells, remains the complete set.
  const prior=structuredClone(expanded);delete prior.obligations;delete prior.partitions;delete prior.units[cells.at(-1)];
  const inferred=await goalPartitionCoverage(root,session,state,prior);assert.equal(inferred.goals.get(1).required.size,19);assert.equal(inferred.goals.get(1).complete,false);
});
