import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {loadOperatorPackages} from './operator-md.mjs';
import {loadOperatorGraph,validateChain,dependencyHandoffErrors} from './validate-chain.mjs';
import {planChain} from './plan-chain.mjs';
import {discoveryFor} from './v23-test-fixture.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
test('a complete multi-unit delivery forecast resumes its declared input owner instead of attempting seed before runtime and identity',async()=>{
  const packages=await loadOperatorPackages(root),graph=await loadOperatorGraph(root,packages);
  const mission={version:1,doneWhen:['business.decide','architecture.decide','backend.generate','backend.generate','interface.generate','interface.generate','runtime.serve','identity.provision','data.seed','uat.verify','git.publish'].map((producedBy,i)=>({producedBy,evidence:`Required delivery outcome ${i}`}))};
  mission.discovery=discoveryFor('handoff',{stage:'publish',tags:['feature','architecture','backend','data','api','interface']});
  mission.doneWhen.push(...['api.verify','interface.audit','quality.verify','business.reconcile'].map(producedBy=>({producedBy,evidence:`Verified ${producedBy} delivery.`})));
  const forecast=planChain({packages,mission,options:{graph,roles:['be','fe'],dependencyHandoffs:true}});
  const requests=Object.fromEntries(Object.entries(forecast.steps).map(([cell,operatorId])=>[cell,{operatorId,goal:forecast.goals[cell],requirements:forecast.presets[cell]??{}}]));
  const planned=Object.fromEntries(Object.keys(forecast.steps).map(cell=>[cell,{requirements:forecast.presets[cell]??{}}]));
  const validate=(f=forecast)=>validateChain(root,packages,f.chain,f.steps,requests,{graph,forecast:f,mission,planned});
  assert.deepEqual(validate(),[]);
  const position=op=>Number(Object.keys(forecast.steps).find(cell=>forecast.steps[cell]===op).split('/')[0]);
  assert.ok(position('interface.plan')<position('interface.generate'));
  assert.ok(position('backend.plan')<position('backend.generate'));
  assert.ok(position('runtime.serve')<position('identity.provision'));
  assert.ok(position('identity.provision')<position('data.seed'));
  assert.ok(position('data.seed')<position('uat.verify'));
  assert.ok(position('interface.audit')<position('uat.verify'));
  assert.ok(position('uat.verify')<position('git.publish'));
  const cell=Object.keys(forecast.handoffs)[0];assert.ok(cell,'fixture must exercise an earlier dependency handoff');
  assert.deepEqual(dependencyHandoffErrors(graph,forecast,cell),[]);
  assert.ok(validateChain(root,packages,forecast.chain,forecast.steps,requests,{graph,mission,planned}).some(error=>error.includes('Next table')),'ordinary chains retain strict immediate Next');
  const unrelated=structuredClone(forecast);unrelated.evidenceDependencies[cell]=[];
  assert.match(dependencyHandoffErrors(graph,unrelated,cell).join(),/declared input\/context dependency/);
  const missingIdentity=structuredClone(forecast);const identity=Object.keys(missingIdentity.steps).find(cell=>missingIdentity.steps[cell]==='identity.provision');
  missingIdentity.steps[identity]='content.generate';
  assert.ok(validate(missingIdentity).some(error=>/uat-account|identity|operator/.test(error)));
});
