import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createSourceFixture,acceptArchitecture,sha,put,current,actual,open,accept,planCells,branch,table} from './workflow-source-fixture.mjs';

test('owning orchestrator continues approved architecture scope without another user answer or delegation, retaining history',async t=>{
 const statements=['The fixture worker has no side effects.','Invalid inputs throw a TypeError.'];
 const f=await createSourceFixture(t,{sessionId:'scope-reading',mission:({discovery})=>({discovery,includes:statements})});
 const api=await f.load('scripts/restatement-delegation.mjs'),{scopeHash}=await f.load('scripts/mission-scope.mjs');
 let blockedPaths,blockedBytes;
 const architecture=await acceptArchitecture(f,{readingLines:statements,answerReading:async(_,{branch,request,reading,decisionId})=>{
  const stateFile=path.join(f.session,'state.json'),state=f.state();
  const review={selected:'as-stated',selectedBy:'orchestrator',sourceRef:'orchestrator:approved-scope-line-review',requestHash:sha(readFileSync(path.join(branch,'request/request.json'))),restatementHash:sha(reading),scopeHash:scopeHash(state.mission),goalVersion:state.mission.version,lines:statements.map((statement,index)=>({line:index+1,statementHash:sha(statement),clauses:[{pointer:`/includes/${index}`,hash:sha(state.mission.includes[index])}],judgment:'The rendered statement repeats this approved constraint exactly; it introduces no decision or effect.'})),exclusions:state.mission.excludes.map((text,index)=>({index,hash:sha(text)})),materialChanges:[]};
  const reject=async(change,pattern)=>{const value=structuredClone(review);change(value);const before=readFileSync(stateFile);await assert.rejects(api.recordScopeRestatementReview(f.root,branch,value),pattern);assert.deepEqual(readFileSync(stateFile),before);};
  await reject(r=>r.selectedBy='user',/owning orchestrator/);
  await reject(r=>r.selectedBy='coordinator',/owning orchestrator/);
  await reject(r=>r.delegationId='invented',/expected null/);
  await reject(r=>r.selected='corrected',/expected.*as-stated/);
  await reject(r=>r.restatementHash=sha('changed'),/restatement bytes/);
  await reject(r=>r.requestHash=sha('foreign'),/accepted authority|request bytes/);
  await reject(r=>r.scopeHash=sha('different mission'),/scope differs/);
  await reject(r=>r.goalVersion+=1,/HISTORY|mission|scope/);
  await reject(r=>r.lines.pop(),/every rendered line/);
  await reject(r=>r.lines[0].clauses[0].pointer='/confirmation/sourceRef',/approved scope clause/);
  await reject(r=>r.lines[0].clauses[0].hash=sha('expanded effect'),/approved clause changed/);
  await reject(r=>r.lines[0].judgment='',/too short/);
  await reject(r=>r.exclusions=[],/every frozen exclusion/);
  await reject(r=>r.materialChanges=['new external effect'],/array is too long/);
  blockedPaths=['request/request.json','response/restatement.md','response/response.json'].map(ref=>path.join(branch,ref));blockedBytes=blockedPaths.map(file=>readFileSync(file));
  const file=path.join(f.home,'scope-review.json');put(file,review);
  const choice=JSON.parse(execFileSync(process.execPath,[path.join(f.root,'scripts/restatement-choice.mjs'),'scope-review',branch,file],{encoding:'utf8',windowsHide:true}));
  assert.equal(choice.decisionId,decisionId);assert.equal(choice.selectedBy,'orchestrator');
  assert.deepEqual(await api.recordScopeRestatementReview(f.root,branch,review),choice);
  assert.equal(Object.values(f.state().choices).filter(c=>c.selectedBy==='user').length,Object.values(state.choices).filter(c=>c.selectedBy==='user').length,'continuation invents no user answer');
  assert.equal(Object.keys(f.state().choices).filter(id=>id.startsWith('restatement-delegation:')).length,0);
  await assert.rejects(api.recordDelegatedRestatementReview(f.root,branch,review),/actual coordinator/);
 }});
 assert.equal(f.state().attempts[`${architecture.step}/1`].status,'matched');
 for(let i=0;i<blockedPaths.length;i++)assert.deepEqual(readFileSync(blockedPaths[i]),blockedBytes[i]);
 const branch=path.join(f.session,`step-${architecture.step}/parallel-1`),request=JSON.parse(readFileSync(path.join(branch,'request/request.json')));
 const {validateStep}=await f.load('scripts/validate-step.mjs');
 assert.deepEqual((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors,[]);
 const {confirmSession}=await f.load('scripts/v23-test-fixture.mjs'),mission={...f.state().mission,goal:f.state().mission.goal+' Clarify later scope.'};delete mission.confirmation;
 await confirmSession(f.session,{selected:'corrected',selectedBy:'user',sourceRef:'user:later-correction',mission});
 await confirmSession(f.session,{selected:'as-stated',selectedBy:'user',sourceRef:'user:later-confirmation'});
 assert.deepEqual((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors,[],'history retains its original scope review after mission correction');
 assert.ok((await api.delegatedRestatementErrors(f.root,branch,f.state(),request)).length,'old scope cannot admit fresh work');
 const state=f.state(),address=state.choices[request.decisionId].basis,file=path.join(f.session,address.ref),bytes=readFileSync(file);
 writeFileSync(file,bytes.toString().replace('approved-scope-line-review','tampered-review'));
 assert.ok((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors.some(error=>/HISTORY_TAMPERED/.test(error)));writeFileSync(file,bytes);
 const {retainSessionBundle,verifyRetention}=await f.load('scripts/session-cleanup.mjs');
 const archive=await retainSessionBundle(f.session,f.state(),'scope-review proof retention');await verifyRetention(archive.doneDir,archive.manifest,f.state());
 assert.deepEqual(readFileSync(path.join(archive.bundle,address.ref)),bytes);
});

test('business scope-review CLI admits the same approved promise without delegation',async t=>{
 const promise='A fixture worker accepts a string and returns its uppercase value.';
 const f=await createSourceFixture(t,{sessionId:'scope-business',mission:({discovery})=>({discovery,includes:[promise]})});
 await acceptArchitecture(f,{sourceStep:6});
 planCells(f,[[4,'business.decide'],[5,'business.decide']]);
 const plain={operatorId:'business.decide',contexts:[{alias:'@workspaces/be',head:f.base},{alias:'@worktrees/businesses/fixture',head:null}],requirements:{featureId:'fixture',targetState:'pending',dimensions:['actor-eligibility'],approval:null,promise,resume:null},inputs:{}};
 const first=current(f,plain,4,{goal:{prerequisite:'6/1'},workspace:false});await open(f,first);
 const reading='# restatement — fixture\n'+table('Restatement',['Line','Statement'],[[1,promise]])+table('Source',['Field','Value'],[['Field','promise'],['Quoted',promise]]);
 const {restatementDecisionId}=await f.load('scripts/restatement-choice.mjs'),decisionId=restatementDecisionId(first,'fixture',reading),dir=branch(f,4);
 put(path.join(dir,'response/restatement.md'),reading);
 await accept(f,first,actual(first,{stop:'RESTATEMENT_UNCONFIRMED',fields:{restatement:'response/restatement.md'},fallbacks:[],commits:[],next:[],interaction:{kind:'restatement-confirm',decisionId,options:[{id:'as-stated',label:'As stated',tradeoff:'Use the bounded promise'},{id:'corrected',label:'Corrected',tradeoff:'Correct the promise'}]}},'blocked',['response/restatement.md']));
 const original=readFileSync(path.join(dir,'response/response.json')),state=f.state(),{scopeHash}=await f.load('scripts/mission-scope.mjs');
 const run=(operation,target,value)=>{const file=path.join(f.home,operation+'.json');put(file,value);return JSON.parse(execFileSync(process.execPath,[path.join(f.root,'scripts/restatement-choice.mjs'),operation,target,file],{encoding:'utf8',windowsHide:true}));};
 const review={selected:'as-stated',selectedBy:'orchestrator',sourceRef:'orchestrator:business-fixture-review',requestHash:sha(readFileSync(path.join(dir,'request/request.json'))),restatementHash:sha(reading),scopeHash:scopeHash(state.mission),goalVersion:state.mission.version,lines:[{line:1,statementHash:sha(promise),clauses:[{pointer:'/includes/0',hash:sha(promise)}],judgment:'This line repeats the approved promise with no new effect.'}],exclusions:state.mission.excludes.map((text,index)=>({index,hash:sha(text)})),materialChanges:[]};
 assert.equal(run('scope-review',dir,review).selectedBy,'orchestrator');
 const resumed=current(f,plain,5,{goal:{prerequisite:'6/1'},workspace:false,number:2,previous:first.attempt.id,resume:{step:4,parallel:1,token:decisionId}});
 resumed.decisionId=decisionId;resumed.selectedOption='as-stated';resumed.requirements.resume=decisionId;
 const updated=f.state();updated.resumes['5/1']={resumes:'4/1',stop:'RESTATEMENT_UNCONFIRMED'};put(path.join(f.session,'state.json'),updated);
 await open(f,resumed);
 assert.equal(f.state().attempts['5/1'].status,'running');
 assert.deepEqual(readFileSync(path.join(dir,'response/response.json')),original);
});
