import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createSourceFixture,acceptArchitecture,sha,put,current,actual,open,accept,planCells,branch,table} from './workflow-source-fixture.mjs';

test('explicit user delegation opens and accepts an in-scope architecture continuation, preserves old proof and refuses drift or self-grants',async t=>{
 const statements=['The fixture worker has no side effects.','Invalid inputs throw a TypeError.'];
 const f=await createSourceFixture(t,{sessionId:'delegated-reading',mission:({discovery})=>({discovery,includes:statements})});
 const reviewer=await createSourceFixture(t,{sessionId:'review-coordinator',existing:f,draft:true,topology:{mode:'coordinated'}});
 const api=await f.load('scripts/restatement-delegation.mjs'),{scopeHash}=await f.load('scripts/mission-scope.mjs');
 let retained,reviewData,blockedBytes,blockedPaths;
 const architecture=await acceptArchitecture(f,{readingLines:statements,answerReading:async(_,{branch,request,reading,decisionId})=>{
  const stateFile=path.join(f.session,'state.json'),state=f.state();
  const grant={selectedBy:'user',sourceRef:'user:explicit-fixture-delegation',statement:'The named coordinator may review unchanged in-scope restatements; material deviations come to me.',scope:{sessionId:state.id,missionVersion:state.mission.version,scopeHash:scopeHash(state.mission)},coordinatorSession:reviewer.session,operators:['architecture.decide','business.decide']};
  const refusal=async(value,pattern)=>{const before=readFileSync(stateFile);await assert.rejects(api.recordRestatementDelegation(f.root,f.session,value),pattern);assert.deepEqual(readFileSync(stateFile),before);};
  await refusal({...grant,selectedBy:'coordinator'},/const|user/);
  await refusal({...grant,statement:''},/too short/);
  await refusal({...grant,coordinatorSession:f.session},/own restatement/);
  await refusal({...grant,operators:['git.publish']},/declared restatement operators/);
  await refusal({...grant,scope:{...grant.scope,scopeHash:sha('different')}},/scope differs/);
  retained=await api.recordRestatementDelegation(f.root,f.session,grant);
  reviewData={selected:'as-stated',selectedBy:'coordinator',sourceRef:'coordinator:actual-fixture-line-review',delegationId:retained.decisionId,coordinatorSession:reviewer.session,requestHash:sha(readFileSync(path.join(branch,'request/request.json'))),restatementHash:sha(reading),scopeHash:grant.scope.scopeHash,goalVersion:grant.scope.missionVersion,lines:statements.map((statement,index)=>({line:index+1,statementHash:sha(statement),clauses:[{pointer:`/includes/${index}`,hash:sha(state.mission.includes[index])}],judgment:'The rendered statement repeats this approved constraint exactly.'})),exclusions:state.mission.excludes.map((text,index)=>({index,hash:sha(text)})),materialChanges:[]};
  const rejectReview=async(change,pattern)=>{const value=structuredClone(reviewData);change(value);const before=readFileSync(stateFile);await assert.rejects(api.recordDelegatedRestatementReview(f.root,branch,value),pattern);assert.deepEqual(readFileSync(stateFile),before);};
  await rejectReview(r=>r.delegationId='missing',/missing actual user delegation/);
  await rejectReview(r=>r.selected='corrected',/expected.*as-stated/);
  await rejectReview(r=>r.restatementHash=sha('changed'),/restatement bytes/);
  await rejectReview(r=>r.requestHash=sha('foreign'),/accepted authority|request bytes/);
  await rejectReview(r=>r.goalVersion+=1,/HISTORY|mission|scope/);
  await rejectReview(r=>r.lines.pop(),/every rendered line/);
  await rejectReview(r=>r.lines[0].clauses[0].pointer='/confirmation/sourceRef',/approved scope clause/);
  await rejectReview(r=>r.lines[0].clauses[0].hash=sha('different'),/approved clause changed/);
  await rejectReview(r=>r.exclusions=[],/every frozen exclusion/);
  await rejectReview(r=>r.materialChanges=['new external effect'],/array is too long/);
  blockedPaths=['request/request.json','response/restatement.md','response/response.json'].map(ref=>path.join(branch,ref));blockedBytes=blockedPaths.map(file=>readFileSync(file));
  const choice=await api.recordDelegatedRestatementReview(f.root,branch,reviewData);assert.equal(choice.decisionId,decisionId);assert.equal(choice.selectedBy,'coordinator');
  assert.deepEqual(await api.recordDelegatedRestatementReview(f.root,branch,reviewData),choice,'same decision is idempotent');
  const {recordRestatementChoice}=await f.load('scripts/restatement-choice.mjs');
  await assert.rejects(recordRestatementChoice(branch,{selected:'as-stated',selectedBy:'coordinator',sourceRef:'not-a-user'}),/actual user answer/);
 }});
 assert.equal(f.state().attempts[`${architecture.step}/1`].status,'matched');
 for(let i=0;i<blockedPaths.length;i++)assert.deepEqual(readFileSync(blockedPaths[i]),blockedBytes[i]);
 const branch=path.join(f.session,`step-${architecture.step}/parallel-1`),request=JSON.parse(readFileSync(path.join(branch,'request/request.json')));
 const {validateStep}=await f.load('scripts/validate-step.mjs');
 assert.deepEqual((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors,[]);
 const before=readFileSync(path.join(branch,'response/response.json'));
 const {confirmSession}=await f.load('scripts/v23-test-fixture.mjs'),mission={...f.state().mission,goal:f.state().mission.goal+' Clarify the later verification boundary.'};delete mission.confirmation;
 await confirmSession(f.session,{selected:'corrected',selectedBy:'user',sourceRef:'user:fixture-later-correction',mission});
 await confirmSession(f.session,{selected:'as-stated',selectedBy:'user',sourceRef:'user:fixture-later-confirmation'});
 assert.deepEqual((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors,[],'opening invocation retains its original delegated choice after correction');
 assert.ok((await api.delegatedRestatementErrors(f.root,branch,f.state(),request)).length,'fresh old-scope reuse is refused');
 assert.deepEqual(readFileSync(path.join(branch,'response/response.json')),before);
 const state=f.state(),address=state.choices[request.decisionId].basis,file=path.join(f.session,address.ref),bytes=readFileSync(file);
 writeFileSync(file,bytes.toString().replace('actual-fixture-line-review','altered-review'));
 assert.ok((await validateStep(f.root,branch,{operator:true,requestPhase:'accept'})).errors.some(error=>/HISTORY_TAMPERED/.test(error)));writeFileSync(file,bytes);
 const {retainSessionBundle,verifyRetention}=await f.load('scripts/session-cleanup.mjs');
 const archive=await retainSessionBundle(f.session,f.state(),'fixture proof retention, not workflow completion');
 await verifyRetention(archive.doneDir,archive.manifest,f.state());
 for(const choice of Object.values(f.state().choices).filter(choice=>choice.basis)){
  assert.deepEqual(readFileSync(path.join(archive.bundle,choice.basis.ref)),readFileSync(path.join(f.session,choice.basis.ref)));
 }
});

test('business restatement uses the distinct public grant and delegated-review CLIs before fresh admission',async t=>{
 const promise='A fixture worker accepts a string and returns its uppercase value.';
 const f=await createSourceFixture(t,{sessionId:'delegated-business',mission:({discovery})=>({discovery,includes:[promise]})});
 await acceptArchitecture(f,{sourceStep:6});
 const reviewer=await createSourceFixture(t,{sessionId:'business-coordinator',existing:f,draft:true,topology:{mode:'coordinated'}});
 planCells(f,[[4,'business.decide'],[5,'business.decide']]);
 const plain={operatorId:'business.decide',contexts:[{alias:'@workspaces/be',head:f.base},{alias:'@worktrees/businesses/fixture',head:null}],requirements:{featureId:'fixture',targetState:'pending',dimensions:['actor-eligibility'],approval:null,promise,resume:null},inputs:{}};
 const first=current(f,plain,4,{goal:{prerequisite:'6/1'},workspace:false});await open(f,first);
 const reading='# restatement — fixture\n'+table('Restatement',['Line','Statement'],[[1,promise]])+table('Source',['Field','Value'],[['Field','promise'],['Quoted',promise]]);
 const {restatementDecisionId}=await f.load('scripts/restatement-choice.mjs'),decisionId=restatementDecisionId(first,'fixture',reading),dir=branch(f,4);
 put(path.join(dir,'response/restatement.md'),reading);
 await accept(f,first,actual(first,{stop:'RESTATEMENT_UNCONFIRMED',fields:{restatement:'response/restatement.md'},fallbacks:[],commits:[],next:[],interaction:{kind:'restatement-confirm',decisionId,options:[{id:'as-stated',label:'As stated',tradeoff:'Use the bounded promise'},{id:'corrected',label:'Corrected',tradeoff:'Correct the promise'}]}},'blocked',['response/restatement.md']));
 const original=readFileSync(path.join(dir,'response/response.json')),state=f.state(),{scopeHash}=await f.load('scripts/mission-scope.mjs');
 const grant={selectedBy:'user',sourceRef:'user:business-fixture-delegation',statement:'This coordinator may review unchanged readings within the confirmed fixture scope.',scope:{sessionId:state.id,missionVersion:state.mission.version,scopeHash:scopeHash(state.mission)},coordinatorSession:reviewer.session,operators:['business.decide']};
 const run=(operation,target,value)=>{const file=path.join(f.home,operation+'.json');put(file,value);return JSON.parse(execFileSync(process.execPath,[path.join(f.root,'scripts/restatement-choice.mjs'),operation,target,file],{encoding:'utf8',windowsHide:true}));};
 const granted=run('delegate',f.session,grant);
 const review={selected:'as-stated',selectedBy:'coordinator',sourceRef:'coordinator:business-fixture-review',delegationId:granted.decisionId,coordinatorSession:reviewer.session,requestHash:sha(readFileSync(path.join(dir,'request/request.json'))),restatementHash:sha(reading),scopeHash:grant.scope.scopeHash,goalVersion:state.mission.version,lines:[{line:1,statementHash:sha(promise),clauses:[{pointer:'/includes/0',hash:sha(promise)}],judgment:'This line repeats the approved promise with no new effect.'}],exclusions:state.mission.excludes.map((text,index)=>({index,hash:sha(text)})),materialChanges:[]};
 assert.equal(run('delegated-review',dir,review).selectedBy,'coordinator');
 const resumed=current(f,plain,5,{goal:{prerequisite:'6/1'},workspace:false,number:2,previous:first.attempt.id,resume:{step:4,parallel:1,token:decisionId}});
 resumed.decisionId=decisionId;resumed.selectedOption='as-stated';resumed.requirements.resume=decisionId;
 const updated=f.state();updated.resumes['5/1']={resumes:'4/1',stop:'RESTATEMENT_UNCONFIRMED'};put(path.join(f.session,'state.json'),updated);
 await open(f,resumed);
 assert.equal(f.state().attempts['5/1'].status,'running');
 assert.deepEqual(readFileSync(path.join(dir,'response/response.json')),original);
});
