import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {configuredAllocationPolicy,configuredProviderOrder,DEFAULT_MODEL_POOLS,DEFAULT_NON_OPERATION_MODELS,effectiveNonOperationModels,loadConfig,nonOperationModels,validateConfig} from '../engine/config.mjs';
import {stringifyYaml} from '../engine/yaml.mjs';
const expected=()=>({language:'vi',model:null,effort:'medium',kernel:{agent:'codex',model:'gpt-5.6-sol',effort:'high'},budgets:{maxOps:null,perOpMs:null,dailyTokens:null},allocation:{mode:'adaptive',preferredProvider:null},models:{selection:'quota-aware',pools:structuredClone(DEFAULT_MODEL_POOLS),nonOperation:{...DEFAULT_NON_OPERATION_MODELS}}});
test('local config initializes the three canonical quota-aware non-operation roles and rejects unknown roles, models and shapes',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-config-'));try{fs.copyFileSync(new URL('../config.example.yaml',import.meta.url),path.join(root,'config.example.yaml'));assert.deepEqual(loadConfig(root,{initialize:true}),expected());assert.deepEqual(effectiveNonOperationModels(loadConfig(root)).kernelManager,{pool:'opus-sol',runtimes:['claude-agent','codex-agent'],selection:'quota-aware'});const badRole=expected();badRole.models.nonOperation.rescuer='opus-sol';assert.throws(()=>validateConfig(badRole),/closed quota-aware/);fs.writeFileSync(path.join(root,'config.yaml'),stringifyYaml(badRole));assert.throws(()=>loadConfig(root),/closed quota-aware/,'loadConfig must not reinterpret an unknown new-schema role as a legacy six-role draft');const badModel=expected();badModel.models.pools['opus-sol']=['unknown-model','codex-agent'];assert.throws(()=>validateConfig(badModel),/opus-sol/);const badCapability=expected();badCapability.models.nonOperation.kernelManager='fable-astra';assert.equal(validateConfig(badCapability),badCapability,'both reasoning peers carry decide');const duplicate=expected();duplicate.models.pools['opus-sol']=['claude-agent','claude-agent'];assert.throws(()=>validateConfig(duplicate),/canonical pair/);assert.throws(()=>nonOperationModels('ownerAuthority',expected()),/Unknown non-operation/);const custom={...expected(),language:'en',model:'test-host-model'};fs.writeFileSync(path.join(root,'config.yaml'),stringifyYaml(custom));assert.deepEqual(loadConfig(root),custom);fs.writeFileSync(path.join(root,'config.yaml'),'null\n');assert.throws(()=>loadConfig(root),/Invalid config/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('legacy top-level model lists migrate only when their meanings consolidate into one supported pool',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-config-legacy-'));try{const compatible={language:'vi',model:null,effort:'medium',supervisor:{runtimes:['codex-agent','claude-agent']},validator:{runtimes:['codex-agent','claude-fable']},critique:{runtimes:['claude-fable','codex-agent']}};fs.writeFileSync(path.join(root,'config.json'),JSON.stringify(compatible));const loaded=loadConfig(root);assert.deepEqual(Object.keys(loaded),['language','model','effort','models']);assert.deepEqual(loaded.models.nonOperation,{planner:'fable-astra',kernelManager:'opus-sol',validator:'fable-astra'});assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'config.json'),'utf8')),compatible);const conflict={...compatible,validator:{runtimes:['codex-agent','claude-fable']},critique:{runtimes:['claude-agent','codex-agent']}};fs.writeFileSync(path.join(root,'config.json'),JSON.stringify(conflict));assert.throws(()=>loadConfig(root),/conflicts/,'a default-valued first assignment still owns the merged legacy role');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('six-role draft migration refuses incompatible merged meanings instead of discarding a custom choice',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-config-six-'));try{const draft=expected();draft.models.nonOperation={goalAssessment:['claude-fable','codex-agent'],operationPlanner:['claude-fable','codex-agent'],kernelManager:['claude-agent','codex-agent'],technicalDecision:['claude-fable','codex-agent'],goalCritic:['claude-fable','codex-agent'],validator:['claude-fable','codex-agent']};fs.writeFileSync(path.join(root,'config.json'),JSON.stringify(draft));assert.throws(()=>loadConfig(root),/kernelManager\/technicalDecision cannot be merged/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('relocated installed config reads the source model registry',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-config-installed-'));try{for(const file of ['engine/config.mjs','engine/runtime-root.mjs','engine/yaml.mjs','config.example.yaml','modules/models/runtimes.yaml']){const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(new URL(`../${file}`,import.meta.url),target);}const installed=await import(`${new URL(`file:///${path.join(root,'engine/config.mjs').replaceAll('\\','/')}`)}?fixture=${Date.now()}`);assert.deepEqual(installed.nonOperationModels('kernelManager',installed.loadConfig(root)),['claude-agent','codex-agent']);assert.equal(fs.existsSync(path.join(root,'model','runtimes.yaml')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('adaptive capacity is the default and the owner may prefer one declared provider without creating a chain',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-config-providers-'));
  try{
    fs.copyFileSync(new URL('../config.example.yaml',import.meta.url),path.join(root,'config.example.yaml'));
    const base=loadConfig(root,{initialize:true});
    assert.deepEqual(configuredAllocationPolicy(base),{mode:'adaptive',preferredProvider:null,source:'allocation'});
    const explicit={...base,allocation:{mode:'adaptive',preferredProvider:'codex'}};
    fs.writeFileSync(path.join(root,'config.yaml'),stringifyYaml(explicit));
    assert.deepEqual(configuredAllocationPolicy(loadConfig(root)),{mode:'adaptive',preferredProvider:'codex',source:'allocation'});
    assert.deepEqual(configuredProviderOrder(loadConfig(root)),['codex'],'the compatibility accessor exposes only the bias, not a chain');
    const legacy={...base};delete legacy.allocation;legacy.providers=['codex','qwen','claude'];
    assert.deepEqual(configuredAllocationPolicy(validateConfig(legacy)),{mode:'adaptive',preferredProvider:'codex',source:'legacy-providers'},'only the first legacy member carries owner intent');
    assert.throws(()=>validateConfig({...base,allocation:{mode:'adaptive',preferredProvider:'openai'}}),/not declared/);
    assert.throws(()=>validateConfig({...base,allocation:{mode:'chain',preferredProvider:'codex'}}),/mode:"adaptive"/);
    assert.throws(()=>validateConfig({...base,providers:['codex']}),/allocation or the legacy providers list/);
  }finally{fs.rmSync(root,{recursive:true,force:true});}
});
