import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {openLedger, ledgerFileFor} from '../engine/ledger-db.mjs';
import {migrateEvidence, archiveEvidence} from '../scripts/migrate/evidence-to-blobs.mjs';
import {getBlob} from '../scripts/lib/artifact-store.mjs';

const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const write=(root,rel,body)=>{const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,body);return file;};
const git=(repo,...args)=>{const r=spawnSync('git',['-C',repo,...args],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);};

test('backfills v1, unindexed custody, checks and proof idempotently, with verified blobs',t=>{
  const previousMigration=process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE='1';
  t.after(()=>{if(previousMigration===undefined)delete process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;else process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE=previousMigration;});
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'starci-ev-backfill-'));
  t.after(()=>fs.rmSync(temp,{recursive:true,force:true,maxRetries:20,retryDelay:25}));
  const repo=path.join(temp,'product'),root=path.join(temp,'artifacts');
  fs.mkdirSync(repo);git(repo,'init','-q');
  const previous=process.env.STARCI_ARTIFACT_ROOT;process.env.STARCI_ARTIFACT_ROOT=root;
  t.after(()=>{if(previous===undefined)delete process.env.STARCI_ARTIFACT_ROOT;else process.env.STARCI_ARTIFACT_ROOT=previous;});
  const proofRel='.starciwork/features/f/impl/be/E/result.md',proof=Buffer.from('accepted proof\n');
  write(repo,proofRel,proof);git(repo,'add','--',proofRel);
  const fileRel='.starciwork/kernel-evidence/wf-a/jobs/job-a/checks/canon.json',output=Buffer.from('{"ok":true}\n');
  write(repo,fileRel,output);
  const looseRel='.starciwork/kernel-evidence/wf-a/dispatch/request.log',loose=Buffer.from('dispatch log\n');write(repo,looseRel,loose);
  const orphanRel='.starciwork/kernel-evidence/wf-old/old.txt',orphan=Buffer.from('orphan\n');write(repo,orphanRel,orphan);
  const ledger=openLedger({file:ledgerFileFor(repo)});ledger.ensureWorkflow({workflowId:'wf-a'});
  ledger.enqueueJob({jobId:'job-a',workflowId:'wf-a',opId:'review.verify',attempt:1,kind:'op'});
  ledger.enqueueJob({jobId:'job-b',workflowId:'wf-a',opId:'review.verify',attempt:2,kind:'op'});
  const add=ledger.db.prepare('INSERT INTO job_artifacts(workflow_id,job_id,op_id,attempt,kind,path,sha256,bytes,created_at) VALUES(?,?,?,?,?,?,?,?,?)');
  add.run('wf-a','job-a','review.verify',1,'file',fileRel,sha(output),output.length,1);
  add.run('wf-a','job-b','review.verify',2,'file',fileRel,sha(output),output.length,1);
  add.run('wf-a','job-a','review.verify',1,'file',proofRel,sha(proof),proof.length,1);
  ledger.db.prepare('INSERT INTO artifact_proofs(workflow_id,job_id,path,claims_json,deps_json,created_at) VALUES(?,?,?,?,?,?)').run('wf-a','job-a',proofRel,'{}','[]',1);
  ledger.db.prepare('INSERT INTO checks(workflow_id,op_id,attempt,checks_json,created_at) VALUES(?,?,?,?,?)').run('wf-a','review.verify',1,JSON.stringify({checks:[{name:'canon',command:'node canon',exitCode:0,evidence:'green'}]}),1);
  ledger.close();
  if(previousMigration===undefined)delete process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;else process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE=previousMigration;
  const backup=path.join(temp,'backup.sqlite');fs.copyFileSync(ledgerFileFor(repo),backup);
  const dry=migrateEvidence({repo});assert.equal(dry.files,4);assert.equal(dry.v1,3);assert.equal(dry.artifactCandidates,5);
  let db=openLedger({file:ledgerFileFor(repo)});
  assert.equal(db.db.prepare('SELECT count(*) n FROM job_artifacts_v2').get().n,0);db.close();
  const first=migrateEvidence({repo,apply:true,backup});
  assert.equal(first.added,4);assert.equal(first.orphanFiles,1);assert.equal(first.checks,1);assert.equal(first.proofs,1);
  assert.deepEqual(getBlob(sha(output)),output);assert.deepEqual(getBlob(sha(orphan)),orphan);
  db=openLedger({file:ledgerFileFor(repo)});
  const rows=db.db.prepare('SELECT name,storage,repo_path,role,sha256 FROM job_artifacts_v2 ORDER BY name').all();
  assert.equal(rows.length,4);
  assert.equal(rows.find(r=>r.name===proofRel).storage,'work-proof');
  assert.equal(rows.find(r=>r.name==='checks/canon.json').repo_path,null);
  assert.equal(db.db.prepare('SELECT http_path FROM blobs WHERE sha256=?').get(sha(output)).http_path,`/api/blob/${sha(output)}`);
  db.close();
  const second=migrateEvidence({repo,apply:true,backup});assert.equal(second.added,0);assert.equal(second.existing,4);assert.equal(second.checks,0);assert.equal(second.proofs,0);
  const archive=path.join(temp,'kernel-evidence-product-20260928.zip');
  assert.equal(archiveEvidence({repo,archive,backup}).files,3);
  assert.equal(archiveEvidence({repo,archive,backup,verifyOnly:true}).files,3);
  db=openLedger({file:ledgerFileFor(repo)});
  assert.ok(db.db.prepare('SELECT archived_at FROM blobs WHERE sha256=?').get(sha(loose)).archived_at);db.close();
});

test('apply requires a backup and records changed v1 bytes as drift',t=>{
  const previousMigration=process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE='1';
  t.after(()=>{if(previousMigration===undefined)delete process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;else process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE=previousMigration;});
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'starci-ev-backfill-'));
  t.after(()=>fs.rmSync(temp,{recursive:true,force:true,maxRetries:20,retryDelay:25}));
  const previousRoot=process.env.STARCI_ARTIFACT_ROOT;process.env.STARCI_ARTIFACT_ROOT=path.join(temp,'artifacts');
  t.after(()=>{if(previousRoot===undefined)delete process.env.STARCI_ARTIFACT_ROOT;else process.env.STARCI_ARTIFACT_ROOT=previousRoot;});
  const repo=path.join(temp,'product');fs.mkdirSync(repo);
  const rel='.starciwork/kernel-evidence/wf-a/jobs/j/a.txt';write(repo,rel,'after');
  const ledger=openLedger({file:ledgerFileFor(repo)});ledger.ensureWorkflow({workflowId:'wf-a'});
  ledger.db.prepare('INSERT INTO job_artifacts(workflow_id,job_id,attempt,kind,path,sha256,bytes,created_at) VALUES(?,?,?,?,?,?,?,?)').run('wf-a','j',1,'file',rel,sha(Buffer.from('before')),6,1);ledger.close();
  if(previousMigration===undefined)delete process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE;else process.env.STARCI_EVIDENCE_SCHEMA_MIGRATE=previousMigration;
  assert.throws(()=>migrateEvidence({repo,apply:true}),/backup/);
  const backup=path.join(temp,'backup.sqlite');fs.copyFileSync(ledgerFileFor(repo),backup);
  const out=migrateEvidence({repo,apply:true,backup});
  assert.equal(out.sourceDrift.count,1);
  const migrated=openLedger({file:ledgerFileFor(repo)});
  assert.equal(migrated.db.prepare('SELECT sha256 FROM job_artifacts_v2').get().sha256,sha(Buffer.from('after')));
  migrated.close();
});
