import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {validateWorkspace,staleWorkspace} from '../core/index.mjs';import {stringifyYaml,parseYaml} from '../core/yaml.mjs';
const cli=fileURLToPath(new URL('../cli/main.mjs',import.meta.url));
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'work-index-md-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(path.join(root,'workspace.yaml'),stringifyYaml({schema:'work/workspace@1',id:'v2-test'}));const files=new Map(),bodies=new Map();
 const write=(dir,extra={},body='Scope is observable and bounded. Done when the stated result is verified.')=>{const file=path.join(root,dir,'index.yaml'),meta={schema:'work/node@2',id:dir.replaceAll('/','.'),kind:'operations',required:true,description:body,...extra};fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,stringifyYaml(meta));files.set(meta.id,file);bodies.set(meta.id,body);return meta.id;};
 const mutate=(id,fn)=>{const file=files.get(id),source=fs.readFileSync(file,'utf8');if(file.endsWith('.yaml')){const meta=parseYaml(source);fn(meta);fs.writeFileSync(file,stringifyYaml(meta));return;}const m=source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/),meta=parseYaml(m[1]);fn(meta);fs.writeFileSync(file,'---\n'+stringifyYaml(meta)+'---\n'+m[2].replace(/\r\n/g,'\n'));};
 const toYaml=(id)=>files.get(id);
 const investigate=(...ids)=>{for(const id of ids){const n=validateWorkspace(root).nodes.find(x=>x.id===id);mutate(id,m=>{m.investigation={contextDigest:n.contextDigest};if(!n.children.length&&m.state==='uninvestigate')m.state='todo';});}};
 const complete=(id)=>{mutate(id,m=>{m.assertions=['verified'];});const n=validateWorkspace(root).nodes.find(x=>x.id===id),dir=path.dirname(files.get(id)),proof='proof.'+id;const evidence=path.join(dir,'evidence',proof,'manifest.yaml');fs.mkdirSync(path.dirname(evidence),{recursive:true});fs.writeFileSync(evidence,stringifyYaml({schema:'work/evidence@1',id:proof,nodeId:id,inputDigest:n.inputDigest,outcome:'pass',assertions:[{id:'verified',outcome:'pass',observation:'Synthetic bound runtime proof'}],assets:[]}));mutate(id,m=>{m.state='done';m.completion={inputDigest:n.inputDigest,evidence:[proof]};});};
 return {root,write,mutate,toYaml,investigate,complete,run:()=>validateWorkspace(root)};}

test('v2 parent semantic change invalidates every descendant and a crossed consumer while preserving sibling isolation for new children',t=>{const f=fixture(t);f.write('goal');f.write('goal/a');f.write('goal/a/deep',{state:'uninvestigate'});f.write('goal/b',{state:'uninvestigate'});f.write('consumer',{state:'uninvestigate',refs:['goal.a.deep']});f.write('other',{state:'uninvestigate'});f.investigate('goal','goal.a','goal.a.deep','goal.b','consumer','other');let r=f.run();assert.ok(r.ok,JSON.stringify(r.errors));const sibling=r.nodes.find(n=>n.id==='goal.b').contextDigest;f.write('goal/new',{state:'uninvestigate'});r=f.run();assert.equal(r.nodes.find(n=>n.id==='goal.b').contextDigest,sibling);assert.equal(r.nodes.find(n=>n.id==='goal.b').effectiveState,'todo');f.mutate('goal',m=>{m.description+=' A newly accepted semantic constraint.';});r=f.run();for(const id of ['goal','goal.a','goal.a.deep','goal.b','goal.new','consumer'])assert.equal(r.nodes.find(n=>n.id===id).effectiveState,'uninvestigate',id);assert.equal(r.nodes.find(n=>n.id==='other').effectiveState,'todo');const stale=staleWorkspace(f.root);assert.ok(stale.nodes.find(n=>n.id==='goal.a.deep').causes.includes('goal'));assert.equal(stale.nodes.find(n=>n.id==='goal.new').status,'not-yet-investigated');});

test('operational activity and blockers keep digests stable, but blockers prevent eligibility',t=>{const f=fixture(t);f.write('piece',{state:'uninvestigate'});f.investigate('piece');const before=f.run().nodes[0];f.mutate('piece',m=>{m.activity='implementing';m.blockers=['Waiting for owned test environment'];});const after=f.run().nodes[0];assert.equal(after.specDigest,before.specDigest);assert.equal(after.contextDigest,before.contextDigest);assert.equal(after.inputDigest,before.inputDigest);assert.equal(after.effectiveState,'todo');assert.equal(after.eligible,false);});

test('ordinary defined todo is actionable without an investigation receipt',t=>{const f=fixture(t);f.write('defined',{state:'todo'});const node=f.run().nodes[0];assert.equal(node.effectiveState,'todo');assert.equal(node.investigationDigest,null);assert.equal(node.eligible,true);});

test('implementation records meaningful changes without duplicating Git file inventories',t=>{
 const f=fixture(t);
 const id=f.write('implementation/backend',{kind:'implementation',state:'todo',implementation:{
  status:'observed',changes:[{what:'Rejected duplicate delivery in a synthetic fixture.',why:'Preserve the original intent.',repository:'fixture-repo',directory:'src/delivery',revision:'1'.repeat(40),verification:['Focused synthetic test; no real integration claim.']}],gaps:['Real integration has not run.']
 }});
 let report=f.run();assert.ok(report.ok,JSON.stringify(report.errors));assert.notEqual(report.nodes.find(n=>n.id===id).effectiveState,'done');
 f.mutate(id,m=>{m.implementation.changes[0].files=['src/delivery/handler.ts'];m.implementation.currentCodeMap=[{layer:'domain',symbol:'handle',path:'src/delivery/handler.ts',responsibility:'Optional useful anchor for original-intent dispatch.'}];});
 report=f.run();assert.ok(report.ok,JSON.stringify(report.errors));
 f.mutate(id,m=>{m.implementation.changes[0].files='not-a-list';});
 assert.equal(f.run().ok,false);
});

test('canonical YAML v2 hashes description changes',t=>{const f=fixture(t);f.write('defined',{state:'todo'},'Initial semantic prose.');const before=f.run().nodes[0];f.mutate('defined',m=>{m.description='Changed semantic prose.';});assert.notEqual(f.run().nodes[0].specDigest,before.specDigest);});

test('YAML v2 enforces published nested types, required completion fields and exact states',t=>{const cases=[m=>{m.history=['not-an-object'];},m=>{m.timestamps='not-an-object';},m=>{m.completion={inputDigest:'bad',evidence:[]};},m=>{m.state='uninvestigated';},m=>{m.investigation={contextDigest:'0'.repeat(64),extra:true};}];for(const change of cases){const f=fixture(t);f.write('defined',{state:'todo'});f.toYaml('defined');f.mutate('defined',change);const result=f.run();assert.equal(result.ok,false);assert.ok(result.errors.some(e=>['SCHEMA_VALUE','STATE','UNKNOWN_FIELD','INVESTIGATION'].includes(e.code)),JSON.stringify(result.errors));}});

test('stored YAML done becomes effective uninvestigate after ancestor semantics change without rewriting evidence',t=>{const f=fixture(t);f.write('scope');f.write('scope/done',{state:'todo'});f.write('unrelated',{state:'todo'});f.complete('scope.done');f.complete('unrelated');f.toYaml('scope');const nodeFile=f.toYaml('scope.done');let r=f.run();assert.ok(r.ok,JSON.stringify(r.errors));const proofFile=path.join(f.root,'scope/done/evidence/proof.scope.done/manifest.yaml'),nodeBytes=fs.readFileSync(nodeFile),proofBytes=fs.readFileSync(proofFile);f.mutate('scope',m=>{m.description+=' Changed ancestor contract.';});r=f.run();const done=r.nodes.find(n=>n.id==='scope.done');assert.equal(done.state,'done');assert.equal(done.effectiveState,'uninvestigate');assert.deepEqual(done.completion.evidence,['proof.scope.done']);assert.equal(r.nodes.find(n=>n.id==='unrelated').effectiveState,'done');assert.deepEqual(fs.readFileSync(nodeFile),nodeBytes);assert.deepEqual(fs.readFileSync(proofFile),proofBytes);});

test('a blocker added to authored done is reported as stale reviewed, never as uninvestigated history',t=>{const f=fixture(t);f.write('done',{state:'todo'});f.complete('done');f.mutate('done',m=>{m.blockers=['Production prerequisite regressed'];});const node=f.run().nodes[0];assert.equal(node.state,'done');assert.equal(node.effectiveState,'uninvestigate');const stale=staleWorkspace(f.root).nodes[0];assert.equal(stale.status,'stale-reviewed');assert.deepEqual(stale.causes,['done']);assert.deepEqual(stale.completionEvidence,['proof.done']);});

test('unchanged todo dependency blocks execution without erasing a current investigation',t=>{const f=fixture(t);f.write('backend',{state:'uninvestigate'});f.write('frontend',{state:'uninvestigate',dependsOn:['backend']});f.investigate('backend','frontend');const r=f.run(),front=r.nodes.find(n=>n.id==='frontend');assert.equal(front.effectiveState,'todo');assert.equal(front.eligible,false);assert.deepEqual(front.blockedBy,['backend']);const stale=staleWorkspace(f.root);assert.equal(stale.nodes.some(n=>n.id==='frontend'),false,JSON.stringify(stale.nodes));});

test('stale command is read-only, reports retained receipts, and exits nonzero for a malformed cycle',t=>{const f=fixture(t);f.write('source',{state:'uninvestigate'});f.write('consumer',{state:'uninvestigate',refs:['source']});f.investigate('source','consumer');f.mutate('source',m=>{m.description+=' Changed source semantics.';});const consumerFile=path.join(f.root,'consumer/index.yaml'),before=fs.readFileSync(consumerFile);const out=spawnSync(process.execPath,[cli,'stale',f.root],{encoding:'utf8'});assert.equal(out.status,0,out.stderr);const report=JSON.parse(out.stdout),consumer=report.nodes.find(n=>n.id==='consumer');assert.equal(consumer.status,'stale-reviewed');assert.ok(consumer.causes.includes('source'));assert.ok(consumer.oldDigests.investigation);assert.deepEqual(fs.readFileSync(consumerFile),before);f.mutate('source',m=>m.dependsOn=['consumer']);f.mutate('consumer',m=>m.dependsOn=['source']);const bad=spawnSync(process.execPath,[cli,'stale',f.root],{encoding:'utf8',timeout:5000});assert.equal(bad.status,1);assert.ok(JSON.parse(bad.stdout).errors.some(e=>e.code==='CYCLE'));});
