import test from 'node:test';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {parseYaml,stringifyYaml} from '../core/yaml.mjs';import {validateWorkspace,sha256} from '../core/index.mjs';
import {propose,approveGoal as approvePresentedGoal,presentGoal,requestCell,acceptCell,acceptDelivery,markWorkDone,resumeFromBootstrap,saveRun,workflowDigest,validateGoal,resolveProjectSkillPath} from '../workflows/lifecycle.mjs';
function fixture(t,missing=false){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'starci-goal-'));t.after(()=>{assert.equal(path.dirname(dir),fs.realpathSync(os.tmpdir()));assert.ok(path.basename(dir).startsWith('starci-goal-'));fs.rmSync(dir,{recursive:true,force:true});});const root=path.join(dir,'.work');const put=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,stringifyYaml(x));};const create=()=>{put(path.join(root,'workspace.yaml'),{schema:'work/workspace@1',id:'synthetic'});put(path.join(root,'piece/index.yaml'),{schema:'work/node@1',id:'piece',kind:'operations',required:true,state:'todo',description:'Synthetic unit scenario, not product acceptance.',assertions:['outcome']});};if(!missing)create();fs.writeFileSync(path.join(dir,'proof.log'),'Synthetic observed result');const goal={schema:'starci/goal@1',id:'goal-1',workflow:'operate-runtime',requestId:'request-1',originalRequest:'Synthetic check of runtime and Work metadata.',finalOutcome:'Synthetic runtime returns ready and owned Work records proof.',scope:{business:['synthetic-runtime'],paths:[],resources:['runtime:test','work:test'],exclusions:['production']},criteria:['outcome'],businessChanges:['Only synthetic runtime readiness changes; no real business policy change.'],impacts:[],resourceEffects:[{target:'runtime:test',operation:'inspect',postcondition:'ready'}],inputs:{request:'synthetic original'},cells:[{id:'operate-runtime',op:'runtime.operate',operation:'service',purpose:'Return actual synthetic readiness result',finalOutput:'Result equals ready',criteria:['outcome'],inputs:{request:{from:'request',key:'request'}},outputSchema:{type:'object',properties:{result:{type:'string'}},required:['result'],additionalProperties:false}}],workTargets:['piece']};const receipt=(phase,digest)=>({actor:'user',phase,digest,approved:true,messageId:'synthetic-'+phase,quote:'Synthetic user confirmation from unit harness.'});const response=request=>({cell:request.cell,op:request.op,operation:request.operation,goalDigest:request.goalDigest,scopeDigest:request.scopeDigest,requestDigest:workflowDigest(request),status:'pass',criteria:[{id:'outcome',status:'pass',observation:'Synthetic unit observation',evidence:['log']}],outputs:{result:'ready'},artifacts:[{id:'log',path:'proof.log',sha256:sha256(fs.readFileSync(path.join(dir,'proof.log')))}]});return {dir,root,goal,create,put,receipt,response};}
test('missing Work routes to bootstrap; approval alone cannot bypass Work',t=>{const f=fixture(t,true);const run=propose(f.goal,{workRoot:f.root});assert.equal(run.route,'prepare-work');assert.throws(()=>requestCell(run,'operate-runtime'));const approved=approveGoal(run,f.receipt('goal',run.goalDigest));assert.equal(approved.status,'awaiting-bootstrap');assert.throws(()=>requestCell(approved,'execute'));assert.equal(fs.existsSync(f.root),false);});
test('an absent catalog workflow cannot create a run or dispatch effects',t=>{const f=fixture(t),goal=structuredClone(f.goal);goal.workflow='manual-agent-work';assert.throws(()=>propose(goal,{workRoot:f.root}),/Unknown workflow/);});
test('project skill resolution follows a relocated runtime instead of the global installation',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'starci-relocated-entry-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'workflows'));fs.writeFileSync(path.join(dir,'SKILL.md'),'---\nname: starci\n---\n');const resolved=resolveProjectSkillPath(pathToFileURL(path.join(dir,'workflows/lifecycle.mjs')).href);assert.equal(resolved,fs.realpathSync(path.join(dir,'SKILL.md')));assert.notEqual(resolved,fs.realpathSync(fileURLToPath(new URL('../SKILL.md',import.meta.url))));});
test('explicit approved goal, exact typed response and acceptance precede Work done',t=>{const f=fixture(t);let run=propose(f.goal,{workRoot:f.root});assert.throws(()=>approveGoal(run,f.receipt('goal','stale')));run=approveGoal(run,f.receipt('goal',run.goalDigest));const issued=requestCell(run,'operate-runtime');assert.equal(issued.request.projectSkillPath,fs.realpathSync(fileURLToPath(new URL('../SKILL.md',import.meta.url))));assert.match(issued.request.delegationPrompt,new RegExp(issued.request.projectSkillPath.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(issued.request.delegationPrompt,/workflow operate-runtime/);assert.throws(()=>requestCell(issued.run,'execute'),/already requested/);run=issued.run;const bad=f.response(issued.request);bad.outputs.unapproved='extra';assert.throws(()=>acceptCell(run,bad,{evidenceRoot:f.dir}));run=acceptCell(run,f.response(issued.request),{evidenceRoot:f.dir});assert.equal(run.status,'awaiting-acceptance');assert.equal(validateWorkspace(f.root).nodes[0].effectiveState,'todo');assert.throws(()=>markWorkDone(run,{}));run=acceptDelivery(run,f.receipt('acceptance',run.resultDigest));const node=validateWorkspace(f.root).nodes[0];f.put(path.join(f.root,'piece/evidence/unit/manifest.yaml'),{schema:'work/evidence@1',id:'unit-proof',nodeId:'piece',inputDigest:node.inputDigest,outcome:'pass',assertions:[{id:'outcome',outcome:'pass',observation:'Synthetic test evidence only'}],assets:[]});const before=fs.readFileSync(path.join(f.root,'piece/index.yaml'),'utf8');assert.throws(()=>markWorkDone(run,{piece:{inputDigest:'0'.repeat(64),evidence:['unit-proof']}}));assert.equal(fs.readFileSync(path.join(f.root,'piece/index.yaml'),'utf8'),before);run=markWorkDone(run,{piece:{inputDigest:node.inputDigest,evidence:['unit-proof']}});assert.equal(run.status,'done');assert.equal(validateWorkspace(f.root).nodes[0].effectiveState,'done');assert.equal(fs.existsSync(path.join(f.root,'piece/workflow')),false);assert.equal(fs.existsSync(path.join(f.root,'_workflows')),false);});
test('changed scope, stale goal approval and missing evidence cannot advance',t=>{const f=fixture(t);let run=propose(f.goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));const changed=structuredClone(run);changed.goal.scope.resources.push('production');assert.throws(()=>requestCell(changed,'execute'));const issued=requestCell(run,'operate-runtime');fs.writeFileSync(path.join(f.dir,'proof.log'),'tampered');assert.throws(()=>acceptCell(issued.run,f.response(issued.request),{evidenceRoot:path.join(f.dir,'missing')}));const response=f.response(issued.request);response.requestDigest='0'.repeat(64);assert.throws(()=>acceptCell(issued.run,response,{evidenceRoot:f.dir}));});
test('existing code needs real lines, source hash and anchor; new paths cannot invent lines',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.dir,'app.ts'),'export const readiness = false;\n');const goal=structuredClone(f.goal);goal.scope.paths=['repo:app.ts'];goal.impacts=[{repository:'repo',service:'control-plane',path:'app.ts',status:'existing',startLine:1,endLine:1,sourceHash:sha256(fs.readFileSync(path.join(f.dir,'app.ts'))),anchor:'readiness',change:'Return approved readiness value',businessReason:'Only the readiness response changes'}];assert.equal(validateGoal(goal,{repositories:{repo:f.dir}}).ok,true);goal.impacts[0].startLine=200;assert.throws(()=>validateGoal(goal,{repositories:{repo:f.dir}}));goal.impacts[0].status='new';assert.throws(()=>validateGoal(goal,{repositories:{repo:f.dir}}));});
test('accepted bootstrap resumes the same approved scope and cannot replace it',t=>{const f=fixture(t,true);let target=propose(f.goal,{workRoot:f.root});target=approveGoal(target,f.receipt('goal',target.goalDigest));const goal=structuredClone(f.goal);goal.id='bootstrap';goal.workflow='prepare-work';goal.workTargets=[];goal.resourceEffects=[{target:'work:test',operation:'create-metadata',postcondition:'valid-work'}];goal.cells[0]={...goal.cells[0],id:'prepare-work',op:'workspace.manage',operation:'prepare',purpose:'Create only Work metadata',finalOutput:'Valid Work bindings'};let bootstrap=propose(goal,{workRoot:f.root});bootstrap=approveGoal(bootstrap,f.receipt('goal',bootstrap.goalDigest));const issued=requestCell(bootstrap,'prepare-work');f.create();bootstrap=acceptCell(issued.run,f.response(issued.request),{evidenceRoot:f.dir});bootstrap=acceptDelivery(bootstrap,f.receipt('acceptance',bootstrap.resultDigest));bootstrap=markWorkDone(bootstrap,{});assert.equal(resumeFromBootstrap(target,bootstrap).status,'approved');const wrong=structuredClone(bootstrap);wrong.goal.originalRequest='another request';assert.throws(()=>resumeFromBootstrap(target,wrong));});
test('YAML accepts readable node metadata but rejects ambiguous keys and unsafe aliases',t=>{const f=fixture(t);assert.equal(validateWorkspace(f.root).ok,true);assert.equal(parseYaml('name: example\nenabled: true\n').enabled,true);assert.throws(()=>parseYaml('id: one\nid: two\n'));assert.throws(()=>parseYaml('a: &x [1]\nb: *x\n'));f.put(path.join(f.root,'piece/node.md'),'conflict');assert.equal(validateWorkspace(f.root).ok,false);});

test('two workflow sessions contribute to one checklist item without duplicate work or early done',t=>{const f=fixture(t);const nodeFile=path.join(f.root,'piece/index.yaml');const meta=parseYaml(fs.readFileSync(nodeFile,'utf8'));meta.assertions=['check-a','check-b'];f.put(nodeFile,meta);const inputDigest=validateWorkspace(f.root).nodes[0].inputDigest;let last;for(const check of ['check-a','check-b']){const goal=structuredClone(f.goal);goal.id=check;goal.criteria=[check];goal.cells[0].criteria=[check];let run=propose(goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));const issued=requestCell(run,'operate-runtime');const response=f.response(issued.request);response.criteria[0].id=check;run=acceptCell(issued.run,response,{evidenceRoot:f.dir});run=acceptDelivery(run,f.receipt('acceptance',run.resultDigest));f.put(path.join(f.root,'piece/evidence',check,'manifest.yaml'),{schema:'work/evidence@1',id:check,nodeId:'piece',inputDigest,outcome:'pass',assertions:[{id:check,outcome:'pass',observation:'Synthetic contribution from '+check}],assets:[]});if(check==='check-a'){assert.throws(()=>markWorkDone(run,{piece:{inputDigest,evidence:[check]}}));assert.equal(validateWorkspace(f.root).nodes[0].effectiveState,'todo');}last=run;}assert.equal(markWorkDone(last,{piece:{inputDigest,evidence:['check-a','check-b']}}).status,'done');const checked=validateWorkspace(f.root);assert.equal(checked.nodes.length,1);assert.equal(checked.nodes[0].id,'piece');assert.equal(fs.existsSync(path.join(f.root,'piece/workflow')),false);assert.deepEqual(fs.readdirSync(path.join(f.root,'piece/evidence')).sort(),['check-a','check-b']);});

test('workflow histories stay outside canonical Work and cannot overwrite another goal',t=>{const f=fixture(t);const run=propose(f.goal,{workRoot:f.root});const before=validateWorkspace(f.root);const sessions=path.join(path.dirname(f.root),'.starci','plans'),dir=saveRun(run,'run-1');assert.equal(dir,path.join(sessions,'run-1'));assert.equal(parseYaml(fs.readFileSync(path.join(dir,'run/index.yaml'),'utf8')).jobs['goal-1'].status,'awaiting-goal-approval');assert.deepEqual(validateWorkspace(f.root),before);assert.equal(fs.existsSync(path.join(f.root,'_workflows')),false);const other=propose({...f.goal,id:'another'},{workRoot:f.root});assert.throws(()=>saveRun(other,'run-1'));assert.equal(saveRun(other,'run-2'),path.join(sessions,'run-2'));assert.equal(fs.existsSync(path.join(f.root,'piece/workflow')),false);});

test('v2 dispatch binds current Work inputs and rejects semantic drift before accepting effects',t=>{const f=fixture(t),yaml=path.join(f.root,'piece/index.yaml');f.put(yaml,{schema:'work/node@2',id:'piece',kind:'operations',required:true,state:'todo',assertions:['outcome'],description:'Synthetic v2 work scope with observable completion.'});let run=propose(f.goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));const issued=requestCell(run,'operate-runtime');assert.equal(issued.request.workBindings.length,1);assert.equal(issued.request.workBindings[0].id,'piece');const meta=parseYaml(fs.readFileSync(yaml,'utf8'));f.put(yaml,{...meta,description:meta.description+' Changed after dispatch.'});assert.throws(()=>acceptCell(issued.run,f.response(issued.request),{evidenceRoot:f.dir}),/Work inputs changed/);});

test('v2 blockers prevent dispatch even when todo is otherwise current',t=>{const f=fixture(t),yaml=path.join(f.root,'piece/index.yaml');f.put(yaml,{schema:'work/node@2',id:'piece',kind:'operations',required:true,state:'todo',assertions:['outcome'],blockers:['Synthetic unresolved prerequisite'],description:'Synthetic v2 blocked scope.'});let run=propose(f.goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));assert.throws(()=>requestCell(run,'operate-runtime'),/investigated, unblocked and eligible/);});

test('markWorkDone preserves v2 YAML description and binds completion to current input',t=>{const f=fixture(t),yaml=path.join(f.root,'piece/index.yaml'),body='Synthetic v2 result is observable. Second prose sentence.';f.put(yaml,{schema:'work/node@2',id:'piece',kind:'operations',required:true,state:'todo',assertions:['outcome'],description:body});let run=propose(f.goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));const issued=requestCell(run,'operate-runtime');run=acceptCell(issued.run,f.response(issued.request),{evidenceRoot:f.dir});run=acceptDelivery(run,f.receipt('acceptance',run.resultDigest));const node=validateWorkspace(f.root).nodes[0];f.put(path.join(f.root,'piece/evidence/v2/manifest.yaml'),{schema:'work/evidence@1',id:'v2-proof',nodeId:'piece',inputDigest:node.inputDigest,outcome:'pass',assertions:[{id:'outcome',outcome:'pass',observation:'Synthetic v2 proof'}],assets:[]});run=markWorkDone(run,{piece:{inputDigest:node.inputDigest,evidence:['v2-proof']}});assert.equal(run.status,'done');const checked=validateWorkspace(f.root).nodes[0],meta=parseYaml(fs.readFileSync(yaml,'utf8'));assert.equal(checked.state,'done');assert.equal(checked.effectiveState,'done');assert.equal(checked.completion.inputDigest,node.inputDigest);assert.equal(meta.description,body);});


test('frontend stages bind only their owned Work and accept completed in-run prerequisites',t=>{const f=fixture(t);fs.rmSync(path.join(f.root,'piece'),{recursive:true,force:true});for(const n of [{id:'ui',state:'uninvestigate'},{id:'fe',state:'todo',dependsOn:['ui']},{id:'uat',state:'todo',dependsOn:['fe']}])f.put(path.join(f.root,n.id,'index.yaml'),{schema:'work/node@2',id:n.id,kind:'operations',required:true,state:n.state,dependsOn:n.dependsOn,assertions:[n.id],description:`Synthetic ${n.id} stage with an observable bounded outcome.`});const make=(id,op,target,previous)=>({id,op,purpose:`Complete ${id}`,finalOutput:`Return ${id}`,criteria:[id],workTargets:[target],inputs:previous?{prior:{from:'cell',cell:previous,key:'result'}}:{request:{from:'request',key:'request'}},outputSchema:{type:'object',properties:{result:{type:'string'}},required:['result'],additionalProperties:false}});f.goal.workflow='implement-frontend';f.goal.inputs={request:'synthetic',requiresBackend:false};f.goal.criteria=['draw','implement','uat'];f.goal.workTargets=['ui','fe','uat'];f.goal.cells=[make('draw','interface.draw','ui'),make('implement','interface.implement','fe','draw'),make('uat','uat.verify','uat','implement')];let run=propose(f.goal,{workRoot:f.root});run=approveGoal(run,f.receipt('goal',run.goalDigest));for(const id of ['draw','implement','uat']){const issued=requestCell(run,id);assert.deepEqual(issued.request.workBindings.map(x=>x.id),[f.goal.cells.find(c=>c.id===id).workTargets[0]]);const response=f.response(issued.request);response.criteria=[{id,status:'pass',observation:`${id} passed`,evidence:['log']}];response.outputs={result:id};run=acceptCell(issued.run,response,{evidenceRoot:f.dir});}assert.equal(run.status,'awaiting-acceptance');assert.equal(validateWorkspace(f.root).nodes.find(n=>n.id==='ui').effectiveState,'uninvestigate');});

function syntheticPresentation(run) {
 const section={action:'reuse',outcome:'Synthetic reviewed outcome',targets:[]};
 const scope={schema:'starci/plan@1',id:'synthetic-scope',requestId:run.goal.requestId,originalRequest:run.goal.originalRequest,finalOutcome:run.goal.finalOutcome,business:section,architecture:section,implementation:section,uat:section,exclusions:[],workflows:[{id:'job',workflow:run.goal.workflow,purpose:run.goal.finalOutcome,input:'Original request',output:'Verified outcome',criteria:run.goal.criteria,workTargets:run.goal.workTargets,paths:run.goal.scope.paths,resources:run.goal.scope.resources,dependsOn:[],estimate:{minMinutes:1,maxMinutes:2,assumptions:'Synthetic fixture only'}}]};
 return presentGoal(run,{messageId:'synthetic-presentation',scope,jobId:'job'});
}
function approveGoal(run,receipt) {return approvePresentedGoal(syntheticPresentation(run),{...receipt,replyTo:'synthetic-presentation'});}
test('original request cannot approve a subsequently presented goal',t=>{
 const f=fixture(t),run=propose(f.goal,{workRoot:f.root});
 assert.throws(()=>approvePresentedGoal(run,f.receipt('goal',run.goalDigest)),/Present/);
 const shown=syntheticPresentation(run);
 assert.throws(()=>approvePresentedGoal(shown,{...f.receipt('goal',run.goalDigest),messageId:f.goal.requestId,replyTo:'synthetic-presentation'}),/later user reply/);
 assert.throws(()=>approvePresentedGoal(shown,{...f.receipt('goal',run.goalDigest),replyTo:'another-message'}),/later user reply/);
 assert.equal(approvePresentedGoal(shown,{...f.receipt('goal',run.goalDigest),replyTo:'synthetic-presentation'}).status,'approved');
 shown.presentation.scope.finalOutcome='Changed after presentation';
 assert.throws(()=>approvePresentedGoal(shown,{...f.receipt('goal',run.goalDigest),replyTo:'synthetic-presentation'}),/Present/);
});

test('Plan bundle separates goal approval and current execution without duplicating goals',t=>{
 const f=fixture(t),run=propose(f.goal,{workRoot:f.root});const dir=saveRun(run,'accounting-plan');
 const read=p=>parseYaml(fs.readFileSync(path.join(dir,p),'utf8'));
 assert.deepEqual(Object.keys(read('index.yaml')).sort(),['approval','goal','id','run','schema']);
 assert.equal(read('approval/index.yaml').jobs['goal-1'].status,'pending');
 assert.equal(read('run/index.yaml').jobs['goal-1'].goal,undefined);
 assert.equal(read('goal/index.yaml').jobs['goal-1'].goal.finalOutcome,f.goal.finalOutcome);
 assert.equal(fs.existsSync(path.join(path.dirname(f.root),'.starci','runs')),false);
 assert.throws(()=>saveRun(run,'../escape'),/Unsafe/);
});
