import test from 'node:test';
import assert from 'node:assert/strict';
import {MANAGER_DECISION,MANAGER_SNAPSHOT,validateManagerDecision,validateManagerSnapshot} from '../models/manager-contract.mjs';

const snapshot=()=>({schema:MANAGER_SNAPSHOT,workflowId:'wf',decisionId:'manager-1',generation:2,version:3,digest:'digest',basisDigest:'basis',
  goal:{job:'deliver',definitionOfDone:['accepted']},progress:{ready:1},ops:[],blockers:[],actions:[{id:'dispatch:a',type:'dispatch',summary:'dispatch a',preconditions:['ready'],contextRefIds:['ctx']}],contextCatalog:[{id:'ctx',kind:'contract',digest:'c'}],noProgress:{round:0,budget:2}});
const decision=s=>({schema:MANAGER_DECISION,workflowId:s.workflowId,decisionId:s.decisionId,generation:s.generation,version:s.version,digest:s.digest,basisDigest:s.basisDigest,orderedActionIds:['dispatch:a'],rationale:'advance ready work',contextRequests:[{actionId:'dispatch:a',refIds:['ctx']}]});

test('canonical manager contract accepts one bound action and returns the executable order',()=>{const s=snapshot(),checked=validateManagerDecision(decision(s),s);assert.equal(validateManagerSnapshot(s).ok,true);assert.equal(checked.ok,true);assert.deepEqual(checked.orderedActionIds,['dispatch:a']);assert.equal(checked.reason,null);});
test('canonical manager contract rejects stale, invented and overlong decisions',()=>{const s=snapshot(),d=decision(s);assert.equal(validateManagerDecision({...d,digest:'old'},s).ok,false);assert.equal(validateManagerDecision({...d,orderedActionIds:['invented']},s).ok,false);assert.equal(validateManagerDecision({...d,rationale:'x'.repeat(4001)},s).ok,false);});
test('malformed snapshot and decision values fail closed without throwing',()=>{for(const value of [null,[],{actions:null},'bad',{...snapshot(),contextCatalog:[null,3]},{...snapshot(),actions:[null,3]}])assert.doesNotThrow(()=>assert.equal(validateManagerSnapshot(value).ok,false));const s=snapshot();for(const value of [null,[],{...decision(s),orderedActionIds:null},{...decision(s),contextRequests:'bad'},{...decision(s),contextRequests:[null,3]},{...decision(s),contextRequests:[{actionId:'dispatch:a',refIds:null}]},{...decision(s),contextRequests:[{actionId:'dispatch:a',refIds:['ctx'],authority:'owner'}]}])assert.doesNotThrow(()=>{const checked=validateManagerDecision(value,s);assert.equal(checked.ok,false);assert.deepEqual(checked.orderedActionIds,[]);});});
