import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {applyOwnerAction,applyOwnerVerification,deriveOwnerRequests,verifyAcceptedIntegrationOwnerRequests} from '../kernel/owner-requests.mjs';
import {applyOwnerInbox,enqueueOwnerInbox} from '../kernel/owner-inbox.mjs';
import {createStore} from '../kernel/store.mjs';
import {continueOwnerRequest,settleOwnerAsk} from '../kernel/owner.mjs';

const state=()=>({id:'wf',job:'implement-backend',generation:3,engine:{generation:3,jobId:'job-1'},inputs:['srs:one','sds:two'],ops:[{id:'ask-1',kind:'provision.ask',status:'waiting-owner',attempt:2,question:{kind:'credential',subject:'Payments sandbox',text:'Provide access',why:'Verify checkout'},credential:{provider:'Payments',custody:'identity:payments',variables:['PAYMENTS_KEY'],preparations:[{preparation:{credential:{obtain:'Provider console'},sources:[{title:'Official',url:'https://example.test/docs'}],prerequisites:[{owner:'owner',action:'Create sandbox key',reason:'Account custody'}]}}]}}]});
const actor={type:'owner',receiptId:'orca-message-1',channel:'orca'};

test('requests derive from canonical asks and leave approved input refs untouched',()=>{const s=state(),before=structuredClone(s.inputs),r=deriveOwnerRequests(s,{now:()=>10})[0];assert.equal(r.workflowId,'wf');assert.equal(r.opId,'ask-1');assert.equal(r.attempt,2);assert.equal(r.generation,3);assert.equal(r.jobId,'job-1');assert.equal(r.guidance.where,'Provider console');assert.deepEqual(s.inputs,before);assert.equal(s.ownerRequests,undefined);});
test('credential presence is saved but only a kernel verification receipt marks it verified',()=>{const s=state(),r=deriveOwnerRequests(s)[0];const saved=applyOwnerAction(s,{type:'credential-saved',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,storageReceipt:{status:'present',custody:'identity:payments',variables:['PAYMENTS_KEY']}});assert.equal(saved.ok,true);assert.equal(saved.request.status,'saved');assert.equal(s.ops[0].ownerVerification,undefined);let current=saved.request;assert.equal(applyOwnerAction(s,{type:'verification',workflowId:'wf',requestId:current.id,generation:3,revision:1,actor,verificationReceiptId:'fake'}).ok,false);const verified=applyOwnerAction(s,{type:'verification',workflowId:'wf',requestId:current.id,generation:3,revision:1,actor:{type:'kernel',receiptId:'v1'},verificationReceiptId:'v1'},{verificationReceipts:[{id:'v1',requestId:current.id,origin:'kernel-verification',status:'verified'}]});assert.equal(verified.request.status,'verified');});
test('provider verification binds the accepted integration check to exact credential revisions',()=>{const s=state(),r=deriveOwnerRequests(s)[0],versions={PAYMENTS_KEY:{ciphertextDigest:'a',writeRevision:'rev'}};const saved=applyOwnerAction(s,{type:'credential-saved',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,storageReceipt:{status:'present',custody:'identity:payments',variables:['PAYMENTS_KEY'],versions}});const input={requestId:saved.request.id,generation:3,acceptedOp:{kind:'integration.verify',status:'done',generation:3},evidence:{evidenceResolved:true},acceptance:{verdict:'pass'},credentialVersions:versions,receiptId:'verify-1',now:()=>10};assert.equal(applyOwnerVerification(s,{...input,credentialVersions:{PAYMENTS_KEY:{writeRevision:'other'}}}).code,'credential-version-mismatch');const verified=applyOwnerVerification(s,input);assert.equal(verified.ok,true);assert.equal(verified.request.status,'verified');});
test('accepted integration verifies only its related request at the exact launch versions',()=>{
  const s=state(),version={ciphertextDigest:'a',writeRevision:'rev'},r=deriveOwnerRequests(s)[0];s.ops[0].requesters=['verify-payments'];
  applyOwnerAction(s,{type:'credential-saved',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,storageReceipt:{status:'present',custody:'identity:payments',variables:['PAYMENTS_KEY'],versions:{PAYMENTS_KEY:version}}});
  const op={id:'verify-payments',kind:'integration.verify',status:'done',attempt:1,generation:3,credentialVersions:[{name:'PAYMENTS_KEY',custody:'identity:payments',version}]};
  const evidence={evidenceResolved:true},acceptance={verdict:'pass'},receiptFor=({request})=>({id:'receipt-'+request.id});
  assert.equal(verifyAcceptedIntegrationOwnerRequests(s,{op,evidence,acceptance,receiptFor}).filter(x=>x.ok).length,1);assert.equal(deriveOwnerRequests(s)[0].status,'verified');
});
test('unrelated verifier and stale credential launch cannot mark a saved request verified',()=>{for(const mode of ['unrelated','stale']){const s=state(),stored={ciphertextDigest:'a',writeRevision:'rev'},r=deriveOwnerRequests(s)[0];s.ops[0].requesters=['verify-payments'];applyOwnerAction(s,{type:'credential-saved',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,storageReceipt:{status:'present',custody:'identity:payments',variables:['PAYMENTS_KEY'],versions:{PAYMENTS_KEY:stored}}});const op={id:mode==='unrelated'?'verify-other':'verify-payments',kind:'integration.verify',status:'done',generation:3,credentialVersions:[{name:'PAYMENTS_KEY',custody:'identity:payments',version:mode==='stale'?{...stored,writeRevision:'old'}:stored}]};const results=verifyAcceptedIntegrationOwnerRequests(s,{op,evidence:{evidenceResolved:true},acceptance:{verdict:'pass'},receiptFor:()=>({id:'receipt'})});assert.equal(results.some(x=>x.ok),false);assert.equal(deriveOwnerRequests(s)[0].status,'saved');}});
test('authority needs an actual owner receipt and explicit confirmation',()=>{const s=state();s.ops[0]={id:'ask-auth',kind:'decision.prepare',status:'waiting-owner',question:{kind:'authority',subject:'Publish release'}};const r=deriveOwnerRequests(s)[0];assert.equal(applyOwnerAction(s,{type:'confirm',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor:{type:'model'},value:true}).code,'owner-receipt-required');assert.equal(applyOwnerAction(s,{type:'answer',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,value:'yes'}).code,'explicit-confirmation-required');assert.equal(applyOwnerAction(s,{type:'confirm',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,value:true}).ok,true);});
test('a decision queued behind the writer is shown as preparing, with no answer control, until it launches',()=>{const s=state();s.ops=[{id:'ask-1',kind:'decision.prepare',status:'running',attempt:9,question:{kind:'decision',subject:'Registration path',text:'Which path?'}},{id:'ask-2',kind:'decision.prepare',status:'ready',attempt:5,question:{kind:'decision',subject:'Suspension authority',text:'Who may revoke?'}},{id:'ask-3',kind:'decision.prepare',status:'pending',attempt:1,question:{kind:'decision',subject:'Billing ledger',text:'Where is platform billing recorded?'}}];
  assert.deepEqual(deriveOwnerRequests(s).map(item=>[item.opId,item.kind,item.status]),[['ask-1','business-decision','waiting-owner'],['ask-2','business-decision','preparing'],['ask-3','business-decision','preparing']]);
  const {applyOwnerAction:apply}={applyOwnerAction};const preparing=deriveOwnerRequests(s)[1];
  assert.equal(apply(s,{requestId:preparing.id,revision:preparing.revision,type:'answer',value:'early',actor}).ok,false,'a preparing request takes no answer');});
test('settled legacy ask operations do not reappear as owner requests',()=>{const s=state();s.ops[0].status='done';s.ops[0].answer={via:'fill'};assert.deepEqual(deriveOwnerRequests(s),[]);});
test('a prepared legacy decision remains owner-answerable while superseded review-epoch asks disappear',()=>{const s=state();s.ops=[{id:'ask-2',kind:'decision.prepare',status:'done',attempt:1,requesters:['work'],question:{kind:'hidden-decision',stop:'credential',text:'Choose the canonical policy',options:[]}},{id:'ask-15',kind:'decision.prepare',status:'blocked',attempt:1,refusal:'superseded',question:{kind:'hidden-decision',text:'Retired question'}}];s.needUser=[{op:'ask-2',kind:'decision',record:'demo.policy.decision',options:['Policy A','Policy B'],requesters:['work']}];const requests=deriveOwnerRequests(s);assert.deepEqual(requests.map(item=>[item.opId,item.kind,item.status,item.options.length]),[['ask-2','business-decision','waiting-owner',2]]);const applied=applyOwnerAction(s,{type:'choose',workflowId:'wf',requestId:requests[0].id,generation:3,revision:0,actor,value:'2'});assert.equal(applied.ok,true);assert.equal(s.ops[0].ownerAnswer.selectedLabel,'Policy B');assert.equal(s.ops[0].ownerAnswer.decisionRecord,'demo.policy.decision');});
test('an authenticated owner receipt is idempotent and stale replay cannot change authority',()=>{const s=state();s.ops[0]={id:'ask-auth',kind:'decision.prepare',status:'waiting-owner',question:{kind:'authority',subject:'Publish'}};const r=deriveOwnerRequests(s)[0],action={type:'confirm',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,value:true};assert.equal(applyOwnerAction(s,action).ok,true);assert.equal(applyOwnerAction(s,action).code,'request-stale');assert.equal(s.ops[0].ownerAnswer.receiptId,actor.receiptId);});
test('a successful inbox receipt resumes its requester once with the normalized answer',()=>{const events=[],store={appendEvent:event=>events.push(event)},s=state();s.ops=[{id:'work',kind:'backend.implement',status:'paused',waitingFor:'ask-auth'},{id:'ask-auth',kind:'decision.prepare',status:'waiting-owner',requesters:['work'],question:{kind:'business-decision',subject:'Retention',record:'RETENTION',options:[{id:'short',label:'30 days'}]}}];const r=deriveOwnerRequests(s)[0],applied=applyOwnerAction(s,{type:'choose',workflowId:'wf',requestId:r.id,generation:3,revision:0,actor,value:'short'});assert.equal(continueOwnerRequest(store,s,{receipt:applied.receipt,currentRequest:applied.request}).code,'continued');assert.equal(s.ops[0].status,'ready');assert.match(s.ops[0].answer,/RETENTION: selected 30 days/);assert.deepEqual(continueOwnerRequest(store,s,{receipt:applied.receipt,currentRequest:applied.request}),{ok:true,code:'already-continued',resumed:[]});assert.equal(events.filter(event=>event.event==='owner-action-continued').length,1);});
test('an enrolled workflow never turns an ask report recommendation into a provisional owner decision',()=>{const events=[],s=state();s.engine={schema:'starci/engine@1'};s.provisional=[];s.needUser=[];s.ops=[{id:'requester',kind:'backend.implement',status:'paused'},{id:'ask-decision',kind:'decision.prepare',status:'running',requesters:['requester'],question:{kind:'business-decision',text:'Choose retention',options:['30 days','1 year']}}];settleOwnerAsk({appendEvent:event=>events.push(event)},s,s.ops[1],{summary:'decision: RETENTION recommended: 1 1. 30 days 2. 1 year'});assert.deepEqual(s.provisional,[]);assert.equal(s.ops[0].status,'paused');assert.equal(s.ops[1].ownerRequestStatus,'waiting-owner');assert.equal(s.needUser.length,1);assert.equal(events.at(-1).ownerRequired,true);});
// §8: the HTTP seam queues one `inbox` row in the ledger — no directory, no temp file, no rename.
test('HTTP seam queues only and kernel applies once through the canonical inbox',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-owner-'));
  const store=createStore({repoRoot:root,id:'wf'});
  t.after(()=>{try{store.close();}catch{}fs.rmSync(root,{recursive:true,force:true});});
  const s={...state(),schema:store.schema},r=deriveOwnerRequests(s)[0];
  const payload={schema:'starci/owner-action@1',action:{type:'credential-saved',workflowId:'wf',opId:'ask-1',attempt:2,jobId:'owner-job',requestId:r.id,generation:3,revision:0,actor,
    storageReceipt:{status:'present',custody:'identity:payments',variables:['PAYMENTS_KEY']}}};
  const result=enqueueOwnerInbox(store,payload,{now:()=>1,random:()=>'x'});
  assert.equal(result.code,'queued');assert.equal(result.job.kind,'owner-action');assert.equal(result.eventId,'owner-1-x');
  assert.equal(s.ops[0].ownerAnswer,undefined,'queueing alone grants no authority and touches no state');
  const pending=store.inbox.pending();
  assert.deepEqual(pending.map(item=>[item.kind,item.key]),[['owner-action',r.id]],'the queue is one ledger row');
  assert.deepEqual(pending[0].payload,result.job);
  assert.equal(applyOwnerInbox(store,s,pending[0].payload).ok,true);
  assert.ok(store.readEvents().some(event=>event.event==='owner-inbox-applied'));
});
