import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {checkScopedLint,codePatternExitCode} from '../scripts/checks/check-scoped-lint.mjs';

const run=(cwd,args)=>{const result=spawnSync('git',['-c','user.name=spec','-c','user.email=spec@example.invalid','-c','commit.gpgsign=false',...args],{cwd,encoding:'utf8',windowsHide:true});assert.equal(result.status,0,result.stderr);return result.stdout.trim();};
const source=debt=>`export function SiteShell() {\n  return null;\n}\n${debt?'// DEBT\n':''}`;
const catalog={schema:'starci/code-pattern-profile@1',profiles:{next:{canon:{package:'@starci/eslint-canon-fe',version:'1.0.0',contentDigest:{algorithm:'sha256',include:['**/*.mjs'],exclude:[],framing:'sorted-posix-relative-path-null-raw-bytes-null',value:'a'.repeat(64),files:1}},expectedSourceRuleIds:['FE-1'],sourceGlobs:['src/**/*.tsx'],inputGlobs:[],semanticOnly:[],obligations:[{id:'NEXT-SHAPE',sourceRuleIds:['FE-1'],applicability:{include:['**/*.tsx']},status:'implemented',mechanical:{requirement:'x',check:{kind:'architecture',ruleIds:['FE_CUSTOM_HOOK_LOCATION']}}}]}}};
const runtime={package:{name:'@starci/eslint-canon-fe',version:'1.0.0',digest:'a'.repeat(64),files:1},canon:{rules:{},recommended:{}},builtinRules:new Map(),typescriptRules:{},eslintVersion:'fixture',eslint:{isPathIgnored:async()=>false,calculateConfigForFile:async()=>({linterOptions:{noInlineConfig:true},rules:{},plugins:{}}),lintFiles:async files=>files.map(filePath=>({filePath,messages:fs.readFileSync(filePath,'utf8').split(/\r?\n/).flatMap((line,index)=>line.includes('console.log')?[{ruleId:'no-console',severity:2,line:index+1,message:'Unexpected console statement.'}]:[]),suppressedMessages:[],errorCount:0,warningCount:0,fatalErrorCount:0}))}};
const architecture=({repositoryRoot})=>{const files=['src/SiteShell.tsx','src/SiteShell/component.tsx','src/SiteShell/index.tsx'].filter(file=>fs.existsSync(path.join(repositoryRoot,file)));const violations=files.flatMap(file=>fs.readFileSync(path.join(repositoryRoot,file),'utf8').split(/\r?\n/).flatMap((line,index)=>line.includes('DEBT')?[{ruleId:'FE_CUSTOM_HOOK_LOCATION',path:file,line:index+1}]:[]));return {schema:'starci/architecture-check@1',ok:!violations.length,kinds:['frontend'],files:files.length,violations,errors:[],coverage:{sourceFiles:files,checkedRuleIds:['FE_CUSTOM_HOOK_LOCATION']}};};
function fixture(t,{debt=false}={}){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'starci-rename-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'src/SiteShell.tsx'),source(debt));run(root,['init','-q','-b','main']);run(root,['add','-A']);run(root,['commit','-q','-m','base']);const base=run(root,['rev-parse','HEAD']);fs.mkdirSync(path.join(root,'src/SiteShell'));run(root,['mv','src/SiteShell.tsx','src/SiteShell/component.tsx']);const destination=path.join(root,'src/SiteShell/component.tsx');const check=(inputs=['src/SiteShell.tsx'])=>checkScopedLint(root,inputs,{profile:'next',profileCatalog:catalog,runtime,architecture,base});return {root,base,destination,check};}

test('a clean moved file passes the admission path scope',async t=>{const r=fixture(t);const report=await r.check();assert.equal(report.slice.status,'clean',JSON.stringify(report.slice.issues));assert.equal(codePatternExitCode(report),0);assert.deepEqual(report.slice.files,['src/SiteShell/component.tsx']);});
test('a new finding on a changed line of a moved file gates the slice',async t=>{const r=fixture(t);fs.writeFileSync(r.destination,source(false).replace('  return null;','  console.log("new");\n  return null;'));const report=await r.check();assert.equal(report.slice.status,'findings',JSON.stringify(report.slice));assert.equal(codePatternExitCode(report),1);assert.ok(report.slice.issues.some(issue=>issue.ruleId==='no-console'&&issue.newBecause==='changed-line'));});
test('a finding carried by a moved file stays preexisting',async t=>{const r=fixture(t,{debt:true});const report=await r.check();assert.equal(report.slice.status,'clean',JSON.stringify(report.slice.issues));assert.equal(report.slice.preexisting[0]?.code,'SLICE_PREEXISTING_FINDINGS');assert.equal(report.slice.preexisting[0]?.file,'src/SiteShell/component.tsx');});
test('a carried finding repeated on a changed line still gates the slice',async t=>{const r=fixture(t,{debt:true});fs.writeFileSync(r.destination,source(true).replace('  return null;','  return null; // DEBT'));const report=await r.check();assert.equal(report.slice.status,'findings',JSON.stringify(report.slice));assert.ok(report.slice.issues.some(issue=>issue.ruleId==='FE_CUSTOM_HOOK_LOCATION'&&issue.line===2&&issue.newBecause==='changed-line'));});
test('a deleted admission file does not make the slice unavailable',async t=>{const r=fixture(t);fs.rmSync(r.destination);const report=await r.check();assert.equal(report.slice.status,'clean',JSON.stringify(report));assert.deepEqual(report.slice.files,[]);});
test('a new file under an owned directory joins the scoped lint set',async t=>{const r=fixture(t);fs.writeFileSync(path.join(r.root,'src/SiteShell/index.tsx'),'export const index = 1;\n');const report=await r.check(['src/SiteShell.tsx','src/SiteShell']);assert.equal(report.slice.status,'clean',JSON.stringify(report.slice.issues));assert.deepEqual(report.slice.files,['src/SiteShell/component.tsx','src/SiteShell/index.tsx']);});
