import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import Ajv2020 from 'ajv/dist/2020.js';
import {canonicalJSON,sha256} from '../core/index.mjs';
import {parseYaml} from '../core/yaml.mjs';
import {measureAuditChecks} from '../kernel/audit.mjs';
import {checkScopedLint,codePatternExitCode,inspectLintResults,parseScopedLintArgs,scopedLintMain,verifyCodePatternReportDigest} from '../scripts/check-scoped-lint.mjs';

const require=createRequire(import.meta.url),targetTypescript={ts:require('typescript'),resolved:require.resolve('typescript'),version:require('typescript').version};

const file=path.resolve('owned.ts');
test('lint integrity accepts an exact unsuppressed clean result',()=>assert.deepEqual(inspectLintResults([file],[{filePath:file,messages:[],suppressedMessages:[]}]),[]));
test('lint integrity rejects suppressed violations even when ordinary messages are empty',()=>assert.equal(inspectLintResults([file],[{filePath:file,messages:[],suppressedMessages:[{ruleId:'canon/rule'}]}])[0].code,'SUPPRESSED_MESSAGE'));
test('lint integrity rejects warning, fatal, missing, duplicate and unrelated results',()=>{for(const message of [{severity:1},{severity:2},{fatal:true}])assert.equal(inspectLintResults([file],[{filePath:file,messages:[message]}])[0].code,'LINT_MESSAGE');assert.equal(inspectLintResults([file],[])[0].code,'MISSING_RESULT');assert.ok(inspectLintResults([file],[{filePath:file},{filePath:file}]).some(issue=>issue.code==='DUPLICATE_RESULT'));assert.ok(inspectLintResults([file],[{filePath:path.resolve('other.ts')}]).some(issue=>issue.code==='UNEXPECTED_FILE'));});

const digest='a'.repeat(64);
const catalog=({status='implemented',architectureStatus='implemented',scriptStatus=null,inputGlobs=[]}={})=>({schema:'starci/code-pattern-profile@1',profiles:{next:{title:'Fixture Next profile',canon:{package:'@starci/eslint-canon-fe',version:'3.0.2',contentDigest:{algorithm:'sha256',include:['**/*.mjs'],exclude:['**/*.test.mjs'],framing:'sorted-posix-relative-path-null-raw-bytes-null',value:digest,files:1}},sourceRuleRoots:['knowledge/patterns/fe'],expectedSourceRuleIds:['FE-FUNCTION-1'],sourceGlobs:['src/**/*.tsx'],inputGlobs,obligations:[
  {id:'NEXT-EXPORT',sourceRuleIds:['FE-FUNCTION-1'],applicability:{include:['src/**/*.tsx'],exclude:['**/*.spec.tsx']},mechanical:{requirement:'Use the canonical export form.',check:{kind:'eslint',ruleIds:['starci-fe/prefer-arrow-export'],expected:{severity:'error'}}},semantic:{guidance:'docs/pattern.md',review:'Decide whether this is a component.'},status},
  {id:'NEXT-ROUTE',sourceRuleIds:['FE-FUNCTION-1'],applicability:{include:['src/**/*.tsx']},mechanical:{requirement:'Keep route dependencies directed.',check:{kind:'architecture',ruleIds:['FE_ROUTE_ONE_PAGE'],externalResult:{schema:'starci/architecture-check@1',command:'starci architecture check'}}},semantic:{guidance:'docs/pattern.md',review:'Inspect the route responsibility.'},status:architectureStatus},
  ...(scriptStatus?[{id:'NEXT-STATIC',sourceRuleIds:['FE-FUNCTION-1'],applicability:{include:['src/**/*.tsx']},mechanical:{requirement:'Apply the explicit static syntax contract.',check:{kind:'script',ruleIds:['FE_SOURCE_NAME_SHAPE'],externalResult:{schema:'starci/code-pattern-script@1',command:'starci code-pattern script'}}},semantic:{guidance:'docs/pattern.md',review:'Confirm the declared role.'},status:scriptStatus}]:[])],semanticOnly:[]}}});
const fixture=t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-code-pattern-'));fs.mkdirSync(path.join(root,'src'),{recursive:true});const source=path.join(root,'src','component.tsx');fs.writeFileSync(source,'export const Component = () => null\n');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,source};};
const architecture=()=>({schema:'starci/architecture-check@1',ok:true,repository:'fixture',kinds:['frontend'],files:2,compiler:{version:'fixture'},violations:[],errors:[],coverage:{sourceFiles:['src/component.tsx','src/other.tsx'],checkedRuleIds:['FE_ROUTE_ONE_PAGE'],ownerPublicApi:{status:'checked'},grammarContract:{status:'checked'}},limitations:['static']});
const runtime=(source,{rules={'starci-fe/prefer-arrow-export':[2]},noInlineConfig=true,ignored=false,results=null,canonRule={},configuredCanonRule=canonRule,onLint=null}={})=>({package:{name:'@starci/eslint-canon-fe',version:'3.0.2',digest,files:1},canon:{rules:{'prefer-arrow-export':canonRule},recommended:{}},builtinRules:new Map([['no-console',{}]]),typescriptRules:{},eslintVersion:'fixture',eslint:{isPathIgnored:async()=>ignored,calculateConfigForFile:async()=>({linterOptions:{noInlineConfig},rules,plugins:{'starci-fe':{rules:{'prefer-arrow-export':configuredCanonRule}}}}),lintFiles:async()=>{onLint?.();return results??[{filePath:source,messages:[],suppressedMessages:[],errorCount:0,warningCount:0,fatalErrorCount:0}];}}});

test('the authored profile, effective config, architecture result and actual ESLint result are all required for clean',async t=>{const {root,source}=fixture(t),report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture});assert.equal(report.status,'clean');assert.equal(report.ok,true);assert.equal(codePatternExitCode(report),0);assert.equal(verifyCodePatternReportDigest(report),true);assert.deepEqual(report.coverage.covered,['NEXT-EXPORT','NEXT-ROUTE']);assert.deepEqual(report.coverage.expectedFiles,['src/component.tsx']);assert.equal(report.machineResults[0].schema,'starci/architecture-check@1');});

test('missing, weakened, ignored, suppressed and incomplete file coverage can never produce a clean gate',async t=>{const {root,source}=fixture(t);const other=path.join(root,'src','other.tsx');fs.writeFileSync(other,'export const Other = () => null\n');const cleanResults=[source,other].map(filePath=>({filePath,messages:[],suppressedMessages:[],errorCount:0,warningCount:0,fatalErrorCount:0}));const cases=[
  {name:'missing file',inputs:['src/component.tsx'],options:{results:cleanResults},code:'SOURCE_FILE_UNCHECKED'},
  {name:'weakened rule',inputs:['src/component.tsx','src/other.tsx'],options:{rules:{'starci-fe/prefer-arrow-export':[1]},results:cleanResults},code:'REQUIRED_RULE_MISMATCH'},
  {name:'inline config accepted',inputs:['src/component.tsx','src/other.tsx'],options:{noInlineConfig:false,results:cleanResults},code:'INLINE_CONFIG_NOT_REFUSED'},
  {name:'ignored file',inputs:['src/component.tsx','src/other.tsx'],options:{ignored:true,results:cleanResults},code:'FILE_IGNORED'},
  {name:'suppressed result',inputs:['src/component.tsx','src/other.tsx'],options:{results:[{filePath:source,messages:[],suppressedMessages:[{ruleId:'starci-fe/prefer-arrow-export'}]},cleanResults[1]]},code:'SUPPRESSED_MESSAGE'}];
  for(const scenario of cases){const report=await checkScopedLint(root,scenario.inputs,{profile:'next',profileCatalog:catalog(),runtime:runtime(source,scenario.options),architecture});assert.notEqual(report.status,'clean',scenario.name);assert.ok(report.issues.some(issue=>issue.code===scenario.code),scenario.name);assert.equal(codePatternExitCode(report),1,scenario.name);}});

test('manifest gaps are findings and unavailable architecture inputs are a distinct failure',async t=>{const {root,source}=fixture(t),missing=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({status:'missing'}),runtime:runtime(source),architecture});assert.equal(missing.status,'findings');assert.ok(missing.issues.some(issue=>issue.code==='MECHANICAL_CHECK_MISSING'));const unavailable=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture:()=>({...architecture(),ok:false,errors:[{ruleId:'ARCH_CONFIG_INVALID'}]})});assert.equal(unavailable.status,'unavailable');assert.equal(codePatternExitCode(unavailable),2);assert.ok(unavailable.issues.some(issue=>issue.code==='ARCHITECTURE_INPUT_UNAVAILABLE'));});

test('a script obligation runs its exact selected files and rule IDs and cannot conceal findings or unavailable inputs',async t=>{const {root,source}=fixture(t),base={schema:'starci/code-pattern-script@1',repository:root,files:['src/component.tsx'],checkedRuleIds:['FE_SOURCE_NAME_SHAPE'],violations:[],errors:[],compiler:{version:'fixture',resolved:true}},calls=[];const clean=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({scriptStatus:'implemented'}),runtime:runtime(source),architecture,scriptChecker:async(profile,input)=>{calls.push({profile,input});return base;}});assert.equal(clean.status,'clean');assert.deepEqual(calls,[{profile:'next',input:{root,files:['src/component.tsx'],ruleIds:['FE_SOURCE_NAME_SHAPE'],contextFiles:['src/component.tsx']}}]);assert.equal(clean.machineResults.find(result=>result.kind==='script').obligation,'NEXT-STATIC');assert.ok(clean.coverage.covered.includes('NEXT-STATIC'));
  const finding=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({scriptStatus:'implemented'}),runtime:runtime(source),architecture,scriptChecker:async()=>({...base,violations:[{ruleId:'FE_SOURCE_NAME_SHAPE',path:'src/component.tsx',line:1,column:1,message:'Name is outside the declared shape.'}]})});assert.equal(finding.status,'findings');assert.ok(finding.issues.some(issue=>issue.code==='SCRIPT_PATTERN_VIOLATION'));
  const unavailable=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({scriptStatus:'implemented'}),runtime:runtime(source),architecture,scriptChecker:async()=>({...base,files:[],checkedRuleIds:[],errors:[{ruleId:'FE_SOURCE_NAME_SHAPE',path:'src/component.tsx',message:'Role contract is missing.'}],compiler:null})});assert.equal(unavailable.status,'unavailable');assert.equal(codePatternExitCode(unavailable),2);assert.ok(unavailable.issues.some(issue=>issue.code==='SCRIPT_INPUT_UNAVAILABLE'));assert.ok(!unavailable.issues.some(issue=>issue.code==='SCRIPT_RESULT_INVALID'));
  const wrongScope=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({scriptStatus:'implemented'}),runtime:runtime(source),architecture,scriptChecker:async()=>({...base,files:[]})});assert.equal(wrongScope.status,'unavailable');assert.ok(wrongScope.issues.some(issue=>issue.code==='SCRIPT_RESULT_INVALID'));});

test('an authored source rule missing from the mechanical and semantic inventories makes the profile invalid',async t=>{const {root,source}=fixture(t),invalid=catalog();invalid.profiles.next.expectedSourceRuleIds.push('FE-UNMAPPED');const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:invalid,runtime:runtime(source),architecture});assert.equal(report.status,'invalid');assert.ok(report.issues.some(issue=>issue.code==='PROFILE_INVENTORY_INVALID'));});

test('an adopted legacy-rule guard requires an explicit off setting and cannot pass when the rule is merely absent',async t=>{const {root,source}=fixture(t),profile=catalog();profile.profiles.next.obligations[0].mechanical.check={kind:'eslint',ruleIds:['no-console'],expected:{severity:'off'}};const absent=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:profile,runtime:runtime(source,{rules:{}}),architecture});assert.equal(absent.status,'findings');assert.ok(absent.issues.some(issue=>issue.code==='REQUIRED_RULE_MISSING'&&issue.ruleId==='no-console'));const disabled=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:profile,runtime:runtime(source,{rules:{'no-console':'off'}}),architecture});assert.equal(disabled.status,'clean');});

test('a private implementation substituted under a canonical rule ID cannot satisfy the authored obligation',async t=>{const {root,source}=fixture(t),report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source,{configuredCanonRule:{create:()=>({})}}),architecture});assert.equal(report.status,'findings');assert.ok(report.issues.some(issue=>issue.code==='REQUIRED_RULE_IMPLEMENTATION_UNAVAILABLE'&&issue.ruleId==='starci-fe/prefer-arrow-export'));});

test('source and config bytes are fingerprinted before and after execution and a scan race fails unavailable',async t=>{const {root,source}=fixture(t),report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source,{onLint:()=>fs.appendFileSync(source,'// changed during scan\n')}),architecture});assert.equal(report.status,'unavailable');assert.equal(report.inputs.stable,false);assert.ok(report.issues.some(issue=>issue.code==='INPUTS_CHANGED_DURING_CHECK'));});

test('a lint configuration mutation during execution also invalidates the measured result',async t=>{const {root,source}=fixture(t),configuration=path.join(root,'package.json');fs.writeFileSync(configuration,'{"type":"module"}\n');const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source,{onLint:()=>fs.writeFileSync(configuration,'{"type":"module","private":true}\n')}),architecture});assert.equal(report.status,'unavailable');assert.equal(report.inputs.stable,false);assert.ok(report.inputs.before.files.includes('package.json'));});

test('a matching source directory named dist is covered at nested and repository-root positions',async t=>{const {root,source}=fixture(t),nested=path.join(root,'src','dist','live.tsx'),rootDist=path.join(root,'dist','root-live.tsx');fs.mkdirSync(path.dirname(nested),{recursive:true});fs.mkdirSync(path.dirname(rootDist),{recursive:true});fs.writeFileSync(nested,'export const Live = () => null\n');fs.writeFileSync(rootDist,'export const RootLive = () => null\n');const files=[source,nested,rootDist],results=files.map(filePath=>({filePath,messages:[],suppressedMessages:[],errorCount:0,warningCount:0,fatalErrorCount:0})),profile=catalog();profile.profiles.next.sourceGlobs=['**/*.tsx'];const report=await checkScopedLint(root,[],{profile:'next',profileCatalog:profile,runtime:runtime(source,{results}),architecture:()=>({...architecture(),files:3,coverage:{...architecture().coverage,sourceFiles:['dist/root-live.tsx','src/component.tsx','src/dist/live.tsx']}}),all:true});assert.ok(report.coverage.expectedFiles.includes('dist/root-live.tsx'));assert.ok(report.coverage.expectedFiles.includes('src/dist/live.tsx'));assert.equal(report.status,'clean');});

test('a junction directory beneath an applicable source root is unavailable even when its name does not match the file glob',async t=>{const {root,source}=fixture(t),external=fs.mkdtempSync(path.join(os.tmpdir(),'starci-linked-source-'));t.after(()=>fs.rmSync(external,{recursive:true,force:true}));fs.writeFileSync(path.join(external,'hidden.tsx'),'export const Hidden = () => null\n');fs.symlinkSync(external,path.join(root,'src','linked'),'junction');const report=await checkScopedLint(root,[],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,all:true});assert.equal(report.status,'unavailable');assert.ok(report.issues.some(issue=>issue.code==='SOURCE_PATH_UNSAFE'&&issue.file==='src/linked'));assert.ok(!report.coverage.expectedFiles.includes('src/linked/hidden.tsx'));});

test('a file redirection is unavailable using a file symlink where supported and an enclosing Windows junction otherwise',async t=>{const {root,source}=fixture(t),external=fs.mkdtempSync(path.join(os.tmpdir(),'starci-linked-file-')),target=path.join(external,'linked.tsx');t.after(()=>fs.rmSync(external,{recursive:true,force:true}));fs.writeFileSync(target,'export const Linked = () => null\n');let rejectedPath='src/linked-file.tsx',variant='file-symlink';try{fs.symlinkSync(target,path.join(root,'src','linked-file.tsx'),'file');}catch(error){if(error?.code!=='EPERM')throw error;variant='directory-junction';rejectedPath='src/linked-file-container';fs.symlinkSync(external,path.join(root,rejectedPath),'junction');}const report=await checkScopedLint(root,[],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,all:true});assert.equal(report.status,'unavailable');assert.ok(report.issues.some(issue=>issue.code==='SOURCE_PATH_UNSAFE'&&issue.file===rejectedPath),variant);assert.ok(['file-symlink','directory-junction'].includes(variant));});

test('static lint configuration dependencies under nested generated-named folders are fingerprinted on both sides of execution',async t=>{const {root,source}=fixture(t),configuration=path.join(root,'eslint.config.mjs'),helper=path.join(root,'src','dist','config-helper.mjs');fs.mkdirSync(path.dirname(helper),{recursive:true});fs.writeFileSync(helper,'export const rules = {}\n');fs.writeFileSync(configuration,"import { rules } from './src/dist/config-helper.mjs'; export default [{ rules }];\n");const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source,{onLint:()=>fs.appendFileSync(helper,'// changed during scan\n')}),architecture,configCompiler:targetTypescript});assert.equal(report.status,'unavailable');assert.equal(report.inputs.stable,false);assert.ok(report.inputs.before.files.includes('eslint.config.mjs'));assert.ok(report.inputs.before.files.includes('src/dist/config-helper.mjs'));assert.ok(report.issues.some(issue=>issue.code==='INPUTS_CHANGED_DURING_CHECK'));});

test('a dynamic lint configuration dependency is unavailable instead of silently omitted',async t=>{const {root,source}=fixture(t);fs.writeFileSync(path.join(root,'eslint.config.mjs'),"const selected = './rules.mjs'; export default await import(selected);\n");const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,configCompiler:targetTypescript});assert.equal(report.status,'unavailable');assert.ok(report.issues.some(issue=>issue.code==='CONFIG_DEPENDENCY_UNAVAILABLE'));});

test('TypeScript JSONC configuration and inherited JSONC inputs use the target parser',async t=>{const {root,source}=fixture(t),base=path.join(root,'config','tsconfig.base.json');fs.mkdirSync(path.dirname(base),{recursive:true});fs.writeFileSync(base,'{ /* inherited */ "compilerOptions": { "strict": true, }, }\n');fs.writeFileSync(path.join(root,'tsconfig.json'),'{ // root\n "extends": "./config/tsconfig.base.json",\n "include": ["src/**/*.tsx",],\n}\n');const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,configCompiler:targetTypescript});assert.ok(report.inputs.before.files.includes('config/tsconfig.base.json'));assert.ok(!report.issues.some(issue=>issue.code==='CONFIG_SOURCE_INVALID'));assert.equal(report.status,'clean');});

test('an unrelated linked archive cannot poison anchored source and configuration scope',async t=>{const {root,source}=fixture(t),external=fs.mkdtempSync(path.join(os.tmpdir(),'starci-unrelated-config-'));t.after(()=>fs.rmSync(external,{recursive:true,force:true}));fs.writeFileSync(path.join(external,'.eslintrc.json'),'{}\n');fs.symlinkSync(external,path.join(root,'archive'),'junction');const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture});assert.equal(report.status,'clean');assert.ok(!report.issues.some(issue=>issue.code==='SOURCE_PATH_UNSAFE'||issue.code==='CONFIG_PATH_UNSAFE'));});

test('an installed config package is byte-bound without interpreting its internal dynamic loading as authored config',async t=>{const {root,source}=fixture(t),packageRoot=path.join(root,'node_modules','fixture-eslint-config'),entry=path.join(packageRoot,'index.mjs');fs.mkdirSync(packageRoot,{recursive:true});fs.writeFileSync(path.join(packageRoot,'package.json'),'{"name":"fixture-eslint-config","version":"1.0.0","exports":"./index.mjs"}\n');fs.writeFileSync(entry,"const selected = process.env.FIXTURE; export default selected ? import(selected) : [];\n");fs.writeFileSync(path.join(root,'eslint.config.mjs'),"import config from 'fixture-eslint-config'; export default config;\n");const report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source,{onLint:()=>fs.appendFileSync(entry,'// changed during scan\n')}),architecture,configCompiler:targetTypescript});assert.equal(report.status,'unavailable');assert.ok(report.issues.some(issue=>issue.code==='INPUTS_CHANGED_DURING_CHECK'));assert.ok(!report.issues.some(issue=>issue.code==='CONFIG_DEPENDENCY_UNAVAILABLE'));});

test('metadata inputs declared by a script obligation are inventoried and passed to that checker',async t=>{const {root,source}=fixture(t),metadata=path.join(root,'jest.config.ts');fs.writeFileSync(metadata,'export default {}\n');const profile=catalog({scriptStatus:'implemented',inputGlobs:['jest.config.ts']});profile.profiles.next.obligations.at(-1).applicability={include:['jest.config.ts']};let observed=null;const report=await checkScopedLint(root,[],{profile:'next',profileCatalog:profile,runtime:runtime(source),architecture,all:true,scriptChecker:async(_profile,input)=>{observed=input;return {schema:'starci/code-pattern-script@1',repository:root,files:['jest.config.ts'],checkedRuleIds:['FE_SOURCE_NAME_SHAPE'],violations:[],errors:[],compiler:{version:'fixture',resolved:true}};}});assert.ok(report.coverage.expectedFiles.includes('jest.config.ts'));assert.deepEqual(observed.files,['jest.config.ts']);assert.equal(report.status,'clean');});

test('Nest metadata preflight inputs and tools bind the parent snapshot and the checker receives the full authored context',async t=>{const {root}=fixture(t),source=path.join(root,'src','service.ts'),helper=path.join(root,'config','jest-helper.json');fs.rmSync(path.join(root,'src','component.tsx'));fs.writeFileSync(source,'export const service = 1\n');fs.mkdirSync(path.dirname(helper),{recursive:true});fs.writeFileSync(helper,'{}\n');fs.writeFileSync(path.join(root,'package.json'),'{}\n');const profile={schema:'starci/code-pattern-profile@1',profiles:{nest:{title:'Fixture Nest profile',canon:{package:'@starci/eslint-canon-be',version:'3.0.2',contentDigest:{algorithm:'sha256',include:['**/*.mjs'],exclude:[],framing:'sorted-posix-relative-path-null-raw-bytes-null',value:digest,files:1}},sourceRuleRoots:['knowledge/patterns/be'],expectedSourceRuleIds:['BE-TEST-1'],sourceGlobs:['src/**/*.ts'],inputGlobs:['package.json'],obligations:[{id:'NEST-JEST-ALIAS-PARITY',sourceRuleIds:['BE-TEST-1'],applicability:{include:['package.json']},mechanical:{requirement:'Measure exact Jest metadata.',check:{kind:'script',ruleIds:['NEST_JEST_ALIAS_PARITY','NEST_TEST_DISCOVERY']}},semantic:{guidance:'docs/test.md',review:'Review behavior separately.'},status:'implemented'}],semanticOnly:[]}}},baseRuntime=runtime(source,{results:[{filePath:source,messages:[],suppressedMessages:[],errorCount:0,warningCount:0,fatalErrorCount:0}]}),nestRuntime={...baseRuntime,package:{...baseRuntime.package,name:'@starci/eslint-canon-be'},canon:{rules:{},recommended:{}}},discoveries=[],calls=[];const metadataDiscovery=input=>{discoveries.push(input);return {files:['package.json','config/jest-helper.json'],toolFiles:[targetTypescript.resolved],specFiles:[],projects:[],errors:[]};},report=await checkScopedLint(root,[],{profile:'nest',profileCatalog:profile,runtime:nestRuntime,architecture,all:true,metadataDiscovery,scriptChecker:async(_profile,input)=>{calls.push(input);return {schema:'starci/code-pattern-script@1',repository:root,files:['package.json'],checkedRuleIds:['NEST_JEST_ALIAS_PARITY','NEST_TEST_DISCOVERY'],violations:[],errors:[],compiler:{version:'fixture',resolved:true}};}});assert.equal(report.status,'clean');assert.equal(discoveries.length,2);assert.ok(report.inputs.before.files.includes('config/jest-helper.json'));assert.deepEqual(calls[0].contextFiles,['package.json','src/service.ts']);});

test('architecture coverage must enumerate every applicable file and rule ID',async t=>{const {root,source}=fixture(t),omittedFile=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture:()=>({...architecture(),coverage:{...architecture().coverage,sourceFiles:[]}})});assert.equal(omittedFile.status,'unavailable');assert.ok(omittedFile.issues.some(issue=>issue.code==='ARCHITECTURE_FILE_COVERAGE_UNAVAILABLE'));const omittedRule=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture:()=>({...architecture(),coverage:{...architecture().coverage,checkedRuleIds:[]}})});assert.equal(omittedRule.status,'unavailable');assert.ok(omittedRule.issues.some(issue=>issue.code==='ARCHITECTURE_RULE_COVERAGE_UNAVAILABLE'));});

test('profile and report schemas compile strictly and accept the authored inventory and a real result',async t=>{const ajv=new Ajv2020({strict:true}),profileSchema=parseYaml(fs.readFileSync(new URL('../schemas/code-pattern-profile.schema.yaml',import.meta.url),'utf8')),reportSchema=parseYaml(fs.readFileSync(new URL('../schemas/code-pattern-check.schema.yaml',import.meta.url),'utf8'));const validateProfile=ajv.compile(profileSchema),validateReport=ajv.compile(reportSchema),authored=parseYaml(fs.readFileSync(new URL('../model/code-patterns.yaml',import.meta.url),'utf8'));assert.equal(validateProfile(authored),true,JSON.stringify(validateProfile.errors));const {root,source}=fixture(t),report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture});assert.equal(validateReport(report),true,JSON.stringify(validateReport.errors));});

test('the stable CLI parser and main return JSON plus distinct exit semantics',async()=>{assert.deepEqual(parseScopedLintArgs(['--profile','nest','--root','repo','--architecture-config','.starci/architecture.json','--','src/a.ts']),{profile:'nest',root:'repo',architectureConfig:'.starci/architecture.json',all:false,files:['src/a.ts']});assert.deepEqual(parseScopedLintArgs(['--profile','next','--root','repo','--all']),{profile:'next',root:'repo',architectureConfig:null,all:true,files:[]});assert.throws(()=>parseScopedLintArgs(['--profile','next','--root','repo','--all','--','src/a.ts']),/Usage/);let output='';const fake={schema:'starci/code-pattern-check@1',status:'findings',ok:false,issues:[{code:'gap'}]};const result=await scopedLintMain(['--profile','next','--root','repo','--','src/a.ts'],{checker:async()=>fake,write:value=>{output+=value;}});assert.equal(result.exitCode,1);assert.deepEqual(JSON.parse(output),fake);const invalid=await scopedLintMain([],{write:()=>{}});assert.equal(invalid.exitCode,2);assert.equal(invalid.report.status,'invalid');});

test('--all derives the complete authored source inventory and fails closed on an empty profile inventory',async t=>{const {root,source}=fixture(t),clean=await checkScopedLint(root,[],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,all:true});assert.equal(clean.status,'clean');assert.deepEqual(clean.coverage.requestedFiles,['src/component.tsx']);fs.rmSync(source);const unavailable=await checkScopedLint(root,[],{profile:'next',profileCatalog:catalog(),runtime:runtime(source),architecture,all:true});assert.equal(unavailable.status,'unavailable');assert.ok(unavailable.issues.some(issue=>issue.code==='SOURCE_INVENTORY_EMPTY'));});

test('the lint audit protocol accepts a typed findings report as measurement but rejects unavailable or contradictory output',async t=>{const {root,source}=fixture(t),report=await checkScopedLint(root,['src/component.tsx'],{profile:'next',profileCatalog:catalog({status:'missing'}),runtime:runtime(source),architecture}),op={id:'audit-code-patterns',kind:'review.verify',operation:'lint',checks:[{name:'code patterns',command:'node scripts/check-scoped-lint.mjs --profile next --root repo -- src/component.tsx'}]};const measured=measureAuditChecks(op,()=>({status:1,stdout:JSON.stringify(report),stderr:''}));assert.equal(measured.ok,true);assert.equal(measured.outcome,'findings');assert.equal(measured.findings,report.issues.length);const publicCommand={...op,checks:[{name:'code patterns',command:'node bin/starci.mjs code-patterns check --profile next --root repo --all'}]},publicMeasured=measureAuditChecks(publicCommand,()=>({status:1,stdout:JSON.stringify(report),stderr:''}));assert.equal(publicMeasured.ok,true);assert.equal(publicMeasured.outcome,'findings');const unavailable={...report,status:'unavailable'};delete unavailable.reportDigest;const sealed={...unavailable,reportDigest:sha256(canonicalJSON(unavailable))};assert.equal(measureAuditChecks(op,()=>({status:2,stdout:JSON.stringify(sealed),stderr:''})).ok,false);assert.equal(measureAuditChecks(op,()=>({status:0,stdout:JSON.stringify(report),stderr:''})).ok,false);});
