import test from 'node:test';
import assert from 'node:assert/strict';
import {validateSDSMap,classifySDSPath} from '../specifications/sds-map.mjs';

const entry=(path,type,payload)=>({path,nodeId:payload.id,workRefs:[],payload,classification:{aggregate:false,type}});
function fixture(){
 const srs=[{path:'features/chatbot/business/srs/functional-requirements/answer/index.yaml',nodeId:'chatbot.fr',workRefs:[],classification:{aggregate:false,type:'functional-requirement'},payload:{id:'FR-CHAT-01',mainFlow:{id:'FR-CHAT-01.MAIN'},alternativeFlows:[{id:'FR-CHAT-01.ALT1'}],exceptionFlows:[{id:'FR-CHAT-01.EX1'}],acceptanceCriteria:[{id:'FR-CHAT-01.AC1'}]}}];
 const code={schema:'starci/sds-code-unit@1',id:'CU-CHAT-API',title:'Chat API controller',status:'draft',side:'backend',repositoryRole:'be',path:'src/chat/chat.controller.ts',symbols:[{name:'ChatController.ask',kind:'method',signature:'ask(input): Promise<Answer>',responsibility:'Accept an authorized chat request.'}],callers:[],callees:[],contractRefs:['CONTRACT-CHAT'],dataRefs:['DATA-CHAT'],qualityRefs:['QUALITY-CHAT'],verificationRefs:['VERIFY-CHAT']};
 const contract={schema:'starci/sds-contract@1',id:'CONTRACT-CHAT',title:'Ask API',status:'draft',kind:'api',callerCodeUnitRef:'CU-CHAT-API',receiverCodeUnitRef:'CU-CHAT-API',mode:'sync',transport:'HTTPS JSON',operation:'POST /chat/ask',request:[{field:'question',rule:'Non-empty text'}],response:[{field:'answer',rule:'Grounded answer or explicit failure'}],errors:['unauthorized','invalid','unavailable'],authorization:'Check current conversation access.',timeout:'Return accepted/waiting state before the request deadline.',retry:'Retry only after resolving the prior outcome.',idempotency:'Use request id for one logical request.',compatibility:'Additive versioned response fields.'};
 const data={schema:'starci/sds-data-model@1',id:'DATA-CHAT',title:'Conversation record',status:'draft',ownerCodeUnitRef:'CU-CHAT-API',store:'Conversation repository',authoritative:true,classification:'private',fields:[{name:'id',type:'identifier'},{name:'state',type:'enum'}],states:['active','answered','failed'],transactions:[{id:'TX-CHAT',boundary:'Persist one answer result atomically.'}],consistency:'Read the committed request outcome.',retention:'Follow accepted product policy.',recovery:{owner:'Chat service',procedure:'Read outcome by request id before retry.'}};
 const verification={schema:'starci/sds-verification@1',id:'VERIFY-CHAT',title:'Chat path verification',status:'draft',businessAcceptanceRefs:['FR-CHAT-01.AC1'],scopeRefs:['SDS-FLOW-CHAT'],level:'backend-e2e',setup:['Authorized conversation fixture.'],steps:['Submit a question.','Read the returned answer state.'],expected:['The grounded result is observable.'],securityChecks:['Denied conversation cannot read data.'],performanceChecks:['Measure boundary latency.'],failureChecks:['Unavailable knowledge returns explicit failure.']};
 const deployment={schema:'starci/sds-deployment@1',id:'DEPLOY-CHAT',title:'Chat topology',status:'draft',topology:'One backend process; separable behind the same contract.',placements:[{codeUnitRef:'CU-CHAT-API',runtime:'backend'}],connections:[],configuration:{owner:'Platform',source:'Validated environment'},credentials:{owner:'Platform',delivery:'Secret reference'},scaling:'Scale the backend instance within measured limits.',failureDomains:['Backend process','Knowledge dependency'],rollout:'Backward-compatible rollout.',rollback:'Restore the prior compatible build.',recovery:{owner:'Platform',procedure:'Restore service and reconcile pending request ids.'}};
 const quality={schema:'starci/sds-quality@1',id:'QUALITY-CHAT',title:'Chat security and latency',status:'draft',qualityKind:'security',businessRefs:['FR-CHAT-01'],scopeRefs:['SDS-FLOW-CHAT','CU-CHAT-API'],mechanism:'Authorize the conversation before retrieval and response.',scenarios:[{id:'denied',trigger:'Foreign conversation id',impact:'Private disclosure',response:'Deny without content'}],measurement:{metric:'Denied disclosure count and boundary latency',conditions:'Measure authorized and denied fixtures'},optimization:['Cache only authorization-safe derived data.'],tradeoffs:['Extra authorization work protects private context.'],verificationRefs:['VERIFY-CHAT']};
 const step=(id,operation)=>({id,codeUnitRef:'CU-CHAT-API',operation,input:'Question and request id',output:'Answer state',contractRefs:['CONTRACT-CHAT'],dataRefs:['DATA-CHAT'],transaction:'TX-CHAT or no write before validation',failureRefs:['FR-CHAT-01.EX1']});
 const flow={schema:'starci/sds-flow@1',id:'SDS-FLOW-CHAT',title:'Answer question code path',status:'draft',businessRefs:[{requirementIds:['FR-CHAT-01'],flowIds:['FR-CHAT-01.MAIN','FR-CHAT-01.ALT1','FR-CHAT-01.EX1'],acceptanceIds:['FR-CHAT-01.AC1']}],entryPoint:{channel:'web app',trigger:'Customer submits a question',codeUnitRef:'CU-CHAT-API'},preconditions:['Conversation exists; authorization is still checked.'],inputs:[{name:'question',validation:'Non-empty'}],participants:['CU-CHAT-API'],mainSequence:{id:'SDS-FLOW-CHAT.MAIN',steps:[step('SDS-FLOW-CHAT.MAIN.S1','Validate, retrieve and answer.')]},alternativeSequences:[{id:'SDS-FLOW-CHAT.ALT1',fromStep:'SDS-FLOW-CHAT.MAIN.S1',condition:'More context is required.',steps:[step('SDS-FLOW-CHAT.ALT1.S1','Return a clarification request.')],resumeAt:'end',outcome:'App waits for clarification.'}],exceptionSequences:[{id:'SDS-FLOW-CHAT.EX1',fromStep:'SDS-FLOW-CHAT.MAIN.S1',condition:'Knowledge retrieval fails.',steps:[step('SDS-FLOW-CHAT.EX1.S1','Persist and return explicit failure.')],resumeAt:'end',outcome:'App offers retry or handoff.'}],recovery:{owner:'Chat service',stateSource:'Conversation request result',retryIdentity:'request id',resumeCondition:'Prior result is known and the dependency is healthy.'},postconditions:{success:['Answer state is committed and visible.'],failure:['No false success is visible.']},resultMapping:{response:'API answer state',appState:'Answer, clarification or failure view',lateResult:'Subscription or refresh reads the same request id.'},topologyRefs:['DEPLOY-CHAT'],verificationRefs:['VERIFY-CHAT']};
 const entries=[entry('features/chatbot/architecture/sds/code-map/backend/chat-api/index.yaml','code-unit',code),entry('features/chatbot/architecture/sds/contracts/ask/index.yaml','contract',contract),entry('features/chatbot/architecture/sds/data/conversation/index.yaml','data-model',data),entry('features/chatbot/architecture/sds/verification/answer/index.yaml','verification',verification),entry('features/chatbot/architecture/sds/deployment/backend/index.yaml','deployment',deployment),entry('features/chatbot/architecture/sds/quality/security/chat/index.yaml','quality',quality),entry('features/chatbot/architecture/sds/flows/answer/index.yaml','flow',flow)];
 return {entries,srs};
}

test('SDS map traces SRS through code, contracts, data, quality, deployment and verification',()=>{const f=fixture();assert.deepEqual(validateSDSMap(f.entries,f.srs),[]);assert.equal(classifySDSPath('features/chatbot/architecture/sds/code-map/backend/chat-api/index.yaml').type,'code-unit');});
test('SDS map rejects broken code paths and Business acceptance',()=>{const f=fixture();f.entries.at(-1).payload.mainSequence.steps[0].codeUnitRef='missing';f.entries.find(item=>item.classification.type==='verification').payload.businessAcceptanceRefs=['missing'];const errors=validateSDSMap(f.entries,f.srs);assert.ok(errors.some(error=>error.code==='SDS_REF'));assert.ok(errors.some(error=>error.code==='SDS_BUSINESS'));});
test('SDS code map rejects implementation provenance fields',()=>{const f=fixture(),unit=f.entries.find(item=>item.classification.type==='code-unit');unit.payload.revision='a'.repeat(40);const errors=validateSDSMap(f.entries,f.srs);assert.ok(errors.some(error=>error.code==='SDS_MAP'&&error.message.includes('independent of source code')));});
test('SDS verification rejects evidence fields',()=>{const f=fixture(),verification=f.entries.find(item=>item.classification.type==='verification');verification.payload.evidence='Runtime output';const errors=validateSDSMap(f.entries,f.srs);assert.ok(errors.some(error=>error.code==='SDS_MAP'&&error.message.includes('evidence fields')));});
test('structured overview is exact-path classified and joins Business to topology',()=>{const f=fixture(),payload={schema:'starci/sds-overview@1',id:'OVERVIEW-CHAT',title:'Chat target architecture',status:'accepted',businessRefs:['FR-CHAT-01'],designGoals:['Answer safely and observably.'],scope:{in:['Question path.'],out:['Model training.']},actors:['Customer'],systemContext:['Web app calls the chat backend.'],qualityStrategy:['Authorize before private reads.'],decisions:[{concern:'Existing chat boundary',disposition:'extend',rationale:'Accepted flow requires durable late results.',impact:'Adds request outcome reconciliation.',migration:'Introduce additively before switching callers.'}],constraints:['SRS remains authoritative.'],topologyRefs:['DEPLOY-CHAT'],implementationHandoff:['Map prescribed symbols and prove conformance.']};f.entries.push(entry('features/chatbot/architecture/overview/index.yaml','overview',payload));assert.equal(classifySDSPath('features/chatbot/architecture/overview/index.yaml').type,'overview');assert.equal(classifySDSPath('features/chatbot/architecture/other/index.yaml'),null);assert.deepEqual(validateSDSMap(f.entries,f.srs),[]);});
test('overview rejects empty, wrong schema, unresolved inputs and source observations',()=>{const f=fixture(),payload={schema:'wrong',id:'OVERVIEW-CHAT',title:'Chat',status:'accepted',businessRefs:['missing'],designGoals:[],scope:{in:[],out:[]},actors:[],systemContext:[],qualityStrategy:[],decisions:[],constraints:[],topologyRefs:['missing'],implementationHandoff:[],revision:'observed'};f.entries.push(entry('features/chatbot/architecture/overview/index.yaml','overview',payload));const errors=validateSDSMap(f.entries,f.srs);assert.ok(errors.some(e=>e.code==='SDS_MAP'&&e.message.includes('Expected starci/sds-overview@1')));assert.ok(errors.some(e=>e.code==='SDS_MAP'&&e.message.includes('source observations')));assert.ok(errors.some(e=>e.code==='SDS_BUSINESS'));assert.ok(errors.some(e=>e.code==='SDS_REF'));});
test('overview Work refs do not impersonate Business owners and legacy Business node refs resolve explicitly',()=>{const f=fixture(),payload={schema:'starci/sds-overview@1',id:'OVERVIEW-CHAT',title:'Chat',status:'accepted',businessRefs:['arbitrary.non.business'],designGoals:['Goal'],scope:{in:['In'],out:['Out']},actors:['Actor'],systemContext:['Context'],qualityStrategy:['Quality'],decisions:[{concern:'Concern',disposition:'add',rationale:'Reason',impact:'Impact',migration:'Migration'}],constraints:['Constraint'],topologyRefs:['DEPLOY-CHAT'],implementationHandoff:['Handoff']},overview=entry('features/chatbot/architecture/overview/index.yaml','overview',payload);overview.workRefs=['arbitrary.non.business'];f.entries.push(overview);const overviewBusiness=issues=>issues.filter(e=>e.code==='SDS_BUSINESS'&&e.path===overview.path);assert.ok(overviewBusiness(validateSDSMap(f.entries,[])).length);payload.businessRefs=['legacy.business.srs'];assert.equal(overviewBusiness(validateSDSMap(f.entries,[],[{nodeId:'legacy.business.srs'}])).length,0);});
test('malformed overview decisions return diagnostics without throwing',()=>{const f=fixture(),payload={schema:'starci/sds-overview@1',id:'OVERVIEW-CHAT',title:'Chat',status:'accepted',businessRefs:['FR-CHAT-01'],designGoals:['Goal'],scope:{in:['In'],out:['Out']},actors:['Actor'],systemContext:['Context'],qualityStrategy:['Quality'],decisions:{},constraints:['Constraint'],topologyRefs:['DEPLOY-CHAT'],implementationHandoff:['Handoff']};f.entries.push(entry('features/chatbot/architecture/overview/index.yaml','overview',payload));assert.doesNotThrow(()=>validateSDSMap(f.entries,f.srs));assert.ok(validateSDSMap(f.entries,f.srs).some(e=>e.code==='SDS_MAP'&&e.message.includes('design decisions')));});
