import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {parseYaml,stringifyYaml} from '../core/yaml.mjs';
import {validateWorkspace} from '../core/index.mjs';

const review=(inputDigest)=>({inputDigest,review:{schema:'starci/design-review@1',reviewer:'Synthetic reviewer',authority:'Runtime split-freshness regression only.',reviewedAt:'2026-09-10T00:00:00Z',observations:[{id:'design-reviewed',outcome:'pass',observation:'The synthetic target design is internally reviewed; no product or implementation claim is made.'}],limitations:['Synthetic runtime regression only.']}});
const sourceIdentity={schema:'starci/source-identity@1',repositories:[{repository:'be',origin:'https://example.invalid/nivo.git',state:'committed',commit:'a'.repeat(40),coverage:{kind:'scoped',paths:['src/synthetic.ts'],dependencyCoverage:'Synthetic leaf only.',limitations:['No product source was inspected or executed.']}}]};

function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-split-freshness-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const file=relative=>path.join(root,relative),put=(relative,value)=>{const target=file(relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,stringifyYaml(value));};
 const branch=(relative,id,kind,extension)=>put(relative,{schema:'work/node@2',id,kind,required:true,description:'Synthetic aggregate.',...(extension?{extensions:{work3:extension}}:{})});
 const leaf=(relative,id,kind,extra={})=>put(relative,{schema:'work/node@2',id,kind,required:true,description:'Synthetic split freshness leaf.',state:'todo',...extra});
 const aggregate=(relative,id,kind,payload,section)=>branch(relative,id,kind,{[payload]:{schema:payload==='srs'?'starci/srs-aggregate@1':'starci/sds-aggregate@1',section,title:section}});
 put('workspace.yaml',{schema:'work/workspace@1',id:'split-freshness'});branch('features/index.yaml','features','business');branch('features/chatbot/index.yaml','chatbot','business');
 branch('features/chatbot/business/index.yaml','business','business');leaf('features/chatbot/business/overview/index.yaml','business.overview','business-overview',{businessOverview:{purpose:'Answer one question.',customerUnderstanding:'A customer asks and receives an outcome.',desiredOutcome:'An honest answer or failure.',scope:'Synthetic question only.',openQuestions:'None.'}});
 aggregate('features/chatbot/business/srs/index.yaml','business.srs','business','srs','feature-srs');aggregate('features/chatbot/business/srs/functional-requirements/index.yaml','business.srs.fr','business','srs','functional-requirements');aggregate('features/chatbot/business/srs/customer-journeys/index.yaml','business.srs.journey','business','srs','customer-journeys');
 const step={id:'FR-1.MAIN.S1',actor:'customer',request:'Ask one question.',systemResponse:'Return an honest answer.',businessEffect:'The outcome becomes visible.',acceptanceRefs:['FR-1.AC1']};
 const fr={schema:'starci/srs-functional-requirement@1',id:'FR-1',title:'Answer question',status:'accepted',goal:'Return an honest answer.',actors:['customer'],trigger:'The customer asks.',preconditions:[],inputs:[{name:'question',validation:'Non-empty.'}],outputs:[{name:'outcome',meaning:'Visible answer or failure.'}],mainFlow:{id:'FR-1.MAIN',steps:[step]},alternativeFlows:[],exceptionFlows:[],branchReview:{alternatives:'No alternative in this synthetic case.',exceptions:'No exception in this synthetic case.'},postconditions:{success:['Outcome visible.'],failure:['No false success.']},businessRuleRefs:[],dataRefs:[],nonFunctionalRefs:[],decisionRefs:[],acceptanceCriteria:[{id:'FR-1.AC1',flowRef:'FR-1.MAIN',stepRefs:['FR-1.MAIN.S1'],given:'An authorized customer.',when:'The question is asked.',then:'An honest outcome is visible.'}]};
 leaf('features/chatbot/business/srs/functional-requirements/answer/index.yaml','business.fr','business',{extensions:{work3:{srs:fr}}});
 const journey={schema:'starci/srs-customer-journey@1',id:'CJ-1',title:'Ask and receive',status:'accepted',actor:'customer',entry:'Customer asks.',preconditions:[],stages:[{id:'CJ-1.S1',actorAction:'Ask.',requirementRef:'FR-1',flowRef:'FR-1.MAIN',acceptanceRefs:['FR-1.AC1'],outcome:'Outcome visible.',nextStep:null}],branches:[],exit:'Outcome visible.',acceptanceCriteria:[{id:'CJ-1.AC1',given:'A customer asks.',when:'The journey ends.',then:'The outcome is visible.'}]};
 leaf('features/chatbot/business/srs/customer-journeys/ask/index.yaml','business.journey','business',{extensions:{work3:{srs:journey}}});
 branch('features/chatbot/architecture/index.yaml','architecture','architecture');leaf('features/chatbot/architecture/overview/index.yaml','architecture.overview','architecture');aggregate('features/chatbot/architecture/sds/index.yaml','architecture.sds','architecture','sds','sds');
 for(const section of ['flows','code-map','deployment','verification'])aggregate(`features/chatbot/architecture/sds/${section}/index.yaml`,`architecture.sds.${section}`,'architecture','sds',section);
 const code={schema:'starci/sds-code-unit@1',id:'CU-1',title:'Question handler',status:'accepted',side:'backend',repositoryRole:'be',path:'src/synthetic.ts',symbols:[{name:'handle',kind:'function',signature:'handle(question): Outcome',responsibility:'Return the outcome.'}],callers:[],callees:[],contractRefs:[],dataRefs:[],qualityRefs:[],verificationRefs:[]};
 leaf('features/chatbot/architecture/sds/code-map/handler/index.yaml','architecture.code','architecture',{extensions:{work3:{sds:code}}});
 const deployment={schema:'starci/sds-deployment@1',id:'DEP-1',title:'Synthetic process',status:'accepted',topology:'monolith',placements:[{codeUnitRef:'CU-1',runtime:'synthetic process'}],connections:[],configuration:{source:'environment'},credentials:{custody:'outside this fixture'},scaling:'One synthetic process.',failureDomains:['process'],rollout:'Replace fixture.',rollback:'Restore fixture.',recovery:{method:'Recreate fixture.'}};
 leaf('features/chatbot/architecture/sds/deployment/process/index.yaml','architecture.deployment','architecture',{extensions:{work3:{sds:deployment}}});
 const verification={schema:'starci/sds-verification@1',id:'VERIFY-1',title:'Outcome verification',status:'accepted',businessAcceptanceRefs:['FR-1.AC1'],scopeRefs:['FLOW-1'],level:'design',setup:['Synthetic input.'],steps:['Call handler.'],expected:['Outcome visible.'],securityChecks:[],performanceChecks:[],failureChecks:[]};
 leaf('features/chatbot/architecture/sds/verification/outcome/index.yaml','architecture.verification','architecture',{extensions:{work3:{sds:verification}}});
 const flowStep={id:'FLOW-1.MAIN.S1',codeUnitRef:'CU-1',operation:'Handle question.',input:'Question.',output:'Outcome.',contractRefs:[],dataRefs:[],transaction:'No write.',failureRefs:[]};
 const flow={schema:'starci/sds-flow@1',id:'FLOW-1',title:'Question flow',status:'accepted',businessRefs:[{requirementIds:['FR-1'],flowIds:['FR-1.MAIN'],acceptanceIds:['FR-1.AC1']}],entryPoint:{channel:'web',trigger:'Question submitted.',codeUnitRef:'CU-1'},preconditions:[],inputs:[{name:'question'}],participants:['CU-1'],mainSequence:{id:'FLOW-1.MAIN',steps:[flowStep]},alternativeSequences:[],exceptionSequences:[],branchReview:{alternatives:'No alternative in this fixture.',exceptions:'No exception in this fixture.'},recovery:{owner:'handler',stateSource:'request',retryIdentity:'request-id',resumeCondition:'same request'},postconditions:{success:['Outcome visible.'],failure:['No false success.']},resultMapping:{response:'Outcome',appState:'Visible outcome',lateResult:'Same request lookup'},topologyRefs:['DEP-1'],verificationRefs:['VERIFY-1']};
 leaf('features/chatbot/architecture/sds/flows/question/index.yaml','architecture.flow','architecture',{assertions:['design-reviewed'],extensions:{work3:{sds:flow}}});
 branch('features/chatbot/implementation/index.yaml','implementation','implementation');leaf('features/chatbot/implementation/backend/index.yaml','implementation.backend','implementation',{assertions:['implemented'],refs:['architecture.flow']});
 leaf('features/unrelated/index.yaml','unrelated','implementation',{assertions:['unrelated-proof']});
 const read=relative=>parseYaml(fs.readFileSync(file(relative),'utf8')),write=(relative,value)=>put(relative,value),mutate=(relative,fn)=>{const value=read(relative);fn(value);write(relative,value);};
 const completeEvidence=(relative,nodeId,inputDigest,assertion)=>{const identity=structuredClone(sourceIdentity),node=read(relative);node.state='done';node.completion={inputDigest,evidence:[`${nodeId}.proof`],sourceIdentity:identity};write(relative,node);put(`${path.posix.dirname(relative)}/evidence/proof/manifest.yaml`,{schema:'work/evidence@1',id:`${nodeId}.proof`,nodeId,inputDigest,outcome:'pass',assertions:[{id:assertion,outcome:'pass',observation:'Synthetic current proof.'}],assets:[],sourceIdentity:identity});};
 return {root,read,write,mutate,completeEvidence};
}

test('split semantic owners bind SRS changes through SDS and implementation without cyclic Work refs',t=>{
 const f=fixture(t),initial=validateWorkspace(f.root);assert.equal(initial.ok,true,JSON.stringify(initial.errors));
 const digest=id=>initial.nodes.find(node=>node.id===id).inputDigest;
 f.mutate('features/chatbot/architecture/sds/flows/question/index.yaml',node=>{node.state='done';node.completion=review(digest('architecture.flow'));});
 f.completeEvidence('features/chatbot/implementation/backend/index.yaml','implementation.backend',digest('implementation.backend'),'implemented');
 f.completeEvidence('features/unrelated/index.yaml','unrelated',digest('unrelated'),'unrelated-proof');
 const complete=validateWorkspace(f.root);assert.equal(complete.ok,true,JSON.stringify(complete.errors));assert.equal(complete.nodes.find(node=>node.id==='architecture.flow').effectiveState,'done');assert.equal(complete.nodes.find(node=>node.id==='implementation.backend').effectiveState,'done');
 f.mutate('features/chatbot/business/srs/functional-requirements/answer/index.yaml',node=>{node.extensions.work3.srs.goal='Return an honest, policy-current answer.';});
 const changed=validateWorkspace(f.root);assert.equal(changed.nodes.find(node=>node.id==='architecture.flow').effectiveState,'uninvestigate');assert.equal(changed.nodes.find(node=>node.id==='implementation.backend').effectiveState,'uninvestigate');assert.ok(changed.errors.some(error=>error.code==='STALE_COMPLETION'&&error.path.endsWith('architecture/sds/flows/question/index.yaml')));assert.ok(changed.errors.some(error=>error.code==='STALE_COMPLETION'&&error.path.endsWith('implementation/backend/index.yaml')));assert.equal(changed.nodes.find(node=>node.id==='unrelated').effectiveState,'done');
 f.mutate('features/chatbot/business/srs/functional-requirements/answer/index.yaml',node=>{node.extensions.work3.srs.goal='Return an honest answer.';});
 const restored=validateWorkspace(f.root);assert.equal(restored.nodes.find(node=>node.id==='architecture.flow').effectiveState,'done');assert.equal(restored.nodes.find(node=>node.id==='implementation.backend').effectiveState,'done');
 f.mutate('features/chatbot/architecture/sds/code-map/handler/index.yaml',node=>{node.extensions.work3.sds.symbols[0].responsibility='Return the current authorized outcome.';});
 const designChanged=validateWorkspace(f.root);assert.equal(designChanged.nodes.find(node=>node.id==='architecture.flow').effectiveState,'uninvestigate');assert.equal(designChanged.nodes.find(node=>node.id==='implementation.backend').effectiveState,'uninvestigate');assert.ok(designChanged.errors.some(error=>error.code==='STALE_COMPLETION'&&error.path.endsWith('architecture/sds/flows/question/index.yaml')));assert.ok(designChanged.errors.some(error=>error.code==='STALE_COMPLETION'&&error.path.endsWith('implementation/backend/index.yaml')));assert.equal(designChanged.nodes.find(node=>node.id==='unrelated').effectiveState,'done');
});
