import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {stringifyYaml,parseYaml} from '../core/yaml.mjs';
import {validateWorkspace} from '../core/index.mjs';

function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'starci-split-srs-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const put=(relative,value)=>{const file=path.join(root,relative);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,stringifyYaml(value));};
 const node=(relative,id,extra={})=>put(relative,{schema:'work/node@2',id,kind:'business',required:true,description:'Synthetic split SRS fixture.',...extra});
 const aggregate=(relative,id,section)=>node(relative,id,{extensions:{work3:{srs:{schema:'starci/srs-aggregate@1',section,title:section}}}});
 put('workspace.yaml',{schema:'work/workspace@1',id:'split-srs'});node('features/index.yaml','features');node('features/chatbot/index.yaml','chatbot');node('features/chatbot/business/index.yaml','chatbot.business');
 node('features/chatbot/business/overview/index.yaml','chatbot.overview',{kind:'business-overview',state:'todo',businessOverview:{purpose:'Help a customer ask for support.',customerUnderstanding:'A chatbot answers or routes a question.',desiredOutcome:'The customer receives a useful result.',scope:'Question answering and human handoff.',openQuestions:'None stated in this synthetic fixture.'}});
 aggregate('features/chatbot/business/srs/index.yaml','chatbot.srs','feature-srs');
 for(const section of ['functional-requirements','non-functional-requirements','business-rules','data','customer-journeys'])aggregate(`features/chatbot/business/srs/${section}/index.yaml`,`chatbot.srs.${section}`,section);
 aggregate('features/chatbot/business/srs/business-rules/policy-decisions/index.yaml','chatbot.srs.decisions','policy-decisions');
 const decision={schema:'starci/srs-policy-decision@1',id:'D-CHAT-01',title:'Chat response policy',status:'draft',decisionStatus:'open',accountableRole:'Product owner',question:'Which sources may support an answer?',requiredDecisions:['Select permitted source classes.'],safeDisposition:'Do not present unsupported answers.',closureEvidence:'Record the approved policy version.',affectedFeatureRefs:['FR-CHAT-01'],affectedDataRefs:[],affectedNfrRefs:['NFR-CHAT-01']};
 node('features/chatbot/business/srs/business-rules/policy-decisions/chat-policy/index.yaml','chatbot.decision',{state:'todo',extensions:{work3:{srs:decision}}});
 const rule={schema:'starci/srs-business-rule@1',id:'BR-CHAT-01',title:'Grounded answer',status:'draft',statements:['An answer cites only permitted sources.'],decisionRefs:['D-CHAT-01'],acceptanceCriteria:[{id:'BR-CHAT-01.AC1',given:'Permitted knowledge exists.',when:'The chatbot answers.',then:'The answer cites that knowledge.'}]};
 node('features/chatbot/business/srs/business-rules/grounded-answer/index.yaml','chatbot.rule',{state:'todo',refs:['chatbot.decision'],extensions:{work3:{srs:rule}}});
 const nfr={schema:'starci/srs-non-functional-requirement@1',id:'NFR-CHAT-01',title:'Response progress',status:'draft',scope:['all'],requirement:'The customer sees answer progress.',decisionRefs:['D-CHAT-01'],measurement:{metric:'Time to visible progress',conditions:'Measure at the customer boundary.',thresholdStatus:'Target awaits D-CHAT-01.',evidenceRequired:'Capture timestamps and visible state.'},acceptanceCriteria:[{id:'NFR-CHAT-01.AC1',given:'An accepted question.',when:'Processing begins.',then:'Progress becomes observable.'}]};
 node('features/chatbot/business/srs/non-functional-requirements/response-progress/index.yaml','chatbot.nfr',{state:'todo',refs:['chatbot.decision'],extensions:{work3:{srs:nfr}}});
 const data={schema:'starci/srs-data-definition@1',id:'DATA-CHAT-01',title:'Conversation',status:'draft',owner:'Customer',fields:[{name:'question',meaning:'Customer request',validation:'Non-empty text',classification:'private'}],relations:[],states:['active','answered'],transitions:[{id:'DATA-CHAT-01.T1',from:'active',to:'answered',event:'Answer returned',guard:'The result is grounded'}],invariants:['A failed request is not answered.'],decisionRefs:[],privacy:{access:'Current customer access is required.',retention:'The product policy controls retention.',referenceWithdrawal:'Withdrawn sources cannot support new answers.'},validationCases:[{given:'An active conversation',when:'A grounded answer returns',then:'State becomes answered.'}]};
 node('features/chatbot/business/srs/data/conversation/index.yaml','chatbot.data',{state:'todo',extensions:{work3:{srs:data}}});
 const ac=(id,flow,step,when,then)=>({id,flowRef:flow,stepRefs:[step],given:['An active authorized conversation.'],when,then:[then]});
 const step=(id,actor,request,response,effect,acceptanceRef)=>({id,actor,request,systemResponse:response,businessEffect:effect,acceptanceRefs:[acceptanceRef]});
 const fr={schema:'starci/srs-functional-requirement@1',id:'FR-CHAT-01',title:'Answer a question',status:'draft',goal:'Return grounded help.',actors:['customer','chatbot'],trigger:'Customer submits a question.',preconditions:['The conversation is active.'],inputs:[{id:'question',name:'Question',validation:'Non-empty text',dataRefs:['DATA-CHAT-01']}],outputs:[{name:'answer',fromStep:'FR-CHAT-01.MAIN.S1',meaning:'Grounded response',effect:'Customer sees help.'}],businessRuleRefs:['BR-CHAT-01'],dataRefs:['DATA-CHAT-01'],nonFunctionalRefs:['NFR-CHAT-01'],decisionRefs:['D-CHAT-01'],mainFlow:{id:'FR-CHAT-01.MAIN',steps:[step('FR-CHAT-01.MAIN.S1','customer','Submit a question.','Return a grounded answer.','Conversation becomes answered.','FR-CHAT-01.AC1')]},alternativeFlows:[{id:'FR-CHAT-01.ALT1',fromStep:'FR-CHAT-01.MAIN.S1',condition:'More context is required.',steps:[step('FR-CHAT-01.ALT1.S1','chatbot','Request clarification.','Ask one clarification question.','Conversation stays active.','FR-CHAT-01.AC2')],resume:{type:'main-step',stepRef:'FR-CHAT-01.MAIN.S1'},postconditions:['No answer is invented.'],acceptanceRefs:['FR-CHAT-01.AC2']}],exceptionFlows:[{id:'FR-CHAT-01.EX1',fromStep:'FR-CHAT-01.MAIN.S1',condition:'Knowledge retrieval fails.',steps:[step('FR-CHAT-01.EX1.S1','chatbot','Stop generation.','Report unavailable help.','No successful answer is recorded.','FR-CHAT-01.AC3')],resume:{type:'end',outcome:'Customer can retry.'},postconditions:['Failure remains observable.'],acceptanceRefs:['FR-CHAT-01.AC3']}],postconditions:{success:['A grounded answer is visible.'],failure:['No false success is recorded.']},acceptanceCriteria:[ac('FR-CHAT-01.AC1','FR-CHAT-01.MAIN','FR-CHAT-01.MAIN.S1','The customer asks.','A grounded answer is shown.'),ac('FR-CHAT-01.AC2','FR-CHAT-01.ALT1','FR-CHAT-01.ALT1.S1','Context is insufficient.','A clarification is shown.'),ac('FR-CHAT-01.AC3','FR-CHAT-01.EX1','FR-CHAT-01.EX1.S1','Knowledge fails.','Failure is shown.')],designHandoff:'Map every flow to SDS code paths.'};
 node('features/chatbot/business/srs/functional-requirements/answer-question/index.yaml','chatbot.fr',{state:'todo',refs:['chatbot.rule','chatbot.data','chatbot.nfr','chatbot.decision'],extensions:{work3:{srs:fr}}});
 const journey={schema:'starci/srs-customer-journey@1',id:'CJ-CHAT-01',title:'Customer gets help',status:'draft',actor:'customer',entry:'Customer needs help.',preconditions:['The product is available.'],stages:[{id:'CJ-CHAT-01.S1',actorAction:'Ask a question.',requirementRef:'FR-CHAT-01',flowRef:'FR-CHAT-01.MAIN',acceptanceRefs:['FR-CHAT-01.AC1'],outcome:'The customer sees an answer.',nextStep:null}],branches:[{id:'CJ-CHAT-01.B1',atStageRefs:['CJ-CHAT-01.S1'],requirementRef:'FR-CHAT-01',flowRef:'FR-CHAT-01.EX1',condition:'Knowledge retrieval fails.',handling:'Show the failure.',acceptanceRefs:['FR-CHAT-01.AC3'],outcome:['The customer may retry.']}],exit:'The customer receives help or an honest failure.',acceptanceCriteria:[{id:'CJ-CHAT-01.AC1',given:'A customer needs help.',when:'They complete the journey.',then:'The outcome is visible.'}]};
 node('features/chatbot/business/srs/customer-journeys/customer-gets-help/index.yaml','chatbot.journey',{state:'todo',refs:['chatbot.fr'],extensions:{work3:{srs:journey}}});
 return {root,mutate(relative,fn){const file=path.join(root,relative),value=parseYaml(fs.readFileSync(file,'utf8'));fn(value);fs.writeFileSync(file,stringifyYaml(value));}};
}

test('split SRS validates separate FR, NFR, rule, data, decision and journey owners',t=>{const f=fixture(t),result=validateWorkspace(f.root);assert.equal(result.ok,true,JSON.stringify(result.errors));});
test('split SRS rejects wrong section schema, broken flow acceptance and missing journey coverage',t=>{const f=fixture(t),fr='features/chatbot/business/srs/functional-requirements/answer-question/index.yaml';f.mutate(fr,value=>{value.extensions.work3.srs.schema='starci/srs-data-definition@1';value.extensions.work3.srs.mainFlow.steps[0].acceptanceRefs=['missing'];});f.mutate('features/chatbot/business/srs/customer-journeys/customer-gets-help/index.yaml',value=>{value.extensions.work3.srs.stages=[];});const result=validateWorkspace(f.root);assert.equal(result.ok,false);assert.ok(result.errors.some(error=>error.code==='SRS_SECTION'));assert.ok(result.errors.some(error=>error.code==='SRS_JOURNEY_COVERAGE'));});
test('split SRS rejects code-derived provenance',t=>{const f=fixture(t),fr='features/chatbot/business/srs/functional-requirements/answer-question/index.yaml';f.mutate(fr,value=>{value.extensions.work3.srs.sourceRefs=[{repositoryRole:'be',revision:'a'.repeat(40),path:'src/chat.ts'}];});const result=validateWorkspace(f.root);assert.ok(result.errors.some(error=>error.code==='SRS_SECTION'&&error.message.includes('independent of source code')));});
