/** Generated by codegen from the `.graphql` documents; never edited by hand. */
export const DOCUMENTS = {
    SignIn: "mutation SignIn($input: SignInInput!) { signIn(input: $input) { sessionToken personId } }",
    SignOut: "mutation SignOut($input: SignOutInput!) { signOut(input: $input) { signedOut } }",
    NotificationPreferences: "query NotificationPreferences { notificationPreferences(input: {}) { channel unsubscribed digestWindowMinutes } }",
    Unsubscribe: "mutation Unsubscribe($input: UnsubscribeInput!) { unsubscribe(input: $input) { channel unsubscribed } }",
    UpdateNotificationPreferences: "mutation UpdateNotificationPreferences($input: UpdateNotificationPreferencesInput!) { updateNotificationPreferences(input: $input) { channel unsubscribed digestWindowMinutes } }",
    PlanUsage: "query PlanUsage { planUsage { plan cap activeCount } }",
    UpgradePlan: "mutation UpgradePlan { upgradePlan { subscriptionId paymentIntentId checkoutUrl status } }",
    CompleteErasure: "mutation CompleteErasure($requestId: ID!) { completeErasure(input: { requestId: $requestId }) { requestId state } }",
    ExportMyData: "query ExportMyData { exportMyData { at action target } }",
    RequestErasure: "mutation RequestErasure { requestErasure { requestId state } }",
    EndRecurrence: "mutation EndRecurrence($input: EndRecurrenceInput!) { endRecurrence(input: $input) { ruleId endedAt orphanedCount } }",
    MakeRecurring: "mutation MakeRecurring($input: MakeRecurringInput!) { makeRecurring(input: $input) { ruleId title frequency timeZone time startDate } }",
    UpcomingOccurrences: "query UpcomingOccurrences($ruleId: ID!) { upcomingOccurrences(input: { ruleId: $ruleId }) { ruleId materialised { occurrenceId localDate dueAtUtc status } previewDates } }",
    Invite: "mutation Invite($input: InviteInput!) { invite(input: $input) { invitationId taskId email role status } }",
    Collaborators: "query Collaborators($taskId: ID!) { collaborators(input: { taskId: $taskId }) { invitationId email role status } }",
    RevokeCollaborator: "mutation RevokeCollaborator($input: RevokeCollaboratorInput!) { revokeCollaborator(input: $input) { invitationId status } }",
    CompleteTask: "mutation CompleteTask($id: ID!) { completeTask(input: { id: $id }) { taskId complete } }",
    CreateTask: "mutation CreateTask($input: CreateTaskInput!) { createTask(input: $input) { taskId title } }",
    DeleteTask: "mutation DeleteTask($id: ID!) { deleteTask(input: { id: $id }) { deleted } }",
    ListTasks: "query ListTasks { tasks { taskId title complete } }",
    ReopenTask: "mutation ReopenTask($id: ID!) { reopenTask(input: { id: $id }) { taskId complete } }",
} as const

/** The operations the client can send. */
export type OperationName = keyof typeof DOCUMENTS
