# GENERATED by scripts/cli/gen-catalog.mjs — do not edit
Register-ArgumentCompleter -Native -CommandName starci -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $groups = 'app debug kernel runtime supervisor workflow'.Split(' ')
    $verbs = @{
        'app' = @('add','check','emit','explain','hygiene','lint','new','scaffold','secret','stack','sync','upgrade')
        'debug' = @('run')
        'kernel' = @('archive','artifacts','autopilot','consume-report','contract-release','coverage','cut-seam','decide','decisions','dispatch','dispatch-ready','enqueue','estimate','extensions','finish','foundation','foundations','graph-edit','hierarchy','inbox','incident','kernel-ack-rev','kernel-proposal','lifecycle','log','logs','messages','notify','nudge','observe','op-contract','op-override','peers','plan','provider-backoff','provider-health','questions','reconcile','record-change','record-checks','redesign','rename','reply','report','retire-ask','route','run-deferred-tests','serve-ask','settle','settle-tail','status','survey','unit','usage','verify-proofs')
        'runtime' = @('check','doctor','install','status','update','validate','version')
        'supervisor' = @('start','status','stop')
        'workflow' = @('define','start','status','stop')
    }
    $flags = '--json --cwd --quiet --help --edition'.Split(' ')
    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    if ($words.Count -le 2) { $candidates = $groups } elseif ($words.Count -eq 3) { $candidates = $verbs[$words[1]] } else { $candidates = $flags }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
