# GENERATED by scripts/cli/gen-catalog.mjs — do not edit
Register-ArgumentCompleter -Native -CommandName starci -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $groups = 'app connect debug gate guard harness kernel machine orca reconciler release route runtime supervisor uat work workflow'.Split(' ')
    $verbs = @{
        'app' = @('add','check','emit','explain','hygiene','lint','new','scaffold','secret','stack','sync','upgrade')
        'connect' = @('ask-gateway','telegram','telegram-media','tunnel')
        'debug' = @('pass','run')
        'gate' = @('canon-scan','custody-exec','env-health','hfs-sync','read','repo-presentation','run','sonar','starcistacks','test-world','unit')
        'guard' = @('command','footprint-scan','seat-tools','verify-commit')
        'harness' = @('open','start','status','stop')
        'kernel' = @('archive','artifacts','autopilot','consume-report','contract-release','coverage','cut-seam','decide','decisions','dispatch','dispatch-ready','enqueue','estimate','extensions','finish','foundation','foundations','graph-edit','hierarchy','inbox','incident','kernel-ack-rev','kernel-proposal','lifecycle','log','logs','messages','notify','nudge','observe','op-contract','op-override','peers','plan','provider-backoff','provider-health','questions','reconcile','record-change','record-checks','redesign','rename','reply','report','retire-ask','route','run-deferred-tests','serve-ask','settle','settle-tail','status','survey','unit','usage','verify-proofs')
        'machine' = @('decisions','kernel-watchdog','lessons','op-metrics','seam-policy','worktrees')
        'orca' = @('terminal-read','terminal-send')
        'reconciler' = @('install-task','restart','start','status','stop','up')
        'release' = @('app-installs','check','clean-test','launch-smoke','proof','publish','sync-runtime')
        'route' = @('op')
        'runtime' = @('architecture','benchmark-snapshot','check','derived-fields','doctor','gen-ops','housekeeping','install','ledger-hygiene','machine-db','readme-blocks','status','update','validate','version')
        'supervisor' = @('actions','bridge','gc','land','notify','owed','poll','push','ram-cap','report','start','status','stop','tell')
        'uat' = @('assisted-runner','slots')
        'work' = @('asset-slot','brand','brand-direction','brand-palette','compose-direction','draw-acceptance','draw-dna','draw-feedback','draw-gates','draw-grammar','draw-layer','draw-loop','draw-rationale','draw-render','draw-review','draw-source','draw-taste','example-critique','example-derive','example-evidence','example-verify','grammar-geometry','grammar-knowledge','grammar-proposal','grammar-registry-pin','graph','layout-tree','render-proof','shell-conformance','ui-proof-brief')
        'workflow' = @('assess','define','start','status','stop')
    }
    $flags = '--json --cwd --quiet --help --edition'.Split(' ')
    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    if ($words.Count -le 2) { $candidates = $groups } elseif ($words.Count -eq 3) { $candidates = $verbs[$words[1]] } else { $candidates = $flags }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
