# GENERATED by scripts/cli/gen-catalog.mjs — do not edit
_starci() {
    local cur prev group
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    group="${COMP_WORDS[1]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "kernel help completion" -- "$cur") )
        return 0
    fi
    if [ "$COMP_CWORD" -eq 2 ]; then
        case "$group" in
        kernel) COMPREPLY=( $(compgen -W "archive artifacts autopilot consume-report contract-release coverage cut-seam decide decisions dispatch dispatch-ready enqueue estimate extensions finish foundation foundations graph-edit hierarchy inbox incident kernel-ack-rev kernel-proposal lifecycle log logs messages notify nudge observe op-contract op-override peers plan provider-backoff provider-health questions reconcile record-change record-checks redesign rename reply report retire-ask route run-deferred-tests serve-ask settle settle-tail status survey unit usage verify-proofs" -- "$cur") );;
            *) COMPREPLY=();;
        esac
        return 0
    fi
    case "$group" in
            kernel) COMPREPLY=( $(compgen -W "" -- "$cur") );;
    esac
    COMPREPLY+=( $(compgen -W "--json --cwd --quiet --help --edition" -- "$cur") )
    return 0
}
complete -F _starci starci
