# GENERATED by scripts/cli/gen-catalog.mjs — do not edit
_starci() {
    local cur prev group
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    group="${COMP_WORDS[1]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "app debug guard harness kernel reconciler runtime supervisor work workflow help completion" -- "$cur") )
        return 0
    fi
    if [ "$COMP_CWORD" -eq 2 ]; then
        case "$group" in
        app) COMPREPLY=( $(compgen -W "add check emit explain hygiene lint new scaffold secret stack sync upgrade" -- "$cur") );;
        debug) COMPREPLY=( $(compgen -W "run" -- "$cur") );;
        guard) COMPREPLY=( $(compgen -W "command footprint-scan seat-tools verify-commit" -- "$cur") );;
        harness) COMPREPLY=( $(compgen -W "open start status stop" -- "$cur") );;
        kernel) COMPREPLY=( $(compgen -W "archive artifacts autopilot consume-report contract-release coverage cut-seam decide decisions dispatch dispatch-ready enqueue estimate extensions finish foundation foundations graph-edit hierarchy inbox incident kernel-ack-rev kernel-proposal lifecycle log logs messages notify nudge observe op-contract op-override peers plan provider-backoff provider-health questions reconcile record-change record-checks redesign rename reply report retire-ask route run-deferred-tests serve-ask settle settle-tail status survey unit usage verify-proofs" -- "$cur") );;
        reconciler) COMPREPLY=( $(compgen -W "install-task restart start status stop up" -- "$cur") );;
        runtime) COMPREPLY=( $(compgen -W "check doctor install status update validate version" -- "$cur") );;
        supervisor) COMPREPLY=( $(compgen -W "start status stop" -- "$cur") );;
        work) COMPREPLY=( $(compgen -W "asset-slot brand-direction" -- "$cur") );;
        workflow) COMPREPLY=( $(compgen -W "define start status stop" -- "$cur") );;
            *) COMPREPLY=();;
        esac
        return 0
    fi
    case "$group" in
            app) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            debug) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            guard) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            harness) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            kernel) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            reconciler) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            runtime) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            supervisor) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            work) COMPREPLY=( $(compgen -W "" -- "$cur") );;
            workflow) COMPREPLY=( $(compgen -W "" -- "$cur") );;
    esac
    COMPREPLY+=( $(compgen -W "--json --cwd --quiet --help --edition" -- "$cur") )
    return 0
}
complete -F _starci starci
