/**
 * Kind-specific working order for an operation contract (5.0).
 *
 * The kernel keeps every bit of process authority - which operation runs, in what order, what is accepted -
 * and the Work ledger decides the order of operations. What an agent lacked was the order of work INSIDE one
 * operation: some wrote a green spec first, some skipped the design, some edited outside their allowlist.
 * `stepsFor` renders a mandatory, numbered sequence per operation kind, interpolated from the operation's own
 * values (allowlist, checks, acceptance, references, resources, requesters, findings), so the contract tells
 * the agent what to do first, what must be red before code, and how to report exactly once with the real
 * report vocabulary (`done|partial|failed|ask|blocked`; blockers `shared-change|srs-gap|sds-gap|interface-gap|brand-gap|grammar-gap|environment|authority`).
 *
 * The frontend lane is four operations, never one: `interface.draw` writes the interface design record
 * (screens, every state, blueprint, contract slots, copy) and declares every artwork the chosen candidate
 * embeds as an `artworkSlots` entry, `interface.asset` re-renders those slots into real repository assets,
 * `frontend.implement` may only build what that record describes and wire the assets it names, and
 * `uat.verify` walks the rendered surface. Each of those sequences says so in its definition of done, so no
 * operation of the lane can report the node finished on its own. Artwork is the same rule as a screen: a
 * candidate's illustration, mascot or decorative image is declared, generated, then wired - never invented at
 * build time and never quietly dropped between the approved picture and the shipped page.
 *
 * `work.author` is the one sequence that runs BEFORE a lane: a node whose record declares no write scope or no
 * check cannot be launched, and its sequence is read the material, name files you actually opened, turn the
 * node's claims into runnable checks, build nothing. Its own write scope is the record it completes, which is
 * why its steps spell out what inside that record still belongs to the kernel.
 *
 * The module is product-agnostic: no repository name, no product path, only what the operation carries.
 */

export const STEPS_HEADING='## Working order (mandatory, in this order)';
export const DONE_HEADING='## Definition of done for this kind';
export const SEQUENCES=['work.author','work.intake','work.migrate','work.cut','owner.ask','implement.ledger','implement.shared','implement.repair','implement.gate','interface.draw','interface.asset','frontend.implement','review.verify','e2e.verify','integration.verify','uat','uat.verify','operations','migration','architecture.revise','business.revise','grammar.update','decide','brand.decide','generic'];

const IMPLEMENT_KINDS=['backend.implement','interface.implement','frontend.implement'];
const IMPLEMENT_NODES=['implementation','ui'];
const DECIDE_KINDS=['architecture.decide','business.decide'];
const MIGRATION=/(^|\/)migrations\//;
/** The encrypted half of a credential custody; the contract names the file an operation reads it through. */
const IDENTITY_SECRETS='secrets.enc.yaml';
/** A Work node delivered by the frontend: the `implementation/frontend/**` layout, or any node path under a `frontend/` scope. */
const FRONTEND_LAYOUT=/(^|\/)implementation\/frontend(\/|$)/;
const FRONTEND_SCOPE=/(^|\/)frontend\//;
/** The lane hint every frontend kind carries in its definition of done. */
const LANE='Lane: the feature\'s `ui` node is its interface design record and walks `interface.draw` -> `interface.asset` (when the record declares artwork slots); each frontend implementation node is held until that record is done, then walks `frontend.implement` -> `uat.verify` against it and is done only after `uat.verify`.';
/** The artwork-slot record shape: declared once by the drawing, generated by the asset op, wired by the build. */
const SLOT_SHAPE='`{id, screen, state, region (the blueprint region it sits in), purpose, brief (the prompt that reproduces it), size {w, h, viewport}, format (png|svg|webp), references (the brand mascot/logo master paths the artwork uses), crop {x, y, w, h} of the candidate it was taken from}`';

const nodePath=node=>{
  for(const value of [node?.inputRef,node?.path,node?.file,node?.layout]){const t=text(value).replaceAll('\\','/');if(t)return t;}
  return '';
};
const frontendNode=node=>{const at=nodePath(node);return Boolean(at)&&(FRONTEND_LAYOUT.test(at)||FRONTEND_SCOPE.test(at));};

const plain=value=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const text=value=>String(value??'').trim();
const list=value=>Array.isArray(value)?value.map(text).filter(Boolean):[];
const code=value=>`\`${text(value)}\``;
const codes=(values,fallback)=>{const items=list(values);return items.length?items.map(code).join(', '):fallback;};
const clip=(value,max=90)=>{const t=text(value).replace(/\s+/g,' ');return t.length>max?`${t.slice(0,max-1)}…`:t;};
const count=(n,one,many=`${one}s`)=>`${n} ${n===1?one:many}`;

/** The sequence key of an operation: its kind and origin first, then the Work node kind and layout it closes, then its allowlist. */
export function sequenceFor(op,{node=null}={}){
  const kind=text(op?.kind),origin=text(op?.origin),nodeKind=text(node?.kind),allowlist=list(op?.allowlist);
  // Authoring a record comes before the node's lane and owns the record itself, so neither the node kind nor
  // the origin may route it anywhere else.
  // The record-authoring contract carries three modes and the operation itself says which: an `intake` scope
  // authors a feature the tree does not hold, `implementation.plan` (an op carrying a `cut` node) splits one
  // too-big node into children, and neither may be rerouted by a node kind, an origin or an allowlist.
  if(kind==='implementation.plan'||(kind==='work.author'&&plain(op?.cut)))return 'work.cut';
  if(kind==='work.author')return plain(op?.intake)?(op.intake.mode==='migrate'?'work.migrate':'work.intake'):'work.author';
  if(kind==='review.verify')return 'review.verify';
  if(kind==='owner.ask')return 'owner.ask';
  if(kind==='interface.draw')return 'interface.draw';
  // The identity record is settled before anything is drawn inside it, and it is the node's whole lane.
  if(kind==='brand.decide'||nodeKind==='brand')return 'brand.decide';
  // Generating the artwork a candidate embeds is its own operation: it reads the drawing's slots and writes
  // image files, so neither the node kind nor a repair origin may reroute it into a build sequence.
  if(kind==='interface.asset')return 'interface.asset';
  if(kind==='architecture.revise')return 'architecture.revise';
  // A requirement repair is its own sequence, whatever business node it sits on: the `business` lane's decide
  // sequence settles a requirement from scratch, this one settles a reading of one already written.
  if(kind==='business.revise')return 'business.revise';
  // Growing the installed grammar happens in the grammar's own repository, so no node kind, origin or allowlist
  // may reroute it into a product build: it is the one sequence that tries NOT to change anything first.
  if(kind==='grammar.update')return 'grammar.update';
  if(DECIDE_KINDS.includes(kind))return 'decide';
  if(kind==='uat.verify')return 'uat.verify';
  // End-to-end proof of a backend slice goes through the API on a real stack, never a screen: `e2e.verify` is the
  // backend lane's prove step, and a ledger `uat` node outside the frontend layout is such a scenario.
  if(kind==='e2e.verify')return 'e2e.verify';
  if(nodeKind==='e2e')return 'e2e.verify';
  // An external system is proven against itself or it is not proven, so an `integration` node has exactly
  // one sequence and no origin, allowlist or implementing kind may route it into a build or an API proof.
  if(kind==='integration.verify'||nodeKind==='integration')return 'integration.verify';
  if(nodeKind==='uat')return frontendNode(node)?'uat.verify':'uat';
  const implement=IMPLEMENT_KINDS.includes(kind)||IMPLEMENT_NODES.includes(nodeKind);
  if(implement&&origin==='shared')return 'implement.shared';
  if(implement&&origin==='repair')return 'implement.repair';
  if(implement&&origin==='gate')return 'implement.gate';
  // A frontend implementation node is the lane's middle step, whatever the implementing kind is called.
  if(kind==='frontend.implement'||(implement&&frontendNode(node)))return 'frontend.implement';
  if(allowlist.some(entry=>MIGRATION.test(entry)))return 'migration';
  if(kind==='runtime.operate'||nodeKind==='operations')return 'operations';
  if(implement)return 'implement.ledger';
  return 'generic';
}

/** The operation's own values, ready to be spliced into one-line steps. */
function values(op,node){
  const checks=Array.isArray(op?.checks)?op.checks.filter(check=>text(check?.command)):[];
  const findings=Array.isArray(op?.findings)?op.findings:[];
  const named=checks.map(check=>`${text(check.name)||'check'}: ${code(check.command)}`).join('; ');
  return {
    kind:text(op?.kind),
    allowlist:codes(op?.allowlist,'the allowlist above'),
    checks:checks.length?named:'the checks this code already has (none were declared; record the ones you ran)',
    declared:checks.length?named:'none were declared - record the exact commands you ran',
    checkCount:checks.length,
    acceptance:codes(list(op?.acceptance).map(item=>clip(item)),'the goal above'),
    acceptanceCount:list(op?.acceptance).length,
    references:codes(op?.references,'the goal and the allowlist above'),
    resources:codes(op?.resources,'no declared runtime'),
    requesters:codes(op?.requesters,'the operation that reported the shared change'),
    findings:count(findings.length,'finding'),
    node:node?.id??op?.nodeId??null,
    cutNode:text(op?.cut?.node)||text(op?.nodeId)||'this node',
    cutReason:text(op?.cut?.reason)||'it is more than one operation can build'
  };
}

/**
 * The one exception to "revise it and move on", stated identically in both revise sequences because it is one
 * rule and not two. A record that is confusing, contradictory or silent is not a reason to stop: the runtime
 * takes the most reasonable reading, says why, bumps the rev and carries on, and the owner reads the log and
 * overturns it if they disagree. Only a reading whose alternatives differ in an OBSERVABLE outcome about money,
 * authority or customer data is not the runtime's to take silently - and even then the work does not stop: the
 * operation reports `ask` with `question.kind: decision`, the numbered options and one recommendation, the
 * kernel writes that decision record for the owner and continues provisionally on the recommendation.
 */
const DECISIVE='the readings differ in an observable outcome about MONEY (what is charged, paid, refunded, taxed or owed, and to whom), AUTHORITY (who may do or see a thing) or CUSTOMER DATA (what is stored, shown, shared or deleted about a person)';
/**
 * Both repair sequences: `architecture.revise` on the design record and `business.revise` on the requirement
 * record. The move is the same at both layers - read the gap, state the readings the record admits, choose the
 * most reasonable one by the accepted records, the other features' decided records and the product's own
 * conventions, write it in with its acceptance, bump the `rev`, log exactly one decision entry, validate - so
 * it is written once here and specialised by what the record is called and what "written" means in it.
 */
const REVISE=({record,where,silent,written,escape})=>v=>({
  steps:[
    `Read the gap report that opened this operation (${v.findings}) and ${v.references}: the exact ${record} passage it names and ${silent}.`,
    `State the readings that passage actually admits - two or three, one line each, each one a behaviour someone could build. A record that admits exactly one reading is not a gap: say so, change nothing, and report \`done\` with that reading. ${escape}.`,
    `Choose the most reasonable reading, and choose it from evidence rather than from preference: the accepted records of this feature, the decided records of the OTHER features (the same case is usually already settled somewhere), and the product's own conventions. A confusing, contradictory or silent record is not a reason to stop - it is this operation's job to settle it. UNLESS ${DECISIVE}: then you do not choose silently - report \`ask\` exactly once with \`question.kind: decision\`, the numbered options (one per reading, with what each one costs and who it affects) and ONE recommendation with its reasoning. The kernel writes that decision record for the owner and carries the work on your recommendation until they answer. That case is the ONLY thing this operation may ever \`ask\` about.`,
    `Write the chosen reading into ${where} inside the allowlist (${v.allowlist}): ${written}. Edit that passage and nothing else - no other section, no other record, no code file - and never delete what the record already settled.`,
    `Bump that record's \`rev\` and append EXACTLY ONE entry to \`extensions.work3.decisionLog\`: \`{rev, at, gap, chosen, why, alternatives}\` - the new rev, the ISO-8601 time, the gap detail you were given, the reading you wrote, why it is the most reasonable one and which records you read it from, and the readings you did not take. Never rewrite and never delete an earlier entry: the log is how the owner sees what the runtime decided for them.`,
    `Run the listed validator check verbatim: ${v.declared}.`,
    `Self-audit: the gap is answered in the text, \`rev\` is higher than it was, the log has exactly one new entry naming this gap, and \`git status\` shows only ${v.allowlist} - no product code.`,
    `Report \`done\` exactly once with the new \`rev\` and the decision-log entry you appended. Never report \`ask\` for anything but the money/authority/customer-data case above: an unclear record is revised, not asked about.`
  ],
  done:[
    `the named gap is answered in ${v.allowlist}: the chosen reading is written into ${where} with ${written}`,
    `\`rev\` is higher than it was and \`extensions.work3.decisionLog\` has exactly one new \`{rev, at, gap, chosen, why, alternatives}\` entry, with every earlier entry untouched`,
    `the validator check exits 0: ${v.declared}`,
    `no product code changed and no other passage of this record, and no other record, moved`,
    `the operation asked the owner only where ${DECISIVE} - and then with numbered options and one recommendation, never with a bare question`
  ]
});
/**
 * The bounds a cut is measured against, mirrored from `kernel/sync.mjs` (`CUT_FILES`, `CUT_ASSERTIONS`) so this
 * module keeps its one property: it depends on nothing and reads only the operation handed to it. A test pins
 * the two copies together, because a contract that states a bound the kernel does not apply is worse than none.
 */
const CUT_FILES=12,CUT_ASSERTIONS=8;

const SEQUENCE_STEPS={
  // Before a node can travel its lane its record must say what may be written and what proves it. That is this
  // operation's whole job: read the material, name real files, turn the node's claims into runnable checks, and
  // build nothing. It is the one operation whose write scope is the record it completes.
  'work.author':v=>({
    steps:[
      `Read the record this operation completes and everything it already names (${v.references}): its parent and sibling records and the accepted requirement and design sections it refers to; restate in three lines what this node must deliver and where its boundary against its siblings runs.`,
      `Open the actual code an implementation of this node would change - follow the referenced design to the owning modules and read them - and list the exact files it would touch; a path you have not opened is not a path you may write, and a scope the material does not determine is a question, never a guess.`,
      `State the node's claims as testable assertions, one per observable outcome the accepted records state; an assertion nobody can run is not an assertion, and a claim the accepted records do not support is dropped rather than softened.`,
      `Write those files as the node's own write scope and one check per assertion into the record the allowlist names (${v.allowlist}); every check is a command this repository already exposes, runnable verbatim, that actually exercises the assertion it declares, and it names the exclusive runtime it needs.`,
      `Leave every other authored line exactly as it is: keep the description, the references, \`required\`, \`state\` and \`dependsOn\` byte for byte, never write \`completion\`, never write the kernel's own extension block, never write anything under the record's own evidence folder, and never edit another node.`,
      `Run the listed validator check verbatim: ${v.declared}; the record must still validate and must now declare both a write scope and checks.`,
      `Report \`done\` exactly once, listing the assertions and the checks you added and the files each one covers. A node whose scope the material does not determine, or an assertion with no command in this repository that could prove it, is \`ask\` with the exact question - which behaviour, which file, which command - never an invented path or a command written in the hope that it exists.`
    ],
    done:[
      `the record at ${v.allowlist} declares a write scope of files you opened and one runnable check per assertion`,
      `every assertion is a claim a named check actually proves, and every check command exists in this repository`,
      `\`completion\`, the kernel's own extension block and the record's evidence folder are untouched, and \`required\`, \`state\` and \`dependsOn\` are exactly as authored`,
      `the validator check exits 0: ${v.declared}`,
      `no product code changed: this operation precedes the node's lane, and the kernel launches that lane itself once the record is complete`
    ]
  }),
  // The runtime prepares the owner's decision; it never takes it. The op first tries the decided records - a
  // question they already settle is answered from them, with the record named - and only a truly open question
  // becomes a decision record draft. Then it asks IN ITS OWN TERMINAL: the owner is at a keyboard, in front of
  // this tab, and making them leave it to type a command is how a question waited a day for a one-word answer.
  // A credential is never asked for as a value: the owner puts it into the tree's own encrypted custody with
  // one command, says `set`, and this operation verifies only that it is there.
  'owner.ask':v=>({
    steps:[
      `Read the question under \`## Question for the owner\` in the goal - who asked it, what it blocks - and every decided business (SRS) and architecture (SDS) record among the references (${v.references}). If a decided record already settles the question, do not ask the owner: report \`done\` with the first line of the summary exactly \`answered-from: <record id>\` followed by the answer in one paragraph, and write nothing.`,
      `Otherwise write ONE policy-decision record draft at the path the allowlist names (${v.allowlist}), schema work/node@2, kind \`business\`, an \`srs-policy-decision\` section with \`decisionStatus: open\`, \`state: todo\`, in the shape of the policy decisions this tree already holds, whose description carries in this order: the question in one sentence; why it matters and what it changes until it is answered; the options, numbered, each with what it means for the architecture, the user stories, the security and authority, the business rules and the quality limits, and what it costs; the decided records each option agrees or conflicts with, by id; and exactly one recommendation with its reason. Real product-shaped content, no placeholders.`,
      `A credential, an account on an outside system, a dataset or a legal authority is something only the owner can provide, and the question names exactly what and exactly how. A credential names the variable the code reads, the outside system it belongs to, and the custody it will live in: \`_resources/identity/<slug>/\` of this Work tree, encrypted with sops. Tell the owner the one command that puts it there - \`node <skill root>/bin/starci.mjs identity set <slug> --name <VAR>\`, which reads the value from stdin, never from the command line, and never prints it - and never ask for the value itself, in the terminal or anywhere else. An environment variable is not custody: it belongs to whichever terminal exported it and is gone on the next machine.`,
      `Then ASK IN THIS TERMINAL, before you report: print the question and the options numbered exactly as they stand in the record, and print "the owner may answer here with the number, or later with workflow-answer --op <this op> --choice <n>". Whether you WAIT depends on the question. A PROVISION (a credential, an account on an outside system, a dataset, a legal authority) or an IRREVERSIBLE effect is the owner's alone: wait for the answer as long as your contract lets you wait, and then report. Any other question is taken provisionally on your recommendation: do not wait - report \`decision: <record id>\` at once, the runtime carries the recommendation into the work behind it, and the owner overturns it later with workflow-answer if they disagree.`,
      `If the owner answers here with a number, report \`done\` with the first line of the summary exactly \`answered-by-owner: <n>\` - that is the owner's ruling and the kernel treats it exactly as the command would. If the owner answers a provision question by saying \`set\` (or \`provided\`), verify only PRESENCE and never the value: for a credential run \`sops exec-env <work tree>/_resources/identity/<slug>/${IDENTITY_SECRETS} 'node -e "process.exit(process.env.<VAR>?0:1)"'\` and, when it exits 0, report \`done\` with the first line exactly \`credential: <VAR> present in identity:<slug>\`; for an account, a dataset or an authority report \`provided: <what the owner provided, in a few words>\`. Never print, echo, log, copy or paste the value, not even partially, and never write it into any file.`,
      `Never answer a question of business, design, authority, security, money or customer data yourself: the recommendation is advice, the decision is the owner's. Never change any other record. Never write product code.`,
      `Run the listed validator check verbatim: ${v.declared}; the record validates in the tree as it stands and \`git status\` shows nothing outside the allowlist.`,
      `If the owner did not answer here, report \`done\` exactly once with the first line of the summary exactly \`decision: <record id>\`, then a line \`recommended: <n>\`, then the options numbered as the owner will answer them. The kernel takes your recommendation provisionally so the work continues, and tells the owner it did.`
    ],
    done:[
      `either the summary begins \`answered-from: <decided record id>\` and no file changed, or \`answered-by-owner: <n>\` / \`credential: <VAR> present in identity:<slug>\` / \`provided: <what>\` because the owner answered in this terminal, or exactly one policy-decision record draft exists at ${v.allowlist} and the summary begins \`decision: <record id>\` with \`recommended: <n>\` and the numbered options`,
      `the question and its numbered options were printed in this terminal with the two ways to answer them, before any report`,
      `no value of any credential or secret appears anywhere - not in a record, a report, a log, this terminal or a file; a credential question names only the variable, the outside system and the \`identity:<slug>\` custody, and presence is all that was ever checked`,
      `no other record and no product code changed, and the validator check exits 0: ${v.declared}`
    ]
  }),
  // An intake authors the records of a feature the tree does not have yet: full business drafts, an architecture
  // skeleton, every leaf record todo (the roots carry no state, like the example). It closes no node - the records
  // it writes are the nodes the tree has afterwards. It first determines every side of the feature as checkable
  // claims, and only then reconciles them against what the product already decided - as three typed cases, never
  // as prose and never as an append: what a decided record already holds is referenced by id, what cannot hold
  // together with it is a decision the OWNER takes, and what is genuinely new is authored here and declares what
  // it reads and what it hands on. Nothing outside this feature is ever edited by an intake.
  'work.intake':v=>({
    steps:[
      `Read the job this workflow was given (the goal above) and the workspace record and example feature the references name (${v.references}); restate in five lines what the feature must let the business do, for whom, and where its boundary against the existing features runs - as the customer would say it, never as a screen or a table.`,
      `Determine the feature, do not just describe it. Before any record is written, settle these sides and write each as checkable claims: ARCHITECTURE - where the feature lives in the control plane, which module owns it, which contracts it goes through, which data it owns and which it only reads; USER STORIES - who does what and sees what, step by step, for the owner, the staff and the agents; SECURITY AND AUTHORITY - who may command, who may approve, who may read which data, what is checked at admission, what is forbidden; BUSINESS RULES - states, money, commitments, and what happens when something goes wrong; QUALITY - performance, reliability, recovery, each with a number; EXTERNAL INTEGRATIONS AND CREDENTIALS - every outside system the feature talks to, the credential or configuration it needs, its exact variable or secret name, and that the OWNER provides it (a key is never invented, never stubbed, never read from a file nobody was asked to fill); OPEN DECISIONS - every question only the owner can answer, as a decision record with the question, the options and a recommendation.`,
      `Reconcile every side against the records the product already decided: read every decided business (SRS) and architecture (SDS) record the feature touches, and write one typed row per touched record into the module record under \`extensions.work3.reconciliation\`, each row \`{case, record, decision, reads, hands, detail}\`. There are exactly three cases and no fourth. \`case: reference\` - this feature repeats what that record already holds: cite it by its \`record\` id and never restate, re-word or redefine a line of it. \`case: conflict\` - this feature cannot hold together with what that record decided: never overwrite it and never average the two; write a decision record under THIS feature (\`state: todo\`) stating both sides, the consequences of each, the numbered options and exactly one recommendation, name that record in \`decision\`, and leave the decided record byte for byte as you found it - the kernel puts the question to the owner, and every part of this feature that rests on it stays a draft behind it. \`case: new\` - no decided record covers it: author it under this feature and declare in \`reads\` the decided records it rests on and in \`hands\` the records of this feature it hands on to. A decided record of another feature is never edited, and no case is left as prose beside the table.`,
      `Open the example feature and read its whole shape - the module record, business/overview, business/srs (business-rules, customer-journeys, data, functional-requirements, non-functional-requirements, decisions), architecture/overview and architecture/sds (components, contracts, data, decisions) - and mirror that shape exactly under the allowlist (${v.allowlist}): the same folders, the same record schema (work/node@2), ids under the same prefix, every leaf record \`state: todo\` and the roots (module, business, srs, architecture, sds index records) without a state exactly as the example has them, every record naming the ones it refers to. When the feature's drafts already exist (a reconciliation pass), rewrite them in place under the same rule; nothing outside the allowlist moves.`,
      `Write the business records as full drafts, not stubs: the overview in the customer's language, every business rule with the outcome it protects, every customer journey step by step with what the person sees and does, the data the feature owns, one testable claim per functional requirement, non-functional requirements with their limits, and every question the job does not settle as an open decision record - a requirement the job does not settle is an open decision, never a guess.`,
      `Write the architecture records as a skeleton that names the components, contracts and data the design will settle, each referencing the requirement it answers, every leaf \`state: todo\` with no design chosen; a design the owner has not taken is an open decision, not a chosen mechanism.`,
      `Run the listed validator check verbatim: ${v.declared}; every record you wrote validates in the tree as it stands, and \`git status\` shows nothing outside the allowlist. Never write \`completion\`, evidence, the kernel's own extension block or any record outside the allowlist; never change another feature's record at all - what a decided record must become is either a \`conflict\` the owner decides or \`new\` work this feature declares, never an edit and never a gap reported against it; never write product code.`,
      `Report \`done\` exactly once with the records you authored, the reconciliation table with its count per case, and the decision records you left for the owner; a boundary the job does not determine is \`ask\` with the exact question, never a guess.`
    ],
    done:[
      `features under ${v.allowlist} carry a module record, a business overview, SRS records (rules, journeys, data, functional and non-functional requirements, open decisions) and an architecture skeleton, every leaf record \`state: todo\` (the roots carry no state, as the example) and the whole feature valid`,
      `every side is determined as checkable claims - architecture, user stories, security and authority, business rules, quality with numbers, external integrations with the exact credential or configuration names the owner provides, open decisions - and none of them is a placeholder`,
      `the module record carries \`extensions.work3.reconciliation\`: one row \`{case, record, decision, reads, hands, detail}\` per decided record the feature touches, its \`case\` one of \`reference\`, \`conflict\` or \`new\` and nothing else`,
      `every \`reference\` row cites a decided record by id and no record of this feature restates it; every \`conflict\` row names a \`todo\` decision record of this feature that states both sides, the consequences, the numbered options and one recommendation; every \`new\` row names a record authored under this feature and declares the \`reads\` it rests on and the \`hands\` it passes work to`,
      `every requirement is a claim the owner can read and test, and every open question is an open decision record, never a guess`,
      `no record of another feature changed by a single byte - a conflict is put to the owner, never overwritten and never averaged - no product code changed, and the validator check exits 0: ${v.declared}`
    ]
  }),
  // A migration brings a feature the tree already decided under the current model. It declares - the typed
  // reconciliation on the module record, the integrations with their custody, one integration node per
  // declaration - and re-decides nothing: no decided record changes its state, its rev or a word, nothing is
  // rewritten as a draft, and nothing under implementation/ or ui/ is touched. What contradicts a decided
  // record is a conflict row and a decision record, never an edit.
  'work.migrate':v=>({
    steps:[
      `Read the module record of this feature and every decided record beneath it under the allowlist (${v.allowlist}), then the decided records of the other features the references name (${v.references}); restate in three lines what this feature decided and where its boundary against the other features runs. Change nothing yet - this operation adds declarations beside decided content and re-decides none of it.`,
      `Reconcile against the other features: for every decided business (SRS) or architecture (SDS) record of ANOTHER feature this feature touches, write one typed row into the module record under \`extensions.work3.reconciliation\`, each row \`{case, record, decision, reads, hands, detail}\`, and nothing but the three cases. \`case: reference\` - this feature rests on what that record holds: cite it by its \`record\` id, restate nothing. \`case: conflict\` - this feature's decided records cannot hold together with it: write a decision record \`state: todo\` under this feature's business/srs/decisions stating both sides, the consequences, the numbered options and exactly one recommendation, name it in \`decision\`, and leave both decided records byte for byte as you found them - mirror the shape of an existing decision record of this tree (the same schema, kind and typed section), never a layout of your own. \`case: new\` - this feature settles what no other record covers: name the record of this feature in the row and declare in \`reads\` the decided records it rests on and in \`hands\` the records it hands on to. No case is left as prose beside the table.`,
      `Declare the integrations: for every outside system the architecture of this feature talks to with a credential the owner holds (a messaging provider, a payment gateway, a mail or storage service, an identity provider) write one entry into the module record under \`extensions.work3.integrations\`: \`{id, provider, credential: {name, providedBy: owner, custody: identity:<slug>}}\`, the \`name\` being the exact variable the code or the configuration records read, the custody the encrypted identity resource of this tree that will hold it. The resource need not exist yet and you never create it: \`custody: identity:<slug>\` is a declaration, and the owner puts the credential there with \`starci identity set <slug> --name <VAR>\` when the integration is proven - that is another operation's ask, never yours. Never a value, never a placeholder value, never a file nobody was asked to fill, never a change to the code that reads the variable. An integration node that already exists keeps its id; a system that needs nothing from the owner is not declared here. A migration never asks for a shared change: everything it writes is a record under its allowlist.`,
      `Author one integration node per declaration that has none yet, at \`features/<feature>/integration/<id>/index.yaml\` inside the allowlist: schema \`work/node@2\`, \`kind: integration\`, \`state: todo\`, \`required: true\`, a description naming the outside system and the credential by name, and one assertion per behaviour a live proof must show. It is the node the tree owes for the declaration; its proof is another operation's.`,
      `Leave every decided record exactly as it was: no \`state\`, no \`rev\`, no wording changes, nothing rewritten as a draft, nothing set to todo, nothing under implementation/ or ui/ touched, no record of another feature changed by a single byte, no \`completion\`, evidence or kernel extension block written. A contradiction you find is a \`conflict\` row and a decision record, never an edit.`,
      `Run the listed validator check verbatim: ${v.declared}; the tree must still validate, and \`git status\` must show only the module record, the decision records and the integration nodes you wrote - all inside the allowlist. An error the validator reports under a path outside your allowlist is not yours: name it in the summary and carry on.`,
      `Report \`done\` exactly once with the count of rows per case, the integrations declared with their credential names, and the nodes you authored. Report \`ask\` only for a provision the owner alone holds (a credential name no code or record settles), never for a question the records answer.`
    ],
    done:[
      `the module record carries \`extensions.work3.reconciliation\`: one row \`{case, record, decision, reads, hands, detail}\` per decided record of another feature this feature touches, its \`case\` one of \`reference\`, \`conflict\` or \`new\` and nothing else; every \`reference\` row cites by id, every \`conflict\` row names a \`todo\` decision record of this feature with both sides, the consequences, the numbered options and one recommendation, every \`new\` row names a record of this feature and declares its \`reads\` and \`hands\``,
      `every outside system the architecture talks to with a credential the owner holds is declared under \`extensions.work3.integrations\` with its id, its provider and a credential {name, providedBy: owner, custody: identity:<slug>}, one \`todo\` integration node exists per declaration, and no secret value appears in any record`,
      `no decided record of this feature changed its state, its rev or its substance; nothing was rewritten as a draft or set to todo; nothing under implementation/ or ui/ changed; no record of another feature changed by a single byte; no product code changed`,
      `the validator check exits 0 for this feature: ${v.declared}`
    ]
  }),
  // Heavy work runs in parallel, and this operation is what makes that possible: a node too big to be one
  // operation becomes many small nodes with disjoint write scopes. Its one hard rule is the order - the SEAM
  // every other child would otherwise touch is named and built FIRST and alone, and only then does the rest fan
  // out - because two builds that both edit the module wiring are not parallel work, they are one merge conflict
  // with two authors. It writes records, never product code, and a node that really is one behaviour is left alone.
  'work.cut':v=>({
    steps:[
      `Read the node this operation cuts (${v.cutNode}) and everything it names (${v.references}): its description, its assertions, its declared write scope, and the accepted requirement (SRS) and design (SDS) records it refers to. Restate in three lines what the whole node must deliver; the kernel measured it as too big because ${v.cutReason}.`,
      `Open the actual code the node's write scope names and read it - the modules, their wiring, their contracts and their migrations. A boundary you have not read is not a boundary you may draw, and a part the material does not determine is \`ask\` with the exact question, never a guess.`,
      `Name the SEAM first, before any other part: the ONE child that owns what every other child would otherwise touch - module wiring and registration, dependency-injection setup, database migrations, shared contracts, shared types and shared fixtures. It is built first and alone. A group with no seam is a group whose children will collide; if nothing is shared, say so in the report and give the reason.`,
      `Cut the rest by acceptance, never by file: each remaining child is ONE observable behaviour, with a write scope of at most ${CUT_FILES} files that is disjoint from every sibling AND from the seam, one runnable check per assertion, and every assertion traced to the same SRS/SDS ids the parent traced to. A behaviour that needs a sibling's file is not a separate child - it belongs to the seam or to that sibling. Then declare the order: every non-seam child carries the seam's node id in \`dependsOn\` and no other dependency on a sibling, so the kernel builds the seam first and fans the rest out behind it; two children that must wait for each other were cut wrong.`,
      `Write each child at \`<node dir>/<part>/index.yaml\` inside the allowlist (${v.allowlist}): schema \`work/node@2\`, \`kind: implementation\`, \`state: todo\`, \`required: true\`, its description, its assertions, its write scope and its checks - exactly the record a build can be launched from without anyone inventing its scope.`,
      `Turn ${v.cutNode} into a derived parent: remove its \`state\`, its \`completion\` and its write scope, and keep its assertions as the group's acceptance under \`extensions.work3.groupAssertions\`. A parent with children authors no state - it derives one from them - and that group acceptance is what the group's single proof is judged against.`,
      `Run the listed validator check verbatim: ${v.declared}; the tree must validate with the parent derived and every child launchable, and \`git status\` must show nothing outside the allowlist. Never write \`completion\`, the kernel's own extension block or anything under an evidence folder, never edit another node, and never write product code.`,
      `Report \`done\` exactly once, naming the seam, then each child with its behaviour, its write scope and its checks. A node that is genuinely one observable behaviour is not split: report \`done\` with \`cut: none\` and the reason, and the kernel runs the node as it is.`
    ],
    done:[
      `either exactly one child is named the SEAM and every other child \`dependsOn\` it, or the report says \`cut: none\` and nothing under ${v.allowlist} changed`,
      `every child is one observable behaviour at \`<node dir>/<part>/index.yaml\` (work/node@2, \`kind: implementation\`, \`state: todo\`, \`required: true\`) with a write scope of at most ${CUT_FILES} files, disjoint from every sibling and from the seam, and one runnable check per assertion`,
      `no child states more than ${CUT_ASSERTIONS} assertions, and every child assertion traces to the same SRS/SDS ids ${v.cutNode} traced to`,
      `${v.cutNode} is a derived parent: no \`state\`, no \`completion\`, no write scope, its assertions kept as \`extensions.work3.groupAssertions\``,
      `the validator check exits 0: ${v.declared}`,
      'no product code changed: this operation precedes the children\'s lanes, and the kernel launches them itself - the seam first, then the rest at once, and one proof for the whole group'
    ]
  }),
  'implement.ledger':v=>({
    steps:[
      `Read ${v.references} and the node assertions (${v.acceptance}); restate in three lines what must be true when you are done.`,
      `Write or extend the spec(s) that prove each of those assertions and run them: they MUST fail now (the kernel checks that they failed at the base head and pass after your change; a spec that is green before your code proves nothing).`,
      `Implement the smallest change inside the allowlist (${v.allowlist}) until those specs pass; no refactor, no drive-by edit.`,
      `Run every listed check verbatim: ${v.checks}.`,
      `Self-audit: every assertion has a passing check, \`git status\` shows no file outside the allowlist, no secret, no TODO left in what you changed.`,
      `Report \`done\` exactly once with the spec paths and the check commands. A change you need outside the allowlist: report \`blocked\` with blocker \`shared-change\` and the exact paths, never touch them. A contradictory or missing design (SDS): report \`blocked\` with blocker \`sds-gap\`, or \`ask\` with the exact gap.`
    ],
    done:[
      `every assertion (${v.acceptance}) is proven by a spec that was red before your change and is green after it`,
      `every check exits 0: ${v.checks}`,
      `only allowlisted paths changed`
    ]
  }),
  'implement.shared':v=>({
    steps:[
      `Read the request from ${v.requesters}: the exact paths (${v.allowlist}) and the behavior they need (${v.acceptance}).`,
      `Make the minimal change that gives the requester what it asked for; no refactor, no renaming, nothing the request did not name.`,
      `Run the requester's checks verbatim: ${v.checks}.`,
      `Self-audit: \`git status\` shows only ${v.allowlist}; nothing else moved.`,
      `Report \`done\` exactly once, naming what changed and why the requester can now proceed; report \`blocked\` with \`shared-change\` and the exact paths if the change needs yet another path.`
    ],
    done:[`the requested change exists on ${v.allowlist} and nothing else`,`the requester's checks exit 0`]
  }),
  'implement.repair':v=>({
    steps:[
      `Read the ${v.findings} listed under "Findings you must resolve" and map each one to the file, line and assertion it names.`,
      `For each finding, re-run the check that exposed it and confirm it fails now: ${v.checks}.`,
      `Fix each finding explicitly inside the allowlist (${v.allowlist}); do not widen the change beyond what a finding names.`,
      `Re-run every check verbatim until each exits 0: ${v.checks}.`,
      `Self-audit: every finding has a fix, \`git status\` shows no file outside the allowlist, no TODO.`,
      `Report \`done\` exactly once with a finding -> fix map in the summary; a finding you cannot resolve inside the allowlist: report \`blocked\` with \`shared-change\` and the exact paths.`
    ],
    done:[`every one of the ${v.findings} has a named fix`,`the check that exposed each finding exits 0`,`only allowlisted paths changed`]
  }),
  'implement.gate':v=>({
    steps:[
      `Read the failing gate(s) in "Findings you must resolve" (${v.findings}): the gate name, its exit code and its evidence.`,
      `Re-run the failing gate command verbatim and read the first failure: ${v.checks}.`,
      `Fix exactly what the failing gate names inside the allowlist (${v.allowlist}); nothing else.`,
      `Re-run the gate until it exits 0, then every other listed check.`,
      `Self-audit: \`git status\` shows no file outside the allowlist.`,
      `Report \`done\` exactly once naming the gate and the fix; report \`blocked\` with \`shared-change\` and the exact paths if the fix lives outside the allowlist.`
    ],
    done:[`the named gate exits 0`,`no other check regressed`,`only allowlisted paths changed`]
  }),
  'interface.draw':v=>({
    steps:[
      `Read ${v.references} - the requirement (SRS) and design (SDS) sections this interface must satisfy - and the node assertions (${v.acceptance}); name every screen this operation draws.`,
      `For each screen, enumerate every state it can be in before you draw anything (at least loading, empty, error, interaction, populated and permission-denied where the requirement allows it) and DESCRIBE each in the record: what it shows, which grammar state contract renders it. Only the main state - the populated, interactive screen - is drawn; loading, empty and error are the grammar's own state contracts and the build renders them from code, never a picture of them.`,
      `Read the WHOLE installed design grammar and every pattern the references list (the grammar family files, every frontend pattern, every UI composition/presentation/proof rule) before you compose; compose inside them - contract components and their anatomy, the token palette, typography, spacing, icon set, blueprint vocabulary - and inside the brand record: every colour, font, mascot and forbidden item comes from the brand, never from your taste; invent no component, token, colour or icon of your own - a region the grammar cannot render is a \`grammar-gap\`, never an improvisation.`,
      `Write the interface design record at the path the allowlist names (${v.allowlist}): per screen its blueprint (the regions in order), each enumerated state with what it shows and the grammar contract that renders it, the contract slots each region fills and the exact copy, AND the design binding the build will read from the Work tree - the grammar family and package version, the brand record and rev, the exact tokens.`,
      `Render ONE candidate per screen and viewport (desktop and mobile) - the main state only - FROM THE INSTALLED GRAMMAR ITSELF: compose the screen from the grammar package's own renderers (its contract components, its stylesheet, the brand tokens) as static markup or a server-side render in a scratch folder outside the product (never product code, never a story committed to the app), open it in headless Chrome and capture the PNG into the node's own assets/, KEEPING THE MARKUP IT RENDERED beside each PNG as \`<candidate>.html\` so the render can be checked from its source. Never an image model for a surface, never hand-painted boxes, never a mockup-tool export, never a capture of a working feature: a candidate that is not the grammar rendering the screen is a defect, and so is one with no markup beside it. Real, product-shaped content in every region - names, amounts, dates, statuses - never lorem or grey bars.`,
      `List every artwork the chosen candidate embeds - each illustration, each appearance of the brand mascot, each decorative image, each chart or media placeholder - in the record as an \`artworkSlots\` entry: ${SLOT_SHAPE}. The image model is for artwork only, and that is the next operation's job (interface.asset): here the slot is a placeholder region in the render with its brief. A candidate whose embedded artwork the record does not list is an incomplete record.`,
      `Self-check against the two canon rules, then report: every assertion (${v.acceptance}) maps to a named screen state described in the record, every enumerated state is described with its grammar contract, the main-state candidate of every screen exists at both viewports with its markup beside it and was captured from the grammar render, NO CANDIDATE PLACES A LIST OF ENTITIES INSIDE A CARD (a collection is a page section with a heading; a card is one item), EVERY COLOUR THE CAPTURE IS LARGELY MADE OF IS A BRAND TOKEN and the brand's primary is present, THE MASCOT APPEARS ONLY WHERE THE BRAND RECORD ALLOWS IT and every appearance has its slot, every component visible in a candidate is a grammar contract, every artwork visible in the chosen candidate has its \`artworkSlots\` entry with a crop that locates it, and nothing in the record rests on a business rule the references do not state. Run \`starci render check <ui node dir> --brand <work root>\` over the node and fix what it names; a check it could not run is unproven, never a pass.`,
      `Report \`done\` exactly once with the record path(s), the rendered candidates and the artwork slots you declared; a business rule the references do not settle is \`blocked\` with blocker \`sds-gap\` and the exact question, never a guess; a grammar that has no contract for a region the screen needs is \`blocked\` with \`grammar-gap\` naming the region; a change outside the allowlist is \`blocked\` with \`shared-change\` and the exact paths.`
    ],
    done:[
      `the record at ${v.allowlist} names every screen and describes every enumerated state (loading, empty, error, interaction, populated, permission-denied where it applies) with the grammar state contract that renders it, as the node's \`ui:\` spec with every kept candidate declared in both \`ui.assets\` and the node's \`assets:\``,
      `every assertion (${v.acceptance}) maps to one screen, and every screen has exactly one candidate PNG per viewport of its main state with the markup it was rendered from kept beside it as \`<candidate>.html\`, captured by a browser from the installed grammar's own rendering - never generated by an image model, never painted by a script, never a mockup export`,
      `every component visible in a candidate is a grammar contract and every colour, font and icon is a brand token; the record pins the grammar package version and the brand rev it was drawn against`,
      `the two canon rules hold in the candidates themselves and \`starci render check\` says so: no list of entities inside a card, no dominant colour outside the brand's tokens, the brand's primary present, and a mascot slot declared wherever the brand allows the mascot`,
      `every artwork the chosen candidate embeds is declared as an \`artworkSlots\` entry with its region, purpose, brief, size, format, brand references and candidate crop; a candidate with artwork the record does not list is incomplete`,
      `no product code changed; the drawing stays inside the installed design grammar`,
      LANE
    ]
  }),
  // The artwork the approved candidate embeds becomes real files, re-rendered from that candidate rather than
  // reinterpreted from its words, and bound back to the slots that declared them. No product code is touched:
  // wiring the file into a component is the build's step, which is why this operation can refuse instead of improvise.
  'interface.asset':v=>({
    steps:[
      `Read the interface design record among the references (${v.references}) and its \`artworkSlots\`: per slot ${SLOT_SHAPE}. Open the chosen candidate image beside the record and locate each slot's crop inside it; a slot whose crop you cannot locate, or artwork in the candidate that no slot declares, is \`blocked\` with blocker \`interface-gap\` naming the screen, state and region - the drawing declares artwork, this operation never invents a brief.`,
      `Read the brand record the references attach - its colour tokens, its mascot and logo masters with the placements each one allows and forbids, and its imagery rules - and open every master a slot references. Settle per slot whether its brief can be honoured inside those rules before you generate anything.`,
      `Generate each slot WITH THE IMAGE MODEL, passing the slot's candidate crop and the brand masters it references as actual input references (\`-i\`), so what you produce is the artwork the person approved rather than a new one that matches the same words. Produce exactly the declared size and format, one file per slot.`,
      `Write each file at the asset path the allowlist names (${v.allowlist}) and nowhere else: no component, no stylesheet, no configuration and no other product file is touched here, and a destination outside the allowlist is \`blocked\` with \`shared-change\` and the exact paths, never a wider write.`,
      `Open every file you wrote and compare it against its slot - the crop it must reproduce, its declared size and format, the brand placement its references allow - then record \`{slot -> file, sha256}\` back into the design record and bind each path in its asset list. Change no brief, region, size, format or crop: those are the drawing's.`,
      `Self-audit: every declared slot has either a file with its sha256 or a named reason it has none, every recorded path exists with the recorded bytes, \`git status\` shows only the allowlisted asset paths and the record, and no product code moved.`,
      `Report \`done\` exactly once with the slot -> file table (slot id, file path, size, format, sha256). A slot whose brief cannot be honoured inside the brand rules is \`blocked\` with blocker \`brand-gap\` naming the exact rule and the exact brief that conflict; a host with no image model is \`failed\` with that reason - a scripted, hand-drawn or placeholder file is never a generated asset, and a slot left empty is never a \`done\`.`
    ],
    done:[
      `every \`artworkSlots\` entry of the design record has a real file at the allowlisted asset path (${v.allowlist}), at its declared size and format, recorded back as \`{slot -> file, sha256}\``,
      `each file was generated from the slot's candidate crop and its brand masters as references, then opened and compared against them - a reinterpretation of the brief is not the approved artwork`,
      `no brief, region, size, format or crop was rewritten, no slot was added or dropped, and no product code changed`,
      `a slot the brand rules cannot satisfy is \`blocked\` \`brand-gap\` and a missing image model is \`failed\`, never a \`done\` with an empty slot`,
      LANE
    ]
  }),
  'frontend.implement':v=>({
    steps:[
      `Read the interface design record named in ${v.references} first - its screens, their enumerated states, blueprints, contract slots, copy and its \`artworkSlots\` with the file and sha256 each slot was generated to; a screen, state or artwork the record does not contain is not yours to invent: report \`blocked\` with blocker \`interface-gap\` naming the missing screen, state or region instead of improvising a layout.`,
      `Write the failing story/spec per screen state in the record and run them: they MUST fail now (the kernel checks that they failed at the base head and pass after your change; a story that is green before your code proves nothing).`,
      `Implement inside the allowlist (${v.allowlist}) with the typed components of the installed design grammar only - no untyped children, no new component family, no ad-hoc token, no screen the record does not describe.`,
      `Wire every artwork slot: import the exact file the record names for that slot into the typed component bound to its region, at the size the slot declares. Never regenerate, redraw, resize beyond the declared slot, substitute another image or ship an empty region in place of one - a slot whose file is missing or whose brief the brand rules cannot satisfy is \`blocked\` with \`interface-gap\` or \`brand-gap\`, never an image you invented, picked or drew yourself.`,
      `Update the stories and the skeleton of every layout you changed, so each state stays renderable on its own (a layout change without its story and skeleton is an unfinished change).`,
      `Run every listed check verbatim: ${v.checks}.`,
      `Self-audit: every state of the record has a passing story/spec, every \`artworkSlots\` entry is listed with the component and region it is wired into and the exact file it imports, \`git status\` shows no file outside the allowlist, no TODO, and no screen or image exists that the record does not describe.`,
      `Report \`done\` exactly once with the story/spec paths, the slot -> component wiring and the check commands; \`blocked\` \`interface-gap\` for a screen, state or artwork the record lacks, \`blocked\` \`brand-gap\` for artwork you cannot ship inside the brand rules, \`blocked\` \`shared-change\` with the exact paths outside the allowlist, \`blocked\` \`sds-gap\` for a missing business rule.`
    ],
    done:[
      `every screen state of the interface design record has a story/spec that was red before your change and is green after it`,
      `every \`artworkSlots\` entry is wired into the component the record binds to its region, importing the generated file the record names - no artwork was regenerated, substituted or invented here`,
      `stories and skeletons match the layout you shipped, and every state renders in isolation`,
      `every check exits 0: ${v.checks}`,
      `only allowlisted paths changed and no screen was invented beyond the record`,
      LANE
    ]
  }),
  'review.verify':v=>({
    steps:[
      `Read ${v.references} and the assertions under review (${v.acceptance}); the code under ${v.allowlist} is what you review, and this operation is read-only: change no product file.`,
      `Run every check of the group yourself, verbatim: ${v.checks}; record each exit code.`,
      `Compare the implemented behavior against each assertion and the design (SDS) it references; read the code and the specs, not the previous report.`,
      `Write each finding as file + line + the assertion it breaks; a finding without a file and line is not a finding.`,
      `Never fix anything: a repair is a separate operation the kernel creates from your findings.`,
      `Report \`done\` exactly once with the findings in \`open[]\` (empty when the group is clean) and the checks file; report \`failed\` only when a check could not run at all.`
    ],
    done:[`every check ran and its exit code is recorded`,`every assertion was compared against the code`,`findings name file, line and assertion; no product file changed`]
  }),
  'e2e.verify':v=>({
    steps:[
      `Read the design (SDS) and requirement (SRS) material in ${v.references} and the node assertions (${v.acceptance}); restate, per assertion, the request a client sends and the observable effect the stack must show.`,
      `Write or extend the end-to-end spec at the path the allowlist names (${v.allowlist}): one scenario per assertion, exercised through the public API on the real stack (database, identity, containers) with no mock of the unit under proof; never through a screen.`,
      `Start only the end-to-end runtime named in resources (${v.resources}) and seed it as the scenario needs; touch no other runtime and change no product code - a behavior that is wrong is a finding to report, not a fix to make here.`,
      `Name every external provider your scenarios do NOT call for real - each one you mock, stub, record, replay or point at a local double - and write those ids into the evidence as \`proof: {boundary: api, fakes: [<provider ids>]}\`. This operation proves the product's API against a real stack, so a faked outside system is allowed here, but never unnamed: a provider the diff fakes that the evidence does not list is a defect, and proving that provider for real is its own \`integration\` node walking \`integration.verify\`.`,
      `Run the listed check verbatim (${v.checks}) and keep the run output; a scenario that passes without the stack running proves nothing and is a defect of the spec.`,
      `Self-audit: every assertion has a scenario, every scenario ran on ${v.resources}, and \`git status\` shows only ${v.allowlist}.`,
      `Report \`done\` exactly once with the run output in the summary and the spec paths; a failing scenario is \`failed\` naming the assertion and the observed response; a runtime that cannot start is \`failed\` with the exact reason (\`blocked\` \`environment\` only when it provably cannot be fixed from the allowlist); never \`done\` on an unrun or partial spec.`
    ],
    done:[
      `the spec at ${v.allowlist} exercises every assertion (${v.acceptance}) through the API on the real stack`,
      `it ran on ${v.resources} and its output is in the report`,
      `the evidence carries \`proof: {boundary: api, fakes: [...]}\` naming every external provider the scenarios faked, stubbed, recorded or replaced with a double`,
      `a failing scenario or a runtime that did not start is \`failed\`, never a \`done\``,
      'Lane: this op is the prove step of `backend.implement` -> `e2e.verify` -> `review.verify`; the node is done only after `review.verify` accepts the slice this spec proved.'
    ]
  }),
  // An external system is proven against itself or it is not proven. The whole sequence exists because a
  // fake of a declared provider was once inside a prove operation's contract: here it is a defect by name,
  // the credential is the owner's and is read from the environment only, and a missing one stops the work
  // with the exact variable rather than quietly running against a double.
  'integration.verify':v=>({
    steps:[
      `Read the integration declaration this node proves (${v.references}) - the \`extensions.work3.integrations\` entry in the business (SRS) or design (SDS) record that declared it: its id, the provider, the exact credential variable the owner provides, the \`custody\` that holds it (\`identity:<slug>\`), and the provider's own sandbox - and the design the integration belongs to and the node assertions (${v.acceptance}); restate per assertion the call this product makes to that provider and the observable effect the provider must show.`,
      `The credential is the owner's and has exactly one source: the encrypted identity resource the declaration's \`custody\` names - the Work tree's own \`_resources/identity/<slug>/${IDENTITY_SECRETS}\`, read through sops at the moment of use. Never an environment variable you export, never a file you create, never a second variable of your own naming, never a default and never a value you invent. If sops is not installed, the key for this tree is not available, or that resource does not hold the variable, stop here and report \`blocked\` with blocker \`environment\` naming the slug and that exact variable and nothing else - no value, no guess, no partial run, no fallback.`,
      `Write the live scenario at the path the allowlist names (${v.allowlist}): one scenario per assertion, each one calling the real provider's own sandbox over the network. No fake, no stub, no mock, no recorded or replayed response, no local double, no skipped or conditionally-skipped test, and no "when the key is missing" branch - a scenario that can pass while the provider is silent proves nothing and is a defect of the spec.`,
      `Run the listed check verbatim, INSIDE the custody: \`sops exec-env <work tree>/_resources/identity/<slug>/${IDENTITY_SECRETS} '<check>'\` for each of ${v.checks}. The value then exists only inside that one process: never copy it into a file, a fixture, an environment file, a log, the report or this contract, never print or echo it, and never commit it. The variable name and the custody slug are what travel; what they hold never does. Keep the whole run output and put it in the report with every secret masked.`,
      `Write the evidence for this node with \`proof: {boundary: live, fakes: []}\` - this operation proves the outside system itself, so it names no fake, and an evidence record of this kind that lists one is a defect.`,
      `Self-audit: every assertion has a scenario that actually reached the provider, the run output carries the provider's real responses, no secret value appears in any file the diff touches, and \`git status\` shows nothing outside ${v.allowlist}.`,
      `Report \`done\` exactly once and only on a green live run, with the run output and the spec paths. A scenario the provider rejected is \`failed\` naming the assertion and the response it returned; a provider outage, a sandbox that will not answer or a rate limit is \`failed\` with that exact reason; a missing credential is \`blocked\` \`environment\` with the variable name. Never \`done\` on a skipped, faked or unrun scenario.`
    ],
    done:[
      `the scenario at ${v.allowlist} calls the real provider's sandbox for every assertion (${v.acceptance}), with the credential read only through \`sops exec-env\` from the identity custody the declaration names`,
      `no fake, stub, mock, recorded response, local double or skipped scenario stands in for the declared provider anywhere in this operation`,
      `the evidence carries \`proof: {boundary: live, fakes: []}\` and the run output is in the report with every secret masked; no credential value exists in any record, spec, fixture, log or report`,
      `a credential the custody cannot give you - no sops, no key for this tree, no such variable in \`identity:<slug>\` - is \`blocked\` \`environment\` naming the slug and the variable, and a provider outage or a red scenario is \`failed\` - never a \`done\``,
      'Lane: the node is the tree\'s one proof of this declared integration; `e2e.verify` may fake the same provider under `proof: {boundary: api}`, and only this operation makes it proven live.'
    ]
  }),
  uat:v=>({
    steps:[
      `Read the flow folder named in ${v.references}: the flow, its seed and its accounts; restate the steps a user takes and what each step must show.`,
      `Write the end-to-end spec at the path the allowlist names (${v.allowlist}), one step of the flow per assertion (${v.acceptance}).`,
      `Start the end-to-end runtime named in resources (${v.resources}) and seed it as the flow says; touch no other runtime.`,
      `Run the spec on that runtime: ${v.checks}; keep the run output. A step that needs a credential runs inside its custody - \`sops exec-env <work tree>/_resources/identity/<slug>/${IDENTITY_SECRETS} '<check>'\` - so the value lives only in that process and is never copied into a file, a log, a report or this contract.`,
      `Self-audit: every flow step has an assertion, the spec ran against the named runtime, \`git status\` shows no file outside the allowlist.`,
      `Report \`done\` exactly once with the run output in the summary. If the runtime cannot start or the flow cannot be seeded, report \`failed\` with the exact reason; never \`done\` on an unrun spec.`
    ],
    done:[`the spec at ${v.allowlist} covers every flow step`,`it ran on ${v.resources} and its output is in the report`,`a runtime that did not start is a \`failed\`, never a \`done\``]
  }),
  'uat.verify':v=>({
    steps:[
      `Read the flow folder named in ${v.references}: the flow steps, its seed and its accounts; restate each step and what the rendered surface must show when it is done.`,
      `Start the runtime named in resources (${v.resources}) and seed it exactly as the flow says, with the commands the flow declares (${v.declared}); touch no other runtime and change no product code.`,
      `Walk the flow on the rendered surface the way a person does - open the page, click, type, read what is on screen - and never through the API: a step proven by a request or a mutation is not walked, and it is a finding against you.`,
      `Capture a screenshot at every step and keep it with that step; a step without a capture did not happen.`,
      `Compare each step against the interface design record and the node assertions (${v.acceptance}): the state shown, the copy, the order of the blueprint, and every \`artworkSlots\` entry of that screen state - the declared artwork is visible in your screenshot, in its own region, and is the file the record names. A missing artwork, an empty region where a slot is declared, or a different image than the slot's file is that step failing, not a note for later; a difference of any kind is that step failing.`,
      `Write the run record under the flow folder at the path the allowlist names (${v.allowlist}): per step what you did, what you saw, its screenshot and its verdict, plus the heads and the seed you ran against.`,
      `Report \`done\` exactly once and only when every step of the walk passed; a step that failed is \`failed\` naming the step, what you saw instead and its screenshot; a runtime that cannot start is \`failed\` with the exact reason (an environment you cannot fix is \`blocked\` with \`environment\`); a walk that stopped early is \`partial\` or \`failed\`, never \`done\`.`
    ],
    done:[
      `every flow step was walked on the rendered surface, never through the API, and every step has a screenshot`,
      `every artwork slot of the screen states you walked is visible at its region in that step's screenshot and is the file the record names; a missing or different asset is a failed step`,
      `the run record at ${v.allowlist} carries each step's verdict against the interface design record and the assertions (${v.acceptance})`,
      `a partial walk, a failed step or a runtime that did not start is \`partial\`/\`failed\`, never a \`done\``,
      LANE
    ]
  }),
  'architecture.revise':REVISE({record:'design (SDS)',where:'the SDS section',
    silent:'the behavior the implementation could not derive from it',
    written:'the behavior, its contract and its acceptance so an implementer derives the code from the text alone',
    escape:'a gap that is really a missing or self-contradictory REQUIREMENT is `blocked` `srs-gap` back to the business record that owns it, never answered with a design decision'}),
  'business.revise':REVISE({record:'requirement (SRS)',where:'the requirement, rule or journey',
    silent:'the outcome the operation could not derive from it - silent, ambiguous, or settled twice in two ways',
    written:'what the product must do, with the acceptance an implementer derives code from and a test can fail on',
    escape:'a gap that is really a missing DESIGN - the requirement is clear and only the realisation is not - is `blocked` `sds-gap` back to the architecture record, never answered with a new product rule'}),
  // The language itself, grown by one word. Its first move is an attempt NOT to grow it: a shape that composes
  // out of existing contracts is not a missing word, and a grammar that gains a unit per screen is no grammar.
  // What it changes lives in another repository with its own gates and its own published version, so the
  // irreversible step - the publish - comes last and only behind green gates.
  'grammar.update':v=>({
    steps:[
      `Read the gap report that opened this operation (${v.findings}) and ${v.references}: the exact shape the requester could not render, the accepted requirement and design that oblige it, the interface design record and the screen, state and region it belongs to - then read the WHOLE installed canon (the grammar family files DNA, family, idioms and playbook, every frontend pattern, every UI composition, presentation and proof rule) and the brand record. A gap that is really a missing business rule or a missing screen is \`blocked\` \`sds-gap\` or \`interface-gap\` back to the record that owns it, never answered with a new component.`,
      `FIRST try to express the shape as a composition of existing contracts and blueprint regions, and write that attempt down: which contracts, which named slots, which constraints, which region each sits in. If it composes, the grammar is not short a word: report \`done\` with the composition, change nothing in the grammar, and let the requester draw it that way.`,
      `Only when it does not compose, name the one new semantic unit: whether it is a primitive (a fixed semantic unit) or a block (it carries feature meaning), its anatomy, its named slots, every state it can be in and the tokens, typography, spacing and icons it reuses - none invented, none widened. One unit per operation; whether the unit is really new is \`ask\` with the composition attempt attached, never a guess.`,
      `Implement it in the grammar repository inside the allowlist (${v.allowlist}), following that repository's own conventions for how a contract component, its slots and its states are declared, with the stories and tests it requires: write them first and show them failing on the revision you started from, then green after your change.`,
      `Run that repository's gates verbatim, all of them, on the same revision - ${v.checks} - and only when every one is green publish a new version of the package. The publish is irreversible: a red or unavailable gate is \`failed\` or \`blocked\`, never a publish. Report the exact version, and read it back from the registry before you claim it (\`npm view <pkg>@<version>\`): a registry may serve a new version only one to three minutes after it accepts it, and an unread version is not a published one.`,
      `Bind that exact version in the consuming repository: when the consumer is inside the allowlist, bump its dependency and prove it resolves; when it is outside, report \`blocked\` with \`shared-change\` and the exact manifest paths. Never edit a consumer silently and never leave the version unbound.`,
      `Record the unit in the canon - the grammar family files and the frontend pattern it belongs to - with its anatomy, slots, states and the tokens it reuses, so a later drawing finds the word instead of asking for it again.`,
      `Self-audit, then report \`done\` exactly once with the unit, the exact published version and the canon entries you wrote: \`git status\` shows nothing outside ${v.allowlist}, no product page or screen changed, and no second unit was slipped in. A path outside the allowlist is \`blocked\` with \`shared-change\` and the exact paths.`
    ],
    done:[
      `the composition of existing contracts was tried first and the attempt is written down, naming the contracts, slots and regions and exactly why the shape does not compose`,
      `exactly one semantic unit was added, classified as a primitive or a block, with its anatomy, slots, states and reused tokens declared - nothing invented, no token set widened`,
      `the unit has the stories and tests that repository requires, red on the revision you started from and green after your change`,
      `every gate of the grammar repository exits 0: ${v.checks}`,
      `one new version is published and was read back from the registry as actually served, with the exact version reported`,
      `the consumer resolves that version - bumped inside the allowlist or raised as \`shared-change\` with the exact paths - and the canon names the new unit`,
      `only allowlisted paths changed: no product page, no screen and no second unit`
    ]
  }),
  operations:v=>({
    steps:[
      `Read ${v.references} and the assertions (${v.acceptance}); name the runtime state before and after.`,
      `Write the change inside the allowlist (${v.allowlist}); never edit an already-committed migration or an already-applied operation.`,
      `Apply it on a real database or service container (${v.resources}) and record the output.`,
      `Roll it back on the same container and prove the rollback leaves the prior state; then apply again to prove idempotence.`,
      `Run every listed check verbatim: ${v.checks}.`,
      `Self-audit: apply, rollback and re-apply outputs are recorded, no secret in any file, \`git status\` shows no file outside the allowlist.`,
      `Report \`done\` exactly once with the apply/rollback/re-apply outputs; a container that cannot start is a \`failed\` with the exact reason, an environment you cannot fix is \`blocked\` with \`environment\`.`
    ],
    done:[`apply, rollback and re-apply all succeeded on ${v.resources}`,`every check exits 0`,`no committed migration was edited`]
  }),
  migration:v=>({
    steps:[
      `Read ${v.references} and the assertions (${v.acceptance}); name the schema before and after.`,
      `Write a NEW migration inside the allowlist (${v.allowlist}); never edit an already-committed migration - a correction is another migration.`,
      `Apply it on a real database container (${v.resources}) and record the output.`,
      `Roll it back on the same container and prove the schema returns to the prior state; then apply again to prove idempotence.`,
      `Run every listed check verbatim: ${v.checks}.`,
      `Self-audit: apply, rollback and re-apply outputs are recorded, no data-destroying statement without the design saying so, \`git status\` shows no file outside the allowlist.`,
      `Report \`done\` exactly once with the apply/rollback/re-apply outputs; a container that cannot start is a \`failed\` with the exact reason.`
    ],
    done:[`the migration applies, rolls back and re-applies on ${v.resources}`,`every check exits 0`,`no committed migration was edited`]
  }),
  decide:v=>{
    // The two decision kinds answer different questions and own different records; the steps say which.
    const business=v.kind==='business.decide';
    const frame=business
      ?'a business decision - what the product must do, written as requirement, rule or journey'
      :'a design decision - how the system satisfies an accepted requirement, written as component, contract or mechanism';
    const against=business
      ?'the requirement it states and the journeys and rules it changes'
      :'the requirement (SRS) it must satisfy and the rest of the design (SDS) it must stay consistent with';
    const forbidden=business
      ?'no component, contract, schema or technology choice - that is an `architecture.decide`'
      :'no new product rule, price or policy - that is a `business.decide`';
    return {
      steps:[
        `Read ${v.references} and the closed options the node offers; this is ${frame}, and the decision is among those options only.`,
        `Weigh each option against the assertions (${v.acceptance}) and ${against}; write the trade-off in one line per option.`,
        `Choose one option and write the decision with its rationale into the node file the allowlist names (${v.allowlist}); no code, no other file, and ${forbidden}.`,
        `Self-audit: the chosen option is one of the offered ones, the rationale names why the others lose, \`git status\` shows only ${v.allowlist}.`,
        `Report \`done\` exactly once with the chosen option; when no offered option satisfies the assertions, report \`ask\` with the options and what each lacks, never invent a new one silently.`
      ],
      done:[`the node records one chosen option with a rationale`,`the decision stays inside its own layer: ${forbidden}`,`no code changed`]
    };
  },
  // The identity every later drawing and build reads, settled once in one record. Its one hard rule is that
  // nothing in it is chosen: every value is read out of a real source file and traceable back to it, so the
  // record describes the product that exists rather than the one the operation would have preferred.
  'brand.decide':v=>({
    steps:[
      `Read ${v.references} - the accepted scope and the rulings the owner has already made about identity - and the node assertions (${v.acceptance}); restate in three lines what this identity must state and which of its decisions are already settled.`,
      `Open the real token and style files of the product's interface - the global stylesheet, the installed design grammar's family root, the theme and token files - and read every value out of them: per token, the grammar token name the renderer actually consumes, the value, and the exact file and declaration it came from. A value you cannot trace to a declaration is not yours to choose.`,
      `Map the owner's rulings onto those token names and write the policy the set is judged against: which role each token fills, whether the danger role may share the primary value, and the minimum contrast every text-on-surface pair must hold; measure the pairs you declare and record the ratios rather than asserting them.`,
      `Settle typography, the one icon set the product may use, the mascot and the logo: reuse the assets that already exist with their real paths and hashes, and only when no mascot asset exists at all, generate ONE placeholder with the image model from the owner's description and store it beside the record with its sha256, marked a placeholder awaiting acceptance - with no generator available, write a concrete brief and leave the slot empty, and never describe a missing file as generated.`,
      `Write the record at the path the allowlist names (${v.allowlist}): identity and family, the traced tokens with their roles and policy, typography, mascot and logo with where each may and may never appear, the icon set, the imagery rules whose prompt rules oblige every later image prompt to name this identity, the artwork-slot conventions, voice, motion, the forbidden list, and the source files every value was read from; no product code.`,
      `Run the listed check verbatim: ${v.declared}; keep its output, then bump the record's \`rev\` and state in one line what changed.`,
      `Report \`done\` exactly once with the new \`rev\`, the checks and the token-to-source trace. A value no source file declares is \`ask\` naming the token and the file it should live in, never a colour you picked; a source file the record needs and that does not exist is \`blocked\` with \`environment\` and the exact path; an identity decision nobody has ruled is \`ask\` with the closed options and what each one costs.`
    ],
    done:[
      `the record at ${v.allowlist} states the whole identity - tokens with their roles and policy, typography, mascot, logo, one icon set, imagery and artwork rules, voice, motion, forbidden - and names the real source file every value came from`,
      `every assertion (${v.acceptance}) is covered and every token value is traceable to a declaration in one of those files; an untraceable value was asked about, never written`,
      `the listed checks exit 0: ${v.declared}`,
      `\`rev\` is higher than it was and the record says what changed`,
      `no product code changed, and no asset was claimed that does not exist with its recorded hash`
    ]
  }),
  generic:v=>({
    steps:[
      `Read ${v.references} and the acceptance (${v.acceptance}); restate in three lines what must be true when you are done.`,
      `Write or extend the spec(s) that prove it and run them: they MUST fail now.`,
      `Make the smallest change inside the allowlist (${v.allowlist}) until they pass.`,
      `Run every listed check verbatim: ${v.checks}.`,
      `Self-audit: every acceptance item has a passing check, \`git status\` shows no file outside the allowlist, no secret, no TODO.`,
      `Report \`done\` exactly once with the spec paths and the check commands; \`blocked\` with \`shared-change\` and the exact paths for anything outside the allowlist.`
    ],
    done:[`every acceptance item is proven by a check that was red before and is green after`,`every check exits 0`,`only allowlisted paths changed`]
  })
};

/** The two markdown sections for the contract: the numbered working order and the definition of done of this kind. */
export function stepsFor(op,{node=null}={}){
  const sequence=sequenceFor(op,{node});
  const {steps,done}=SEQUENCE_STEPS[sequence](values(op,node));
  return [
    `${STEPS_HEADING}`,
    `Sequence \`${sequence}\`. Do these in order; skipping or reordering a step is a finding at review.`,
    ...steps.map((step,index)=>`${index+1}. ${step}`),
    ``,
    DONE_HEADING,
    ...done.map(item=>`- ${item}`)
  ].join('\n');
}
