// git-hooks.mjs - the git hooks of the runtime repository itself (the .claude checkout), rendered from the app hook templates.
//   pre-push    the same release gate the apps carry: the body of packages/hfs/templates/app/hooks/husky/pre-push, read once and
//               given a generator header (the single source: the template's {{header}} line is the only thing replaced)
//   pre-commit  L0 only: `git diff --cached --check` and a syntax check (`node --check`) of the staged .mjs/.cjs files; no test run
// installGitHooks writes them into <git common dir>/hooks/ (every worktree of the repository shares that directory): executable,
// LF, the generated header on top. A hook of that name without the header is somebody else's and is never overwritten: it is
// reported. It does not touch git config. `starci runtime link` calls it.
import fs from 'node:fs';
import path from 'node:path';
import { skillRoot } from '../../engine/runtime-root.mjs';
import { revParseQuery } from '../api/git/rev-parse-query.mjs';
import { folded as lf } from '../lib/event-contract.mjs';
import { RUNTIME_GIT_HOOKS_MARKER, WORK_HOOK_MARKER, workHookCheck } from './hook-install.mjs';

/** The line every generated hook carries; a hook file without it is foreign. */
export const GIT_HOOKS_MARKER = RUNTIME_GIT_HOOKS_MARKER;
export const HOOK_NAMES = Object.freeze(['pre-commit', 'pre-push']);
/** The code the push gate prints when it refuses a push that is not a release (rule R225). */
const PUSH_REFUSAL_CODE = 'RIGHTS_PUSH_NOT_RELEASE';
const PRE_PUSH_TEMPLATE = ['packages', 'hfs', 'templates', 'app', 'hooks', 'husky', 'pre-push'];
const SHEBANG = '#!/bin/sh\n';
const header = (name) => `# Generated by the StarCi runtime (scripts/guards/git-hooks.mjs, ${GIT_HOOKS_MARKER}): the ${name} hook of this repository. Do not edit; link the runtime again to rewrite it.`;

const runtimePreCommit = ({ root, nodePath = process.execPath }) => `{{header}}
${workHookCheck({ check: path.join(root, 'scripts', 'work', 'validate', 'work-hygiene.mjs'), nodePath })}
# Commit gate (L0 only): whitespace errors of the staged diff and a syntax check of the staged .mjs and .cjs files. No test run:
# the op gate does types and the targeted specs.
git diff --cached --check || exit 1
set -f
IFS='
'
for file in $(git diff --cached --name-only --diff-filter=ACMR -- '*.mjs' '*.cjs'); do
  node --check "$file" || exit 1
done
`;

const withHeader = (name, body) => `${SHEBANG}${lf(body).replace('{{header}}', header(name))}`;

/** The hook files of the runtime repository as {'pre-commit': text, 'pre-push': text}; the app pre-push template at `root` is the one source of the push gate. */
export function renderRuntimeHooks({ root = skillRoot, fs: fsApi = fs, nodePath = process.execPath } = {}) {
  const template = fsApi.readFileSync(path.join(root, ...PRE_PUSH_TEMPLATE), 'utf8');
  if (!template.includes('{{header}}')) throw new Error('the app pre-push template has no {{header}} line');
  if (!template.includes(PUSH_REFUSAL_CODE)) throw new Error(`the app pre-push template does not print ${PUSH_REFUSAL_CODE}`);
  return { 'pre-commit': withHeader('pre-commit', runtimePreCommit({ root, nodePath })), 'pre-push': withHeader('pre-push', template) };
}

/** <git common dir>/hooks of the repository at `root`, or null when `root` is not inside a git checkout. */
function commonHooksDir(root) {
  const r = revParseQuery(['--git-common-dir'], { dir: root, timeout: 20_000 });
  if (r.status !== 0 || !r.stdout.trim()) return null;
  return path.join(path.resolve(root, r.stdout.trim()), 'hooks');
}

/**
 * installGitHooks({root, hooksDir, templateRoot, fs}): `root` is the checkout whose hooks directory is written, `templateRoot` the runtime that holds the app
 * hook templates (default: this runtime). -> {ok, hooksDir, hooks: [{name, path, state}]}
 * state: 'installed' (new file), 'updated' (a generated hook rewritten), 'current' (already equal), 'foreign' (a hook of that name
 * without the generated header: left alone). ok is false only when the hooks directory cannot be resolved (reason 'not-a-git-checkout').
 */
export function installGitHooks({ root = skillRoot, hooksDir, templateRoot = skillRoot, fs: fsApi = fs } = {}) {
  const dir = hooksDir ?? commonHooksDir(root);
  if (!dir) return { ok: false, reason: 'not-a-git-checkout', hooksDir: null, hooks: [] };
  const rendered = renderRuntimeHooks({ root: templateRoot, fs: fsApi });
  fsApi.mkdirSync(dir, { recursive: true });
  const hooks = [];
  for (const name of HOOK_NAMES) {
    const file = path.join(dir, name);
    const body = rendered[name];
    const exists = fsApi.existsSync(file);
    const current = exists ? fsApi.readFileSync(file, 'utf8') : null;
    const owned = current?.includes(GIT_HOOKS_MARKER) || (name === 'pre-commit' && current?.includes(WORK_HOOK_MARKER));
    if (current !== null && !owned) { hooks.push({ name, path: file, state: 'foreign' }); continue; }
    if (current === body) { hooks.push({ name, path: file, state: 'current' }); continue; }
    const tmp = `${file}.${process.pid}.tmp`;
    fsApi.writeFileSync(tmp, body, { mode: 0o755 });
    fsApi.renameSync(tmp, file);
    try { fsApi.chmodSync(file, 0o755); } catch { /* windows has no mode bits */ }
    hooks.push({ name, path: file, state: exists ? 'updated' : 'installed' });
  }
  return { ok: true, hooksDir: dir, hooks };
}
