// git-hooks.mjs - the git hooks of the runtime repository itself (the .claude checkout).
//   pre-push    the release push gate: the remote main and the v* tags of the runtime move only with a release. The hook runs
//               scripts/guards/release-push-gate.mjs, which judges the pushed refs against the release definition
//               (scripts/guards/release-definition.mjs) that `starci release cut` also passes through; any other ref is not its business
//   pre-commit  L0 only: `git diff --cached --check`, a syntax check (`node --check`) of the staged .mjs/.cjs files and the `sonar-rules`
//               self-check of the staged .mjs files (scripts/guards/sonar-hook.mjs); no test run
// installGitHooks writes them into <git common dir>/hooks/ (every worktree of the repository shares that directory): executable,
// LF, the generated header on top. A hook of that name without the header is somebody else's and is never overwritten: it is
// reported. It does not touch git config. `starci runtime link` calls it.
import fs from 'node:fs';
import path from 'node:path';
import { skillRoot } from '../../engine/runtime-root.mjs';
import { revParseQuery } from '../api/git/rev-parse-query.mjs';
import { folded as lf } from '../lib/event-contract.mjs';
import { sonarHookCheck } from './sonar-hook.mjs';
import { RUNTIME_GIT_HOOKS_MARKER, WORK_HOOK_MARKER, shellQuote, workHookCheck } from './hook-install.mjs';

/** The line every generated hook carries; a hook file without it is foreign. */
export const GIT_HOOKS_MARKER = RUNTIME_GIT_HOOKS_MARKER;
export const HOOK_NAMES = Object.freeze(['pre-commit', 'pre-push']);
const SHEBANG = '#!/bin/sh\n';
const PUSH_GATE_SCRIPT = ['scripts', 'guards', 'release-push-gate.mjs'];
const header = (name) => `# Generated by the StarCi runtime (scripts/guards/git-hooks.mjs, ${GIT_HOOKS_MARKER}): the ${name} hook of this repository. Do not edit; link the runtime again to rewrite it.`;

const runtimePrePush = ({ root, nodePath = process.execPath }) => `{{header}}
# Push gate: the remote main and the v* tags of this repository move only with a release. The body is scripts/guards/release-push-gate.mjs,
# which judges the pushed refs against the release definition (scripts/guards/release-definition.mjs) the release cut also runs. Git's
# stdin lines pass through; there is no switch that opens it.
exec ${shellQuote(nodePath)} ${shellQuote(path.join(root, ...PUSH_GATE_SCRIPT))}
`;

const runtimePreCommit = ({ root, nodePath = process.execPath }) => `{{header}}
${workHookCheck({ root, nodePath })}
# Commit gate (L0 only): whitespace errors of the staged diff, a syntax check of the staged .mjs and .cjs files and the Sonar rules
# of the staged .mjs files. No test run:
# the op gate does types and the targeted specs.
git diff --cached --check || exit 1
set -f
IFS='
'
for file in $(git diff --cached --name-only --diff-filter=ACMR -- '*.mjs' '*.cjs'); do
  node --check "$file" || exit 1
done
${sonarHookCheck({ root, nodePath })}`;

const withHeader = (name, body) => `${SHEBANG}${lf(body).replace('{{header}}', header(name))}`;

/** The hook files of the runtime repository as {'pre-commit': text, 'pre-push': text}; `root` is the runtime that holds the hook bodies. */
export function renderRuntimeHooks({ root = skillRoot, nodePath = process.execPath } = {}) {
  return { 'pre-commit': withHeader('pre-commit', runtimePreCommit({ root, nodePath })), 'pre-push': withHeader('pre-push', runtimePrePush({ root, nodePath })) };
}

/** <git common dir>/hooks of the repository at `root`, or null when `root` is not inside a git checkout. */
function commonHooksDir(root) {
  const r = revParseQuery(['--git-common-dir'], { dir: root, timeout: 20_000 });
  if (r.status !== 0 || !r.stdout.trim()) return null;
  return path.join(path.resolve(root, r.stdout.trim()), 'hooks');
}

/**
 * installGitHooks({root, hooksDir, templateRoot, fs}): `root` is the checkout whose hooks directory is written, `templateRoot` the runtime whose scripts the hooks
 * run (default: this runtime). -> {ok, hooksDir, hooks: [{name, path, state}]}
 * state: 'installed' (new file), 'updated' (a generated hook rewritten), 'current' (already equal), 'foreign' (a hook of that name
 * without the generated header: left alone). ok is false only when the hooks directory cannot be resolved (reason 'not-a-git-checkout').
 */
export function installGitHooks({ root = skillRoot, hooksDir, templateRoot = skillRoot, fs: fsApi = fs } = {}) {
  const dir = hooksDir ?? commonHooksDir(root);
  if (!dir) return { ok: false, reason: 'not-a-git-checkout', hooksDir: null, hooks: [] };
  const rendered = renderRuntimeHooks({ root: templateRoot });
  fsApi.mkdirSync(dir, { recursive: true });
  const hooks = [];
  for (const name of HOOK_NAMES) {
    const file = path.join(dir, name);
    const body = rendered[name];
    const exists = fsApi.existsSync(file);
    const current = exists ? fsApi.readFileSync(file, 'utf8') : null;
    const owned = current?.includes(GIT_HOOKS_MARKER) || (name === 'pre-commit' && current?.includes(WORK_HOOK_MARKER));
    if (current !== null && !owned) { hooks.push({ name, path: file, state: 'foreign' }); continue; }
    if (current === body) { hooks.push({ name, path: file, state: 'current' }); continue; }
    const tmp = `${file}.${process.pid}.tmp`;
    fsApi.writeFileSync(tmp, body, { mode: 0o700 });
    fsApi.renameSync(tmp, file);
    try { fsApi.chmodSync(file, 0o700); } catch { /* windows has no mode bits */ }
    hooks.push({ name, path: file, state: exists ? 'updated' : 'installed' });
  }
  return { ok: true, hooksDir: dir, hooks };
}
