// Authoring source. English text generates runtime authority; Vietnamese generates human mirrors.
// Paths are templates defined in common.md and each contract's placeholders, never execution targets.
const pair = (en, vi) => ({ en, vi });
const read = (id, path, en, vi) => ({ id, path, purpose: pair(en, vi) });
const write = (id, path, fields, en, vi) => ({ id, path, fields, content: pair(en, vi) });
const step = (reads, writes, en, vi) => ({ reads: reads.split(' ').filter(Boolean), writes: writes.split(' ').filter(Boolean), action: pair(en, vi) });
const proof = (id, en, vi) => ({ id, requirement: pair(en, vi) });
const stop = (code, en, vi) => ({ code, condition: pair(en, vi) });
const businessRead = () => read('business', '.work/<business>/business/**/node.md', 'Read accepted requirements, decisions, constraints and acceptance IDs declared as relevant inputs in the selected .work graph. Intent governs expected behavior; source is not a replacement. Do not invent a mandatory BA predecessor for a scope that does not require one; a needed missing input is a reported graph/scope gap, not a new dependency silently added here.', 'Đọc requirement/quyết định/ràng buộc/AC được khai là input liên quan trong graph .work đã chọn. Ý định quyết định expected, source không thay nghiệp vụ. Không bịa predecessor BA bắt buộc cho scope không cần; input cần mà thiếu là gap graph/scope phải báo, không tự thêm dependency.');
const repoRead = () => read('repo', 'repository:<repo-id>/<bound-paths>', 'When source exists/is selected, resolve repository resource, actual checkout/root/HEAD and dirty state; read applicable instructions, manifests, owning code, callers and relevant tests. Greenfield/spec-only work records source not-yet-created and grounds intent in the user request; no invented repository or fact citation. Source implementation still needs an actual selected writable repository.', 'Khi có/chọn source, resolve resource repo, checkout/root/HEAD/dirty thật; đọc hướng dẫn, manifest, code owner, caller, test. Greenfield/spec-only ghi source chưa tạo, lấy ý định từ yêu cầu; không bịa repo/trích dẫn fact. Implement source vẫn cần repo thật được chọn và được ghi.');
const architectureRead = () => read('architecture', '.work/<business>/architecture/**/node.md', 'Read data ownership, operations/API/events, boundaries, code-scope and rationale declared by the selected .work graph; distinguish proposed paths from observed files. No universal architecture-first op chain is implied; report genuinely missing required scope before proceeding.', 'Đọc ownership dữ liệu, operation/API/event, boundary/code-scope/lý do được graph .work đã chọn khai; tách file dự kiến với file thật. Không mặc định chain mọi op phải architecture trước; thiếu scope thật sự bắt buộc thì báo trước khi tiếp tục.');
const targetRead = () => read('target', 'N/node.md', 'Read current target, ancestor scope, refs, dependencies, assertions and validator freshness. For an explicitly new target, absence is expected: inspect the nearest existing ancestor/workspace, then create only that selected scope. Preserve unaffected accepted content.', 'Đọc node đích, scope cha, refs, dependencies, assertions và freshness. Với target mới được yêu cầu, chưa tồn tại là đúng: đọc ancestor/workspace gần nhất rồi chỉ tạo scope đã chọn. Giữ phần chấp nhận không bị ảnh hưởng.');
const environmentRead = () => read('environment', '.work/_resources/environments/<environment>/resource.yaml', 'Read exact target/origins, owner, configuration revision, declared probes and allowed effects; validate live observations without inferring identity from hostname alone.', 'Đọc target/origin chính xác, owner, revision cấu hình, probe và tác động được phép; đối chiếu runtime thật, không suy danh tính từ hostname.');
const identityRead = () => read('identity', '.work/_resources/identities/<identity>/resource.yaml', 'For authenticated/identity-changing scope, read actor alias, provider subject, roles/membership refs, environment and sealed custody reference; never print/copy credentials. Explicit anonymous scope records anonymous instead, without inventing an account resource.', 'Với scope đăng nhập/đổi identity, đọc alias, provider subject, role/membership refs, environment, sealed custody ref; không in/chép credential. Scope anonymous rõ ghi anonymous, không bịa resource account.');
const fixtureRead = () => read('fixture', '.work/_resources/fixtures/<fixture>/resource.yaml', 'When fixture inputs are needed, read their revision, owned namespace/IDs, expected precondition, creation method, cleanup owner and exact allowed deletion set; never preseed tested outcomes. Explicit no-fixture scope records why no mutable prerequisite/cleanup applies, without a fabricated fixture.', 'Khi cần fixture, đọc revision/namespace-ID sở hữu/precondition/cách tạo/cleanup owner/tập xóa cho phép; không seed outcome test. Scope no-fixture rõ ghi lý do không có prerequisite mutable/cleanup, không bịa fixture.');
const nodeWrite = (path, fields, en, vi) => write('node', path, fields, en, vi);
const evidenceWrite = (files, en, vi) => write('evidence', 'E/manifest.yaml + ' + files, ['id','nodeId','inputDigest','outcome','assertions','assets','provenance','codeRefs','extensions'], en, vi);
const sourceWrite = () => write('source', 'repository:<repo-id>/<write-ceiling>', ['source files','tests','migration/assets/config only when selected'], 'Only exact owned paths in the approved code-scope, with smallest required caller/integration changes; record actual diff and commit mapping, not proposed changes as delivered.', 'Chỉ file thuộc code-scope được giao cùng caller/integration cần thiết nhỏ nhất; ghi diff và commit thật, không coi dự kiến là đã giao.');
const resourceWrite = (category, fields, en, vi) => write('resource', `.work/_resources/${category}/<resource>/resource.yaml`, ['id','kind','owner','revision',...fields.map(f=>'details.'+f)], en, vi);
const genericProof = () => proof('binding', 'Run workspace validation; every cited ID/path exists or is explicitly proposed, required assertions are covered, input bindings are current, and an honest not-run/fail cannot earn done.', 'Chạy validate workspace; ID/path trích dẫn tồn tại hoặc ghi rõ dự kiến, đủ assertions bắt buộc, binding còn mới; not-run/fail không được done.');
const commitProof = () => proof('commit', 'Inspect exact staged diff and actual tests; bind full real source commit(s), per repository, and separately retain integration/tested mappings. Report uncommitted or no-change honestly.', 'Đọc staged diff chính xác và test thật; gắn SHA nguồn đầy đủ theo repo, lưu mapping integration/tested riêng. Báo thật khi chưa commit hoặc không đổi.');
const ops = [];
function add(id, goal, vi, kind, effect, reads, writes, steps, proofs, blockers, extra={}) {
  const scopeWriters=new Set(['goal.setup','business.decide','architecture.decide','backend.plan','interface.plan','uat.plan','data.plan','scope.retire']);
  const graphMode=scopeWriters.has(id)?'selected-scope-only':'read-only';
  if(graphMode==='read-only') {
    const target=reads.find(r=>r.id==='target');
    if(target) target.purpose=pair('Read the existing selected N/node.md, ancestor scope, declared refs/dependencies/assertions and validator freshness. This consumer op requires its target node to exist. An absent target is a scope/graph gap: report it and propose a separately selected scope op; do not create a target or invent its acceptance/graph here.','Đọc N/node.md đã chọn đang tồn tại, scope cha, ref/dependency/assertion đã khai và freshness. Consumer op cần node đích có sẵn. Thiếu target là gap scope/graph: báo và đề xuất scope op được chọn riêng; không tạo target hay bịa acceptance/graph tại đây.');
  }
  if(id==='goal.setup') {
    writes.unshift(write('workspace','.work/workspace.yaml',['schema','id','extensions'],'Initialize only an explicitly new canonical workspace; reuse an existing workspace unchanged. Never invent repository/environment resources merely to satisfy setup.','Chỉ khởi tạo workspace canonical mới được yêu cầu; dùng workspace cũ nguyên trạng. Không bịa resource repo/environment để đủ setup.'));
    steps[0].writes.unshift('workspace');
    writes.find(w=>w.id==='node').fields.push('extensions.work3.nativeGoal: actual returned current-task goal reference only');
  }
  if(id==='interface.draw') {
    writes.push(write('designSource','.work/_resources/design/<resource>/resource.yaml + .work/_resources/design/<resource>/assets/<asset>',['files:[{path}]','details: accepted direction identity / source provenance'],'Write the selected approved art-direction asset as a canonical source input, with files paths relative to its resource.yaml directory. The core hashes actual bytes; do not author a sha256 field in files. Preserve the selected node graph: if its design resource/ref is missing, report the scope gap instead of silently adding a dependency. Generated/captured evidence images are not automatically design authority.','Ghi art-direction asset đã chọn/duyệt thành input nguồn canonical; path trong files tương đối với thư mục resource.yaml. Core hash bytes thật, không viết sha256 trong files. Giữ graph node chọn: thiếu resource/ref design thì báo gap scope, không tự thêm dependency. Ảnh generated/capture evidence không tự là design authority.'));
    steps[1].writes.push('designSource');steps[2].writes.push('designSource');
  }
  // Specs are inputs. Actual delivery/findings are outputs: put them in evidence rather than
  // causing a verifier to invalidate its own inputDigest by editing semantic node prose.
  if(['implementation','operations','release','uat.ui','uat.ux'].includes(kind)) {
    const n=writes.find(w=>w.id==='node'),e=writes.find(w=>w.id==='evidence');
    if(n&&e) {
      const resultContent=n.content;
      e.path+=' + E/result.md';
      e.content=pair(e.content.en+' Operator-specific observed result in E/result.md: '+resultContent.en,
        e.content.vi+' Kết quả quan sát chuyên môn ở E/result.md: '+resultContent.vi);
      n.fields=['state','blocker','completion.inputDigest','completion.evidence',...(['implementation','release'].includes(kind)?['completion.codeRefs']:[])];
      n.content=pair('Read the existing selected scope, expected assertions and .work graph unchanged. Write only state/blocker/completion here; actual observations, findings, commit mappings and remaining cleanup belong to the evidence result, not semantic node prose. Missing refs/dependencies/acceptance require a reported gap or separately selected scope update; never add/remove them to obtain pass.',
        'Đọc nguyên scope/assertion mong đợi/graph .work đã chọn. Ở đây chỉ ghi state/blocker/completion; observation/finding/mapping commit/cleanup còn lại ở evidence, không body ngữ nghĩa. Thiếu ref/dependency/acceptance thì báo gap hoặc cập nhật scope được chọn riêng; không thêm/bỏ để đạt pass.');
    }
  }
  const nodeOutput=writes.find(w=>w.id==='node');
  if(graphMode==='selected-scope-only'&&nodeOutput) {
    if(id==='scope.retire') nodeOutput.content=pair('Write only the explicitly authorized retirement decision/scope before review; preserve stable IDs and obligations. Actual removal/retention observations belong in evidence.','Chỉ ghi quyết định/scope retirement được phép rõ trước review; giữ ID/nghĩa vụ. Quan sát xóa/retention thật nằm ở evidence.');
    for(const field of ['dependsOn','refs','assertions','required']) if(!nodeOutput.fields.includes(field)) nodeOutput.fields.push(field);
    nodeOutput.content=pair(nodeOutput.content.en+' Graph edits apply only to the explicitly selected approved scope: declare real prerequisite node IDs in dependsOn and semantic input node/resource IDs in refs. No catalogue-wide chain or new unrelated scope; finish all graph/spec changes before review proof.',nodeOutput.content.vi+' Chỉ sửa graph thuộc scope được chọn rõ đã duyệt: prerequisite node IDs thật ở dependsOn, input ngữ nghĩa node/resource IDs ở refs. Không chain toàn catalogue hoặc scope khác; chốt graph/spec trước proof review.');
  }
  if(graphMode==='read-only'&&nodeOutput) nodeOutput.fields=nodeOutput.fields.filter(field=>!['dependsOn','refs','required'].includes(field));
  blockers.push(stop('DECLARED_DEPENDENCY_UNMET','A declared prerequisite is not effectively done, or a required declared input/scope is missing. Report node/resource IDs and propose a separately selected graph update when needed; never run predecessors or weaken dependsOn/refs/required to proceed.','Prerequisite đã khai chưa effective done hoặc thiếu input/scope bắt buộc đã khai. Báo ID node/resource và đề xuất cập nhật graph được chọn riêng khi cần; không chạy predecessor hoặc nới dependsOn/refs/required để tiếp tục.'));
  ops.push({ id, goal: pair(goal,vi), nodeKinds:[kind], completionProfile:kind, sideEffects:effect,graphPolicy:{mode:graphMode,location:'.work node dependsOn/refs and resource files',prerequisiteState:'done',dispatch:'never'},
    reads, writes, steps, proofs:[genericProof(),...proofs], blockers,
    placeholders:{ business:'Selected business slug / slug nghiệp vụ đã chọn', 'repo-id':'Resolved repository resource ID / resource ID repo đã resolve', 'bound-paths':'Inspected source read set / tập file nguồn cần đọc', 'write-ceiling':'Explicit owned source paths / tập file nguồn được ghi', environment:'Resolved environment resource slug / slug environment đã resolve', identity:'Selected actor resource slug / slug actor đã chọn', fixture:'Selected fixture resource slug / slug fixture đã chọn', resource:'Selected owned resource slug / slug resource thuộc quyền sửa', asset:'Actual selected source asset filename/format / tên file-định dạng asset nguồn thật đã chọn', piece:'Stable selected piece slug / slug piece đã chọn', flow:'Selected UAT journey slug / slug journey UAT đã chọn', screen:'Selected surface/state slug / slug screen-state đã chọn', ...extra.placeholders },
    ...Object.fromEntries(Object.entries(extra).filter(([key])=>key!=='placeholders')) });
}

add('goal.setup','Establish one business purpose and its initial completion tree without executing product work.','Thiết lập một mục đích nghiệp vụ và cây completion ban đầu, chưa chạy việc product.','business',['native current-task goal creation/reuse only when explicitly requested and supported'],
 [read('intent','current user request + existing .work/workspace.yaml','Read the actual requested outcome, agreed scope and existing workspace identity; do not turn examples or future ideas into obligations.','Đọc mục tiêu người dùng thật sự yêu cầu, scope đã thống nhất và identity workspace; không biến ví dụ/ý tưởng tương lai thành nghĩa vụ.'),targetRead()],
 [nodeWrite('.work/<business>/node.md + .work/<business>/setup/node.md + selected child directories/node.md',['id','kind','required','dependsOn','refs','assertions','body: Purpose / Scope / Done when / Decisions / Unknowns'],'Write the parent purpose with no state. The one setup leaf .work/<business>/setup/node.md is N for this op, kind business, with only scope-review assertions. All planned business/architecture/code/UAT leaves remain todo, or explicit blocked/na with real reasons. Scope decisions distinguish implement, defer and not applicable. Store requirement IDs once.','Ghi mục đích cha không có state. Lá setup duy nhất .work/<business>/setup/node.md là N của op, kind business, chỉ có assertion review scope. Mọi lá nghiệp vụ/kiến trúc/code/UAT dự kiến vẫn todo, hoặc blocked/na có lý do thật. Tách implement/defer/không áp dụng; ID requirement chỉ có một nơi.'),evidenceWrite('E/scope-review.md','Retain source-intent citations and actual scope/coverage review under the setup leaf only. Set setup done only after real review evidence and validation; initial scaffolding has no completion. No code/UAT pass.','Giữ trích dẫn ý định và review scope/coverage thật chỉ dưới lá setup. Chỉ setup done sau evidence review thật/validate; scaffold ban đầu chưa completion. Không code/UAT pass.')],
 [step('intent target','node','Resolve the existing canonical workspace, or initialize only the explicitly new workspace identity; establish one purpose, actors/outcomes stated so far, inclusions and exclusions. Mark unspecified behavior unknown.','Resolve workspace canonical hiện có, hoặc chỉ khởi tạo identity workspace mới được yêu cầu; chốt một mục đích, actor/kết quả đã nói, phần làm/không làm. Hành vi chưa nói là unknown.'),step('intent target','node','Map the purpose into the smallest useful completion tree. A task may cover three UAT flows, but each flow has separate UI and UX assertion leaves; do not pre-expand irrelevant lifecycle branches.','Chia mục đích thành cây completion nhỏ đủ dùng. Một task có thể ba flow UAT nhưng mỗi flow có lá UI/UX riêng; không bung stage không liên quan.'),step('intent target','node','Record applicability and dependencies by stable IDs. A defer decision needs rationale/owner/revisit trigger and stays visible; it is not done or na. Reuse explicit approval, asking only unresolved material scope choices.','Ghi applicability và dependency bằng ID ổn định. Defer có lý do/owner/mốc xem lại và vẫn hiện; không đổi thành done/na. Dùng lại duyệt đã có, chỉ hỏi scope quan trọng chưa rõ.'),step('intent target','node','When the user explicitly requests a native goal for this current chat/task and an actual supported goal tool exists, inspect/create/reuse that goal according to the tool contract; retain only its returned reference in extensions.work3.nativeGoal. Otherwise keep purpose in .work and the current chat. Never invent a platform goal ID or create a separate task/agent goal automatically.','Khi người dùng yêu cầu rõ native goal cho chat/task hiện tại và có goal tool thật hỗ trợ, inspect/tạo/dùng lại theo tool contract; chỉ lưu ref thật trả về trong extensions.work3.nativeGoal. Còn lại giữ purpose ở .work và chat. Không bịa goal ID hoặc tự tạo task/goal agent riêng.'),step('target','evidence','Review tree coverage against the original purpose, validate references and report selected eligible ops as suggestions only. Stop without dispatch or cooking child pieces.','Review cây so với mục đích gốc, validate refs, chỉ gợi ý op đủ điều kiện. Dừng, không dispatch/cook con.')],
 [proof('scope','Every declared outcome is mapped to a required leaf, explicit deferred decision or justified non-applicability; setup completion never rolls implementation forward.','Mọi kết quả được yêu cầu có lá bắt buộc, quyết định defer rõ hoặc không áp dụng có lý do; setup xong không kéo implementation sang done.')],
 [stop('PURPOSE_AMBIGUOUS','Multiple materially different purposes or repository identities remain unresolved.','Còn nhiều mục đích hoặc identity repo khác nhau về bản chất chưa xác định.')]);

add('business.decide','Specify the selected business behavior precisely enough to implement and independently accept it.','Viết chuẩn nghiệp vụ được chọn đủ rõ để implement và nghiệm thu độc lập.','business',[],
 [targetRead(),repoRead(),read('intent','current accepted user intent + supplied domain documents','Classify each statement as intent, observed fact, example, proposal, unknown or contradiction, with source citation/revision. Existing behavior does not authorize a new rule.','Phân loại từng phát biểu: ý định, fact quan sát, ví dụ, đề xuất, unknown, mâu thuẫn; gắn nguồn/revision. Hành vi cũ không cấp quyền tạo rule mới.')],
 [nodeWrite('.work/<business>/business/<piece>/node.md',['body: Objective / Glossary / Actors & permissions / FR / NFR / Business rules / Non-business constraints / State transitions / Acceptance / Decisions / Open questions','refs','assertions','extensions.work3.decisions'],'FR rows: ID, actor, trigger, preconditions, input/schema, normal action/output, failure/denial, postcondition, priority, source and AC refs. NFR rows: metric, numeric target when decided, unit, workload, percentile/window, environment, measurement method and source; undecided targets stay unknown. BR rows: condition, decision, authority, affected transitions and exceptions. Technical/contractual constraints are separate from domain policy.','FR gồm ID, actor, trigger, precondition, input/schema, xử lý/kết quả, lỗi/từ chối, postcondition, ưu tiên, nguồn, AC refs. NFR có metric, target số khi đã quyết, đơn vị, tải, percentile/window, môi trường, cách đo, nguồn; chưa quyết thì unknown. BR có điều kiện, quyết định, thẩm quyền, transition và ngoại lệ. Tách ràng buộc kỹ thuật/hợp đồng khỏi chính sách domain.'),evidenceWrite('E/coverage-review.md','Record requirement-to-acceptance coverage, concrete source observations and unresolved contradictions; a specification review is not implementation evidence.','Ghi coverage requirement–acceptance, quan sát nguồn cụ thể và mâu thuẫn chưa giải quyết; review spec không phải bằng chứng implementation.')],
 [step('target intent repo','node','Inventory the actual domain: goals/non-goals, actor roles, ownership boundaries, vocabulary, current consumers and source-observed rules. Cite facts at repository/path/revision; label new requirements as intent.','Lập domain thật: goal/non-goal, role, ownership, thuật ngữ, consumer và rule thấy trong source. Fact gắn repo/path/revision; yêu cầu mới là ý định.'),step('intent target','node','Enumerate each FR including invalid input, permission denial, retries, concurrency, cancellation and recovery only where applicable. Describe output and persisted side effects separately.','Liệt kê FR gồm input sai, bị từ chối, retry, concurrency, hủy và phục hồi khi áp dụng. Tách output và side effect lưu trữ.'),step('intent repo','node','Specify measurable NFRs and non-business constraints separately: performance, availability, accessibility, security/privacy, observability, retention, compatibility and operational limits. Never invent legal requirements or numeric thresholds to fill a cell.','Viết NFR đo được và non-business constraints riêng: hiệu năng, availability, accessibility, security/privacy, observability, retention, compatibility, giới hạn vận hành. Không bịa luật hay ngưỡng số để lấp ô.'),step('intent repo','node','Build actor-action-resource permission matrix and state-transition table: from, trigger, guards, writer, to, effects, failure/no-op, repeat behavior and invariants. Include precedence when rules conflict.','Lập ma trận actor–action–resource và transition: from, trigger, guard, writer, to, effect, failure/no-op, lặp lại, bất biến. Nêu ưu tiên khi rule xung đột.'),step('intent target','node','Write acceptance IDs as Given/When/Then or equivalent observable assertions with positive, negative and boundary scenarios. Link FR/NFR/BR IDs, intended UAT flow and proof instrument; expected behavior is fixed before implementation.','Viết AC có ID dạng Given/When/Then hoặc assertion quan sát được; gồm positive/negative/boundary. Liên kết FR/NFR/BR, flow UAT dự kiến và công cụ chứng minh; expected chốt trước implementation.'),step('intent target','node','For every discovered requirement/consumer choose implement, preserve, defer or not-applicable. Record rationale, decision authority, owner and revisit condition. Defer does not remove required scope without an actual user decision.','Mỗi requirement/consumer chọn implement/preserve/defer/không áp dụng; ghi lý do, thẩm quyền, owner, điều kiện xem lại. Defer không tự loại scope bắt buộc nếu người dùng chưa quyết.'),step('target repo intent','evidence','Review every requirement for a unique acceptance destination and every enforcement claim for real source evidence. List all material gaps together, preserve accepted unchanged rows, then finish the BA piece only.','Review mỗi requirement có nơi nghiệm thu rõ, mỗi claim đang enforce có source thật. Gom gap quan trọng, giữ dòng không đổi đã chấp nhận, rồi chỉ kết thúc piece BA.')],
 [proof('coverage','Each applicable FR/NFR/BR has acceptance IDs and source intent; no vague fast/secure/user-friendly NFR is accepted as measurable. Implementation/UAT status is untouched.','FR/NFR/BR áp dụng có AC IDs và nguồn ý định; NFR nhanh/an toàn/dễ dùng mơ hồ không được coi đo được. Không đổi trạng thái implementation/UAT.')],
 [stop('BUSINESS_UNKNOWN','A required rule, actor permission, numeric target or acceptance result has no authoritative decision.','Rule bắt buộc, quyền actor, ngưỡng hoặc expected thiếu quyết định thẩm quyền.'),stop('BUSINESS_CONTRADICTION','Accepted sources conflict; preserve both citations and ask the actual owner, never average them.','Nguồn đã chấp nhận mâu thuẫn; giữ hai trích dẫn và hỏi owner thật, không dung hòa tùy ý.')]);

add('architecture.decide','Resolve a bounded design into real repository ownership, contracts and implementable code scope.','Quyết định thiết kế hữu hạn có ownership repo thật, contract và code-scope implement được.','architecture',[],
 [targetRead(),businessRead(),repoRead(),read('constraints','selected resource contracts + actual package/deployment manifests','Read exact versions, deployment topology and data constraints; compatibility claims need source/documentation or experiments, not memory.','Đọc version, topology deploy và ràng buộc dữ liệu thật; claim compatibility cần nguồn/tài liệu/thử nghiệm, không dựa trí nhớ.')],
 [nodeWrite('.work/<business>/architecture/<piece>/node.md',['body: Observed system / Decision / Alternatives / Data ownership / Operations / API & events / Failure modes / Code scope / Verification / Open risks','refs','dependsOn','assertions'],'For each operation specify caller, owner/writer, transport, request/response/errors, authorization, stores, transaction, idempotency/concurrency, event ordering, migrations and acceptance IDs. Code scope rows name repository ID, existing/proposed path, symbol/module, create/modify/delete intent, responsibility, callers, protected paths, tests and prerequisites.','Mỗi operation ghi caller, owner/writer, transport, request/response/error, authorization, store, transaction, idempotency/concurrency, thứ tự event, migration, AC IDs. Code-scope có repo ID, path thật/dự kiến, symbol/module, create/modify/delete, trách nhiệm, caller, protected paths, test, prerequisite.'),evidenceWrite('E/source-map.json + E/design-review.md','Record observed current source map and compatibility checks; selected alternative/risk review is design proof, not a passing runtime.','Ghi source map thật và check compatibility; review thiết kế/rủi ro không phải runtime pass.')],
 [step('repo constraints target','evidence','Inspect current entrypoints, dependency graph, composition/DI, persistence and deployment files before proposing boundaries. Record what is unknown and actual existence/absence of candidate paths.','Inspect entrypoint, dependency graph, composition/DI, persistence và deployment trước khi đề xuất boundary. Ghi unknown và file thật sự có/không.'),step('business constraints repo','node','Map each accepted outcome to one enforcing owner and each store to its authoritative writer; state read-only consumers, tenant isolation and sanctioned shared writes.','Map mỗi outcome sang owner enforce, mỗi store sang writer thẩm quyền; nêu consumer chỉ đọc, tenant isolation và shared write được phép.'),step('business constraints','node','Choose the smallest design meeting hard constraints; compare materially different alternatives when the decision warrants it. Document trade-offs, backward compatibility, rollout/migration, rollback limits and operational failure modes.','Chọn thiết kế nhỏ nhất đạt ràng buộc cứng; so phương án khác cơ chế khi cần. Ghi trade-off, compatibility, rollout/migration, giới hạn rollback và failure vận hành.'),step('business repo constraints','node','Specify API/event contracts and every mutation transaction, retry and concurrency policy. A framework list is not architecture; ambiguous writer or data ownership is a blocker.','Viết contract API/event cùng transaction/retry/concurrency của từng mutation. Danh sách framework không phải kiến trúc; writer/ownership dữ liệu mơ hồ là blocker.'),step('repo business','node','Resolve concrete source paths and symbols with caller wiring, tests and protected boundaries. New files remain proposed until created; no claim that a guessed module already exists.','Resolve path/symbol cụ thể, wiring caller, test, protected boundary. File mới vẫn là dự kiến tới khi tạo; không claim module đoán đã tồn tại.'),step('target business repo constraints','evidence','Review AC coverage, ownership contradictions, adverse paths and compatibility evidence. If independent review is requested, use only authorized available delegation; otherwise label self-review honestly. Stop after the design result.','Review AC coverage, mâu thuẫn ownership, adverse path, compatibility proof. Chỉ review độc lập qua delegation được phép khi yêu cầu; còn lại ghi self-review thật. Dừng sau kết quả thiết kế.')],
 [proof('implementability','Every selected operation has an owner, actual/proposed repo-path scope and test instrument; every required business outcome maps to a contract. No source implementation claim.','Mỗi operation có owner, repo/path thật hoặc dự kiến và cách test; outcome bắt buộc map sang contract. Không claim đã implement.')],
 [stop('OWNERSHIP_UNKNOWN','An operation/store has no determined owner or required write crosses another owner without scope.','Operation/store chưa rõ owner hoặc cần ghi ngoài owner được giao.'),stop('COMPATIBILITY_UNKNOWN','A required version, contract or migration compatibility claim lacks evidence.','Compatibility version/contract/migration bắt buộc thiếu proof.')]);

add('backend.plan','Partition selected backend operations into independently implementable pieces and dependencies.','Chia operation backend thành piece implement độc lập và dependency rõ.','architecture',[],
 [targetRead(),businessRead(),architectureRead(),repoRead()],
 [nodeWrite('.work/<business>/implementation/backend/<piece>/node.md',['body: Goal / Operations / Write ceiling / Protected paths / Contracts / Tests / Done when','dependsOn','refs','assertions','state'],'Create/revise todo implementation leaves. Each operation maps to one primary owner piece; each piece lists repository/path/symbol, stores, source test commands, AC IDs and dependency IDs. Planning does not mark these implementation leaves done.','Tạo/sửa lá implementation todo; mỗi operation có một piece owner chính. Mỗi piece ghi repo/path/symbol, store, lệnh test nguồn, AC IDs, dependency. Plan không làm các lá implementation done.'),evidenceWrite('E/partition-review.md','Record coverage, disjoint ownership and dependency review for the selected planning node.','Ghi review coverage, ownership không chồng và dependencies cho node planning đã chọn.')],
 [step('target architecture business repo','node','Enumerate selected operations and their actual writer/store boundaries. Group cohesive changes by business outcome and safe commit boundary, not a fixed file-count limit.','Liệt kê operation và boundary writer/store thật. Gom thay đổi gắn kết theo outcome và commit an toàn, không ép số file.'),step('architecture repo','node','Assign complete source ceilings, protected paths, migrations and caller wiring; include tests for transport, validation, authorization, transaction and read-back where applicable.','Giao ceiling source đầy đủ, protected paths, migration, wiring caller; kèm test transport/validation/quyền/transaction/read-back khi áp dụng.'),step('architecture business target','node','Declare dependencies explicitly, identify shared owner work and justify any parallel-ready pieces. Never spawn workers or implement as a side effect of a plan.','Khai dependency rõ, xác định shared-owner work và piece đủ song song. Plan không tự spawn hay implement.'),step('architecture business repo target','evidence','Verify every selected operation is assigned once, no unresolved ownership overlap and each piece can be reviewed and tested. Finish the planning node only.','Kiểm operation được giao một lần, không overlap chưa xử lý, mỗi piece review/test được. Chỉ kết thúc node planning.')],
 [proof('partition','Complete selected operation coverage and resolvable dependency graph; generated implementation leaves remain unfinished.','Đủ operation được chọn và graph dependencies resolve được; lá implementation vẫn chưa xong.')],
 [stop('PARTITION_CONFLICT','Writer/store ownership cannot be partitioned without reopening architecture.','Không chia writer/store được nếu chưa mở lại quyết định kiến trúc.')]);

add('backend.generate','Implement one selected backend outcome and prove its declared contract on actual code.','Implement một outcome backend đã chọn và chứng minh contract trên code thật.','implementation',['owned source edits','scoped local commits when authorized','tests in declared sandbox'],
 [targetRead(),businessRead(),architectureRead(),repoRead()],
 [nodeWrite('N/node.md',['body: Implementation mapping / Commit mapping / Remaining gaps','completion.inputDigest','completion.evidence','completion.codeRefs'],'Map each AC/operation to delivered repo/path/symbol and actual commit. Preserve business and architecture authority; unknown rules are blockers, not implementation defaults.','Map AC/operation sang repo/path/symbol giao thật và commit thật. Giữ thẩm quyền BA/kiến trúc; rule chưa rõ là blocker, không tự đặt default.'),sourceWrite(),evidenceWrite('E/tests.json + E/test-output.txt + E/lineage.json','Store actual command, cwd/repo, source commit/tree, environment, exit code, counts and expected/actual per required proof, with sanitized original output.','Lưu command thật, cwd/repo, commit/tree nguồn, environment, exit code, số test, expected/actual cho proof bắt buộc cùng output đã che bí mật.')],
 [step('target business architecture repo','','Bind the exact operation/AC set and inspect existing code plus sibling conventions, including DI/module registration and every relevant caller. Reuse already conforming behavior.','Gắn operation/AC chính xác; inspect code, convention cùng họ, DI/module registration và caller. Giữ hành vi đang đúng.'),step('business architecture repo','source','Implement transport, validation, permission checks, use-case logic and persistence inside the declared ownership. Enforce denials before unauthorized side effects; do not invent fallback behavior.','Implement transport, validation, quyền, use-case, persistence đúng ownership. Chặn trước side effect trái quyền; không bịa fallback.'),step('business architecture repo','source','Implement declared transaction, retry/idempotency, concurrency, error identity and read-time revalidation. Migrations are source only; applying them remotely is not included.','Implement transaction/retry/idempotency/concurrency/error/read-time revalidation đã khai. Migration chỉ là source; không tự apply remote.'),step('repo target','source evidence','Add/repair scoped tests; execute positive, denial, invalid-input and applicable race/reload regressions plus repository-required checks. Preserve raw failure and no-test/not-run status; repair only within this approved implementation goal.','Thêm/sửa test đúng scope; chạy positive, denial, invalid-input và race/reload áp dụng cùng check bắt buộc repo. Giữ fail/no-test/not-run; chỉ sửa trong goal implementation này.'),step('repo target','node evidence','Review diff, verify no unrelated changes, commit the piece when authorized and read back the real SHA/diff. Bind proof to actual tested bytes; fresh code needs fresh required evidence. Stop after delivery.','Review diff, kiểm không lẫn thay đổi, commit khi được phép và đọc lại SHA/diff thật. Gắn proof với bytes đã test; code mới cần proof mới. Dừng sau giao.')],
 [commitProof(),proof('behavior','Tests prove each declared operation facet including negative authorization and persistent state when promised; compile-only output cannot certify behavior.','Test chứng minh facet của operation, gồm từ chối quyền và trạng thái lưu khi đã hứa; chỉ compile không chứng minh hành vi.')],
 [stop('BUSINESS_UNKNOWN','Implementation reaches a rule not decided by the accepted business node.','Code chạm rule BA chưa quyết.'),stop('SCOPE_WIDENING','Required operation, owner or protected path lies outside selected code-scope.','Operation/owner/protected path cần thiết nằm ngoài code-scope.'),stop('PROOF_UNAVAILABLE','A required check cannot execute or does not prove the declared behavior.','Check bắt buộc không chạy được hoặc không chứng minh đúng hành vi.')]);

add('interface.plan','Define the selected frontend surfaces, shared shell and interaction/state contracts before source work.','Định nghĩa surface FE, shell chung và interaction/state contract trước khi code.','architecture',[],
 [targetRead(),businessRead(),repoRead(),read('design','.work/_resources/design/<resource>/resource.yaml + selected supplied references','Read actual design-system package/tokens/components, brand constraints and supplied reference assets. Reference appearance cannot invent business copy or data.','Đọc design-system package/token/component thật, brand constraint và reference được cung cấp. Hình thức reference không cho phép bịa copy/dữ liệu nghiệp vụ.')],
 [nodeWrite('.work/<business>/architecture/interface/<piece>/node.md + selected implementation/frontend/<piece>/node.md',['body: Surface map / Shared shell / Interaction states / Data contracts / Accessibility / Source scope / Acceptance','refs','dependsOn','assertions'],'Surface rows: stable ID, route/host, actor/task, shell owner, entry/exit, reads/writes, loading/empty/error/denied/success, viewport/keyboard needs, source path and AC refs. Keep implementation children todo.','Mỗi surface: ID ổn định, route/host, actor/task, owner shell, entry/exit, read/write, loading/empty/error/denied/success, viewport/keyboard, source path, AC refs. Con implementation vẫn todo.'),evidenceWrite('E/surface-review.md','Record discovered routes/screens and accepted/proposed distinctions, omitted scope with reasons, and mapping review.','Ghi route/screen tìm thấy, tách accepted/proposed, scope bỏ kèm lý do và review mapping.')],
 [step('business repo target','node','Inspect actual routes, layouts, components, modal hosts and client API bindings; record existing versus proposed surfaces.','Inspect route/layout/component/modal host/client API thật; phân biệt surface hiện có và dự kiến.'),step('business design','node','Assign shared navigation/shell once, with no-shell explicitly valid where appropriate; map actor goals, actions and feedback. Preserve accepted design choices.','Giao navigation/shell chung một nơi; không có shell là hợp lệ nếu đúng ngữ cảnh. Map goal/action/feedback actor; giữ lựa chọn design đã chấp nhận.'),step('business repo design','node','Specify each surface state and transition, backend contract/dependency, focus/error/recovery behavior and responsive/accessibility expectations. Do not invent endpoints or selectors.','Viết state/transition từng surface, contract BE/dependency, focus/error/recovery, responsive/accessibility. Không bịa endpoint/selector.'),step('target business repo design','evidence','Check that selected outcomes and observed in-scope routes are mapped, ownership does not overlap and test/visual coverage has a home. End with the plan, not generation.','Kiểm outcome/route trong scope được map, ownership không chồng, test/visual coverage có nơi ghi. Kết thúc plan, không generate.')],
 [proof('surfaces','Each selected surface has an actor/task, actual or proposed route, state coverage and implementation/UAT destination.','Mỗi surface có actor/task, route thật/dự kiến, state coverage và nơi implementation/UAT.')],
 [stop('SURFACE_UNKNOWN','Required entry, action contract or shell owner cannot be grounded.','Entry/action contract/owner shell bắt buộc không có nguồn.')]);

add('interface.draw','Produce and inspect the requested visual direction for one business-grounded surface.','Tạo và xem visual direction được yêu cầu cho một surface có nguồn nghiệp vụ.','architecture',['requested local/generated design assets'],
 [targetRead(),businessRead(),read('design','.work/_resources/design/<resource>/resource.yaml + selected architecture/interface node','Read exact brand/source assets, surface anatomy, current design system, imagery rights/provenance and accepted references; consult available image/design skill when used.','Đọc brand/source asset thật, anatomy surface, design system, quyền/provenance hình ảnh và reference; khi dùng thì đọc image/design skill có sẵn.')],
 [nodeWrite('N/node.md',['body: Brief / Regions / States / Assets / Direction decision / Implementation limits','refs','assertions'],'Specify actor/task, content authority, hierarchy, region anatomy, native controls, asset purpose/medium, responsive constraints and acceptance mapping. Record actual selected direction or unresolved material choice.','Ghi actor/task, nguồn content, hierarchy, anatomy từng vùng, native control, purpose/medium asset, responsive, acceptance mapping. Ghi direction thật được chọn hoặc lựa chọn quan trọng chưa quyết.'),evidenceWrite('E/direction.png or actual requested format + E/prompt.txt + E/visual-review.md','Retain actual generated/drawn image and tool provenance, full prompt when relevant, inspected fidelity findings and separate asset identities. A generated drawing proves no product behavior.','Giữ ảnh generate/vẽ thật, tool provenance, prompt khi áp dụng, nhận xét fidelity đã xem, ID asset riêng. Bản vẽ không chứng minh hành vi product.')],
 [step('target business design','node','Freeze the selected brief and content/region mapping, labelling placeholder/example copy. Choose a code-native/vector or raster medium matching the request; do not force ImageGen where not appropriate.','Chốt brief và mapping content/region, đánh dấu copy placeholder/ví dụ. Chọn code-native/vector/raster đúng yêu cầu; không ép ImageGen sai ngữ cảnh.'),step('business design','evidence','Use the available appropriate tool/skill to create the requested direction; retain the actual output and provenance. Missing tool means blocked output, never a claimed generated image.','Dùng tool/skill thích hợp có thật để tạo direction; giữ output và provenance thật. Thiếu tool thì blocker, không claim đã sinh ảnh.'),step('target design business','node evidence','Open and inspect actual output for business contradictions, hierarchy, component ownership, legibility, responsive feasibility and each independent asset. Distinguish subjective judgement from measured geometry.','Mở xem output thật về mâu thuẫn nghiệp vụ, hierarchy, owner component, dễ đọc, khả thi responsive và từng asset. Tách nhận định chủ quan với geometry đo.'),step('target design','node evidence','Present the actual direction. Reuse accepted choice; ask only if materially different alternatives were requested and selection remains open. Stop without frontend code.','Trình bày direction thật. Dùng lựa chọn đã duyệt; chỉ hỏi khi có phương án khác đáng kể được yêu cầu mà chưa chọn. Dừng, không code FE.')],
 [proof('visual','Actual visual bytes opened and reviewed against the brief; dimensions/tool provenance recorded; no UI/UAT pass assigned from the drawing.','Bytes ảnh thật được mở/review so brief; ghi kích thước/tool provenance; không gán UI/UAT pass từ bản vẽ.')],
 [stop('DESIGN_INPUT_UNKNOWN','Required business content, identity asset rights or material direction choice is missing.','Thiếu content nghiệp vụ, quyền asset nhận diện hoặc lựa chọn direction quan trọng.'),stop('VISUAL_TOOL_UNAVAILABLE','Requested visual output cannot be produced with available permitted tools.','Không tạo được visual yêu cầu bằng tool sẵn có được phép.')]);

add('interface.generate','Implement one selected frontend outcome and capture its actual rendered result.','Implement một outcome FE đã chọn và chụp kết quả render thật.','implementation',['owned source edits','scoped local commits when authorized','authorized local preview/test actions'],
 [targetRead(),businessRead(),architectureRead(),repoRead(),read('design','.work/_resources/design/<resource>/resource.yaml + accepted direction evidence','Read the actual installed component API/tokens and accepted surface/direction/state map; only require a separate visual direction if this task selected one.','Đọc API/token component cài thật và surface/direction/state map đã chấp nhận; chỉ bắt direction riêng nếu task có chọn.'),environmentRead()],
 [nodeWrite('N/node.md',['body: Source mapping / State coverage / Commit mapping / Captured result / Remaining gaps','completion.inputDigest','completion.evidence','completion.codeRefs'],'Map delivered components/routes/client calls to ACs and state coverage; record actual source revision separately from served render revision.','Map component/route/client call đã giao sang AC/state coverage; tách source revision với revision render đang serve.'),sourceWrite(),evidenceWrite('E/tests.json + E/render.png + E/render-review.md + E/runtime.json + E/lineage.json','Retain real test output and screenshot from the implemented surface, actually opened/inspected. Include viewport/theme, observed route/state, driver, served build and limitations; no fixture screenshot labelled product proof.','Giữ test output và ảnh từ surface đã implement thật, có mở xem. Ghi viewport/theme, route/state, driver, build đang serve, giới hạn; không gọi ảnh fixture là proof product.')],
 [step('repo target business architecture design','','Inspect target and callers, actual installed component API, API schema and all applicable states. Reuse the approved shell; distinguish bounded refinement from a new business/state design.','Inspect target/caller, API component cài thật, API schema và state áp dụng. Dùng shell đã duyệt; tách refine nhỏ với đổi business/state design.'),step('repo business architecture design','source','Implement native controls, data reads/actions, loading/empty/error/denied/success/recovery, keyboard/focus and responsive behavior inside owned source. No hardcoded fake success or guessed endpoint.','Implement native control, read/action dữ liệu, loading/empty/error/denied/success/recovery, keyboard/focus/responsive trong source sở hữu. Không fake success hay đoán endpoint.'),step('repo target design','source evidence','Run relevant component/unit/type/build checks and interaction tests. Fix only within the selected implementation goal; preserve actual failures and keep required visual work unfinished if unavailable.','Chạy component/unit/type/build và interaction test liên quan. Chỉ sửa trong goal này; giữ fail thật, visual bắt buộc chưa có thì chưa xong.'),step('environment repo target design','evidence','Bind an available authorized runtime/preview and real served build using common browser protocol. Navigate the implemented surface and capture requested viewport/state; open the image, inspect layout/overflow/content and record findings.','Gắn runtime/preview được phép và build serve thật theo browser protocol. Mở surface implement, chụp viewport/state đã chọn; xem ảnh, kiểm layout/overflow/content, ghi findings.'),step('repo target','node evidence','Review owned diff, commit actual code when authorized, and bind tests/render to their real revisions. Capture again if relevant committed output changed. Full independent UAT remains its own selected proof, not implied by the screenshot. Stop.','Review diff thuộc scope, commit khi được phép, gắn test/render với revision thật. Chụp lại nếu output commit thay đổi liên quan. UAT độc lập vẫn là proof riêng, ảnh không thay thế. Dừng.')],
 [commitProof(),proof('render','Actual implemented surface screenshot is retained and visually inspected; code-only delivery is explicitly partial when this required capture cannot be made.','Giữ ảnh surface implement thật và đã xem; nếu ảnh bắt buộc chưa chụp được thì ghi rõ giao code một phần.')],
 [stop('UI_CONTRACT_UNKNOWN','Required business state, action API or component ownership is unresolved.','State nghiệp vụ/API action/owner component bắt buộc chưa rõ.'),stop('RUNTIME_UNVERIFIED','No permitted runtime can prove the implemented surface/build; do not fabricate a screenshot.','Runtime được phép chưa chứng minh surface/build đang implement; không bịa ảnh.')]);

add('interface.fix','Repair one scoped observed frontend defect and recheck the affected behavior/render.','Sửa một lỗi FE quan sát được đúng scope và kiểm lại hành vi/render bị ảnh hưởng.','implementation',['owned source edits','scoped local commits when authorized','targeted tests and authorized browser actions'],
 [targetRead(),businessRead(),repoRead(),read('finding','selected current evidence manifest + its actual assets','Read the exact failing assertion, source/render revision, measured observation and accepted design contract; a suggestion without reproduced evidence remains a hypothesis.','Đọc assertion fail, revision source/render, quan sát đo được, design contract đã chấp nhận; gợi ý chưa reproduce vẫn là giả thuyết.'),environmentRead()],
 [nodeWrite('N/node.md',['body: Defect / Cause / Repair scope / Regression / Commit mapping','completion.inputDigest','completion.evidence','completion.codeRefs'],'Link the original defect evidence and current repaired proof; never erase the old failure or silently change expected behavior.','Link evidence lỗi gốc và proof sửa hiện tại; không xóa fail cũ hoặc đổi expected âm thầm.'),sourceWrite(),evidenceWrite('E/regression.json + E/before-after-review.md + E/after.png when visual + E/lineage.json','Record actual reproduction, cause, changed files and affected regressions; visual fixes need current inspected capture, behavior fixes need observed action/output.','Ghi reproduce/cause/file đổi/regression thật; fix visual cần ảnh hiện tại đã xem, fix behavior cần action/output quan sát được.')],
 [step('finding repo business target','evidence','Reproduce or corroborate the exact defect at current source and distinguish stale evidence, library ownership and product-source cause.','Reproduce hoặc đối chứng lỗi tại source hiện tại; tách evidence cũ, owner thư viện, nguyên nhân source product.'),step('finding repo business','source','Apply the smallest repair within agreed ownership and preserved business/design contract. If the defect needs a new requirement, shared-owner API or redesign outside scope, stop before expanding.','Sửa nhỏ nhất đúng ownership và contract business/design hiện có. Cần requirement/API shared owner/redesign ngoài scope thì dừng trước khi mở rộng.'),step('repo finding environment','evidence','Rerun targeted and collateral checks; capture and open the actual changed UI when appearance is affected, and test the interaction/persistence claim separately.','Chạy lại check target/liên quan; nếu đổi appearance thì chụp/mở UI thật, kiểm interaction/persistence riêng.'),step('repo target','node evidence','Review and commit the scoped piece when authorized, record actual code/proof revisions and unresolved limitations. Stop; do not launch a larger generation chain.','Review/commit piece đúng scope khi được phép, ghi revision code/proof thật và hạn chế. Dừng, không mở chain generate lớn hơn.')],
 [commitProof(),proof('regression','The same original expected assertion now has new observed evidence; unchanged collateral checks remain passing or explicitly unresolved.','Expected assertion gốc có evidence quan sát mới; collateral check vẫn pass hoặc ghi rõ chưa giải quyết.')],
 [stop('REPAIR_SCOPE_UNKNOWN','Root cause or required ownership change is not established.','Chưa rõ nguyên nhân hoặc thay đổi ownership cần thiết.'),stop('EXPECTED_CHANGE_REQUIRED','The proposed repair changes a business/design expectation not authorized by this task.','Cách sửa đổi expected business/design task chưa cho phép.')]);

export { ops, pair, read, write, step, proof, stop, add, targetRead, businessRead, architectureRead, repoRead, environmentRead, identityRead, fixtureRead, nodeWrite, evidenceWrite, sourceWrite, resourceWrite, genericProof, commitProof };
