// gen-catalog.mjs — generate the CLI catalog products from modules/cli/commands (cli/design.md).
// Modes: --write writes; --check reports RT_CLI_CATALOG_DRIFT when generated output differs.
// Outputs: packages/cli/src/catalog.generated.mjs, docs/cli.md, and
// packages/cli/completions/{starci.bash,_starci,starci.fish,starci.ps1}.
// The runtime install pin module is derived from the root package identity.
import fs from 'node:fs';
import path from 'node:path';
import { skillRoot } from '../../engine/runtime-root.mjs';
import { isMain } from '../lib/is-main.mjs';
import { loadCatalog, catalogHash, CATALOG_SCHEMA } from './catalog.mjs';
const GENERATED = 'GENERATED by scripts/cli/gen-catalog.mjs — do not edit';
const DRIFT_CODE = 'RT_CLI_CATALOG_DRIFT';
// Built-in retired group spellings; per-verb spellings come from each verb's removed list.
const RETIRED_BUILTINS = [
  { spelling: 'starci api', use: 'starci kernel' },
  { spelling: 'starci init', use: 'starci runtime install' },
  { spelling: 'starci update', use: 'starci runtime update' },
  { spelling: 'starci doctor', use: 'starci runtime doctor' },
  { spelling: 'starci version', use: 'starci runtime version' },
  { spelling: 'starci validate', use: 'starci runtime validate' },
  { spelling: 'starci start', use: 'starci workflow start' },
  { spelling: 'starci goal', use: 'starci workflow define' },
  { spelling: 'hfs', use: 'starci app' },
  { spelling: 'starci-test-stack', use: 'starci app stack' },
];
const VERB_FIELDS = ['summary', 'owner', 'positional', 'flags', 'exit', 'json', 'examples', 'editions', 'since', 'removed', 'impl', 'effect', 'roles', 'conventions'];
/** The generated module text. */
const renderCatalogModule = async (cat) => {
  const hash = await catalogHash(cat.sources);
  const groups = {};
  const retired = [...RETIRED_BUILTINS];
  for (const g of cat.groups) {
    const verbs = {};
    for (const v of g.verbs) {
      const entry = {};
      for (const k of VERB_FIELDS) if (v[k] !== undefined) entry[k] = v[k];
      verbs[v.verb] = entry;
      for (const r of v.removed ?? []) retired.push({ spelling: r, use: `starci ${g.group} ${v.verb}` });
    }
    groups[g.group] = { summary: g.summary, owner: g.owner, since: g.since, verbs };
  }
  const catalog = { schema: CATALOG_SCHEMA, hash, global: cat.global.flags, commands: cat.global.commands, groups };
  return `// ${GENERATED}\nexport const CATALOG = ${JSON.stringify(catalog, null, 2)};\n\nexport const RETIRED = ${JSON.stringify(retired, null, 2)};\n`;
};
const flagSig = (f) => `--${f.name}${f.type === 'boolean' ? '' : f.type === 'enum' ? ` <${(f.enum ?? []).join('|')}>` : ' <v>'}${f.required ? ' (required)' : ''}`;
const renderDocs = (cat) => {
  const out = [
    'Owner: modules/cli/commands/_global.yaml', '',
    `# starci CLI reference`, '',
    `<!-- ${GENERATED} -->`, '',
    'One binary, ' + cat.groups.length + ' groups. Global flags: `--json`, `--cwd <dir>`, `--quiet`, `--help`, `--edition full|lite`.',
    'Exit codes: 0 clean, 1 findings, 2 refusal or bad usage, 3 the runtime group needs a runtime that is not installed.', '',
  ];
  for (const g of cat.groups) {
    out.push(`## starci ${g.group}`, '', `${g.summary}`, '');
    for (const v of g.verbs) {
      out.push(`### starci ${g.group} ${v.verb}`, '', `${v.summary}`, '');
      if (v.flags?.length) {
        out.push('| flag | type | |', '| --- | --- | --- |');
        for (const f of v.flags) out.push(`| \`--${f.name}\` | ${f.type}${f.enum ? ` ${f.enum.join('|')}` : ''}${f.default !== undefined ? ` (default ${f.default})` : ''} | ${f.required ? 'required' : ''} |`);
        out.push('');
      }
      if (v.positional?.length) out.push(`Positionals: ${v.positional.map((p) => `${p.name}${p.required === false ? '?' : ''}`).join(', ')}`, '');
      if (v.effect) out.push(`Effect: ${v.effect}`, '');
      if (v.roles?.length) out.push(`Roles: ${v.roles.join(', ')}`, '');
      if (v.conventions?.length) out.push('Conventions:', '', ...v.conventions.map((line) => `- ${line}`), '');
      out.push(`exit: ${Object.entries(v.exit ?? {}).map(([c, t]) => `${c} ${t}`).join('; ')}`, '',
        `json: ${v.json}`, '');
      if (v.examples?.length) out.push('```sh', ...v.examples, '```', '');
    }
  }
  return out.join('\n');
};
/** Shell completions for bash, zsh, fish, powershell. */
const renderCompletions = (cat) => {
  const groups = cat.groups.map((g) => g.group);
  const completionShells = ['bash', 'zsh', 'fish', 'powershell'];
  const globalCommands = cat.global.commands ?? [];
  const topLevel = [...groups, 'help', 'completion', ...globalCommands];
  const flagsOf = (verb) => [...(verb.flags ?? []), ...cat.global.flags];
  const flagNamesOf = (verb) => flagsOf(verb).map((flag) => `--${flag.name}`);
  const shellQuote = (value) => `'${String(value).replaceAll("'", "'\\''")}'`;
  const psQuote = (value) => `'${String(value).replaceAll("'", "''")}'`;
  const psArray = (values) => `@(${values.map(psQuote).join(',')})`;
  const bashWords = (values) => String(values.join(' ')).replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('$', '\\$').replaceAll('`', '\\`');
  const zshDescription = (value) => String(value ?? '').replace(/[\[\]]/g, '').replace(/[\r\n]+/g, ' ');
  const groupVerbs = cat.groups.map((group) => [group.group, group.verbs.map((verb) => verb.verb)]);
  const commands = cat.groups.flatMap((group) => group.verbs.map((verb) => ({ group: group.group, verb })));
  const bashVerbs = [
    ...groupVerbs.map(([group, verbs]) => `        ${group}) COMPREPLY=( $(compgen -W "${bashWords(verbs)}" -- "$cur") );;`),
    `        completion) COMPREPLY=( $(compgen -W "${completionShells.join(' ')}" -- "$cur") );;`,
    ...(globalCommands.includes('explain') ? [`        explain) COMPREPLY=( $(compgen -W "${bashWords(groups)}" -- "$cur") );;`] : []),
  ].join('\n');
  const bashFlagCases = commands.map(({ group, verb }) => `        ${group}:${verb.verb}) COMPREPLY=( $(compgen -W "${bashWords(flagNamesOf(verb))}" -- "$cur") );;`).join('\n');
  const bashGlobalValueCases = cat.global.flags.filter((flag) => flag.type !== 'boolean').map((flag) => flag.type === 'enum'
    ? `        --${flag.name}) COMPREPLY=( $(compgen -W "${bashWords(flag.enum ?? [])}" -- "$cur") ); return 0;;`
    : `        --${flag.name}) return 0;;`).join('\n');
  const bashLocalValueCases = commands.flatMap(({ group, verb }) => (verb.flags ?? []).filter((flag) => flag.type !== 'boolean').map((flag) => flag.type === 'enum'
    ? `        ${group}:${verb.verb}:--${flag.name}) COMPREPLY=( $(compgen -W "${bashWords(flag.enum ?? [])}" -- "$cur") ); return 0;;`
    : `        ${group}:${verb.verb}:--${flag.name}) return 0;;`)).join('\n');
  const bash = `# ${GENERATED}
_starci() {
    local cur prev group verb
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev=""
    if [ "$COMP_CWORD" -gt 0 ]; then prev="\${COMP_WORDS[COMP_CWORD-1]}"; fi
    group="\${COMP_WORDS[1]}"
    verb="\${COMP_WORDS[2]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${topLevel.join(' ')}" -- "$cur") )
        return 0
    fi
    if [ "$COMP_CWORD" -eq 2 ]; then
        case "$group" in
${bashVerbs}
            *) COMPREPLY=();;
        esac
        return 0
    fi
    case "$prev" in
${bashGlobalValueCases}
    esac
    case "$group:$verb:$prev" in
${bashLocalValueCases}
    esac
    case "$group:$verb" in
${bashFlagCases}
        *) COMPREPLY=();;
    esac
    return 0
}
complete -F _starci starci
`;
  const zsub = [
    ...cat.groups.map((group) => `    ${shellQuote(`${group.group}:${zshDescription(group.summary)}`)}`),
    `    ${shellQuote('help:show top-level help')}`,
    `    ${shellQuote('completion:print a shell completion script')}`,
    ...(globalCommands.includes('explain') ? [`    ${shellQuote('explain:show a verb contract and the spellings it replaces')}`] : []),
  ].join('\n');
  const zverbs = [
    ...cat.groups.map((group) => `      ${group.group}) _values 'verbs' ${group.verbs.map((verb) => shellQuote(`${verb.verb}[${zshDescription(verb.summary)}]`)).join(' ')} ;;`),
    `      completion) _values 'shells' ${completionShells.map(shellQuote).join(' ')} ;;`,
    `      help) return 0 ;;`,
    ...(globalCommands.includes('explain') ? [`      explain) _values 'groups' ${groups.map(shellQuote).join(' ')} ;;`] : []),
  ].join('\n');
  const zGlobalValueCases = cat.global.flags.filter((flag) => flag.type !== 'boolean').map((flag) => flag.type === 'enum'
    ? `    --${flag.name}) _values 'values' ${(flag.enum ?? []).map(shellQuote).join(' ')}; return 0 ;;`
    : `    --${flag.name}) return 0 ;;`).join('\n');
  const zLocalValueCases = commands.flatMap(({ group, verb }) => (verb.flags ?? []).filter((flag) => flag.type !== 'boolean').map((flag) => flag.type === 'enum'
    ? `    ${shellQuote(`${group}:${verb.verb}:--${flag.name}`)}) _values 'values' ${(flag.enum ?? []).map(shellQuote).join(' ')}; return 0 ;;`
    : `    ${shellQuote(`${group}:${verb.verb}:--${flag.name}`)}) return 0 ;;`)).join('\n');
  const zFlagCases = commands.map(({ group, verb }) => `    ${shellQuote(`${group}:${verb.verb}`)}) _values 'flags' ${flagNamesOf(verb).map(shellQuote).join(' ')} ;;`).join('\n');
  const zsh = `#compdef starci
# ${GENERATED}
_starci() {
  local -a groups
  local prev
  groups=(
${zsub}
  )
  if (( CURRENT == 2 )); then
    _describe 'group' groups
  elif (( CURRENT == 3 )); then
    case "$words[2]" in
${zverbs}
    esac
  else
    prev="$words[CURRENT-1]"
    case "$prev" in
${zGlobalValueCases}
    esac
    case "$words[2]:$words[3]:$prev" in
${zLocalValueCases}
    esac
    case "$words[2]:$words[3]" in
${zFlagCases}
    esac
  fi
}
_starci "$@"
`;
  const fishLines = [`# ${GENERATED}`, `function __starci_needs_group
    set -l words (commandline -opc)
    test (count $words) -eq 1
end`, `function __starci_needs_verb --argument-names group
    set -l words (commandline -opc)
    test (count $words) -eq 2
    and test "$words[2]" = "$group"
end`, `function __starci_using_command --argument-names group verb
    set -l words (commandline -opc)
    test (count $words) -ge 3
    and test "$words[2]" = "$group"
    and test "$words[3]" = "$verb"
end`];
  for (const group of cat.groups) fishLines.push(`complete -c starci -n '__starci_needs_group' -a ${shellQuote(group.group)} -d ${shellQuote(group.summary ?? '')}`);
  fishLines.push(`complete -c starci -n '__starci_needs_group' -a 'help' -d 'show top-level help'`);
  fishLines.push(`complete -c starci -n '__starci_needs_group' -a 'completion' -d 'print a shell completion script'`);
  if (globalCommands.includes('explain')) fishLines.push(`complete -c starci -n '__starci_needs_group' -a 'explain' -d 'show a verb contract and the spellings it replaces'`);
  for (const group of cat.groups) for (const verb of group.verbs) fishLines.push(`complete -c starci -n '__starci_needs_verb ${group.group}' -a ${shellQuote(verb.verb)} -d ${shellQuote(verb.summary ?? '')}`);
  for (const shell of completionShells) fishLines.push(`complete -c starci -n '__starci_needs_verb completion' -a ${shellQuote(shell)}`);
  if (globalCommands.includes('explain')) {
    for (const group of cat.groups) {
      fishLines.push(`complete -c starci -n '__starci_needs_verb explain' -a ${shellQuote(group.group)} -d ${shellQuote(group.summary ?? '')}`);
    }
  }
  for (const { group, verb } of commands) for (const flag of verb.flags ?? []) fishLines.push(`complete -c starci -n '__starci_using_command ${group} ${verb.verb}' -l ${flag.name}${flag.type === 'boolean' ? '' : ' -r'}${flag.type === 'enum' ? ` -a ${shellQuote((flag.enum ?? []).join(' '))}` : ''}${flag.summary ? ` -d ${shellQuote(flag.summary)}` : ''}`);
  for (const flag of cat.global.flags) fishLines.push(`complete -c starci -l ${flag.name}${flag.type === 'boolean' ? '' : ' -r'}${flag.type === 'enum' ? ` -a ${shellQuote((flag.enum ?? []).join(' '))}` : ''}${flag.summary ? ` -d ${shellQuote(flag.summary)}` : ''}`);
  const fish = fishLines.join('\n') + '\n';
  const psVerbs = [
    ...groupVerbs.map(([group, verbs]) => `        ${psQuote(group)} = ${psArray(verbs)}`),
    `        'completion' = ${psArray(completionShells)}`,
    `        'help' = @()`,
    ...(globalCommands.includes('explain') ? [`        'explain' = ${psArray(groups)}`] : []),
  ].join('\n');
  const psFlags = commands.map(({ group, verb }) => `        ${psQuote(`${group} ${verb.verb}`)} = ${psArray(flagNamesOf(verb))}`).join('\n');
  const psGlobalValues = cat.global.flags.filter((flag) => flag.type !== 'boolean').map((flag) => `        ${psQuote(`--${flag.name}`)} = ${psArray(flag.type === 'enum' ? flag.enum ?? [] : [])}`).join('\n');
  const psLocalValues = commands.flatMap(({ group, verb }) => (verb.flags ?? []).filter((flag) => flag.type !== 'boolean').map((flag) => `        ${psQuote(`${group} ${verb.verb} --${flag.name}`)} = ${psArray(flag.type === 'enum' ? flag.enum ?? [] : [])}`)).join('\n');
  const ps = `# ${GENERATED}
Register-ArgumentCompleter -Native -CommandName starci -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $groups = ${psArray(topLevel)}
    $verbs = @{
${psVerbs}
    }
    $flags = @{
${psFlags}
    }
    $globalValues = @{
${psGlobalValues}
    }
    $localValues = @{
${psLocalValues}
    }
    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
    $currentIndex = if ([string]::IsNullOrEmpty($wordToComplete)) { $words.Count } else { $words.Count - 1 }
    $candidates = @()
    if ($currentIndex -eq 1) {
        $candidates = $groups
    } elseif ($currentIndex -eq 2) {
        $candidates = @($verbs[$words[1]])
    } elseif ($currentIndex -ge 3) {
        $group = $words[1]
        $verb = $words[2]
        $previous = if ($currentIndex -gt 3) { $words[$currentIndex - 1] } else { $null }
        $localValueKey = "$group $verb $previous"
        if ($null -ne $previous -and $globalValues.ContainsKey($previous)) {
            $candidates = @($globalValues[$previous])
        } elseif ($null -ne $previous -and $localValues.ContainsKey($localValueKey)) {
            $candidates = @($localValues[$localValueKey])
        } else {
            $candidates = @($flags["$group $verb"])
        }
    }
    $candidates | Where-Object { $null -ne $_ -and $_.StartsWith($wordToComplete, [System.StringComparison]::OrdinalIgnoreCase) } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
  return { 'starci.bash': bash, '_starci': zsh, 'starci.fish': fish, 'starci.ps1': ps };
};
const renderRuntimeInstallModule = (root) => {
  const manifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  if (manifest.name !== 'starci' || typeof manifest.version !== 'string'
    || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(manifest.version))
    throw new Error('runtime install pin requires the starci root package and an exact version');
  return `// ${GENERATED}\nexport const RUNTIME_VERSION = ${JSON.stringify(manifest.version)};\n`;
};
/** Every output the generator owns: {relpath: text}. */
export const generateAll = async (root = skillRoot) => {
  const cat = loadCatalog(root);
  return {
    'packages/cli/src/catalog.generated.mjs': await renderCatalogModule(cat),
    'packages/cli/src/runtime-install.generated.mjs': renderRuntimeInstallModule(root),
    'docs/cli.md': renderDocs(cat),
    ...Object.fromEntries(Object.entries(renderCompletions(cat)).map(([k, v]) => [`packages/cli/completions/${k}`, v])),
  };
};
const main = () => {
  const argv = process.argv.slice(2);
  const mode = argv[0];
  const rootIdx = argv.indexOf('--root');
  if (!['--write', '--check'].includes(mode) || (rootIdx >= 0 && argv[rootIdx + 1] === undefined) || argv.length > (rootIdx < 0 ? 1 : 3)) {
    console.error('use: starci runtime gen-catalog [--write|--check] [--root <tree>]');
    process.exit(2);
  }
  const root = rootIdx < 0 ? skillRoot : path.resolve(argv[rootIdx + 1]);
  generateAll(root).then((outputs) => {
    if (mode === '--write') {
      for (const [rel, text] of Object.entries(outputs)) {
        const file = path.join(root, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, text);
        console.log(`wrote ${rel}`);
      }
      return;
    }
    const diffs = Object.entries(outputs).filter(([rel, text]) => {
      const file = path.join(root, rel);
      return !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text;
    }).map(([rel]) => rel);
    if (diffs.length) {
      console.error(`${DRIFT_CODE}: generated output differs — ${diffs.join(', ')} (run: starci runtime gen-catalog --write)`);
      process.exit(1);
    }
    console.log('cli catalog: generated outputs are in sync');
  }).catch((e) => { console.error(String(e?.message ?? e)); process.exit(1); });
};
if (isMain(import.meta.url)) main();
