// gen-catalog.mjs — generate the CLI catalog products from modules/cli/commands
// (cli/design.md). Writes, never by hand:
//   node scripts/cli/gen-catalog.mjs --write   write the outputs
//   node scripts/cli/gen-catalog.mjs --check   exit 1 with the diff list when any output differs (RT_CLI_CATALOG_DRIFT)
// Outputs: packages/cli/src/catalog.generated.mjs, docs/cli.md,
// packages/cli/completions/{starci.bash,_starci,starci.fish,starci.ps1}.
import fs from 'node:fs';
import path from 'node:path';
import { skillRoot } from '../../engine/runtime-root.mjs';
import { isMain } from '../lib/is-main.mjs';
import { loadCatalog, catalogHash, CATALOG_SCHEMA } from './catalog.mjs';

const GENERATED = 'GENERATED by scripts/cli/gen-catalog.mjs — do not edit';
const DRIFT_CODE = 'RT_CLI_CATALOG_DRIFT';

// The dispatcher's built-in retired spellings (group-level names, design.md
// "Removed commands"); per-verb spellings come from each verb's removed: list.
const RETIRED_BUILTINS = [
  { spelling: 'starci api', use: 'starci kernel' },
  { spelling: 'starci init', use: 'starci runtime install' },
  { spelling: 'starci update', use: 'starci runtime update' },
  { spelling: 'starci doctor', use: 'starci runtime doctor' },
  { spelling: 'starci version', use: 'starci runtime version' },
  { spelling: 'starci validate', use: 'starci runtime validate' },
  { spelling: 'starci check', use: 'starci runtime check' },
  { spelling: 'starci start', use: 'starci workflow start' },
  { spelling: 'starci goal', use: 'starci workflow define' },
  { spelling: 'hfs', use: 'starci app' },
  { spelling: 'starci-test-stack', use: 'starci app stack' },
];

const VERB_FIELDS = ['summary', 'owner', 'positional', 'flags', 'exit', 'json', 'examples', 'editions', 'since', 'removed', 'impl'];

/** The generated module text. */
export const renderCatalogModule = async (cat) => {
  const hash = await catalogHash(cat.sources);
  const groups = {};
  const retired = [...RETIRED_BUILTINS];
  for (const g of cat.groups) {
    const verbs = {};
    for (const v of g.verbs) {
      const entry = {};
      for (const k of VERB_FIELDS) if (v[k] !== undefined) entry[k] = v[k];
      verbs[v.verb] = entry;
      for (const r of v.removed ?? []) retired.push({ spelling: r, use: `starci ${g.group} ${v.verb}` });
    }
    groups[g.group] = { summary: g.summary, owner: g.owner, since: g.since, verbs };
  }
  const catalog = { schema: CATALOG_SCHEMA, hash, global: cat.global.flags, groups };
  return `// ${GENERATED}\nexport const CATALOG = ${JSON.stringify(catalog, null, 2)};\n\nexport const RETIRED = ${JSON.stringify(retired, null, 2)};\n`;
};

const flagSig = (f) => `--${f.name}${f.type === 'boolean' ? '' : f.type === 'enum' ? ` <${(f.enum ?? []).join('|')}>` : ' <v>'}${f.required ? ' (required)' : ''}`;

/** docs/cli.md — generated English reference. */
export const renderDocs = (cat) => {
  const out = [
    `# starci CLI reference`, '',
    `<!-- ${GENERATED} -->`, '',
    'One binary, six groups. Global flags: `--json`, `--cwd <dir>`, `--quiet`, `--help`, `--edition full`.',
    'Exit codes: 0 clean, 1 findings, 2 refusal or bad usage, 3 the runtime group needs a runtime that is not installed.', '',
  ];
  for (const g of cat.groups) {
    out.push(`## starci ${g.group}`, '', `${g.summary}`, '');
    for (const v of g.verbs) {
      out.push(`### starci ${g.group} ${v.verb}`, '', `${v.summary}`, '');
      if (v.flags?.length) {
        out.push('| flag | type | |', '| --- | --- | --- |');
        for (const f of v.flags) out.push(`| \`--${f.name}\` | ${f.type}${f.enum ? ` ${f.enum.join('|')}` : ''}${f.default !== undefined ? ` (default ${f.default})` : ''} | ${f.required ? 'required' : ''} |`);
        out.push('');
      }
      if (v.positional?.length) out.push(`Positionals: ${v.positional.map((p) => `${p.name}${p.required === false ? '?' : ''}`).join(', ')}`, '');
      out.push(`exit: ${Object.entries(v.exit ?? {}).map(([c, t]) => `${c} ${t}`).join('; ')}`, '',
        `json: ${v.json}`, '');
      if (v.examples?.length) out.push('```sh', ...v.examples, '```', '');
      if (v.removed?.length) out.push(`Removed spellings: ${v.removed.map((r) => `\`${r}\``).join(', ')}`, '');
    }
  }
  return out.join('\n');
};

const allFlagsOf = (cat, verb) => [...cat.global.flags.map((f) => `--${f.name}`), ...(verb.flags ?? []).map((f) => `--${f.name}`)];

/** Shell completions for bash, zsh, fish, powershell. */
export const renderCompletions = (cat) => {
  const groups = cat.groups.map((g) => g.group);
  const verbsOf = (g) => cat.groups.find((x) => x.group === g)?.verbs.map((v) => v.verb) ?? [];
  const gwords = groups.join(' ');
  const globalFlags = cat.global.flags.map((f) => `--${f.name}`).join(' ');
  const bashCases = cat.groups.map((g) => `        ${g.group}) COMPREPLY=( $(compgen -W "${verbsOf(g.group).join(' ')}" -- "$cur") );;`).join('\n');
  const verbCases = cat.groups.map((g) => `            ${g.group}) COMPREPLY=( $(compgen -W "${(cat.groups.find((x) => x.group === g)?.verbs ?? []).flatMap((v) => allFlagsOf(cat, v)).join(' ')}" -- "$cur") );;`).join('\n');
  const bash = `# ${GENERATED}
_starci() {
    local cur prev group
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    group="\${COMP_WORDS[1]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${gwords} help completion" -- "$cur") )
        return 0
    fi
    if [ "$COMP_CWORD" -eq 2 ]; then
        case "$group" in
${bashCases}
            *) COMPREPLY=();;
        esac
        return 0
    fi
    case "$group" in
${verbCases}
    esac
    COMPREPLY+=( $(compgen -W "${globalFlags}" -- "$cur") )
    return 0
}
complete -F _starci starci
`;
  const zsub = cat.groups.map((g) => `    '${g.group}:${(g.summary ?? '').replace(/'/g, '')}'`).join('\n');
  const zverbs = cat.groups.map((g) => `            ${g.group}) _values 'verbs' ${verbsOf(g.group).map((v) => `'${v}[${(v.summary ?? '').replace(/'/g, '')}]'`).join(' ')} ;;`).join('\n');
  const zsh = `#compdef starci
# ${GENERATED}
_starci() {
  local -a groups
  groups=(
${zsub}
  )
  if (( CURRENT == 2 )); then
    _describe 'group' groups
  elif (( CURRENT == 3 )); then
    case "$words[2]" in
${zverbs}
    esac
  else
    _values 'flags' ${globalFlags.split(' ').map((f) => `'${f}'`).join(' ')}
  fi
}
_starci "$@"
`;
  const fishHead = `# ${GENERATED}`;
  const fishLines = [fishHead];
  for (const g of groups) fishLines.push(`complete -c starci -n '__fish_use_subcommand' -a ${g}`);
  for (const g of cat.groups) for (const v of g.verbs) fishLines.push(`complete -c starci -n '__fish_seen_subcommand_from ${g.group}' -a ${v.verb} -d '${(v.summary ?? '').replace(/'/g, '')}'`);
  for (const f of cat.global.flags) fishLines.push(`complete -c starci -l ${f.name}${f.type === 'boolean' ? '' : ' -r'}`);
  const fish = fishLines.join('\n') + '\n';
  const ps = `# ${GENERATED}
Register-ArgumentCompleter -Native -CommandName starci -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $groups = '${gwords}'.Split(' ')
    $verbs = @{
${cat.groups.map((g) => `        '${g.group}' = @(${verbsOf(g.group).map((v) => `'${v}'`).join(',')})`).join('\n')}
    }
    $flags = '${globalFlags}'.Split(' ')
    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    if ($words.Count -le 2) { $candidates = $groups } elseif ($words.Count -eq 3) { $candidates = $verbs[$words[1]] } else { $candidates = $flags }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
  return { 'starci.bash': bash, '_starci': zsh, 'starci.fish': fish, 'starci.ps1': ps };
};

/** Every output the generator owns: {relpath: text}. */
export const generateAll = async (root = skillRoot) => {
  const cat = loadCatalog(root);
  return {
    'packages/cli/src/catalog.generated.mjs': await renderCatalogModule(cat),
    'docs/cli.md': renderDocs(cat),
    ...Object.fromEntries(Object.entries(renderCompletions(cat)).map(([k, v]) => [`packages/cli/completions/${k}`, v])),
  };
};

const main = () => {
  const argv = process.argv.slice(2);
  const mode = argv[0];
  const rootIdx = argv.indexOf('--root');
  if (!['--write', '--check'].includes(mode) || (rootIdx >= 0 && argv[rootIdx + 1] === undefined) || argv.length > (rootIdx < 0 ? 1 : 3)) {
    console.error('use: node scripts/cli/gen-catalog.mjs [--write|--check] [--root <tree>]');
    process.exit(2);
  }
  const root = rootIdx < 0 ? skillRoot : path.resolve(argv[rootIdx + 1]);
  generateAll(root).then((outputs) => {
    if (mode === '--write') {
      for (const [rel, text] of Object.entries(outputs)) {
        const file = path.join(root, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, text);
        console.log(`wrote ${rel}`);
      }
      return;
    }
    const diffs = Object.entries(outputs).filter(([rel, text]) => {
      const file = path.join(root, rel);
      return !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text;
    }).map(([rel]) => rel);
    if (diffs.length) {
      console.error(`${DRIFT_CODE}: generated output differs — ${diffs.join(', ')} (run: node scripts/cli/gen-catalog.mjs --write)`);
      process.exit(1);
    }
    console.log('cli catalog: generated outputs are in sync');
  }).catch((e) => { console.error(String(e?.message ?? e)); process.exit(1); });
};
if (isMain(import.meta.url)) main();
