import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath, pathToFileURL} from 'node:url';
import {parseYaml, stringifyYaml} from '../core/yaml.mjs';
import {walk as walkAll} from './check-example-work.mjs';
import {readWorkspace, resolveOwnedDirs, hashOwnedDirs, indexInlineCriteria, inlineCriteriaOf, splitRef, resolveRecordRef} from './example-ownership.mjs';

/**
 * The layout promises a reader can answer every work question from the tree without opening source
 * (schemas/work-layout.yaml, README of this lane). Three of those questions are only reachable today by
 * grep: what depends on X (reverse edges), what is the effective state of Y (authored state plus derived
 * staleness plus blockers), and what is the honest tally (done/todo/stale/blocked, designed todos versus
 * leftovers). This module computes all three, mechanically, from the records and evidence already on disk -
 * nothing here is authored, and a derived field typed by hand into a record is exactly the lie this script
 * exists to make impossible (enforced separately by scripts/check-example-derived.mjs).
 *
 * `effectiveState`'s staleness rule is the one core/index.mjs already uses for its canonical work/node@2
 * model (validate()'s `roll()`: `n.effectiveState = localInvalid ? 'invalid' : n.stale ? 'suspended' :
 * n.meta.state`) - staleness overrides authored state to `suspended` before anything else is considered.
 * This tree's simpler schema (scripts/check-example-work.mjs's FAMILIES) has no `invalid`/`uninvestigate`
 * concept, but it does have a state core's model does not: `blocked`, for a record whose own `blockedBy`
 * chain is currently unmet. The precedence is the same shape as core's: staleness is checked first (it can
 * turn even a `todo` record's evidence into something no longer trustworthy), then unmet blockers, then the
 * authored state stands as given.
 */

/** Every id-shaped string the layout's rules make a real edge, exactly as scripts/check-example-work.mjs's
 * own ID_RE recognizes one - kept identical on purpose, so "is this a reference" is answered the same way
 * in both places. */
export const ID_RE = /^(br|ac|fr|nfr|data|journey|decision|sds|ui|impl|uat|contract|integration|gap|event)\.[a-z0-9-]+(\.[a-z0-9-]+)+$/;

/** The edge kinds the layout's rules define, in the order a reader should see them. `provenBy` on a
 * work/contract is split into its own two roles because the layout's concept 9/reconciliation model treats
 * "who proves the provider side" and "who proves the consumer side" as distinct facts, not one bag of ids. */
export const EDGE_KIND_ORDER = ['refs','composes','dependsOn','subscribes','extends','appliesTo',
  'conflictsWith','blockedBy','tension','contractProvider','contractConsumer','provenBy'];
const EDGE_FIELD_NAMES = new Set(['refs','composes','dependsOn','subscribes','extends','appliesTo',
  'conflictsWith','blockedBy','tension']);

const DERIVED_DIR_NAME = '_derived';
const HEADER = [
  '# GENERATED by scripts/example-derive.mjs - do not edit by hand.',
  '# Regenerate with: node scripts/example-derive.mjs --work <path-to-.starciwork> --write',
  '# This is the reverse-edge index, effective-state and frontier the Work layout promises a reader can',
  '# read instead of grepping for. It is excluded from the record walk (schemas/work-layout.yaml): it is',
  '# not itself a record, has no id, and authors none of the fields it computes.',
].join('\n')+'\n';

const sha256File = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const isPlainObject = v => v !== null && typeof v === 'object' && !Array.isArray(v);
const isoTime = v => typeof v === 'string' && Number.isFinite(Date.parse(v)) ? Date.parse(v) : NaN;

/** Deterministic JSON, keys sorted at every level - the same shape core/index.mjs's own canonicalJSON uses,
 * reproduced locally (four lines) rather than imported, since importing core/index.mjs would pull in its
 * entire validate() machinery for one helper. Used only to compare two derived structures for the gate. */
function canonicalJSON(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalJSON).join(',')}]`;
  if (isPlainObject(value)) return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonicalJSON(value[k])}`).join(',')}}`;
  return JSON.stringify(value);
}

/** Every id-shaped string under `value`, tagged with the dotted key path it was found at (arrays do not add
 * a segment), so the caller can tell `blockedBy.record` from `refs`. Mirrors check-example-work.mjs's own
 * `collect`, kept separate because that module's version does not return the trail per match in a form this
 * module can classify into edge kinds. */
function collectIdsByTrail(value, trail, out) {
  if (typeof value === 'string') {
    const s = value.trim();
    if (ID_RE.test(s)) { out.push({trail, id: s}); return; }
    // `P#frag` addresses an inlined criterion through its parent - the edge lands on P, which owns it.
    const {id, frag} = splitRef(s);
    if (frag !== null && frag && ID_RE.test(id)) out.push({trail, id});
    return;
  }
  if (Array.isArray(value)) { for (const item of value) collectIdsByTrail(item, trail, out); return; }
  if (isPlainObject(value)) for (const [k, v] of Object.entries(value)) collectIdsByTrail(v, trail ? `${trail}.${k}` : k, out);
}

/** The edge kind one collected `{trail, id}` hit belongs to, or null when the layout's rules do not name
 * this field as an edge (an "unclassified" hit - `ac.*`'s `rule`, `work/event`'s `producer`, `work/gap`'s
 * `closedBy`, a decision's `blocks` - real pointers, just not ones the layout enumerates as a graph edge). */
function classifyEdge(recordSchema, trail) {
  const field = trail.split('.')[0];
  if (field === 'provenBy') {
    if (recordSchema === 'work/contract') {
      if (trail === 'provenBy.provider') return 'contractProvider';
      if (trail === 'provenBy.consumer') return 'contractConsumer';
    }
    return 'provenBy';
  }
  return EDGE_FIELD_NAMES.has(field) ? field : null;
}

/**
 * Reads every record and evidence file under `workRoot` (a `.starciwork` directory). `_derived/**` is never
 * walked - it is this script's own output, not input, and re-ingesting it as records would make every run
 * see references to itself.
 */
function readTree(workRoot) {
  const records = new Map(); // id -> {id, schema, state, data, file, dir, relPath, feature}
  const evidenceByDir = new Map(); // dir (posix, relative to workRoot) -> {data, file}
  const derivedPrefix = `${DERIVED_DIR_NAME}/`;

  for (const file of walkAll(workRoot).filter(f => f.endsWith('.yaml'))) {
    const relPath = path.relative(workRoot, file).replaceAll('\\', '/');
    if (relPath === DERIVED_DIR_NAME || relPath.startsWith(derivedPrefix)) continue;
    let data;
    try { data = parseYaml(fs.readFileSync(file, 'utf8')); } catch { continue; }
    if (!isPlainObject(data)) continue;
    const dir = path.dirname(relPath).replaceAll('\\', '/');

    if (relPath.endsWith('/evidence.yaml') || relPath === 'evidence.yaml') {
      evidenceByDir.set(dir, {data, file});
      continue;
    }
    if (typeof data.id !== 'string' || !data.id) continue;
    const segments = relPath.split('/');
    const feature = segments[0] === 'features' && segments.length > 1 ? segments[1] : null;
    records.set(data.id, {
      id: data.id, schema: data.schema ?? null, state: Object.hasOwn(data, 'state') ? data.state : null,
      data, file, dir, relPath, feature,
    });
  }
  return {records, evidenceByDir};
}

/** The reverse index: id -> edge kind -> sorted, deduplicated list of ids that reference it that way.
 * Self-references (a record's own `id` echoed back by a field the collector also walks) are dropped - a
 * record does not use itself. */
function buildUsedBy(records) {
  const usedBy = new Map(); // targetId -> Map(kind -> Set(sourceId))
  const unclassified = []; // {from, field, target}
  // Compact format: an inline criterion's own `id:` under acceptance:/statements: is a declaration, not
  // an edge (same reason the top-level `id` key is skipped); and a reference to a collapsed `ac.*` id is
  // an edge to the parent record that now carries the criterion.
  const inline = indexInlineCriteria(records);
  const DECL_TRAIL = /^(?:acceptance|statements)\.(?:.+\.)?id$/;
  const canon = id => records.has(id) ? id : (inline.byAcId.get(id) ?? id);
  for (const record of records.values()) {
    const hits = [];
    for (const [key, value] of Object.entries(record.data)) {
      if (key === 'id') continue;
      collectIdsByTrail(value, key, hits);
    }
    for (const {trail, id: targetId} of hits) {
      if (DECL_TRAIL.test(trail)) continue;
      const canonical = canon(targetId);
      if (canonical === record.id) continue;
      const kind = classifyEdge(record.schema, trail);
      if (!kind) { unclassified.push({from: record.id, field: trail, target: canonical}); continue; }
      if (!usedBy.has(canonical)) usedBy.set(canonical, new Map());
      const byKind = usedBy.get(canonical);
      if (!byKind.has(kind)) byKind.set(kind, new Set());
      byKind.get(kind).add(record.id);
    }
  }
  unclassified.sort((a, b) => a.from.localeCompare(b.from) || a.field.localeCompare(b.field) || a.target.localeCompare(b.target));
  return {usedBy, unclassified};
}

/**
 * Whether `record`'s evidence no longer speaks for it, and why. Three independent tests, either one
 * enough:
 *  - digest staleness: the evidence is explicitly marked `stale: true`, or its `recordDigest` no longer
 *    matches the sha256 of the record's own current bytes (the exact digest kernel/reconciliation.mjs's
 *    `recordDigests`/`nodeFileOf` compute, reproduced here for the same reason check-example-work.mjs
 *    reproduces it: importing recordDigests would require building the `tree` object it expects).
 *  - code-digest staleness (layout concept 1): the evidence carries a `codeDigest` (scripts/example-
 *    ownership.mjs's `hashOwnedDirs`, over the record's own owners/module or, when it names none, every
 *    implementation proving it) that no longer matches what that same computation produces from the code
 *    on disk right now - a code change stales a proof without anyone touching the record. Not checked
 *    when the evidence carries no `codeDigest` at all (nothing was ever claimed about the code).
 *  - appliesTo staleness (layout concept 7): some other record's `appliesTo` names this one, and that
 *    record's `change.at` is later than this evidence's own `provenance.capturedAt` - the constraint moved
 *    after this record was last proven. Only checked when evidence exists and both timestamps parse; a
 *    record with no evidence has no proof to invalidate this way.
 */
function staleness(record, evidenceByDir, appliesToSources, records, workspaceDoc, workRoot) {
  const evidence = evidenceByDir.get(record.dir);
  if (!evidence) return null;
  if (evidence.data.stale === true) return {reason: 'evidence-marked-stale'};
  if (typeof evidence.data.recordDigest === 'string' && evidence.data.recordDigest) {
    if (sha256File(record.file) !== evidence.data.recordDigest) return {reason: 'digest-mismatch'};
  }
  if (typeof evidence.data.codeDigest?.digest === 'string') {
    const dirs = resolveOwnedDirs(record.id, record, records, workspaceDoc, workRoot);
    const fresh = hashOwnedDirs(dirs);
    if ((fresh?.digest ?? null) !== evidence.data.codeDigest.digest) return {reason: 'code-digest-mismatch'};
  }
  const capturedAt = isoTime(evidence.data.provenance?.capturedAt);
  if (Number.isFinite(capturedAt)) {
    for (const sourceId of appliesToSources.get(record.id) ?? []) {
      const changeAt = isoTime(records.get(sourceId)?.data?.change?.at);
      if (Number.isFinite(changeAt) && changeAt > capturedAt) return {reason: `appliesTo-newer:${sourceId}`};
    }
  }
  return null;
}

/** `record`'s direct `blockedBy` targets that are not (authored) `done` - the check-example-work.mjs gate
 * already refuses any `blockedBy` on a target that reached `done` without going stale first, so in a tree
 * that passes that gate every present `blockedBy` entry is, by construction, currently unmet; this is
 * computed directly rather than assumed, so a fixture that violates that invariant is still handled. */
function unmetBlockers(record, records, canon = id => id) {
  const edges = Array.isArray(record.data.blockedBy) ? record.data.blockedBy : [];
  return edges.filter(e => isPlainObject(e) && typeof e.record === 'string')
    .filter(e => records.get(canon(e.record))?.state !== 'done');
}

/** authored -> suspended (staleness) -> blocked (unmet blockedBy) -> authored, in that order; see the
 * module doc comment for why staleness is checked first. Records with no authored `state` (branches like
 * work/feature, and work/acceptance-criterion leaves, which the layout never gives a lifecycle state) have
 * no effective state either. */
function effectiveStateOf(record, evidenceByDir, appliesToSources, records, workspaceDoc, workRoot, canon = id => id) {
  if (record.state === null || record.state === undefined) return {state: null, reason: null};
  const stale = staleness(record, evidenceByDir, appliesToSources, records, workspaceDoc, workRoot);
  if (stale) return {state: 'suspended', reason: stale.reason};
  if (unmetBlockers(record, records, canon).length) return {state: 'blocked', reason: null};
  return {state: record.state, reason: null};
}

/**
 * `record`'s `blockedBy` chain, resolved to its roots: a `work/gap`, an open `work/policy-decision`
 * (`outcome: open`), or - the real tree has both - a dead end with no further `blockedBy` of its own that is
 * neither, which is reported as-is rather than forced into a shape it is not (a cluster of ordinary records
 * blocking each other is itself a fact worth seeing, not a gap somebody forgot to write). A cycle (this
 * tree has genuine ones: br.task.single-owner / sds.task.ownership-guard / contract.share.completion-guard-
 * for-task / fr.task.complete all cite each other) stops that branch and is reported with `cyclic: true`
 * rather than recursing forever.
 */
function resolveBlockers(record, records, canon = id => id) {
  const roots = new Map(); // id -> {id, rootKind, because, cyclic}
  const rootKindOf = target => target.schema === 'work/gap' ? 'gap'
    : (target.schema === 'work/policy-decision' && target.data.outcome === 'open') ? 'decision'
    : 'record';

  function walkEdge(rawId, because, visited) {
    const targetId = canon(rawId);
    const target = records.get(targetId);
    if (!target) { record_(targetId, 'missing', because, false); return; }
    if (visited.has(targetId)) { record_(targetId, rootKindOf(target), because, true); return; }
    const nextVisited = new Set(visited); nextVisited.add(targetId);
    const kind = rootKindOf(target);
    const subEdges = Array.isArray(target.data.blockedBy) ? target.data.blockedBy : [];
    if (kind !== 'record' || !subEdges.length) { record_(targetId, kind, because, false); return; }
    for (const sub of subEdges) {
      if (isPlainObject(sub) && typeof sub.record === 'string') walkEdge(sub.record, sub.because ?? because, nextVisited);
    }
  }
  function record_(id, rootKind, because, cyclic) {
    const existing = roots.get(id);
    if (!existing) { roots.set(id, {id, rootKind, because: because ?? null, cyclic}); return; }
    if (cyclic) existing.cyclic = true;
  }

  const topEdges = Array.isArray(record.data.blockedBy) ? record.data.blockedBy : [];
  for (const edge of topEdges) {
    if (isPlainObject(edge) && typeof edge.record === 'string') walkEdge(edge.record, edge.because ?? null, new Set([record.id]));
  }
  return [...roots.values()].sort((a, b) => a.id.localeCompare(b.id));
}

/** The full derivation over one `.starciwork` tree: usedBy/effectiveState/blockers per record, plus the
 * cross-cutting frontier and tally. Pure function of what is on disk right now - no clock, no randomness,
 * so two runs over the same tree always compute byte-identical structures (required for the --write-less
 * gate to mean anything). */
export function computeDerived(workRoot) {
  const {records, evidenceByDir} = readTree(workRoot);
  const {usedBy, unclassified} = buildUsedBy(records);
  const appliesToSources = new Map(); // targetId -> Set(sourceId) via the appliesTo edge kind
  for (const [targetId, byKind] of usedBy) if (byKind.has('appliesTo')) appliesToSources.set(targetId, byKind.get('appliesTo'));
  const workspaceDoc = readWorkspace(workRoot);
  // Compact format: `P#frag` and collapsed bare `ac.*` ids resolve to the record carrying the criterion.
  const inline = indexInlineCriteria(records);
  const canon = ref => resolveRecordRef(records, ref, inline) ?? ref;

  const derivedRecords = new Map();
  for (const record of records.values()) {
    const {state: effectiveState, reason} = effectiveStateOf(record, evidenceByDir, appliesToSources, records, workspaceDoc, workRoot, canon);
    const blockedByEdges = Array.isArray(record.data.blockedBy) ? record.data.blockedBy : [];
    const byKind = usedBy.get(record.id);
    const usedByOut = {};
    if (byKind) for (const kind of EDGE_KIND_ORDER) if (byKind.has(kind)) usedByOut[kind] = [...byKind.get(kind)].sort();
    derivedRecords.set(record.id, {
      id: record.id, schema: record.schema, feature: record.feature, state: record.state,
      effectiveState, suspensionReason: reason, usedBy: usedByOut,
      blockers: blockedByEdges.length ? resolveBlockers(record, records, canon) : [],
    });
  }

  // tally: done/todo/stale/blocked, per feature and overall - only over records the layout gives a
  // lifecycle state to (effectiveState !== null), scoped to actual features (workspace.yaml/brand/index.yaml
  // sit outside any feature and are not "work the lead tallies").
  const blankCounts = () => ({done: 0, todo: 0, stale: 0, blocked: 0, total: 0});
  const overall = blankCounts();
  const byFeature = new Map();
  const bucketOf = state => state === 'done' ? 'done' : state === 'suspended' ? 'stale' : state === 'blocked' ? 'blocked' : state === 'todo' ? 'todo' : null;
  for (const record of derivedRecords.values()) {
    if (!record.feature || record.effectiveState === null) continue;
    const bucket = bucketOf(record.effectiveState);
    if (!bucket) continue;
    overall[bucket]++; overall.total++;
    if (!byFeature.has(record.feature)) byFeature.set(record.feature, blankCounts());
    const featureCounts = byFeature.get(record.feature);
    featureCounts[bucket]++; featureCounts.total++;
  }

  // closedBy is a list of record ids (schemas/work-layout.yaml, concept 7); a bare string is the common
  // one-closer case and is normalised the same way here as scripts/check-example-work.mjs's gate treats it.
  const normalizeClosedBy = v => v == null ? null : Array.isArray(v) ? v : [v];
  const gaps = [...records.values()].filter(r => r.schema === 'work/gap')
    .map(r => ({id: r.id, feature: r.feature, state: r.state, closedBy: normalizeClosedBy(r.data.closedBy)}))
    .sort((a, b) => a.id.localeCompare(b.id));
  const unbuiltModuleGaps = gaps.filter(g => g.id.endsWith('.unbuilt-module') && g.state === 'todo').length;

  const frontier = [...derivedRecords.values()]
    .filter(r => r.state === 'todo' && unmetBlockers(records.get(r.id), records, canon).length === 0)
    .map(r => ({id: r.id, feature: r.feature, title: records.get(r.id).data.title ?? null}))
    .sort((a, b) => (a.feature ?? '').localeCompare(b.feature ?? '') || a.id.localeCompare(b.id));

  return {
    records: derivedRecords,
    tally: {
      overall,
      byFeature: new Map([...byFeature.entries()].sort(([a], [b]) => a.localeCompare(b))),
      gaps, unbuiltModuleGaps,
    },
    frontier,
    unclassified,
  };
}

/** The plain JS structure written to `_derived/index.yaml` - built from `computeDerived`'s output with every
 * collection already in its final deterministic order, so `stringifyYaml` need not (and does not) reorder
 * anything itself. */
export function buildYamlDocument(derived) {
  const recordIds = [...derived.records.keys()].sort();
  const records = {};
  for (const id of recordIds) {
    const r = derived.records.get(id);
    const out = {schema: r.schema, feature: r.feature, state: r.state, effectiveState: r.effectiveState};
    if (r.suspensionReason) out.suspensionReason = r.suspensionReason;
    if (Object.keys(r.usedBy).length) out.usedBy = r.usedBy;
    if (r.blockers.length) out.blockers = r.blockers.map(b => ({id: b.id, rootKind: b.rootKind, cyclic: b.cyclic, because: b.because}));
    records[id] = out;
  }
  return {
    schema: 'work/derived@1',
    records,
    tally: {
      overall: derived.tally.overall,
      byFeature: Object.fromEntries(derived.tally.byFeature),
      gaps: derived.tally.gaps,
      unbuiltModuleGaps: derived.tally.unbuiltModuleGaps,
    },
    frontier: derived.frontier,
    unclassifiedEdges: derived.unclassified,
  };
}

export function buildFrontierMarkdown(derived) {
  const t = derived.tally.overall;
  const lines = [
    '# Frontier',
    '',
    'GENERATED by `node scripts/example-derive.mjs --write` - do not edit by hand.',
    '',
    `Overall: ${t.done} done, ${t.todo} todo, ${t.stale} stale, ${t.blocked} blocked (${t.total} record(s) with a lifecycle state).`,
    `Open unbuilt-module gaps: ${derived.tally.unbuiltModuleGaps}.`,
    '',
  ];
  const byFeature = new Map();
  for (const item of derived.frontier) {
    const key = item.feature ?? '(none)';
    if (!byFeature.has(key)) byFeature.set(key, []);
    byFeature.get(key).push(item);
  }
  const features = [...new Set([...derived.tally.byFeature.keys(), ...byFeature.keys()])].sort();
  for (const feature of features) {
    lines.push(`## ${feature}`);
    const items = byFeature.get(feature) ?? [];
    if (!items.length) lines.push('(none)');
    else for (const item of items) lines.push(`- ${item.id}${item.title ? ` — ${item.title}` : ''}`);
    lines.push('');
  }
  return lines.join('\n');
}

const DERIVED_INDEX_REL = `${DERIVED_DIR_NAME}/index.yaml`;
const DERIVED_FRONTIER_REL = `${DERIVED_DIR_NAME}/frontier.md`;

/**
 * The one call a caller (this file's CLI, or scripts/check-example-derived.mjs) needs: compute the tree,
 * and either write it (returns {wrote:true}) or compare it against what is on disk (returns {ok, diff}).
 * Comparison is structural (canonicalJSON of the parsed YAML, not the file's bytes), so it is not fooled by
 * whitespace the YAML library might legitimately choose differently across versions - it is fooled by
 * nothing else, because computeDerived is a pure function of the tree.
 */
export function runDerive(workRoot, {write} = {}) {
  const derived = computeDerived(workRoot);
  const doc = buildYamlDocument(derived);
  const derivedDir = path.join(workRoot, DERIVED_DIR_NAME);
  const indexPath = path.join(workRoot, DERIVED_INDEX_REL);
  const frontierPath = path.join(workRoot, DERIVED_FRONTIER_REL);
  if (write) {
    fs.mkdirSync(derivedDir, {recursive: true});
    fs.writeFileSync(indexPath, HEADER + stringifyYaml(doc), 'utf8');
    fs.writeFileSync(frontierPath, buildFrontierMarkdown(derived), 'utf8');
    return {wrote: true, derived, doc};
  }
  let onDisk = null;
  try { onDisk = parseYaml(fs.readFileSync(indexPath, 'utf8')); } catch { onDisk = null; }
  const ok = onDisk !== null && canonicalJSON(onDisk) === canonicalJSON(doc);
  return {ok, derived, doc, onDisk};
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const args = process.argv.slice(2);
  const workFlagIndex = args.indexOf('--work');
  const workArg = workFlagIndex >= 0 ? args[workFlagIndex + 1] : null;
  const write = args.includes('--write');
  if (!workArg) {
    console.error('Usage: node scripts/example-derive.mjs --work <path-to-.starciwork> [--write]');
    process.exitCode = 2;
  } else {
    const workRoot = path.resolve(workArg);
    const result = runDerive(workRoot, {write});
    const t = result.derived.tally.overall;
    console.log(`${t.total} record(s) with a lifecycle state: ${t.done} done, ${t.todo} todo, ${t.stale} stale, ${t.blocked} blocked; ${result.derived.tally.gaps.length} gap(s) (${result.derived.tally.unbuiltModuleGaps} open unbuilt-module); ${result.derived.frontier.length} in the frontier.`);
    if (write) {
      console.log(`wrote ${path.relative(workRoot, path.join(workRoot, DERIVED_INDEX_REL))} and ${path.relative(workRoot, path.join(workRoot, DERIVED_FRONTIER_REL))}`);
    } else if (!result.ok) {
      console.log(`REFUSED: ${DERIVED_INDEX_REL} is missing or stale; run with --write to refresh it.`);
      process.exitCode = 1;
    }
  }
}
