// contract.mjs - HFS_CONTRACT_SNAPSHOT_DRIFT (R23): the contract is committed and the front-end copy equals the back end's.
//   back end   a repository with a GraphQL transport commits `contracts/<app>/schema.graphql` for each api app, and an api app with
//              an operation table commits `contracts/<app>/openapi.json`
//   front end  every `apps/<app>/src/modules/api/contract/<be-app>.{graphql,json}` is hash-equal to the sibling back end's
//              `contracts/<be-app>/schema.graphql` (openapi.json for .json); hfs.json `stacks` names the sibling
//              repository, and a sibling that is not checked out is reported (info), not compared
// The snapshots are generated by `npm run contract:emit` (`hfs emit-contracts`, packages/hfs/emit/contracts.mjs): printSchema of the
// resolvers the app root composes, and the OpenAPI 3.1 document of the typed operation table `apps/<app>/src/operations.ts`.
// That the committed snapshot equals what the app emits now is contractEmitFindings (full pass only, never --fast): it emits every
// api app into a temp directory through the injected `emit` (packages/hfs/emit) and compares hashes; an emit that cannot run is a finding.
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { found } from './read.mjs';

export const CONTRACT_SNAPSHOT_DRIFT = 'HFS_CONTRACT_SNAPSHOT_DRIFT';
export const GRAPHQL_TRANSPORT_SLOT = 'be.transport.graphql';
const COPY = /^apps\/([^/]+)\/src\/modules\/api\/contract\/([^/]+)\.(graphql|json)$/;
const SNAPSHOT_OF = { graphql: 'schema.graphql', json: 'openapi.json' };

/** sha256 of a file's text with line endings folded, or null when it cannot be read. */
export function contractHash(file) {
  try { return createHash('sha256').update(fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n')).digest('hex'); } catch { return null; }
}

/** The findings of R23 for the repository at `repoRoot`. `stacks` is hfs.json's sibling back-end path (front end only). */
export function contractFindings({ repoRoot, files, repo, resolver, stacks }) {
  const findings = [];
  if (repo.profile === 'be') {
    const serves = files.some((file) => resolver.classifyPath(file).slot === GRAPHQL_TRANSPORT_SLOT);
    const tracked = new Set(files);
    for (const app of repo.apps.filter((a) => a.kind === 'api')) {
      const operations = `contracts/${app.name}/${SNAPSHOT_OF.json}`;
      if (tracked.has(`apps/${app.name}/src/operations.ts`) && !tracked.has(operations)) findings.push(found(CONTRACT_SNAPSHOT_DRIFT, operations, `${app.name} declares an operation table (apps/${app.name}/src/operations.ts) but ${operations} is not committed; declare be.contract.openapi in hfs.json optionalSlots, run \`npm run contract:emit\` and commit the snapshot`, { app: app.name }));
      if (!serves) continue;
      const snapshot = `contracts/${app.name}/${SNAPSHOT_OF.graphql}`;
      if (!tracked.has(snapshot)) findings.push(found(CONTRACT_SNAPSHOT_DRIFT, snapshot, `${app.name} serves GraphQL but ${snapshot} is not committed; declare be.contract.graphql in hfs.json optionalSlots, run \`npm run contract:emit\` and commit the snapshot`, { app: app.name }));
    }
    return findings;
  }
  for (const file of files) {
    const match = COPY.exec(file);
    if (!match) continue;
    const [, app, beApp, ext] = match;
    if (!stacks) {
      findings.push(found(CONTRACT_SNAPSHOT_DRIFT, file, `${file} is a contract copy but hfs.json names no sibling back end (stacks), so it cannot be compared with the back end's snapshot`, { app }));
      continue;
    }
    const sibling = path.resolve(repoRoot, stacks);
    if (!fs.existsSync(sibling)) {
      findings.push(found(CONTRACT_SNAPSHOT_DRIFT, file, `${file} was not compared: the sibling back end ${stacks} is not checked out here`, { app, level: 'info' }));
      continue;
    }
    const snapshot = `contracts/${beApp}/${SNAPSHOT_OF[ext]}`;
    const theirs = contractHash(path.join(sibling, snapshot));
    if (theirs === null) {
      findings.push(found(CONTRACT_SNAPSHOT_DRIFT, file, `${stacks}/${snapshot} does not exist, so ${file} copies nothing; the back end commits its contract first`, { app, snapshot }));
      continue;
    }
    const ours = contractHash(path.join(repoRoot, file));
    if (ours !== theirs) findings.push(found(CONTRACT_SNAPSHOT_DRIFT, file, `${file} (${String(ours).slice(0, 12)}) differs from ${stacks}/${snapshot} (${theirs.slice(0, 12)}); run \`npm run contract:pull\``, { app, snapshot }));
  }
  return findings;
}

/** The first lines of an error, enough to act on. */
const errorText = (error) => String(error?.message ?? error).split(/\r?\n/).filter(Boolean).slice(0, 4).join(' | ');

/**
 * R23, full pass: each committed `contracts/<app>/schema.graphql` and `contracts/<app>/openapi.json` equals what `emit` writes for
 * the app now. `emit({ repoRoot, declaration, outDir })` is `emitContracts` of packages/hfs/emit and answers `{ written, skipped }`;
 * it is injected because the runtime scripts do not import the hfs package. Every api app is emitted on its own into a temp
 * directory, so one app that cannot emit does not hide the others; an uncommitted snapshot is contractFindings' finding. Answers
 * `{ findings, apps }`, `apps` being what was judged: `[{ app, artifact, status }]`, `artifact` being `schema.graphql` or
 * `openapi.json` and `status` one of `fresh`, `stale`, `not-committed`, `none` (nothing emitted, nothing committed; GraphQL only),
 * `left-behind` (committed, nothing emitted) or `emit-failed`.
 */
export function contractEmitFindings({ repoRoot, files, repo, emit }) {
  const findings = [];
  const apps = [];
  if (repo.profile !== 'be') return { findings, apps };
  const tracked = new Set(files);
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'hfs-contracts-'));
  try {
    for (const app of repo.apps.filter((a) => a.kind === 'api')) {
      const artifacts = [{ artifact: SNAPSHOT_OF.graphql, what: 'serves no GraphQL any more' }, { artifact: SNAPSHOT_OF.json, what: 'declares no operations any more' }];
      let emitted;
      try {
        emitted = emit({ repoRoot, declaration: { apps: [app] }, outDir: scratch });
      } catch (error) {
        for (const { artifact } of artifacts) apps.push({ app: app.name, artifact, status: 'emit-failed' });
        const snapshot = `contracts/${app.name}/${SNAPSHOT_OF.graphql}`;
        findings.push(found(CONTRACT_SNAPSHOT_DRIFT, snapshot, `contracts/${app.name} cannot be verified: \`hfs emit-contracts\` failed for ${app.name}: ${errorText(error)}`, { app: app.name, reason: 'emit-failed' }));
        continue;
      }
      for (const { artifact, what } of artifacts) {
        const snapshot = `contracts/${app.name}/${artifact}`;
        const committed = tracked.has(snapshot) ? contractHash(path.join(repoRoot, snapshot)) : null;
        if (!emitted.written.includes(snapshot)) {
          if (committed === null) {
            if (artifact === SNAPSHOT_OF.graphql) apps.push({ app: app.name, artifact, status: 'none' });
            continue;
          }
          apps.push({ app: app.name, artifact, status: 'left-behind' });
          findings.push(found(CONTRACT_SNAPSHOT_DRIFT, snapshot, `${snapshot} is committed but ${app.name} ${what}; delete it`, { app: app.name, reason: 'left-behind' }));
          continue;
        }
        const fresh = contractHash(path.join(scratch, snapshot));
        if (committed === null) {
          // the uncommitted snapshot itself is reported by contractFindings above; here it only counts as not judged
          apps.push({ app: app.name, artifact, status: 'not-committed' });
        } else if (committed === fresh) {
          apps.push({ app: app.name, artifact, status: 'fresh' });
        } else {
          apps.push({ app: app.name, artifact, status: 'stale' });
          findings.push(found(CONTRACT_SNAPSHOT_DRIFT, snapshot, `${snapshot} (${committed.slice(0, 12)}) differs from what ${app.name} emits now (${String(fresh).slice(0, 12)}); run \`npm run contract:emit\` and commit the result`, { app: app.name, reason: 'stale' }));
        }
      }
    }
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
  return { findings, apps };
}
