#!/usr/bin/env node
// tunnel.mjs — keeps one cloudflared tunnel pointed at the ask gateway
// (scripts/connectors/ask-gateway.mjs) and records the public base URL the
// Telegram notifier links to (docs/connectors.md).
//
//   node scripts/connectors/tunnel.mjs start       launch the manager detached
//   node scripts/connectors/tunnel.mjs run         run the manager in the foreground
//   node scripts/connectors/tunnel.mjs status | stop
//   node scripts/connectors/tunnel.mjs dry-run     print the cloudflared command and the generated config
//
// Mode (config.yaml connectors.cloudflare.mode):
//   quick — `cloudflared tunnel --url http://127.0.0.1:<port>`: a random
//           https://*.trycloudflare.com host parsed from cloudflared's output.
//   named — `tunnel` + `credentialsFile`: the manager writes its OWN config
//           (tunnel, credentials-file, ingress hostname -> gateway, then
//           http_status:404) and runs `cloudflared tunnel --config <it> run <id>`;
//           or a remotely managed tunnel token from `tokenEnv`, passed to
//           cloudflared as TUNNEL_TOKEN in its environment, never on argv.
// cloudflared is always given an explicit --config under the StarCi state
// directory, so ~/.cloudflared/config.yml (which may belong to another tunnel)
// is never read.
//
// The manager restarts cloudflared when it dies (backoff 1s doubling to 60s,
// reset after 5 minutes of uptime) and keeps state in
// <state>/connectors/tunnel.json. STARCI_CLOUDFLARED_COMMAND and
// STARCI_CLOUDFLARED_ARGS (a JSON list of prefix args) replace the binary for
// tests, the way STARCI_ORCA_COMMAND does for Orca; STARCI_TUNNEL_BACKOFF_MS
// sets the first restart delay.
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { connectorEnv, connectorSecret, connectorsConfig } from '../../engine/config.mjs';
import { argsOf, claimManager, lockHolder, ownerConfig, pidAlive, readJson, recordAlive, spawnDetached, stateFile, writeJson } from './lib.mjs';

const QUICK_URL = /https:\/\/(?!api\.)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.trycloudflare\.com\b/i;
const CONNECTED = /Registered tunnel connection|Connection [0-9a-f-]+ registered/i;
const LOG_CAP = 5 * 1024 * 1024;

/** The public https://*.trycloudflare.com URL a quick tunnel printed, or null. */
export const parseQuickTunnelUrl = (text) => String(text ?? '').match(QUICK_URL)?.[0]?.toLowerCase() ?? null;
/** Whether cloudflared output reports a registered edge connection. */
export const parseConnected = (text) => CONNECTED.test(String(text ?? ''));

export const tunnelStateFile = (env = process.env) => stateFile('tunnel.json', env);
export const tunnelState = (env = process.env) => readJson(tunnelStateFile(env));

/**
 * The public base the notifier may link to: only while the manager is alive and cloudflared has
 * reported its URL (quick) or a registered connection (named).
 */
export function publicBase(env = process.env) {
  const s = tunnelState(env);
  if (!recordAlive(s) || !s.baseUrl || !s.connected) return null;
  return s.baseUrl;
}

const yamlString = (value) => JSON.stringify(String(value));

/** The config file cloudflared runs with — never the user's default ~/.cloudflared/config.yml. */
export function cloudflaredConfigText(cf, port) {
  const lines = ['# Generated by StarCi scripts/connectors/tunnel.mjs; rewritten on every start.', 'no-autoupdate: true'];
  if (cf.mode === 'named' && cf.auth === 'credentials-file') {
    lines.push(`tunnel: ${yamlString(cf.tunnel)}`, `credentials-file: ${yamlString(cf.credentialsFile)}`, 'ingress:',
      `  - hostname: ${yamlString(cf.hostname)}`, `    service: ${yamlString(`http://127.0.0.1:${port}`)}`, '  - service: http_status:404');
  }
  return `${lines.join('\n')}\n`;
}

/**
 * The cloudflared invocation for a normalized connectors.cloudflare block: {command, args, env, configText}.
 * `env` carries TUNNEL_TOKEN only in token mode; callers never print it.
 */
export function cloudflaredPlan(cf, { port, configFile, env = process.env, secretEnv = env } = {}) {
  const command = env.STARCI_CLOUDFLARED_COMMAND || 'cloudflared';
  let prefix = [];
  try { prefix = JSON.parse(env.STARCI_CLOUDFLARED_ARGS || '[]'); } catch { prefix = []; }
  const base = ['tunnel', '--config', configFile, '--no-autoupdate'];
  const childEnv = { ...env };
  delete childEnv.TUNNEL_TOKEN;
  let args;
  if (cf.mode === 'quick') args = [...base, '--url', `http://127.0.0.1:${port}`];
  else if (cf.mode === 'named' && cf.auth === 'credentials-file') args = [...base, 'run', cf.tunnel];
  else if (cf.mode === 'named') {
    const token = connectorSecret(cf.tokenEnv, secretEnv);
    if (!token) throw Error(`cloudflare.mode named needs the tunnel token in ${cf.tokenEnv} (or ${cf.tokenEnv}_FILE), or tunnel + credentialsFile`);
    childEnv.TUNNEL_TOKEN = token;
    args = [...base, 'run'];
  } else throw Error(`cloudflare.mode ${cf.mode}: no tunnel to run`);
  return { command, args: [...prefix, ...args], env: childEnv, configText: cloudflaredConfigText(cf, port) };
}

const appendLog = (file, text) => {
  try {
    if (fs.existsSync(file) && fs.statSync(file).size > LOG_CAP) fs.renameSync(file, `${file}.1`);
    fs.appendFileSync(file, text);
  } catch { /* logging is best effort */ }
};

/** Run and keep alive cloudflared per `cf`. Resolves never; `stop()` on the returned handle ends it. */
export function superviseTunnel(cf, { port, env = process.env, secretEnv = env, onState = () => {} } = {}) {
  const configFile = stateFile('cloudflared.yml', env), logFile = stateFile('cloudflared.log', env), file = tunnelStateFile(env);
  const plan = cloudflaredPlan(cf, { port, configFile, env, secretEnv });
  fs.mkdirSync(path.dirname(configFile), { recursive: true });
  fs.writeFileSync(configFile, plan.configText);
  const firstBackoff = Number(env.STARCI_TUNNEL_BACKOFF_MS ?? 1000);
  const state = {
    schema: 'starci/connector-tunnel@1', pid: process.pid, mode: cf.mode, auth: cf.auth ?? null, tunnel: cf.tunnel ?? null,
    hostname: cf.hostname ?? null, gatewayPort: port, childPid: null, baseUrl: cf.mode === 'named' ? `https://${cf.hostname}` : null,
    connected: false, access: cf.access === true, restarts: 0, lastExit: null, startedAt: new Date().toISOString(), updatedAt: null,
  };
  const save = () => { state.updatedAt = new Date().toISOString(); writeJson(file, state); onState({ ...state }); };
  let child = null, stopped = false, backoff = firstBackoff, timer = null;
  const launch = () => {
    if (stopped) return;
    const startedAt = Date.now();
    if (cf.mode === 'quick') state.baseUrl = null;
    state.connected = false;
    child = spawn(plan.command, plan.args, { env: plan.env, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true });
    state.childPid = child.pid ?? null; save();
    const onData = (chunk) => {
      const text = chunk.toString();
      appendLog(logFile, text);
      let changed = false;
      if (cf.mode === 'quick' && !state.baseUrl) { const url = parseQuickTunnelUrl(text); if (url) { state.baseUrl = url; changed = true; } }
      if (!state.connected && parseConnected(text)) { state.connected = true; changed = true; }
      if (changed) save();
    };
    child.stdout.on('data', onData); child.stderr.on('data', onData);
    const exited = (code, signal) => {
      if (!child) return;
      child = null;
      state.childPid = null; state.connected = false;
      state.lastExit = { code: code ?? null, signal: signal ?? null, at: new Date().toISOString() };
      if (stopped) { save(); return; }
      if (Date.now() - startedAt > 5 * 60 * 1000) backoff = firstBackoff;
      state.restarts += 1; save();
      timer = setTimeout(launch, backoff);
      backoff = Math.min(backoff * 2, 60000);
    };
    child.on('exit', exited);
    child.on('error', (error) => { appendLog(logFile, `spawn error: ${error.message}\n`); exited(null, null); });
  };
  launch();
  return {
    state: () => ({ ...state }),
    stop() {
      stopped = true; clearTimeout(timer);
      const running = child; child = null;
      if (running) { try { running.kill(); } catch { /* gone */ } }
      state.childPid = null; state.connected = false; state.stoppedAt = new Date().toISOString(); save();
    },
  };
}

/**
 * The one tunnel manager for this host. `start` may be called by every serve-ask at once, and each
 * call used to launch its own manager before the first wrote tunnel.json (nine managers, nine
 * cloudflared). A manager now claims <state>/tunnel.lock first and refuses while another live
 * manager holds the lock or owns tunnel.json: {ok:false, holder}. Otherwise it supervises
 * cloudflared and returns {ok:true, handle, release}.
 */
export function runManager(cf, { port, env = process.env, secretEnv = env } = {}) {
  const claim = claimManager('tunnel', { current: tunnelState(env), env });
  if (!claim.ok) return { ok: false, holder: claim.holder ?? null };
  try {
    return { ok: true, handle: superviseTunnel(cf, { port, env, secretEnv }), release: claim.release };
  } catch (error) { claim.release(); throw error; }
}

/** A live manager: the one tunnel.json names, or the holder of the manager lock (one still starting). */
export const managerAlive = (env = process.env) => {
  const state = tunnelState(env);
  return recordAlive(state) ? state : lockHolder('tunnel', env);
};

const loadCloudflare = () => {
  const config = ownerConfig();
  if (!config) throw Error('config.yaml cannot be read');
  return { config, connectors: connectorsConfig(config), secretEnv: connectorEnv(config) };
};

function main() {
  const args = argsOf(process.argv.slice(2));
  const verb = args._[0] ?? 'status';
  const state = tunnelState();
  const out = (value) => console.log(JSON.stringify(value));
  if (verb === 'status') { out({ ok: true, running: Boolean(managerAlive()), publicBase: publicBase(), ...(state ?? {}) }); return; }
  if (verb === 'stop') {
    for (const pid of [state?.pid, state?.childPid]) if (pid && pidAlive(pid)) { try { process.kill(pid); } catch { /* gone */ } }
    out({ ok: true, stopped: state?.pid ?? null }); return;
  }
  let loaded;
  try { loaded = loadCloudflare(); } catch (error) { out({ ok: false, error: error.message }); process.exit(2); }
  const { connectors, secretEnv } = loaded, cf = connectors.cloudflare, port = Number(args.port ?? connectors.gateway.port);
  if (cf.mode === 'off') { out({ ok: false, error: 'connectors.cloudflare.mode is off in config.yaml' }); process.exit(2); }
  if (cf.auth === 'credentials-file' && !cf.credentialsPresent) { out({ ok: false, error: `cloudflare.credentialsFile ${cf.credentialsFile} does not exist` }); process.exit(2); }
  for (const warning of connectors.warnings) console.error(`warning: ${warning}`);
  if (verb === 'dry-run') {
    try {
      const plan = cloudflaredPlan(cf, { port, configFile: stateFile('cloudflared.yml'), secretEnv });
      out({ ok: true, command: plan.command, args: plan.args, tokenInEnv: Boolean(plan.env.TUNNEL_TOKEN), config: plan.configText });
    } catch (error) { out({ ok: false, error: error.message }); process.exit(2); }
    return;
  }
  if (verb === 'start') {
    const live = managerAlive();
    if (live) { out({ ok: true, already: true, pid: live.pid, publicBase: publicBase() }); return; }
    try { cloudflaredPlan(cf, { port, configFile: stateFile('cloudflared.yml'), secretEnv }); } catch (error) { out({ ok: false, error: error.message }); process.exit(2); }
    const pid = spawnDetached(fileURLToPath(import.meta.url), ['run', '--port', String(port)]);
    out({ ok: true, launched: pid, mode: cf.mode, hostname: cf.hostname, state: tunnelStateFile() }); return;
  }
  if (verb === 'run') {
    let managed;
    try { managed = runManager(cf, { port, secretEnv }); } catch (error) { out({ ok: false, error: error.message }); process.exit(2); }
    if (!managed.ok) { out({ ok: false, already: true, error: 'another tunnel manager owns the tunnel state', pid: managed.holder?.pid ?? null }); process.exit(1); }
    const stop = () => { managed.handle.stop(); managed.release(); process.exit(0); };
    process.on('SIGINT', stop); process.on('SIGTERM', stop); process.on('exit', managed.release);
    return;
  }
  console.error('usage: tunnel.mjs start|run|status|stop|dry-run [--port <n>]'); process.exit(2);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
