// Compatibility reader for pre-upstream leaves. New authoring uses sds-map.mjs.
import { validateTypedBindings } from './srs-v3.mjs';
export const SDS_V4_SCHEMA = 'starci/sds@4';
const text = value => typeof value === 'string' && value.trim().length > 0;
const object = value => value !== null && typeof value === 'object' && !Array.isArray(value);
const exact = (value, fields, at, errors) => { if (!object(value)) { errors.push(`${at}: object required`); return false; } for (const f of fields) if (!Object.hasOwn(value,f)) errors.push(`${at}: missing ${f}`); for (const f of Object.keys(value)) if (!fields.includes(f)) errors.push(`${at}: unexpected ${f}`); return true; };
const texts = (v,at,e,required=true) => { if (!Array.isArray(v)||(required&&!v.length)||v.some(x=>!text(x))) e.push(`${at}: ${required?'nonempty ':''}text array required`); };
const unique = (v,at,e) => { const seen=new Set(); for(const x of v??[]){if(!text(x?.id)||seen.has(x.id)||x.id.includes('#'))e.push(`${at}: stable unique id required`);seen.add(x?.id);} };
const common=['schema','op','status','id','nodeType','name','summary','refs','content'];
const refTypes=new Set(['functional-requirement','non-functional-requirement','business-rule','business-data','customer-journey','acceptance','branch','srs-flow','overview','flow','code-unit','contract','data','quality','deployment','decision','verification','legacy-code-unit','legacy-contract','legacy-data']);
const safePath=x=>text(x)&&!x.startsWith('/')&&!/^[A-Za-z]:|[\\\x00-\x1f]/.test(x)&&x.split('/').every(p=>p&&p!=='.'&&p!=='..');
const fields={
 overview:['designGoals','scope','actors','externalSystems','constraints','businessRefs','strategy','selectedTopologyRef','mapGuide','diagram'],
 flow:['goal','businessRefs','entryPoint','preconditions','inputs','participants','mainSequence','alternativeSequences','exceptionSequences','recovery','postconditions','resultMapping','topologyRefs','verificationRefs'],
 'code-unit':['layer','responsibility','boundaries','owner','repository','file','symbol','signature','inputs','outputs','existence','currentObservation','sourceObservation','plannedChanges','callers','callees','dependencies','providedInterfaces','consumedInterfaces','enforcement','contractRefs','dataRefs','flowRefs','qualityRefs','testRefs'],
 contract:['owner','callerRef','receiverRef','interaction','endpoint','requestSchema','responseSchema','validation','errors','errorMapping','authentication','authorization','resourceScope','correlation','idempotency','ordering','timeout','retry','cancellation','outcomeLookup','version','compatibility'],
 data:['businessDataRefs','storage','modelCodeRefs','fields','relationships','constraints','indexes','migration','authority','writeOwnerRef','readerRefs','repositoryRefs','transaction','consistency','concurrency','isolation','classification','lifecycle','recovery'],
 quality:['category','nfrRefs','mechanism','codeRefs','flowRefs','conditions','expectedResult','measurement','target','tradeoffs','limitations'],
 deployment:['topology','selected','placements','connections','dataOwnership','backgroundWork','failureDomains','correlation','configuration','rollout','rollback'],
 decision:['problem','drivers','options','choice','rationale','tradeoffs','status','decisionOwner','revisitWhen','affectedRefs'],
 verification:['businessRefs','flowRefs','branchRefs','codeUnitRefs','nfrRefs','tests','fixtures','actorAuthority','preconditions','actions','faults','expectedData','expectedEffects','expectedResponse','expectedAppState','forbiddenChanges','measurements']
};

export function validateSDSV4(spec){
 const errors=[]; if(!exact(spec,common,'SDS',errors))return {ok:false,errors};
 if(spec.schema!==SDS_V4_SCHEMA)errors.push('SDS.schema: expected starci/sds@4'); if(spec.op!=='architecture.decide')errors.push('SDS.op: expected architecture.decide'); if(!['draft','blocked','pass'].includes(spec.status))errors.push('SDS.status: unsupported value');
 if(!text(spec.id)||spec.id.includes('#')||!text(spec.name)||!text(spec.summary))errors.push('SDS: stable id, name and summary required'); if(!fields[spec.nodeType])errors.push('SDS.nodeType: unsupported value');
 if(!Array.isArray(spec.refs))errors.push('SDS.refs: array required'); for(const [i,r] of (spec.refs??[]).entries())if(!exact(r,['type','nodeId','itemId'],`SDS.refs[${i}]`,errors)||!refTypes.has(r.type)||!text(r.nodeId)||!text(r.itemId))errors.push(`SDS.refs[${i}]: supported typed reference required`);
 if(!fields[spec.nodeType]||!exact(spec.content,fields[spec.nodeType],`${spec.id}.content`,errors))return {ok:errors.length===0,errors}; const c=spec.content;
 if(spec.nodeType==='overview')overview(c,errors); if(spec.nodeType==='flow')flow(spec,c,errors); if(spec.nodeType==='code-unit')codeUnit(c,errors); if(spec.nodeType==='contract')contract(c,errors); if(spec.nodeType==='data')data(c,errors); if(spec.nodeType==='quality')quality(c,errors); if(spec.nodeType==='deployment')deployment(c,errors); if(spec.nodeType==='decision')decision(c,errors); if(spec.nodeType==='verification')verification(c,errors);
 if(spec.status==='pass'&&spec.nodeType==='quality'&&c.target.status==='undecided')errors.push('quality: undecided target cannot pass');
 if(spec.status==='pass'&&spec.nodeType==='decision'&&c.status!=='accepted')errors.push('decision: passing SDS requires accepted decision');
 if(spec.nodeType==='flow'){const ids=[...c.alternativeSequences,...c.exceptionSequences].map(x=>x.id);if(new Set(ids).size!==ids.length)errors.push('flow: branch ids must be unique across alternative and exception sequences');}
 if(spec.nodeType==='code-unit'&&c.existence==='existing'&&(!safePath(c.sourceObservation?.path)||c.sourceObservation?.repository!==c.repository||c.sourceObservation?.path!==c.file||c.sourceObservation?.symbol!==c.symbol))errors.push('code-unit: source observation must match target repository/file/symbol');
 if(spec.nodeType==='verification')for(const t of c.tests)if(!safePath(t.file))errors.push('verification.test.file: normalized repository-relative path required');
 return {ok:errors.length===0,errors};
}
function overview(c,e){for(const k of ['designGoals','scope','actors','externalSystems','constraints','businessRefs','strategy','mapGuide'])texts(c[k],`overview.${k}`,e);if(!text(c.selectedTopologyRef)||!text(c.diagram))e.push('overview: selected topology and connected diagram required');}
function flow(spec,c,e){
 if(!text(c.goal)||!object(c.entryPoint)||!['ui','api','webhook','event','schedule','job'].includes(c.entryPoint.kind)||![c.entryPoint.description,c.entryPoint.codeUnitRef].every(text))e.push('flow: goal and concrete entry point required');
 for(const k of ['businessRefs','preconditions','inputs','participants','recovery','postconditions','resultMapping','topologyRefs','verificationRefs'])texts(c[k],`flow.${k}`,e);
 sequence(c.mainSequence,'flow.mainSequence',e); unique(c.mainSequence,'flow.mainSequence',e); const main=new Set(c.mainSequence?.map(x=>x.id));
 for(const key of ['alternativeSequences','exceptionSequences']){if(!Array.isArray(c[key]))e.push(`flow.${key}: array required`);for(const b of c[key]??[]){if(!exact(b,['id','fromStep','condition','steps','resumeAt','end','postconditions'],key,e))continue;if(!main.has(b.fromStep)||!(b.resumeAt==='end'||main.has(b.resumeAt))||!text(b.condition)||!text(b.end))e.push(`${b.id}: branch location/resume/end required`);sequence(b.steps,b.id,e);texts(b.postconditions,`${b.id}.postconditions`,e);}}
}
function sequence(rows,at,e){if(!Array.isArray(rows)||!rows.length){e.push(`${at}: ordered steps required`);return;}for(const s of rows){if(!exact(s,['id','codeUnitRef','callerRef','input','validation','authorization','state','transaction','call','effect','output','failure','verificationRefs'],at,e))continue;for(const k of ['id','codeUnitRef','callerRef','input','validation','authorization','state','transaction','call','effect','output','failure'])if(!text(s[k]))e.push(`${s.id}.${k}: explicit or not-applicable rationale required`);texts(s.verificationRefs,`${s.id}.verificationRefs`,e);}}
function codeUnit(c,e){if(!['frontend','backend','shared'].includes(c.layer)||!['existing','planned'].includes(c.existence))e.push('code-unit: layer and existing/planned status required');for(const k of ['responsibility','boundaries','owner','repository','file','symbol','signature','currentObservation'])if(!text(c[k]))e.push(`code-unit.${k}: text required`);if(!safePath(c.file))e.push('code-unit.file: normalized repository-relative path required');for(const k of ['inputs','outputs','plannedChanges','callers','callees','dependencies','providedInterfaces','consumedInterfaces','contractRefs','dataRefs','flowRefs','qualityRefs','testRefs'])texts(c[k],`code-unit.${k}`,e,false);if(c.existence==='planned'&&(!c.plannedChanges.length||c.sourceObservation!==null))e.push('code-unit: planned unit needs plannedChanges and null sourceObservation');if(c.existence==='existing'){if(!exact(c.sourceObservation,['repository','path','symbol','revision','observation'],'code-unit.sourceObservation',e)||![c.sourceObservation?.repository,c.sourceObservation?.path,c.sourceObservation?.symbol,c.sourceObservation?.observation].every(text)||!/^[a-f0-9]{40}$|^[a-f0-9]{64}$/.test(c.sourceObservation?.revision??''))e.push('code-unit: existing unit needs exact observed repository/path/symbol/revision');}if(!exact(c.enforcement,['validation','authorization','stateVersion','transaction','errorMapping'],'code-unit.enforcement',e)||Object.values(c.enforcement??{}).some(x=>!text(x)))e.push('code-unit.enforcement: each boundary needs a location or not-applicable rationale');}
function contract(c,e){for(const k of ['owner','callerRef','receiverRef','interaction','endpoint','requestSchema','responseSchema','validation','errorMapping','authentication','authorization','resourceScope','correlation','idempotency','ordering','timeout','retry','cancellation','outcomeLookup','version','compatibility'])if(!text(c[k]))e.push(`contract.${k}: text required`);texts(c.errors,'contract.errors',e);}
function data(c,e){for(const k of ['storage','migration','authority','writeOwnerRef','transaction','consistency','concurrency','isolation','classification','lifecycle','recovery'])if(!text(c[k]))e.push(`data.${k}: text required`);for(const k of ['businessDataRefs','modelCodeRefs','fields','relationships','constraints','indexes','readerRefs','repositoryRefs'])texts(c[k],`data.${k}`,e,k==='fields');}
function quality(c,e){if(!['security','performance','reliability'].includes(c.category))e.push('quality.category: unsupported');for(const k of ['mechanism','conditions','expectedResult','measurement','tradeoffs','limitations'])if(!text(c[k]))e.push(`quality.${k}: text required`);for(const k of ['nfrRefs','codeRefs','flowRefs'])texts(c[k],`quality.${k}`,e);if(!exact(c.target,['status','value','decisionOwner','missingDecision'],'quality.target',e)||!['decided','undecided'].includes(c.target?.status))e.push('quality.target: decided/undecided required');if(c.target?.status==='decided'&&!text(c.target.value))e.push('quality.target: decided target requires a nonempty value');if(c.target?.status==='undecided'&&(!text(c.target.decisionOwner)||!text(c.target.missingDecision)))e.push('quality.target: missing decision and owner required');}
function deployment(c,e){if(!['monolith','microservices'].includes(c.topology)||typeof c.selected!=='boolean')e.push('deployment: topology and selected boolean required');for(const k of ['dataOwnership','backgroundWork','correlation','configuration','rollout','rollback'])if(!text(c[k]))e.push(`deployment.${k}: text required`);for(const k of ['placements','connections','failureDomains'])texts(c[k],`deployment.${k}`,e);}
function decision(c,e){for(const k of ['problem','choice','rationale','tradeoffs','decisionOwner','revisitWhen'])if(!text(c[k]))e.push(`decision.${k}: text required`);for(const k of ['drivers','options','affectedRefs'])texts(c[k],`decision.${k}`,e);if(!['proposed','accepted','rejected','undecided'].includes(c.status))e.push('decision.status: unsupported');}
function verification(c,e){for(const k of ['businessRefs','flowRefs','codeUnitRefs','fixtures','preconditions','actions','expectedData','expectedEffects','expectedResponse','expectedAppState','forbiddenChanges'])texts(c[k],`verification.${k}`,e);for(const k of ['branchRefs','nfrRefs','faults','measurements'])texts(c[k],`verification.${k}`,e,false);if(!text(c.actorAuthority))e.push('verification.actorAuthority: required');if(!Array.isArray(c.tests)||!c.tests.length)e.push('verification.tests: required');for(const t of c.tests??[])if(!exact(t,['repository','file','case','existence'], 'verification.test',e)||![t.repository,t.file,t.case].every(text)||!['existing','planned'].includes(t.existence))e.push('verification.test: repo/file/case and existence required');if(Object.hasOwn(c,'executionEvidence')||Object.hasOwn(c,'evidence'))e.push('verification: evidence fields do not belong in SDS');}

export function validateSDSV4Bindings(spec,{nodes,allowedNodeIds}){
 const errors=[]; const sdsRefs={...spec,refs:(spec.refs??[]).filter(r=>['overview','flow','code-unit','contract','data','quality','deployment','decision','verification'].includes(r.type))}; errors.push(...validateTypedBindings(sdsRefs,{nodes,allowedNodeIds,schema:SDS_V4_SCHEMA,ownerKind:'architecture'}));
 for(const ref of (spec.refs??[]).filter(r=>['functional-requirement','non-functional-requirement','business-rule','business-data','customer-journey','acceptance','branch','srs-flow'].includes(r.type))){const node=nodes.find(n=>n.meta.id===ref.nodeId),target=node?.meta.extensions?.work3?.specification;let found=target?.id===ref.itemId&&target?.nodeType===(ref.type==='business-data'?'data':ref.type);if(ref.type==='srs-flow')found=target?.nodeType==='functional-requirement'&&target.content.flowId===ref.itemId;if(ref.type==='acceptance')found=target?.nodeType==='functional-requirement'&&target.content.acceptanceCriteria?.some(x=>x.id===ref.itemId);if(ref.type==='branch')found=target?.nodeType==='functional-requirement'&&[...target.content.alternativeFlows??[],...target.content.exceptionFlows??[]].some(x=>x.id===ref.itemId);if(!allowedNodeIds.has(ref.nodeId)||node?.meta.kind!=='business'||target?.schema!=='starci/srs@3'||!found)errors.push(`Unbound SRS ${ref.type} ${ref.nodeId}#${ref.itemId}`);}
 const legacyKinds={'legacy-code-unit':'structure','legacy-contract':'contracts','legacy-data':'data'};
 for(const ref of (spec.refs??[]).filter(r=>legacyKinds[r.type])){const node=nodes.find(n=>n.meta.id===ref.nodeId),target=node?.meta.extensions?.work3?.specification,view=target?.views?.find(v=>v.id===ref.itemId);if(!allowedNodeIds.has(ref.nodeId)||node?.meta.kind!=='architecture'||target?.schema!=='starci/specification@3'||view?.kind!==legacyKinds[ref.type])errors.push(`Unbound legacy SDS ${ref.type} ${ref.nodeId}#${ref.itemId}`);}
 return errors;
}
