// Generated by {{appBinary}} sync (app root). Do not edit: run "npx {{appBinary}} sync --write".
// Database types hook: contract:emit owns the emitter; this is its single managed call site in codegen.
import { execFileSync } from 'node:child_process';

execFileSync('npm', ['run', 'db:types', '--silent'], { stdio: 'inherit' });
