// A closed set of synthetic operator packages for the chain specs (plan-chain.spec.mjs,
// validate-chain.spec.mjs, validate-session.spec.mjs): the same shapes loadOperatorPackages returns,
// parsed from operator.md text, so a spec exercises the planner and the gate on tables it owns rather
// than on whichever tables the tree carries the day it runs. The ids follow the tree's, the tables
// are the minimum the rules read: Context roles, Inputs (kind, from, required), Outputs, Steps writes,
// Next, and operator.json's primaryOutput and tools.
import { parseOperatorMd } from './operator-md.mjs';

export function fakePackage({ id, primary, mode = 'isolated', tools = {}, context = [], inputs = [], outputs = [], writes = [], next = [], fields = [] }) {
  const row = (cells) => `| ${cells.join(' | ')} |`;
  const md = [
    `# \`${id}\``, '', '## Job', '', `Do the one job of ${id}.`, '', '## Done when', '', `A \`${primary}\` receipt exists.`, '',
    '## Context', '', row(['Alias', 'Bind', 'Required']), row(['---', '---', '---']),
    ...context.map(([alias, required]) => row([`\`${alias}\``, 'what it binds', required ? 'yes' : 'no'])),
    '', '## Inputs', '', row(['Kind', 'From', 'Required']), row(['---', '---', '---']),
    ...(inputs.length ? inputs.map(([kind, from, required]) => row([`\`${kind}\``, from, required ? 'yes' : 'no'])) : [row(['—', 'this operator opens the chain, so it consumes no earlier branch', 'no'])]),
    '', '## Requirements', '', row(['Field', 'Type', 'Default', 'Ask']), row(['---', '---', '---', '---']),
    ...fields.map(([field, def]) => row([`\`${field}\``, 'string', def ?? '—', 'the value'])),
    '', '## Steps', '', row(['#', 'Step', 'Params', 'Reads', 'Writes', 'Stops']), row(['---', '---', '---', '---', '---', '---']),
    row(['1', 'Do it', '—', '—', writes.length ? writes.map((w) => `\`${w}\``).join(', ') : '—', '—']),
    '', '## Outputs', '', row(['Kind', 'File', 'Type', 'Required']), row(['---', '---', '---', '---']),
    ...outputs.map((kind) => row([`\`${kind}\``, `\`response/data/${kind}.json\``, 'data', 'yes'])),
    '', '## Stops', '', row(['Code', 'Disposition']), row(['---', '---']), row(['`INVALID_INPUT`', 'terminate']),
    '', '## Next', '', row(['When', 'Operator']), row(['---', '---']),
    ...next.map((op) => row([`it hands to ${op}`, `\`${op}\``])), '',
  ].join('\n');
  const manifest = { id, domain: id.split('.')[0], primaryOutput: primary, resources: { profile: 'sol-fresh', mode, tools: Object.fromEntries(Object.entries(tools).map(([k, v]) => [`@tools/${k}`, v])) } };
  return { dir: `/fake/${id.replace(/\./g, '-')}`, name: id.replace(/\./g, '-'), manifest, shape: 'v9', en: parseOperatorMd(md, 'en'), vi: null };
}

const FE = ['@workspaces/fe', true];
const BE = ['@workspaces/be', true];
// The synthetic tree: enough operators to plan every fixture shape (a surface, a backend feature, a
// release, a content unit, a library release) and to trip every rule the gate enforces.
export const fakeTree = () => [
  fakePackage({ id: 'environment.preflight', primary: 'environment-readiness', mode: 'inline', tools: { git: 'read', container: 'read' }, outputs: ['environment-readiness'], next: ['workspace.bind', 'content.generate'], fields: [['project'], ['roles', '[]']] }),
  fakePackage({ id: 'workspace.bind', primary: 'workspace-route-binding', mode: 'inline', tools: { git: 'read' }, outputs: ['workspace-route-binding', 'route'], next: ['business.decide', 'architecture.decide', 'backend.generate', 'interface.plan', 'interface.generate', 'interface.audit', 'runtime.serve', 'quality.verify', 'library.update', 'git.publish'], fields: [['project'], ['role']] }),
  fakePackage({ id: 'business.decide', primary: 'business-promise-authority', tools: { sourcewrite: 'declared-write-set' }, context: [BE, ['@worktrees/businesses/<featureId>', true]], inputs: [['architecture-decision', '`architecture.decide`; architecture evidence', false]], outputs: ['business-promise-authority', 'model'], writes: ['@worktrees/businesses/<featureId>'], next: ['architecture.decide', 'backend.generate', 'interface.plan', 'interface.generate'], fields: [['featureId'], ['mode', 'model']] }),
  fakePackage({ id: 'architecture.decide', primary: 'architecture-decision', tools: { git: 'read' }, context: [BE], inputs: [['model', '`business.decide`; the head that branch modelled', false]], outputs: ['architecture-decision'], next: ['backend.generate', 'interface.generate', 'business.decide'], fields: [['objective']] }),
  fakePackage({ id: 'backend.generate', primary: 'backend-source-application', tools: { sourcewrite: 'declared-write-set', git: 'commit-session-branch' }, context: [BE], inputs: [['architecture-decision', '`architecture.decide`; the frozen contract', true], ['model', '`business.decide`', false]], outputs: ['backend-source-application', 'changes'], writes: ['@workspaces/be/branch/session'], next: ['quality.verify', 'interface.plan', 'interface.generate', 'business.reconcile', 'runtime.serve'], fields: [['featureId']] }),
  fakePackage({ id: 'business.reconcile', primary: 'business-promise-authority', tools: { sourcewrite: 'declared-write-set' }, context: [BE, ['@worktrees/businesses/<featureId>', true]], inputs: [['backend-source-application', '`backend.generate`; the delivered source', true], ['quality-verification', '`quality.verify`; the gates it passed', false], ['uat-flow-verification', '`uat.verify`; the walk it survived', false]], outputs: ['business-promise-authority'], writes: ['@worktrees/businesses/<featureId>'], next: ['git.publish'], fields: [['featureId']] }),
  fakePackage({ id: 'interface.plan', primary: 'surface-map', tools: { git: 'read' }, context: [FE], inputs: [['business-promise-authority', '`business.decide`; the promise the pages carry', false]], outputs: ['surface-map', 'units'], next: ['interface.generate'], fields: [['target']] }),
  fakePackage({ id: 'interface.generate', primary: 'frontend-source-application', tools: { sourcewrite: 'declared-write-set', git: 'commit-session-branch', host: 'loopback' }, context: [FE], inputs: [['business-promise-authority', '`business.decide`; required by new', false], ['backend-source-application', '`backend.generate`; required when a data contract changes', false], ['architecture-decision', '`architecture.decide`; when a boundary changes', false], ['units', '`interface.plan`, the unit this branch executes', false], ['frontend-surface-audit', '`interface.audit`, the findings that opened this round', false]], outputs: ['frontend-direction-decision', 'frontend-presentation-resolution', 'frontend-source-application', 'changes'], writes: ['@workspaces/fe/branch/session'], next: ['runtime.serve', 'interface.audit', 'quality.verify', 'interface.generate'], fields: [['target'], ['mode', 'apply'], ['changeLevel']] }),
  fakePackage({ id: 'interface.fix', primary: 'frontend-source-application', mode: 'inline', tools: { sourcewrite: 'declared-write-set', git: 'commit-session-branch' }, context: [FE], inputs: [['frontend-source-application', '`interface.generate`, or the prior `interface.fix`', true], ['frontend-surface-audit', '`interface.audit`, when the finding is a row of its verdict table', false]], outputs: ['frontend-source-application', 'changes'], writes: ['@workspaces/fe/branch/session'], next: ['interface.audit', 'quality.verify'], fields: [['finding']] }),
  fakePackage({ id: 'runtime.serve', primary: 'platform-operation-receipt', mode: 'inline', tools: { container: 'operate', git: 'merge-into-integration-branch' }, inputs: [['changes', '`backend.generate`, `interface.generate` or `library.update`; the session\'s committed work', false]], outputs: ['platform-operation-receipt', 'changes'], writes: ['@worktrees/sessions/central-runtime'], next: ['interface.audit', 'quality.verify', 'uat.verify', 'workspace.bind'], fields: [['routeKey']] }),
  fakePackage({ id: 'interface.audit', primary: 'frontend-surface-audit', tools: { browsercontrol: 'required', git: 'read' }, context: [FE, ['@knowledge/ui/proof', true]], inputs: [['frontend-source-application', '`interface.generate`, or the `interface.fix` that repaired one finding on it', true], ['frontend-presentation-resolution', '`interface.generate`, the owner of every node', true], ['route', '`workspace.bind`, the bound route', true], ['platform-operation-receipt', '`runtime.serve`, the serve that put the commit on the port', false]], outputs: ['frontend-surface-audit', 'screenshot'], next: ['interface.fix', 'interface.generate', 'quality.verify', 'uat.verify'], fields: [['auditScope']] }),
  fakePackage({ id: 'quality.verify', primary: 'quality-verification', mode: 'inline', tools: { git: 'read' }, context: [['@workspaces/<project>/<role>/gates', true]], inputs: [['backend-source-application', '`backend.generate`, the backend delivery to verify', false], ['frontend-source-application', '`interface.generate`, the frontend delivery to verify', false], ['frontend-surface-audit', '`interface.audit`, the proof topics it closed', false], ['uat-flow-verification', '`uat.verify`, the experience topic it closed', false]], outputs: ['quality-verification', 'gate-result'], writes: ['@tools/shell'], next: ['backend.generate', 'interface.fix', 'git.publish', 'release.deploy', 'business.reconcile', 'uat.verify'], fields: [['gates', 'all']] }),
  fakePackage({ id: 'uat.verify', primary: 'uat-flow-verification', tools: { browsercontrol: 'required', database: 'namespaced-write' }, context: [BE, ['@worktrees/uat/<flow>/<case>', true]], inputs: [['frontend-surface-audit', 'the surface audit that found the frontend clean', true], ['quality-verification', 'the quality gate that passed', true], ['route', '`workspace.bind` on the fe role', true], ['platform-operation-receipt', '`runtime.serve`', false]], outputs: ['uat-flow-verification', 'uat-snapshot'], writes: ['@worktrees/uat/<flow>/<case>'], next: ['git.publish', 'interface.fix', 'business.reconcile'], fields: [['flow'], ['approval']] }),
  fakePackage({ id: 'git.publish', primary: 'git-publication', mode: 'inline', tools: { git: 'merge-and-push' }, inputs: [['workspace-route-binding', '`workspace.bind`; a publish never resolves its own checkout', true], ['changes', '`backend.generate` or `interface.generate`, the exact file set', true], ['quality-verification', '`quality.verify`, the receipt whose measured commit is pushed', true]], outputs: ['git-publication'], writes: ['@remote/git/<project>/<role>'], next: ['release.deploy'], fields: [['boundary'], ['approval']] }),
  fakePackage({ id: 'release.deploy', primary: 'release-deployment', mode: 'inline', tools: { container: 'operate' }, inputs: [['quality-verification', '`quality.verify`; passing verification at the release commit', true], ['route', '`workspace.bind`; the source checkout', false]], outputs: ['release-deployment'], next: [], fields: [['release'], ['approval']] }),
  fakePackage({ id: 'library.update', primary: 'library-source-application', tools: { sourcewrite: 'declared-write-set', git: 'commit-session-branch' }, context: [FE], inputs: [['route', '`workspace.bind`; the verified checkout', true]], outputs: ['library-source-application', 'changes'], writes: ['@workspaces/fe/branch/session'], next: ['quality.verify'], fields: [['plan']] }),
  fakePackage({ id: 'content.generate', primary: 'content-generation-receipt', tools: { shell: 'declared-commands', imagegen: 'required' }, context: [['@remote/minio/<contentId>/<locale>', true]], outputs: ['content-generation-receipt'], next: [], fields: [['unit']] }),
];
export const fakeMission = (doneWhen, extra = {}) => ({ version: 1, language: 'en', goal: 'the goal', includes: ['this'], excludes: [], doneWhen, sourceRef: 'user-message:goal', ...extra });
export const line = (producedBy, evidence = `${producedBy} evidences it`) => ({ evidence, producedBy });
