import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openSession, confirmSession, cleanupFixtureOwners } from './v23-test-fixture.mjs';
import { openAttempt, acceptAttempt } from './attempt-gate.mjs';
import { editForecast } from './plan-history.mjs';
import { validateStep } from './validate-step.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('unit expansion reads a genuinely accepted current plan, preserves its request, and schedules unit dependencies without redispatching the plan', async t => {
  const owner = await mkdtemp(path.join(os.tmpdir(), 'starci-plan-expand-'));
  t.after(async()=> { cleanupFixtureOwners(owner); await rm(owner,{recursive:true,force:true}); });
  const opened = await openSession(path.join(owner,'.worktrees/sessions'), { project:'expansion', hostBinding:{kind:'codex-task',hostId:`native-${path.basename(owner)}`,worktree:owner,sourcePromptRef:'user:opening'},mission:{language:'en',goal:'Plan two independently attributable fixture units.',target:'Declared seed plan',includes:['Seed planning'],excludes:[],outputs:['Seed plan'],doneWhen:[{evidence:'Two attributable seed units are planned.',producedBy:'data.plan'}],verification:'Validate the plan and units.',sourceRef:'user:opening'} });
  await confirmSession(opened.session,{selected:'as-stated',selectedBy:'user',sourceRef:'user:approved'});
  const session=opened.session, branch=path.join(session,'step-1/parallel-1'), file=path.join(session,'state.json');
  await mkdir(path.join(branch,'request'),{recursive:true});
  const contexts=[{alias:'@workspaces/be',head:null},{alias:'@worktrees/_templates',head:null},{alias:'@worktrees/uat/items',head:null}];
  const request={contractVersion:'starci/v2.2',schemaVersion:9,operatorId:'data.plan',sessionId:opened.sessionId,step:1,parallel:1,contexts,requirements:{goal:'Two fixture units support the declared journey.',feature:'items',env:'dev'},inputs:{},resume:null,goal:{doneWhen:0},attempt:{id:'1/1:a1',number:1,kind:'initial',previous:null},expected:{version:1,goalVersion:1,sourceRef:'state.json#mission:v1/doneWhen:0',criteria:[{id:'units',required:true,expected:'Two attributable units are planned.',verification:'Validate the plan and units.'}]},environment:{isolationId:'1/1:a1',mode:'isolated',workspace:null,reads:contexts.map(c=>c.alias),writes:[],exclusive:[],outputRoot:'response'},frozenInputs:[]};
  let state=JSON.parse(await readFile(file));state.chain=[['1/1']];state.steps={'1/1':'data.plan'};state.current='1/1';await writeFile(file,JSON.stringify(state));
  await writeFile(path.join(branch,'request/request.json'),JSON.stringify(request));
  await openAttempt(branch);
  const units=[{id:'second',kind:'table',goal:'The second owned fixture is available.',inputs:[],dependsOn:['first']},{id:'first',kind:'table',goal:'The first owned fixture is available.',inputs:[],dependsOn:[]}];
  const table=(head,rows)=>`\n## ${head[0]}\n\n| ${head[1].join(' | ')} |\n| ${head[1].map(()=> '---').join(' | ')} |\n${rows.map(row=>`| ${row.join(' | ')} |`).join('\n')}\n`;
  const quote=value=>'`'+value+'`';
  const receipt='# seed-plan — items\n'+table(['Units',['Unit','Serves','Namespace','Goal']],units.map(u=>[quote(u.id),`flow ${quote(u.id)}`,quote(`uat-${u.id}`),u.goal]))+table(['Targets',['Unit','Store','Attribution','Volume','Rollback']],units.map(u=>[quote(u.id),quote('items'),'owner','2','Remove every record owned by the unit account.']))+table(['Fixtures',['Unit','State','Action','JSON','SQL','Expected','Creates outcome']],units.map(u=>[quote(u.id),'valid','reuse',quote(`.worktrees/uat/items/${u.id}/seed/records.json`),'—','Two owned records read back.','false']))+table(['Fallbacks taken',['Code','Action']],[]);
  await mkdir(path.join(branch,'response/data'),{recursive:true});
  await writeFile(path.join(branch,'response/response.md'),receipt);
  await writeFile(path.join(branch,'response/data/units.json'),JSON.stringify({schemaVersion:9,producedBy:'data.plan',units}));
  const evidence=['response/response.md','response/data/units.json'];
  const response={contractVersion:'starci/v2.2',schemaVersion:9,operatorId:'data.plan',step:1,parallel:1,status:'done',fields:{'seed-plan':evidence[0],units:evidence[1]},fallbacks:[],commits:[],next:['data.seed'],boundProfile:'sol-reviewer',ranProfile:'sol-reviewer',attempt:{id:'1/1:a1',number:1,expectedVersion:1},actual:{expectedVersion:1,observedAt:new Date().toISOString(),observations:[{criterionId:'units',observed:'Both attributable units are declared.',evidence}]},comparison:{expectedVersion:1,verdict:'matched',criteria:[{criterionId:'units',verdict:'matched',evidence,note:'Both units and their targets validate.'}],next:'advance'},goalCheck:{achieved:true,evidence}};
  response.outcome={summary:'Two attributable fixture units are planned.',primary:{kind:'document',label:'Seed plan',ref:'response/response.md'}};
  await writeFile(path.join(branch,'response/response.json'),JSON.stringify(response));
  assert.equal((await acceptAttempt(branch)).state,'matched');
  state=JSON.parse(await readFile(file));
  const forecast={chain:[['1/1'],['2/1']],steps:{'1/1':'data.plan','2/1':'data.seed'},goals:{'1/1':{prerequisite:'2/1'},'2/1':{doneWhen:0}},reasons:{},presets:{},dependencies:{'1/1':[],'2/1':['1/1']},evidenceDependencies:{'1/1':[],'2/1':['1/1']},nodes:{'1/1':'data.plan','2/1':'data.seed'},fanout:{'2/1':'units'},handoffs:{},imports:{}};
  const bytes=await readFile(path.join(branch,'request/request.json'));
  const result=await editForecast(root,session,state,forecast,{kind:'expand',cell:'2/1',producer:'1/1'},2);
  assert.deepEqual(result.chain,[['1/1'],['2/1'],['3/1']]);
  assert.equal(result.units['2/1'].id,'first');assert.equal(result.units['3/1'].id,'second');assert.deepEqual(result.units['3/1'].dependsOn,['2/1']);
  assert.deepEqual(await readFile(path.join(branch,'request/request.json')),bytes);
  assert.deepEqual((await validateStep(root,branch,{operator:true,requestPhase:'accept'})).errors,[]);
  const forged=structuredClone(state);forged.attempts['1/1'].status='running';
  await assert.rejects(editForecast(root,session,forged,forecast,{kind:'expand',cell:'2/1',producer:'1/1'},2),/matched|running/);
  await writeFile(path.join(branch,'response/data/units.json'),'{}');
  await assert.rejects(editForecast(root,session,state,forecast,{kind:'expand',cell:'2/1',producer:'1/1'},2),/changed|schema|units|producedBy/);
});
