import fs from 'node:fs';import path from 'node:path';import {stringifyYaml} from '../core/yaml.mjs';import {validateWorkspace} from '../core/index.mjs';
export function makeExample(root){
 if(fs.existsSync(root))throw Error('Example destination must be new');
 const write=(p,v)=>{const file=path.join(root,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof v==='string'?v:stringifyYaml(v));};
 write('workspace.yaml',{schema:'work/workspace@1',id:'example-expandable-work'});write('.gitignore','_local/\n_workflows/\n');
 for(const [name,source]of [['work.schema','work.schema'],['work-layout','work-layout']])write('_schema/'+name+'.yaml',JSON.parse(fs.readFileSync(new URL('../schemas/'+source+'.json',import.meta.url))));
 const defs=[['vps','business',false],['vps/create','business',false],['vps/create/business','business',false],['vps/create/business/rules','business',true],['vps/create/business/journeys','business',true],['vps/create/business/acceptance','business',true],['vps/create/architecture','architecture',true],['vps/create/backend','business',false],['vps/create/backend/code','business',false],['vps/create/backend/code/control-plane','implementation',true],['vps/create/backend/code/provisioning','implementation',true],['vps/create/frontend','business',false],['vps/create/frontend/draw','business',true],['vps/create/frontend/code','business',false],['vps/create/frontend/code/create-form','implementation',true],['vps/create/frontend/code/progress','implementation',true],['vps/create/uat','business',false],['vps/create/uat/flow1','uat.ux',true],['vps/create/uat/flow2','uat.ux',true]];
 for(const [dir,kind,leaf]of defs){const meta={schema:'work/node@1',id:dir.replaceAll('/','.'),kind,required:true,description:'Synthetic layout example for '+dir+'. Replace with reviewed business requirements and real source bindings; no implementation or acceptance is claimed.'};if(leaf){meta.state='todo';meta.assertions=['reviewed-scope','verified-outcome'];}if(dir==='vps/create/frontend')meta.assets=[{path:'assets/design.svg'}];write(dir+'/index.yaml',meta);}
 write('vps/create/frontend/assets/design.svg','<svg xmlns="http://www.w3.org/2000/svg" width="640" height="180"><rect width="640" height="180" fill="#eef2e8"/><text x="24" y="84" font-family="sans-serif" font-size="22">Synthetic layout asset</text><text x="24" y="120" font-family="sans-serif" font-size="16">Not an approved UI design</text></svg>');
 for(const flow of ['flow1','flow2'])fs.mkdirSync(path.join(root,'vps/create/uat',flow,'assets'),{recursive:true});
 const result=validateWorkspace(root);if(!result.ok)throw Error(JSON.stringify(result.errors));return {ok:true,nodes:result.nodes.length,root,synthetic:true};
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(import.meta.filename))console.log(JSON.stringify(makeExample(path.resolve(process.argv[2]))));
