// lessons-file.mjs — the reader of the versioned lessons file (modules/supervisor/lessons.yaml, GENERATED by
// `starci machine lessons export --write`; supervise.yaml selfLearning.learn). Dependency-free, so api
// dispatch can inject a matching lesson beside a retry's prior attempt failures (modules/kernel/api.yaml
// commands.dispatch priorFailures) without loading the Supervisor.
import fs from 'node:fs';
import path from 'node:path';

export const LESSONS_FILE = 'modules/supervisor/lessons.yaml';

/** The lessons of the file text: [{signature, source, weight, status, text}]. The file's own flat form only. Pure. */
export function parseLessonsFile(text) {
  const lessons = [];
  let cur = null;
  for (const line of String(text ?? '').split(/\r?\n/)) {
    const head = /^ {2}- signature: (.*)$/.exec(line);
    if (head) { cur = { signature: JSON.parse(head[1]) }; lessons.push(cur); continue; }
    const field = /^ {4}(source|weight|status|text): (.*)$/.exec(line);
    if (field && cur) {
      if (field[1] === 'text') cur[field[1]] = JSON.parse(field[2]);
      else if (field[1] === 'weight') cur[field[1]] = Number(field[2]);
      else cur[field[1]] = field[2];
    }
  }
  return lessons;
}

/**
 * The lessons (at most `limit`, heaviest first) whose signature or text names one of `names` (red check names).
 * [] when the file is absent or unreadable - a lesson never blocks a dispatch.
 */
export function lessonsForChecks(names, { root, read = (f) => fs.readFileSync(f, 'utf8'), limit = 3 } = {}) {
  const wanted = (names ?? []).filter((n) => typeof n === 'string' && n.length >= 3);
  if (!wanted.length || !root) return [];
  try {
    return parseLessonsFile(read(path.join(root, LESSONS_FILE)))
      .filter((l) => l.status !== 'reverted' && wanted.some((n) => `${l.signature} ${l.text}`.includes(n)))
      .sort((a, b) => (b.weight ?? 1) - (a.weight ?? 1)).slice(0, limit);
  } catch { return []; }
}

/** prior_attempt_failures with the matching lessons appended as `lesson <source>` entries (starci kernel dispatch). Pure over the file. */
export const withLessons = (priorFailures, { root, read } = {}) => (priorFailures?.length
  ? [...priorFailures, ...lessonsForChecks(priorFailures.map((f) => f.name), { root, read }).map((l) => ({ name: `lesson ${l.source}`, evidence: `${l.signature}: ${l.text}` }))]
  : priorFailures ?? []);
