// check 4 refined: legality vocabulary internal consistency + vs ops catalog
import {readFileSync, readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {parseYaml} from '../../../../core/yaml.mjs';
const root = fileURLToPath(new URL('../../../../', import.meta.url));
const modDir = root + 'modules/ops/ops/';
const leg = parseYaml(readFileSync(root + 'modules/goal/legality.yaml', 'utf8'));
const stateVars = leg.producesVocabulary?.stateVariables ?? [];
const opProd = leg.producesVocabulary?.opProduces ?? {};
const fam = v => String(v).replace(/\s*\(.*?\)\s*/g,'').replace(/^([a-zA-Z]+)\.[^:]*/, '$1.X');
const varFams = new Set(stateVars.map(fam));
const opIds = new Set(readdirSync(modDir).filter(f => f.endsWith('.yaml')).map(f => f.replace(/\.yaml$/,'')));
console.log('opProduces keys not in ops catalog:', Object.keys(opProd).filter(k=>!opIds.has(k)));
console.log('ops missing from opProduces:', [...opIds].filter(k=>!(k in opProd)));
const usedVars = Object.entries(opProd).flatMap(([op,vs])=>vs.map(v=>[v,op]));
console.log('\nopProduces vars with no stateVariables family match:');
for (const [v,op] of usedVars) if (!varFams.has(fam(v))) console.log(`  ${v}  (${op})`);
console.log('\nstateVariables never produced by any op:');
const usedFams = new Set(usedVars.map(([v])=>fam(v)));
for (const v of stateVars) if (!usedFams.has(fam(v))) console.log(`  ${v}`);
