import React, {useState} from 'react'
import {createRoot} from 'react-dom/client'
import catalog from './catalog.generated.json'
import './styles.css'
function App(){
 const [query,setQuery]=useState('')
 const ops=catalog.operators.filter(o=>(o.id+' '+o.goal).toLowerCase().includes(query.toLowerCase()))
 return <><header><a className="brand" href="/">StarCi <span>V3</span></a><nav><a href="#workflows">Workflows</a><a href="#operators">Operators</a><a href="/docs/">Docs ↗</a><a href="https://github.com/starci183/starci-skills">GitHub ↗</a></nav></header><main><section className="hero"><p className="eyebrow">ONE SKILL · COMPLETE JOBS · VERIFIED OUTCOMES</p><h1>From request<br/>to proof.</h1><p className="intro">One StarCi entry selects a bounded workflow. Each operator owns the work, its limits, and evidence that the result meets the request.</p><div className="stats"><span><b>1</b> skill</span><span><b>{catalog.workflows.length}</b> workflows</span><span><b>{catalog.operators.length}</b> operators</span><span><b>3 × 3</b> maximum matrix</span></div><a className="button" href="#workflows">Explore the workflows ↓</a></section><section id="workflows"><p className="eyebrow">CHOOSE THE OUTCOME</p><h2>Workflows</h2><div className="grid">{catalog.workflows.map(w=><article key={w.id}><small>{w.execution==='frontend-gate'?'Local gate':'Coordinator contract'}</small><h3>{w.id}</h3><p>{w.when}</p><a href={'/docs/#workflow-'+w.id}>Matrix, handoffs and criteria →</a></article>)}</div></section><section id="operators"><p className="eyebrow">BOUNDED AUTHORITY</p><h2>Complete operators</h2><label>Find an operator<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or purpose"/></label><p aria-live="polite">{ops.length} {ops.length===1?'operator':'operators'}</p>{ops.map(o=><details key={o.id}><summary><strong>{o.id}</strong><span>{o.goal}</span></summary><ol>{o.contract.steps.map((s,i)=><li key={i}>{s.action.en}</li>)}</ol><a href={'/docs/#op-'+o.id}>Read inputs, outputs and authority →</a></details>)}</section><aside>Before every skill invocation, check the JSON build in <code>.dist</code>. Missing or stale artifacts rebuild immediately. A failed build blocks execution. Missing Work routes to prepare-work. Approve the concrete goal before work and accept the verified result before Work becomes done. Work metadata uses YAML.</aside></main><footer>StarCi {catalog.version} · Generated from current JSON contracts.</footer></>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
