import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { nextState } from '../skills/route-machine.mjs';
import { validateInput as validateBoundary } from './fe/mutation-boundary-freeze/validate-input.mjs';
import { validateInput as validateReturn } from './fe/return-consume/validate-input.mjs';
import { validateInput as validateGuard } from './fe/progress-guard/validate-input.mjs';

const load=(id)=>JSON.parse(readFileSync(new URL(`../skills/${id}/machine.json`,import.meta.url)));
test('all owned mission machines start with analyze-input and use v7',()=>{for(const id of ['starci-feature-deliver','starci-fe-process','starci-uat-verify']){const m=load(id);assert.equal(m.schemaVersion,7);assert.equal(m.start,'analyze-input');assert.equal(m.states['analyze-input'].kind,'analysis')}});
test('audit mutation boundary requires route, before hash, contract fingerprint, and authorization',()=>{const v={schemaVersion:7,operatorId:'fe/mutation-boundary-freeze',context:{verifiedFrontendRoute:'.workspaces/projects/academy/fe.json',approvedContractFingerprint:`sha256:${'a'.repeat(64)}`},input:{intent:'audit',mutationAuthorizationRef:'approval://audit-fix',files:[{path:'src/Profile.tsx',beforeSha256:`sha256:${'b'.repeat(64)}`}],dominance:'unique'}};assert.deepEqual(validateBoundary(v),{valid:true,errors:[]});delete v.input.mutationAuthorizationRef;assert.equal(validateBoundary(v).valid,false)});
test('typed RETURN consumption requires exact correlation fields and runtime receipt',()=>{const receipt={version:'7.0.0',receiptId:'receipt:r1',type:'RETURN',missionId:'m1',skillId:'starci-backend-process',operatorId:null,parentId:'call1',childId:null,timestamp:'2026-01-01T00:00:00.000Z',progressFingerprint:`sha256:${'c'.repeat(64)}`,trace:{authorityRefs:['business://x'],sourceHeads:['git:be']}};const v={schemaVersion:7,operatorId:'fe/return-consume',context:{expectedMissionId:'m1',expectedChildId:'call1',expectedResumeState:'apply',expectedReceiptType:'RETURN'},input:{receipt,requiredAuthorityRefs:['business://x'],requiredSourceHeads:['git:be']}};assert.deepEqual(validateReturn(v),{valid:true,errors:[]});v.input.receipt.type='CALL';assert.equal(validateReturn(v).valid,false)});
test('coordinator advances domain calls then joins quality and UAT proof without self-certifying',()=>{const m=load('starci-feature-deliver');for(const outcome of ['call-business','call-backend','call-frontend','call-quality','call-uat'])assert.equal(nextState(m,'plan',{output:{outcome}},{}),'handoff');assert.equal(nextState(m,'plan',{output:{outcome:'join-proof'}},{}),'join');assert.equal(nextState(m,'join',{output:{outcome:'joined'}},{}),'complete')});
test('UAT freezes before execution and any lens failure dominates into publish',()=>{const m=load('starci-uat-verify');assert.equal(nextState(m,'snapshot',{output:{outcome:'frozen'}},{}),'freeze-cases');assert.equal(nextState(m,'freeze-cases',{output:{outcome:'frozen'}},{}),'behavior');assert.equal(nextState(m,'behavior',{output:{outcome:'failed'}},{}),'publish');assert.equal(nextState(m,'ux',{output:{outcome:'failed'}},{}),'publish');assert.equal(nextState(m,'ui',{output:{outcome:'failed'}},{}),'publish')});
test('repair and peer-call histories reject a repeated progress fingerprint',()=>{const fp=`sha256:${'d'.repeat(64)}`;const v={schemaVersion:7,operatorId:'fe/progress-guard',context:{history:[fp]},input:{candidateFingerprint:fp,cycleKind:'repair'}};assert.equal(validateGuard(v).valid,false);v.input.candidateFingerprint=`sha256:${'e'.repeat(64)}`;assert.deepEqual(validateGuard(v),{valid:true,errors:[]})});
