import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { validateInput as validateBoundary } from './fe/mutation-boundary-freeze/validate-input.mjs';
import { validateInput as validateReturn } from './fe/return-consume/validate-input.mjs';
import { createReceipt } from '../runtime/trace.mjs';
import { validateInput as validateGuard } from './fe/progress-guard/validate-input.mjs';
import { validateOutput as validateSourceRepairOutput } from './fe/source-repair/validate-output.mjs';

const load=(id)=>JSON.parse(readFileSync(new URL(`../skills/${id}/machine.json`,import.meta.url)));
const route=(machine,stateId,outcome)=>{const matches=machine.states[stateId].on.filter((edge)=>edge.when?.outputEquals?.outcome===outcome);assert.equal(matches.length,1);return matches[0].target;};
test('all owned mission machines start with analyze-input and use v7',()=>{for(const id of ['starci-feature-deliver','starci-fe-process','starci-uat-verify']){const m=load(id);assert.equal(m.schemaVersion,7);assert.equal(m.start,'analyze-input');assert.equal(m.states['analyze-input'].kind,'analysis')}});
test('audit mutation boundary requires route, owner ceiling, before hash, contract fingerprint, and authorization',()=>{const v={schemaVersion:7,operatorId:'fe/mutation-boundary-freeze',context:{verifiedFrontendRoute:'.workspaces/projects/academy/fe.json',approvedContractFingerprint:`sha256:${'a'.repeat(64)}`},input:{intent:'audit',uxUiChangeLevel:'refine',layoutOwnerCeilingMode:'surface-and-nested-layouts',layoutOwnerCeiling:{targetOwnerRef:'surface://Profile',directInteractionOwnerRefs:['modal://ProfileEdit'],mutableNestedLayoutRefs:['layout://ProfileNested'],mutableAncestorLayoutRefs:[],immutableAncestorLayoutRefs:['layout://AppShell']},mutationAuthorizationRef:'approval://audit-fix',files:[{path:'src/Profile.tsx',beforeSha256:`sha256:${'b'.repeat(64)}`,ownerRef:'surface://Profile'},{path:'src/ProfileNested.tsx',beforeSha256:`sha256:${'c'.repeat(64)}`,ownerRef:'layout://ProfileNested'},{path:'src/ProfileEditModal.tsx',beforeSha256:`sha256:${'e'.repeat(64)}`,ownerRef:'modal://ProfileEdit'}],dominance:'unique'}};assert.deepEqual(validateBoundary(v),{valid:true,errors:[]});const escaped=structuredClone(v);escaped.input.files.push({path:'src/AppShell.tsx',beforeSha256:`sha256:${'d'.repeat(64)}`,ownerRef:'layout://AppShell'});assert.match(validateBoundary(escaped).errors.join('\n'),/owned above the mutable layout ceiling/);const widened=structuredClone(v);widened.input.layoutOwnerCeiling.mutableAncestorLayoutRefs.push('layout://LearnShell');assert.match(validateBoundary(widened).errors.join('\n'),/forbids mutable ancestor layouts/);delete v.input.mutationAuthorizationRef;assert.equal(validateBoundary(v).valid,false)});
test('typed RETURN consumption requires exact correlation fields and runtime receipt',()=>{const common={missionId:'m1',skillId:'starci-backend-process',operatorId:'core/handoff-ack',parentId:'call1',childId:null,context:{invocationRef:'invocation://return-consume-test',executionRef:`execution://${'c'.repeat(64)}`},input:{handoff:'x'},expectedOutput:{outcome:'acknowledged'},actualOutput:{outcome:'acknowledged'},authorityRefs:['business://x'],sourceHeads:['git:be']};createReceipt('CALL',{...common,receiptId:'receipt:r1-call'},{debug:true,now:()=> '2026-01-01T00:00:00.000Z'});const receipt=createReceipt('RETURN',{...common,receiptId:'receipt:r1'},{debug:true,now:()=> '2026-01-01T00:00:01.000Z'});const v={schemaVersion:7,operatorId:'fe/return-consume',context:{expectedMissionId:'m1',expectedChildId:'call1',expectedResumeState:'apply',expectedReceiptType:'RETURN'},input:{receipt,requiredAuthorityRefs:['business://x'],requiredSourceHeads:['git:be']}};assert.deepEqual(validateReturn(v),{valid:true,errors:[]});const forged=structuredClone(v);forged.input.receipt.type='CALL';assert.equal(validateReturn(forged).valid,false)});
test('coordinator advances domain calls then joins quality and UAT proof without self-certifying',()=>{const m=load('starci-feature-deliver');for(const outcome of ['call-business','call-backend','call-frontend','call-quality','call-uat'])assert.equal(route(m,'plan',outcome),'handoff');assert.equal(route(m,'plan','join-proof'),'join');assert.equal(route(m,'join','joined'),'complete')});
test('UAT freezes before execution and any lens failure dominates into publish',()=>{const m=load('starci-uat-verify');assert.equal(route(m,'snapshot','frozen'),'freeze-cases');assert.equal(route(m,'freeze-cases','frozen'),'behavior');assert.equal(route(m,'behavior','failed'),'publish');assert.equal(route(m,'ux','failed'),'publish');assert.equal(route(m,'ui','failed'),'publish')});
test('repair and peer-call histories reject a repeated progress fingerprint',()=>{const fp=`sha256:${'d'.repeat(64)}`;const v={schemaVersion:7,operatorId:'fe/progress-guard',context:{history:[fp]},input:{candidateFingerprint:fp,cycleKind:'repair'}};assert.equal(validateGuard(v).valid,false);v.input.candidateFingerprint=`sha256:${'e'.repeat(64)}`;assert.deepEqual(validateGuard(v),{valid:true,errors:[]})});
test('repair above the frozen layout ceiling requests authorization instead of blocking',()=>{const m=load('starci-fe-process');const value={schemaVersion:7,operatorId:'fe/source-repair',output:{outcome:'authorization-required',result:null,gaps:['layout://LearnShell and src/layouts/LearnShell.tsx are above the frozen page-and-nested-layout ceiling'],evidenceRefs:['finding://global-shell'],handoff:null}};assert.deepEqual(validateSourceRepairOutput(value),{valid:true,errors:[]});assert.equal(route(m,'repair','authorization-required'),'mutation-choice')});
