import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { validateInput } from './fe/ui-direction/validate-input.mjs';
import { validateOutput } from './fe/ui-direction/validate-output.mjs';
const input = () => ({ schemaVersion: 7, operatorId: 'fe/ui-direction', context: { evidenceRefs: ['business://outcome', 'ux://flow', 'ux://containers'], authorityRevision: 'sha256:approved' }, input: { targetRef: 'surface-set://learning', constraints: ['produce 3-4 materially different directions', 'cover failure, recovery, long content, and three viewports'] } });
const output = () => ({ schemaVersion: 7, operatorId: 'fe/ui-direction', output: { outcome: 'directions-ready', result: { summary: 'Three materially different directions synthesized; focused-split recommended against explicit axes.', artifactRefs: ['artifact://directions', 'artifact://visible-review'] }, gaps: [], evidenceRefs: ['business://outcome', 'ux://flow'] } });
test('accepts one closed synthesis contract with visible-review evidence', () => { assert.deepEqual(validateInput(input()), { valid: true, errors: [] }); assert.deepEqual(validateOutput(output()), { valid: true, errors: [] }); });
test('rejects operator-owned review routing and non-semantic outcomes', () => { const routed = output(); routed.output.status = 'pending'; assert.equal(validateOutput(routed).valid, false); const wrong = output(); wrong.output.outcome = 'recommended-selected'; assert.equal(validateOutput(wrong).valid, false); });
test('binds UI synthesis to AI-first, laws, Grammar-last, and atomic boundaries', () => { const execute = readFileSync(new URL('./fe/ui-direction/execute.md', import.meta.url), 'utf8'); assert.match(execute, /Synthesize three or four materially different UI directions/); assert.match(execute, /AI-first -> Rules-first -> Grammar-last/); assert.match(execute, /separate jobs/); });
