import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { validateInput } from './fe/ux-ui-resolve/validate-input.mjs';
import { validateOutput } from './fe/ux-ui-resolve/validate-output.mjs';
const input = () => ({ schemaVersion: 7, operatorId: 'fe/ux-ui-resolve', context: { evidenceRefs: ['uat://failed-report', '.claude/requests/flashcard-state.request.json'], authorityRevision: 'sha256:uat' }, input: { targetRef: '.claude/requests/flashcard-state.request.json', constraints: ['same exact request set', 'state-semantics defect', 'implementation-owned repair'] } });
const output = (outcome = 'repair-ready') => ({ schemaVersion: 7, operatorId: 'fe/ux-ui-resolve', output: { outcome, result: { summary: outcome === 'resolved' ? 'Exact request set closed after passing proof.' : 'Bounded implementation repair compiled from failed UAT evidence.', artifactRefs: ['artifact://ux-ui-resolution'] }, gaps: [], evidenceRefs: ['evidence://viewport'] } });
test('accepts an exact failed-UAT resolution contract', () => { assert.deepEqual(validateInput(input()), { valid: true, errors: [] }); assert.deepEqual(validateOutput(output()), { valid: true, errors: [] }); });
test('preserves plan and close outcomes while rejecting routing state', () => { assert.deepEqual(validateOutput(output('resolved')), { valid: true, errors: [] }); const value = input(); value.status = 'ready'; assert.equal(validateInput(value).valid, false); });
test('frontend UI operators declare AI-first, Rules-first, Grammar-last and separated audit', () => { for (const rel of ['./fe/ui-direction/execute.md','./fe/ui-detail-freeze/execute.md','./fe/implementation/execute.md','./fe/visual-fidelity/execute.md']) { const text = readFileSync(new URL(rel, import.meta.url), 'utf8'); assert.match(text, /AI-first/); assert.match(text, /Rules-first/); assert.match(text, /Grammar-last/); assert.match(text, /separate (jobs|boundaries)/); } });
