import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const t = (decision, stage, status = 'ready', factsAdd = []) => ({ decision, stage, status, factsAdd });
const linear = (domain, name, knowledge, inputStage, outputStage, inputs, outputRef, purpose, action, options = {}) => ({
  domain, name, knowledge, inputs, outputRef, purpose, action,
  accepts: options.accepts ?? [{ stage: inputStage, status: 'ready', facts: options.inputFacts ?? [] }],
  transitions: options.transitions ?? [t('ready', outputStage, 'ready', options.outputFacts ?? [])],
  sourceRefs: options.sourceRefs ?? [], sideEffects: options.sideEffects ?? [],
  stops: options.stops ?? ['required evidence is missing or stale', 'the result would cross the declared boundary']
});

const operators = [
  linear('workspace','route-verify','workspace.routing','request.received','business.evidence',['projectRef','roleRef','requestRef'],'routeReceiptRef','Resolve one verified project/role checkout and source-context partition.','Verify disk path, Git identity, revision, instructions, allowed roots, and /<role>/<project>/ Qdrant partition.',{outputFacts:['workspace-route-ready'],sideEffects:['write immutable route receipt below the run workspace']}),
  linear('workspace','identity-verify','workspace.initialization','workspace.identity','workspace.bootstrap',['machineIdentityRef','encryptedCredentialRosterRef'],'identityReceiptRef','Prove machine decrypt identity without exposing credential values.','Verify the declared identity can resolve encrypted custody and record only value-free capability evidence.',{outputFacts:['workspace-identity-ready']}),
  linear('workspace','bootstrap-verify','workspace.initialization','workspace.bootstrap','workspace.declarations',['identityReceiptRef','agentBootstrapRef','sourceIndexRef'],'bootstrapReceiptRef','Prove the minimal agent bootstrap routes to one maintained Source index.','Reject copied workflow law, missing index entries, stale load order, and a second hidden authority home.',{inputFacts:['workspace-identity-ready'],outputFacts:['workspace-bootstrap-ready']}),
  linear('workspace','declarations-compile','workspace.initialization','workspace.declarations','workspace.routes.hydrate',['bootstrapReceiptRef','portableDeclarationsRef'],'compiledDeclarationsRef','Validate and compile portable project/role declarations.','Refuse absolute paths, observed heads, secrets, duplicate ownership, and unresolved repository identities.',{inputFacts:['workspace-bootstrap-ready'],outputFacts:['workspace-declarations-ready'],sideEffects:['write tracked portable workspace declarations only']}),
  linear('workspace','routes-hydrate','workspace.initialization','workspace.routes.hydrate','workspace.worktree',['compiledDeclarationsRef','localRepositoryMapRef'],'hydrationReceiptRef','Hydrate rebuildable machine-local routes from portable declarations.','Resolve exact disk/Git paths and current heads without changing the portable declaration.',{inputFacts:['workspace-declarations-ready'],outputFacts:['workspace-routes-hydrated'],sideEffects:['write ignored machine-local route state']}),
  linear('workspace','worktree-verify','workspace.initialization','workspace.worktree','workspace.ready',['hydrationReceiptRef','worktreeDeclarationRef'],'worktreeReceiptRef','Prove one durable write root and its ownership boundary.','Verify lock, Git root, branch, owner role, clean/baseline policy, and allowed paths before a writer receives it.',{inputFacts:['workspace-routes-hydrated'],outputFacts:['workspace-worktree-ready']}),

  linear('business','evidence-normalize','business.authority-lifecycle','business.evidence','business.model',['routeReceiptRef','requestRef','ownerEvidenceRef','sourceEvidenceRefs'],'evidencePackRef','Separate facts, intent, examples, unknowns, and contradictions.','Normalize provenance without creating product truth; every claim retains its exact evidence reference.',{inputFacts:['workspace-route-ready'],outputFacts:['business-evidence-ready']}),
  linear('business','model','business.authority-lifecycle','business.model','business.publish',['evidencePackRef','previousHeadRef'],'businessModelRef','Reconcile one evidence-backed feature model.','Model actors, goals, rules, states, operations, failures, surfaces, and acceptance while preserving lineage.',{inputFacts:['business-evidence-ready'],outputFacts:['business-model-ready']}),
  linear('business','publish','business.authority-lifecycle','business.publish','architecture.route',['businessModelRef','previousHeadRef','requestedTransitionRef'],'businessHeadRef','Publish one valid immutable business lifecycle transition.','Validate predecessor and transition, write the business worktree head, and emit its hash and status.',{inputFacts:['business-model-ready'],transitions:[t('architecture-required','architecture.decision.frame','ready',['business-head-ready','architecture-analysis-required']),t('direct-plan','architecture.source','ready',['business-head-ready']),t('blocked','business.blocked','blocked',['business-publication-blocked'])],sideEffects:['write and commit only the routed business worktree']}),
  linear('business','reconcile','business.authority-lifecycle','delivery.proved','business.complete',['businessHeadRef','deliveryProofRef','finalSourceHeadsRef'],'reconciliationReceiptRef','Reconcile delivered source with the exact business head.','Verify implemented claims and final source heads, publish implemented or discrepancy lineage, and never rewrite unsupported truth.',{inputFacts:['delivery-proof-ready'],transitions:[t('implemented','business.complete','complete',['business-reconciled']),t('discrepancy','business.blocked','blocked',['business-discrepancy'])],sideEffects:['write and commit only the routed business worktree']}),

  linear('architecture','decision-frame','architecture.decision-analysis','architecture.decision.frame','architecture.decision.current',['businessHeadRef','objectiveRef','constraintEvidenceRefs'],'decisionFrameRef','Freeze the exact cross-system decision and constraint classes.','Separate fixed intent, measurable constraints, preferences, assumptions, and unknowns.',{inputFacts:['architecture-analysis-required'],outputFacts:['architecture-frame-ready']}),
  linear('architecture','current-state','architecture.decision-analysis','architecture.decision.current','architecture.decision.alternatives',['decisionFrameRef','routeReceiptRefs','sourcePartitionRefs'],'currentStateRef','Trace current ownership, flow, failure, and recovery boundaries.','Query routed source partitions, open exact files, and bind every current-state claim to live evidence.',{inputFacts:['architecture-frame-ready'],outputFacts:['architecture-current-state-ready'],sourceRefs:['starci-academy-be']}),
  linear('architecture','alternatives','architecture.decision-analysis','architecture.decision.alternatives','architecture.decision.challenge',['decisionFrameRef','currentStateRef'],'optionSetRef','Create materially viable alternatives under one criteria set.','Compare correctness, ownership, consistency, security, failure recovery, capacity/cost, migration, operability, and testability.',{inputFacts:['architecture-current-state-ready'],outputFacts:['architecture-options-ready']}),
  linear('architecture','decision-challenge','architecture.decision-analysis','architecture.decision.challenge','architecture.decision.handoff',['decisionFrameRef','currentStateRef','optionSetRef'],'challengeReceiptRef','Adversarially test the strongest architecture candidate.','Exercise partial failure, retry, concurrency, stale state, deletion, recovery, dependency outage, and rollback.',{inputFacts:['architecture-options-ready'],transitions:[t('ready','architecture.decision.handoff','ready',['architecture-challenge-ready']),t('revise','architecture.decision.alternatives','ready',['architecture-feedback']),t('blocked','architecture.blocked','blocked',['architecture-decision-blocked'])]}),
  linear('architecture','decision-handoff','architecture.decision-analysis','architecture.decision.handoff','architecture.source',['decisionFrameRef','optionSetRef','challengeReceiptRef','selectedDecisionRef'],'planningContextRef','Freeze the selected decision for role-specific planning.','Emit invariants, risks, affected contracts/data, migration/rollback, proof expectations, and unknowns without files.',{inputFacts:['architecture-challenge-ready'],outputFacts:['architecture-decision-ready']}),
  linear('architecture','source-discovery','be.boundary-planning','architecture.source','architecture.pattern',['businessHeadRef','planningContextRef','routeReceiptRef','sourcePartitionRef'],'sourceReceiptRef','Discover live schema and complete sibling-family evidence.','Use Qdrant to locate candidates, then open exact source, tests, exceptions, modules, and gates at the verified revision.',{inputFacts:['business-head-ready'],outputFacts:['backend-source-ready'],sourceRefs:['starci-academy-be']}),
  linear('architecture','pattern-bind','be.boundary-planning','architecture.pattern','architecture.boundary',['businessHeadRef','planningContextRef','sourceReceiptRef'],'patternBindingRef','Bind every accepted backend fact to fixed pattern situations.','Map situation codes to exact paths and live evidence; unrecognized facts become standards gaps.',{inputFacts:['backend-source-ready'],outputFacts:['backend-patterns-ready']}),
  linear('architecture','boundary-plan','be.boundary-planning','architecture.boundary','architecture.boundary.challenge',['businessHeadRef','planningContextRef','sourceReceiptRef','patternBindingRef'],'boundaryPlanRef','Compile one canonical exact source-and-test boundary.','Name every path, responsibility, dependency, branch, test, gate, exclusion, alternative, and proof before writes.',{inputFacts:['backend-patterns-ready'],outputFacts:['backend-boundary-ready'],sideEffects:['write immutable canonical plan receipt below the run workspace']}),
  linear('architecture','boundary-challenge','be.boundary-planning','architecture.boundary.challenge','architecture.boundary.review',['boundaryPlanRef','sourceReceiptRef','patternBindingRef'],'boundaryChallengeRef','Independently challenge the exact backend revision.','Reopen schema, siblings, bindings, paths, tests, gates, roots, and revision; emit clean, revise, or blocked.',{inputFacts:['backend-boundary-ready'],transitions:[t('clean','architecture.boundary.review','pending',['backend-boundary-challenged']),t('revise','architecture.boundary','ready',['backend-boundary-feedback']),t('blocked','architecture.blocked','blocked',['backend-boundary-blocked'])],sourceRefs:['starci-academy-be']}),

  linear('be','implementation','be.boundary-planning','architecture.boundary.review','quality.format',['approvedBoundaryRef','approvalReceiptRef','businessHeadRef','baselineCommitRef'],'changeReceiptRef','Implement only one approved backend boundary.','Reverify identity and baseline, mirror bound owners, mutate approved paths, and record every before/after hash.',{accepts:[{stage:'architecture.boundary.review',status:'approved',facts:['backend-boundary-approved']},{stage:'be.repair',status:'ready',facts:['backend-boundary-approved','in-boundary-repair']}],outputFacts:['backend-source-written'],sourceRefs:['starci-academy-be'],sideEffects:['write only approved backend product-source paths','write immutable mutation receipt']}),

  ...[
    ['format','quality.format','quality.lint',['changeReceiptRef','formatCommandRef'],'formatReceiptRef','Run the repository check-only formatter.'],
    ['lint','quality.lint','quality.typecheck',['changeReceiptRef','lintCommandRef'],'lintReceiptRef','Run canonical lint with zero errors and zero warnings.'],
    ['typecheck','quality.typecheck','quality.build',['changeReceiptRef','typecheckCommandRef'],'typecheckReceiptRef','Run the declared typecheck entrypoint without source mutation.'],
    ['build','quality.build','quality.unit',['changeReceiptRef','buildCommandRef'],'buildReceiptRef','Build the exact routed role using its declared entrypoint.'],
    ['unit-coverage','quality.unit','quality.integration',['changeReceiptRef','unitCommandRef','coveragePolicyRef'],'unitCoverageReceiptRef','Run real unit tests and produce the sole LCOV/four-metric coverage receipt.'],
    ['integration','quality.integration','quality.e2e',['changeReceiptRef','integrationCommandRef','integrationBoundaryRef'],'integrationReceiptRef','Prove declared connected boundaries without substituting unit or E2E.'],
    ['e2e','quality.e2e','quality.sonar',['changeReceiptRef','e2eCommandRef','seedReceiptRef'],'e2eReceiptRef','Run the real E2E entrypoint with nonzero tests and independent behavioral evidence.'],
    ['sonar','quality.sonar','deployment.intent',['changeReceiptRef','lcovReceiptRef','sonarProjectRef'],'sonarReceiptRef','Run final Sonar analysis and wait for the quality-gate verdict.']
  ].map(([name,inputStage,passStage,inputs,outputRef,purpose], index) => linear('quality',name,'quality.source-gates',inputStage,passStage,inputs,outputRef,purpose,'Execute only this gate, record command/identity/counts/verdict, and never repair source locally.',{inputFacts:index===0?['backend-source-written']:[],transitions:[t('pass',passStage,'ready',[`quality-${name}-pass`]),t('in-boundary','be.repair','ready',['in-boundary-repair']),t('boundary-drift','architecture.boundary','ready',['backend-boundary-feedback']),t('external-blocker','quality.blocked','blocked',['quality-external-blocker'])],sideEffects:['write ignored gate evidence only']})),
  linear('quality','delivery-proof','quality.source-gates','quality.proof','delivery.proved',['changeReceiptRef','gateReceiptSetRef','businessHeadRef'],'sourceDeliveryProofRef','Reconcile the complete source-only delivery fence.','Verify change boundary plus format, lint, typecheck, build, unit coverage, integration, E2E, and Sonar receipts all bind the same revision.',{inputFacts:['quality-sonar-pass'],transitions:[t('pass','delivery.proved','ready',['delivery-proof-ready']),t('blocked','quality.blocked','blocked',['quality-proof-blocked'])]}),

  linear('quality','workflow-diagnose','quality.readiness-repair','quality.diagnose','quality.diagnosed',['skillRef','invocationRef','observedEnvironmentRef'],'diagnosisReceiptRef','Trace another workflow against the real machine without running it.','Name every state, read, observed fact, guard, and exact stop; distinguish environment absence from operator/skill defects.',{transitions:[t('diagnosed','quality.diagnosed','complete',['workflow-diagnosed'])]}),
  linear('quality','readiness-inventory','quality.readiness-repair','quality.inventory','quality.inventory.result',['routeSetRef','declaredGateSetRef','staleRegistryRef'],'inventoryReceiptRef','Execute check-only readiness across routed roles.','Measure route, ports, source gates, indexes, lint machines, formatting, assurance, retired structure, remnants, and debt coverage.',{transitions:[t('green','quality.inventory.result','complete',['readiness-green']),t('findings','quality.inventory.result','ready',['readiness-findings'])]}),
  linear('quality','rule-binding-check','quality.readiness-repair','quality.rule-bindings','quality.rule-bindings.result',['ruleRegistryRef','gateCatalogRef','publishedMachineRef'],'ruleBindingReceiptRef','Prove pattern situations, gates, and published machine identities are accountable.','Reject unknown emitted rules, orphan law, identity drift, and consumer-local substitutions.',{transitions:[t('pass','quality.rule-bindings.result','complete',['rule-bindings-pass']),t('fail','quality.blocked','blocked',['rule-bindings-fail'])]}),
  linear('quality','finding-repair','quality.readiness-repair','quality.repair','quality.repair.result',['approvedFindingRef','baselineRef','ownerBoundaryRef'],'repairReceiptRef','Repair one approved measured finding without weakening enforcement.','Mutate only the finding owner, rerun the exact failed proof, and preserve unrelated work and external custody.',{transitions:[t('repaired','quality.repair.result','complete',['finding-repaired']),t('boundary-drift','quality.blocked','blocked',['repair-boundary-drift'])],sideEffects:['mutate only the approved finding boundary']}),
  linear('quality','debt-repay','quality.readiness-repair','quality.debt','quality.debt.result',['approvedDebtRef','baselineRef','scopeRef'],'debtReceiptRef','Repay one owner-approved scoped debt record.','Work only inside live scope, prove owning gates, update progress, and close only genuinely green evidence.',{transitions:[t('closed','quality.debt.result','complete',['debt-closed']),t('progress','quality.debt.result','ready',['debt-progress']),t('blocked','quality.blocked','blocked',['debt-blocked'])],sideEffects:['mutate approved debt scope and durable debt record']}),

  linear('source','conversation-record','source.provenance','source.conversation.record','source.conversation.recorded',['providerRef','conversationSnapshotRef','artifactRefs','redactionReceiptRef'],'conversationHeadRef','Record one provider-neutral immutable conversation provenance snapshot.','Bind project/role, revision, artifact links, snapshot hash, and redaction proof without committing raw transcript or secret.',{transitions:[t('recorded','source.conversation.recorded','complete',['conversation-recorded'])],sideEffects:['write durable provenance head and rebuildable search cache']}),
  linear('source','conversation-query','source.provenance','source.conversation.query','source.conversation.result',['queryRef','projectRoleRef','provenanceIndexRef'],'conversationQueryReceiptRef','Query conversation provenance without mutating durable heads.','Return matching snapshot/artifact identities and citations from rebuildable cache; never return secret-bearing raw transcript.',{transitions:[t('found','source.conversation.result','complete',['conversation-results']),t('empty','source.conversation.result','complete',['conversation-empty'])]}),

  ...[
    ['block-reconcile',['pageRef','blockRef','sourceContractRef'],'blockReceiptRef','Reconcile one component-impact block inside its complete parent page.'],
    ['maintenance-apply',['feedbackRef','approvedBoundaryRef','baselineRef'],'maintenanceProofRef','Apply approved frontend maintenance to product source and prove the correction first.'],
    ['learning-request',['feedbackProofRef','authorityGapRef'],'learningRequestRef','Record one durable design-learning request after source proof.'],
    ['learning-resolve',['learningRequestRef','sourceProofRef','authorityContextRef'],'learningReceiptRef','Audit the correction and learn it into the smallest Grammar or Principle authority.'],
    ['surface-audit',['surfaceSetRef','businessHeadRef','sourceContextRefs'],'surfaceAuditRef','Audit a closed surface set and classify local drift, systemic gap, consumer drift, or truth mismatch.'],
    ['authority-reconcile',['surfaceAuditRef','approvedAuthorityBoundaryRef'],'authorityReceiptRef','Update the smallest approved Grammar, Principle, pattern, or gate authority.'],
    ['consumer-align',['authorityReceiptRef','approvedConsumerSetRef'],'consumerAlignmentRef','Align every approved consumer to the reconciled authority and prove the real product.']
  ].map(([name,inputs,outputRef,purpose],index)=>linear('fe',name,'fe.design-maintenance',`fe.maintenance.${name}`,index===6?'fe.maintenance.complete':`fe.maintenance.${name}.result`,inputs,outputRef,purpose,'Execute only this maintenance responsibility; preserve source-first proof, rejected attempts, exact authority ownership, and closed consumer scope.',{transitions:[t('complete',index===6?'fe.maintenance.complete':`fe.maintenance.${name}.result`,'complete',[`fe-${name}-complete`]),t('blocked','fe.maintenance.blocked','blocked',[`fe-${name}-blocked`])],sideEffects:name==='maintenance-apply'||name==='consumer-align'?['mutate only approved frontend product-source paths']:name==='learning-request'||name==='learning-resolve'||name==='authority-reconcile'?['write only the approved design request or authority boundary']:[]})),

  linear('platform','tunnel-plan','platform.operations','platform.tunnel.plan','platform.tunnel.apply',['routeReceiptRef','hostnameRef','originRef','ownershipRef'],'tunnelPlanRef','Plan one value-free Cloudflare HTTP tunnel and DNS route.','Resolve exact account/tunnel/hostname/origin, detect conflicts, and never widen to the zone.',{outputFacts:['platform-tunnel-plan-ready']}),
  linear('platform','tunnel-apply','platform.operations','platform.tunnel.apply','platform.tunnel.proved',['tunnelPlanRef','credentialReceiptRef'],'tunnelReceiptRef','Apply one approved tunnel ingress and proxied DNS mapping.','Use the shared helper idempotently, refuse conflicting ownership, and prove public HTTPS.',{inputFacts:['platform-tunnel-plan-ready'],transitions:[t('proved','platform.tunnel.proved','complete',['platform-tunnel-proved']),t('blocked','platform.blocked','blocked',['platform-tunnel-blocked'])],sideEffects:['mutate only the declared Cloudflare tunnel and DNS route']}),
  linear('platform','mcp-config','platform.operations','platform.mcp.config','platform.mcp.index',['routeSetRef','collectionRef','modelRef','credentialRosterRef'],'mcpConfigReceiptRef','Compile value-safe source-context MCP/Qdrant configuration.','Bind selected roles, collection, embedding model, dimensions, read-only policy, and public endpoint without credential values.',{outputFacts:['platform-mcp-config-ready'],sideEffects:['write ignored generated MCP execution config']}),
  linear('platform','source-index','platform.operations','platform.mcp.index','platform.mcp.publish',['mcpConfigReceiptRef','routeSetRef','exclusionPolicyRef'],'sourceIndexReceiptRef','Index routed source partitions into Qdrant.','Chunk only allowed source, preserve repository/revision/virtual paths, exclude secrets/build/cache/generated state, and verify counts.',{inputFacts:['platform-mcp-config-ready'],outputFacts:['platform-source-index-ready'],sideEffects:['replace only declared Qdrant source partitions']}),
  linear('platform','mcp-publish','platform.operations','platform.mcp.publish','platform.mcp.proved',['mcpConfigReceiptRef','sourceIndexReceiptRef','tunnelReceiptRef'],'mcpPublishReceiptRef','Publish the read-only MCP boundary and prove routed search.','Start declared services, verify authenticated transport/read-only behavior, and query each role partition through public HTTPS.',{inputFacts:['platform-source-index-ready'],transitions:[t('proved','platform.mcp.proved','complete',['platform-mcp-proved']),t('blocked','platform.blocked','blocked',['platform-mcp-blocked'])],sideEffects:['reconcile declared MCP/Qdrant runtime services']}),
  linear('platform','sonar-service-reconcile','platform.operations','platform.sonar.reconcile','platform.sonar.proved',['projectSetRef','qualityProfileRef','credentialReceiptRef'],'sonarServiceReceiptRef','Reconcile shared Sonar service and strict project quality gates.','Plan and apply only declared service/project/profile/token projections, then prove analysis and blocking quality-gate behavior.',{transitions:[t('proved','platform.sonar.proved','complete',['platform-sonar-proved']),t('blocked','platform.blocked','blocked',['platform-sonar-blocked'])],sideEffects:['mutate declared Sonar service/project enforcement state']}),
  linear('platform','observability-reconcile','platform.operations','platform.observability.reconcile','platform.observability.proved',['stackRef','metricsDestinationRef','credentialReceiptRef'],'observabilityReceiptRef','Reconcile declared runtime metrics collection and remote write.','Apply cAdvisor/Prometheus/Grafana configuration, protect credentials, and prove bounded target and remote-write health.',{transitions:[t('proved','platform.observability.proved','complete',['platform-observability-proved']),t('blocked','platform.blocked','blocked',['platform-observability-blocked'])],sideEffects:['mutate declared observability stack and provider configuration']}),

  linear('deployment','intent-bind','deployment.lifecycle','deployment.intent','deployment.manifest',['routeReceiptRefs','imperativeRequestRef','deploymentIntentRef'],'deploymentContractRef','Resolve exactly one project, role, environment, topology, and declared release.','Bind explicit request, invocation envelope, then one unambiguous verified manifest; never infer another project or domain.',{inputFacts:['quality-sonar-pass'],outputFacts:['deployment-target-bound']}),
  linear('deployment','manifest-validate','deployment.lifecycle','deployment.manifest','deployment.plan',['deploymentContractRef','manifestRef','routeReceiptRefs'],'manifestReceiptRef','Validate durable deployment intent and ownership.','Validate project/roles, stack root, execution root, host, artifacts, domains/drivers, workflow, probes, credentials-by-reference, and rollback.',{inputFacts:['deployment-target-bound'],outputFacts:['deployment-manifest-valid']}),
  linear('deployment','execution-plan','deployment.lifecycle','deployment.plan','deployment.review',['deploymentContractRef','manifestReceiptRef','observedStateRef'],'executionPlanRef','Compute value-free setup, release, migration, traffic, monitoring, and rollback deltas.','Separate already-declared imperative execution from new host/domain/tenant/project/destructive/rotation approval boundaries.',{inputFacts:['deployment-manifest-valid'],transitions:[t('execute','deployment.execute','ready',['deployment-plan-ready']),t('approval-required','deployment.review','pending',['deployment-approval-required']),t('blocked','deployment.blocked','blocked',['deployment-plan-blocked'])]}),
  linear('deployment','execution-root-init','deployment.lifecycle','deployment.execute','deployment.credentials',['executionPlanRef','manifestReceiptRef','ignoreProofRef'],'executionRootReceiptRef','Initialize disposable ignored execution state.','Prove the whole .infra/<environment> root is ignored before creating value-free plans, SSH state, and monitor observations.',{accepts:[{stage:'deployment.execute',status:'ready',facts:['deployment-plan-ready']},{stage:'deployment.review',status:'approved',facts:['deployment-plan-approved']}],outputFacts:['deployment-execution-root-ready'],sideEffects:['initialize ignored rebuildable .infra execution root']}),
  linear('deployment','credential-resolve','deployment.lifecycle','deployment.credentials','deployment.host',['executionPlanRef','credentialRosterRef','custodyPolicyRef'],'credentialReceiptRef','Resolve required credential names through existing custody.','Prove presence and authorized access without exposing, rotating, logging, or passing values in arguments.',{inputFacts:['deployment-execution-root-ready'],outputFacts:['deployment-credentials-ready']}),
  linear('deployment','host-prepare','deployment.lifecycle','deployment.host','deployment.artifact.build',['executionPlanRef','hostRef','credentialReceiptRef','setupSourceRef'],'hostReceiptRef','Prove and prepare only the declared host/runtime boundary.','Verify host separation, resources, ports, runtime manager, declared setup source, and fresh-connection health.',{inputFacts:['deployment-credentials-ready'],outputFacts:['deployment-host-ready'],sideEffects:['apply only declared idempotent host setup']}),
  linear('deployment','artifact-build','deployment.lifecycle','deployment.artifact.build','deployment.artifact.publish',['executionPlanRef','sourceRevisionRefs','artifactBuildRefs'],'artifactBuildReceiptRef','Build immutable artifacts from declared contexts.','Run declared verification/build inputs and record immutable tag/digest candidates without publication.',{inputFacts:['deployment-host-ready'],outputFacts:['deployment-artifacts-built'],sideEffects:['write ignored build outputs and immutable local artifacts']}),
  linear('deployment','artifact-publish','deployment.lifecycle','deployment.artifact.publish','deployment.migration',['executionPlanRef','artifactBuildReceiptRef','registryRef','credentialReceiptRef'],'artifactPublishReceiptRef','Publish immutable artifacts to the declared registry.','Push exact digests, record registry identities, and refuse mutable-only identity or cross-project registry ownership.',{inputFacts:['deployment-artifacts-built'],outputFacts:['deployment-artifacts-published'],sideEffects:['publish declared immutable artifacts']}),
  linear('deployment','migration','deployment.lifecycle','deployment.migration','deployment.domain',['executionPlanRef','artifactPublishReceiptRef','migrationPlanRef','rollbackPointRef'],'migrationReceiptRef','Apply only declared migration or initialization jobs.','Prove backup/rollback prerequisites, execute the exact job once, and record schema/data identity without destructive inference.',{inputFacts:['deployment-artifacts-published'],transitions:[t('applied','deployment.domain','ready',['deployment-migration-ready']),t('not-applicable','deployment.domain','ready',['deployment-migration-na']),t('rollback','deployment.rollback','ready',['deployment-rollback-required']),t('blocked','deployment.blocked','blocked',['deployment-migration-blocked'])],sideEffects:['apply declared migration or initialization job']}),
  linear('deployment','domain-reconcile','deployment.lifecycle','deployment.domain','deployment.rollout',['executionPlanRef','domainPlanRef','credentialReceiptRef'],'domainReceiptRef','Reconcile each declared hostname through exactly one owner and driver.','Plan then apply only the named Terraform or Cloudflare tunnel route; prove DNS/TLS ownership and refuse zone widening.',{inputFacts:[],outputFacts:['deployment-domain-ready'],sideEffects:['reconcile declared domain and TLS provider state']}),
  linear('deployment','rollout','deployment.lifecycle','deployment.rollout','deployment.monitor',['executionPlanRef','artifactPublishReceiptRef','hostReceiptRef','domainReceiptRef'],'rolloutReceiptRef','Roll out immutable identities through the declared runtime manager.','Apply the declared Compose, Swarm, Kubernetes, or workflow target and record observed artifact/service identity.',{inputFacts:['deployment-artifacts-published','deployment-domain-ready'],outputFacts:['deployment-rollout-ready'],sideEffects:['mutate declared remote runtime and release workflow state']}),
  linear('deployment','monitor','deployment.lifecycle','deployment.monitor','deployment.proof',['executionPlanRef','rolloutReceiptRef','probeSetRef','steadyWindowRef'],'monitorReceiptRef','Observe workflow, host, service, TLS/DNS, and application readiness through the steady window.','Write bounded value-free observations and classify failure to recover, rollback, blocked, or steady.',{inputFacts:['deployment-rollout-ready'],transitions:[t('steady','deployment.proof','ready',['deployment-steady']),t('recover','deployment.recover','ready',['deployment-recovery-required']),t('rollback','deployment.rollback','ready',['deployment-rollback-required']),t('blocked','deployment.blocked','blocked',['deployment-monitor-blocked'])],sideEffects:['write value-free monitor observations below ignored execution root']}),
  linear('deployment','recover','deployment.lifecycle','deployment.recover','deployment.retry',['executionPlanRef','monitorReceiptRef','failureEvidenceRef','ownedBoundaryRef'],'recoveryReceiptRef','Repair the smallest owned recoverable deployment boundary.','Classify source, credential presence, provider, domain, SSH/host, runtime, rollout, or health; repair only the selected boundary and name the retry stage.',{inputFacts:['deployment-recovery-required'],transitions:[t('retry','deployment.retry','ready',['deployment-retry-ready']),t('rollback','deployment.rollback','ready',['deployment-rollback-required']),t('approval-required','deployment.review','pending',['deployment-approval-required']),t('blocked','deployment.blocked','blocked',['deployment-recovery-blocked'])],sideEffects:['mutate only the declared smallest deployment-owned repair boundary']}),
  linear('deployment','rollback','deployment.lifecycle','deployment.rollback','deployment.proof',['executionPlanRef','rollbackPointRef','failureEvidenceRef'],'rollbackReceiptRef','Restore the declared prior artifact/runtime/domain identity without unapproved data loss.','Apply the exact rollback mechanism, preserve migration/data rules, and prove remote/public rollback state.',{inputFacts:['deployment-rollback-required'],transitions:[t('rolled-back','deployment.proof','ready',['deployment-rolled-back']),t('blocked','deployment.blocked','blocked',['deployment-rollback-blocked'])],sideEffects:['apply declared rollback to provider and runtime state']}),
  linear('deployment','proof','deployment.lifecycle','deployment.proof','delivery.proved',['deploymentContractRef','executionPlanRef','artifactPublishReceiptRef','rolloutOrRollbackReceiptRef','monitorReceiptRef'],'deliveryProofRef','Reconcile routes, immutable artifacts, provider changes, runtime identity, probes, credentials hygiene, and rollback identity.','Require current receipts for every applicable deployment stage and emit complete only after public steady state or proved rollback.',{inputFacts:[],transitions:[t('complete','delivery.proved','ready',['delivery-proof-ready']),t('blocked','deployment.blocked','blocked',['deployment-proof-blocked'])]})
];

const scalar = (name) => [name, { type: 'string', minLength: 1 }];
const statePairs = (items) => [...new Set(items.map((item) => `${item.stage}\0${item.status}`))].map((pair) => pair.split('\0'));
const writeJson = (file, value) => writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);

for (const operator of operators) {
  const directory = path.join(root, operator.domain, operator.name);
  mkdirSync(directory, { recursive: true });
  const title = `${operator.domain}/${operator.name}`;
  const accepts = operator.accepts.map((item) => ({ stage: item.stage, status: item.status, allFacts: item.facts, noneFacts: [] }));
  const emits = operator.transitions.map((item) => ({ stage: item.stage, status: item.status, factsAdd: item.factsAdd, factsRemove: [] }));
  const inputPairs = statePairs(operator.accepts);
  const outputPairs = statePairs(operator.transitions);
  const envelope = (pairs, payload) => ({
    $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', additionalProperties: false,
    required: ['schemaVersion','runId','stage','status','facts','payload'],
    allOf: [{ oneOf: pairs.map(([stage,status]) => ({ properties: { stage: { const: stage }, status: { const: status } }, required: ['stage','status'] })) }],
    properties: {
      schemaVersion: { const: 6 }, runId: { type: 'string', minLength: 1 },
      stage: { enum: [...new Set(pairs.map(([stage]) => stage))] }, status: { enum: [...new Set(pairs.map(([,status]) => status))] },
      facts: { type: 'array', uniqueItems: true, items: { type: 'string', minLength: 1 } }, payload
    }
  });
  const inputPayload = { type: 'object', additionalProperties: false, required: operator.inputs, properties: Object.fromEntries(operator.inputs.map(scalar)) };
  const outputPayload = { type: 'object', additionalProperties: false, required: [operator.outputRef,'decision','evidenceRefs','findings'], properties: {
    [operator.outputRef]: { type: 'string', minLength: 1 }, decision: { enum: operator.transitions.map((item) => item.decision) },
    evidenceRefs: { type: 'array', minItems: 1, uniqueItems: true, items: { type: 'string', minLength: 1 } },
    findings: { type: 'array', uniqueItems: true, items: { type: 'string', minLength: 1 } }
  } };
  writeJson(path.join(directory,'input.schema.json'), { $id: `https://starci.dev/v6/operators/${title}/input.schema.json`, title: `${title} operator input`, ...envelope(inputPairs,inputPayload) });
  writeJson(path.join(directory,'output.schema.json'), { $id: `https://starci.dev/v6/operators/${title}/output.schema.json`, title: `${title} operator output`, ...envelope(outputPairs,outputPayload) });
  writeJson(path.join(directory,'operator.json'), { schemaVersion: 6, id: title, domain: operator.domain, inputSchema: 'input.schema.json', outputSchema: 'output.schema.json', knowledgeRefs: [operator.knowledge], sourceReferenceRefs: operator.sourceRefs, accepts, emits, sideEffects: operator.sideEffects, stopConditions: operator.stops });
  writeFileSync(path.join(directory,'input.md'), `# ${title} input\n\n${operator.purpose}\n\nAccept only the declared state and exact artifact references: ${operator.inputs.map((item)=>`\`${item}\``).join(', ')}. Validate before knowledge retrieval or side effects.\n`);
  writeFileSync(path.join(directory,'output.md'), `# ${title} output\n\nReturn \`${operator.outputRef}\`, one typed decision (${operator.transitions.map((item)=>`\`${item.decision}\``).join(', ')}), evidence references, and findings. The skill state machine—not this operator—routes the emitted state.\n`);
  const loads = `| \`@${operator.knowledge.replaceAll('.','-')}\` | \`${operator.knowledge}\` | qdrant | retrieve only the law needed by this operator |` + (operator.sourceRefs.length ? `\n| \`@source-context\` | \`/<role>/<project>/\` | source-qdrant | locate candidates, then open exact checkout files |` : '');
  writeFileSync(path.join(directory,'execute.md'), `# Execute ${title}\n\n1. Validate input and freeze its artifact identities.\n2. Retrieve \`${operator.knowledge}\` from Qdrant; do not load unrelated knowledge.\n3. ${operator.action}\n4. Write only declared receipts/side effects, validate output, and return control to the skill state machine.\n\n## LOADS\n\n| Alias | Target | Kind | Why |\n| --- | --- | --- | --- |\n${loads}\n\nStop when ${operator.stops.join('; ')}.\n`);
  const transitions = JSON.stringify(Object.fromEntries(operator.transitions.map((item)=>[item.decision,[item.stage,item.status]])));
  const inputGuards = JSON.stringify(operator.accepts.map((item)=>({stage:item.stage,status:item.status,facts:item.facts})));
  writeFileSync(path.join(directory,'validate-input.mjs'), `import { validatorFor, runValidatorCli } from '../../validation.mjs';\nconst guards=${inputGuards};\nexport const validateInput=validatorFor(new URL('./input.schema.json',import.meta.url),(value)=>{const guard=guards.find((item)=>item.stage===value.stage&&item.status===value.status);if(!guard)return ['$: undeclared input state'];return guard.facts.filter((fact)=>!value.facts.includes(fact)).map((fact)=>\`$.facts: missing \${fact}\`);});\nif(process.argv[1]?.endsWith('validate-input.mjs')) await runValidatorCli(validateInput,'node validate-input.mjs <artifact.json>');\n`);
  writeFileSync(path.join(directory,'validate-output.mjs'), `import { validatorFor, runValidatorCli } from '../../validation.mjs';\nconst transitions=${transitions};\nexport const validateOutput=validatorFor(new URL('./output.schema.json',import.meta.url),(value)=>{const expected=transitions[value.payload.decision];const errors=[];if(!expected||value.stage!==expected[0]||value.status!==expected[1])errors.push('$: decision does not match emitted state');if(value.status==='ready'&&value.payload.evidenceRefs.length===0)errors.push('$.payload.evidenceRefs: ready output requires evidence');return errors;});\nif(process.argv[1]?.endsWith('validate-output.mjs')) await runValidatorCli(validateOutput,'node validate-output.mjs <artifact.json>');\n`);
}

console.log(`materialized ${operators.length} atomic operators`);
