export { catalogEntities, catalogMigrations } from "./persistence/connection"
export type { ProductLookup, ProductView } from "./catalog.contracts"
export { InjectCatalogService } from "./catalog.decorators"
export { CatalogModule } from "./catalog.module"
export { CatalogService } from "./catalog.service"
