---
title: Files-media
---

# Files-media

## LOADS

None.

## Record

The input is an accepted file or media capability: upload, download, preview, attachment, avatar,
video, export or generated asset. This module decides how bytes, metadata, ownership, transfer
authority and cleanup are represented in backend source. It does not reopen whether the product
needs media. It makes that accepted shape safe to store and move.

## Law

Bytes and their application meaning are different things. Bytes belong in a storage provider or
streaming boundary; metadata belongs in the application database; the database stores an opaque
reference, never a pretend copy of the bytes. A declared MIME type is a hint, not proof. A storage
key is generated by the service inside a tenant namespace, never copied from a user filename. A
download is a short-lived capability with an explicit scope, not a public bucket or an unbounded
proxy. Every successful write has a lifecycle owner and every failed or abandoned write has an
idempotent path to cleanup.

The boundaries are deliberate. `transport` chooses the upload/download door and response syntax;
`data-access` owns metadata persistence and transactions; `naming` governs symbols and paths, not
provider keys; `exception-identity` gives failures stable wire identity; `maintainability` judges
separation and duplication; `testing` proves byte, ownership, capability and lifecycle stories.
This module decides the media-specific relationship among those layers and never substitutes for
their ruling.

**This is binding, not advisory.** Every operation that accepts, stores, publishes, downloads,
replaces or deletes a file resolves to each matching `MEDIA-*` situation. “It is only an avatar”
does not exempt it: the small upload is still untrusted bytes, tenant-owned state and a resource
that can become orphaned.

## Situation codes

| Code | Situation | What the source must look like |
|---|---|---|
| `MEDIA-1` | Bytes and application metadata are being placed | Bytes travel through a storage adapter/stream; a database record stores metadata and an opaque provider key, never a binary blob in an entity or API object |
| `MEDIA-2` | An upload's size, MIME and content are being trusted | Size is bounded before unbounded buffering; declared type is checked against detected content and an allowlist; rejected content never becomes a trusted media record |
| `MEDIA-3` | A provider key and tenant owner are being assigned | The service generates an opaque, non-user-controlled key under a tenant namespace and checks tenant/resource ownership on every read, write and delete |
| `MEDIA-4` | A caller needs to transfer bytes | A short-lived, purpose-scoped signed capability is issued by the backend or storage adapter; it is not a permanent public URL or a reusable broad credential |
| `MEDIA-5` | Media can be abandoned, replaced or deleted | Metadata state and provider objects have an explicit lifecycle, with idempotent finalization, deletion and reconciliation for orphaned objects |

## Reading an accepted shape

1. Identify where bytes first enter and leave, where media metadata is queried, and which tenant or
   resource owns it. Do not infer these from a filename or a transport verb.
2. Separate the byte path from the metadata path. Decide whether the operation streams, stages or
   directly transfers bytes, and record the provider reference that the database will retain.
3. Validate size and content before assigning trusted media state. A client MIME header, extension or
   TypeScript type is not content evidence.
4. Generate the storage key and check ownership before any provider operation. A key is an address,
   not an authorization decision.
5. Issue the narrowest transfer capability and name its expiry and purpose. A preview, download and
   upload completion are different capabilities even when they address the same object.
6. Map all successful, failed, retried and abandoned paths to lifecycle states and cleanup evidence.
7. Apply every matching code independently. An upload can satisfy `MEDIA-1` while violating
   `MEDIA-2`, and a correct signed URL under `MEDIA-4` can still point at an orphan under `MEDIA-5`.

## `MEDIA-1` — bytes and metadata have separate homes

**Situation.** A feature needs to retain a file and answer application questions about it: owner,
size, detected type, checksum, status, provider and key. The byte stream and those questions have
different lifecycles and scaling characteristics.

**What it emits in source.** A storage port/adapter accepts a stream or provider transfer request;
an entity or record stores metadata plus an opaque provider key/reference. API DTOs expose a media
identifier and approved metadata, never a database blob or provider client object. Metadata may be
created in a transaction, while byte transfer is coordinated through an explicit pending/finalized
state.

**Boundary.** Not `DATA-*`: data access decides the manager, entity and transaction mechanics; this
code decides that the entity is metadata-only. Not `TRANSPORT`: a multipart resolver or download
route is the door, not the storage home. Not `MAINTAIN-*`: moving a blob out of an entity is a media
boundary even if duplication also exists.

## `MEDIA-2` — size, declared type and detected content agree

**Situation.** A client or provider supplies bytes plus a filename and MIME declaration. Each can be
forged, truncated or inconsistent; accepting the declaration alone can turn a script, archive bomb
or oversized payload into trusted media.

**What it emits in source.** The boundary enforces a configured maximum while streaming or before a
bounded buffer is allocated, checks an allowlist of detected media types, and compares detected
content with the declared type where the contract requires it. Extension and client MIME are
metadata, not authority. Invalid, mismatched or over-limit input exits through the validation and
exception contracts before a final media record is published.

**Boundary.** Not `VALIDATE-*` in general: validation owns the common input contract, while this code
adds byte-level limits and content sniffing. Not `TRANSPORT`: a route can limit request size but
cannot prove the content. Not `EXCEPTION-IDENTITY`: exception identity names the refusal; it does
not decide when bytes are unsafe. `PERF-4` may add memory/time budgets, but `MEDIA-2` decides the
content safety rule.

## `MEDIA-3` — keys are opaque and ownership is checked

**Situation.** The service must choose a provider key and decide whether an actor may use the media.
User filenames contain path separators, collisions and sensitive information; a key that merely
looks tenant-scoped does not grant access.

**What it emits in source.** A server-side key generator creates a non-guessable key with an
explicit tenant/resource namespace. The metadata record carries the owning tenant and resource
identity. Every fetch, replacement and deletion resolves ownership from trusted context and checks
it before constructing a provider request. Original filename is separate display metadata and is
never concatenated into a provider path.

**Boundary.** Not `NAMING-*`: naming selects source vocabulary; this code protects provider address
and ownership. Not `AUTHORIZATION-*`: authorization decides actor entitlement; this code ensures the
media operation cannot bypass it by presenting a key. Not `DATA-*`: data access persists the owner,
while this code requires the owner to participate in every media path.

## `MEDIA-4` — transfer authority is short-lived and scoped

**Situation.** A client needs to upload or download bytes without exposing storage credentials or
forcing the application to proxy every large transfer.

**What it emits in source.** The backend checks ownership and purpose, then issues a signed URL or
equivalent capability with a short expiry, one object/key, one method and the required content
constraints. Completion is verified against the pending record; the capability itself is never
treated as proof that application state is finalized. Public ACLs, permanent URLs and account-wide
provider credentials in a request are forbidden.

**Boundary.** Not `TRANSPORT`: transport exposes the endpoint that mints or consumes the capability;
this code defines its scope and lifetime. Not `AUTHORIZATION`: entitlement is checked before minting,
then the capability constrains the provider transfer. Not `EXCEPTION-IDENTITY`: an expired or
invalid capability needs a stable failure code, but status/message are not the capability.

## `MEDIA-5` — every object has a lifecycle owner

**Situation.** A transfer can fail after provider creation, a client can abandon a pending upload,
or replacement can leave an old object behind. A database row alone cannot clean provider bytes.

**What it emits in source.** Media metadata has explicit pending/ready/deleting/deleted or equivalent
states. Finalization is idempotent and verifies the object before marking ready. Replacement and
deletion record the old key for deletion, while a scheduled reconciler lists only the declared
tenant/prefix scope and removes objects with no live metadata after a safety window. Retries are
safe; cleanup failure is observable and does not silently erase the metadata audit trail.

**Boundary.** Not `DATA-4`: a metadata transaction can make the record atomic, but provider deletion
is an external side effect and needs an outbox/reconciler story. Not `MAINTAIN-*`: lifecycle states
express ownership of external resources, not a refactoring preference. `TESTING-*` proves crash,
retry and orphan cases; it does not define the lifecycle.

## Layer held

| Code | Tier | Held by |
|---|---|---|
| `MEDIA-1` | `documented` | Storage/data-flow review; blob placement and metadata ownership cross provider and database boundaries |
| `MEDIA-2` | `documented` | Boundary and byte-fixture tests; content safety depends on configured limits and provider/parser behavior |
| `MEDIA-3` | `documented` | Authorization/data-flow review plus tenant isolation tests; a single-file AST cannot prove ownership |
| `MEDIA-4` | `documented` | Capability contract tests and provider configuration review |
| `MEDIA-5` | `documented` | Lifecycle integration/reconciliation tests; crash and retry behavior is not visible in one file |

## Inputs

| Input | Evidence required |
|---|---|
| byte path | Stream, staging area, provider adapter and maximum transfer size |
| metadata | Fields stored in the database, checksum/type source and public projection |
| ownership | Tenant/resource identity and the authorization decision for each operation |
| capability | Method, key, purpose, constraints, expiry and completion verification |
| lifecycle | Pending, ready, replacement, delete, retry and orphan-reconciliation paths |
| failures | Stable validation, authorization, provider and cleanup identities |

## Rules

1. Store bytes in the provider and metadata in the database; never use an entity as a blob cache.
2. Bound size before unbounded buffering and validate detected content, not only extension or header.
3. Generate opaque tenant-scoped keys; never use a user filename as a provider address.
4. Check ownership before provider access and before issuing any transfer capability.
5. Make signed capabilities short-lived, single-purpose and constrained to the intended object.
6. Model pending/finalized/deleted state and make finalization, deletion and reconciliation idempotent.
7. Keep transport, data access, naming, exception identity, maintainability and testing in their own
   modules; compose their decisions instead of duplicating them here.
8. Every file/media operation resolves every applicable situation; size or internal status is not an exemption.

## Exceptions

- **Small inline assets.** A genuinely bounded, immutable asset may be embedded in a package or
  configuration when its deployment lifecycle is the product contract. It still satisfies `MEDIA-2`
  and must not be confused with tenant-owned runtime media.
- **Application proxy.** A route may stream bytes through the application for a named audit, virus
  scanning or range requirement. It still uses `MEDIA-3`, `MEDIA-4` and bounded resource budgets;
  proxying is not permission to expose a provider credential.
- **Provider-reported type.** A trusted provider scan can supply detected type only when its
  provenance and failure behavior are recorded; a client declaration remains non-authoritative.
- **Immediate deletion.** A synchronous delete is valid for a provider with transactional semantics;
  otherwise `MEDIA-5` requires a retryable tombstone or reconciler.

## Stops

Stop before source exists when the byte home and metadata home are unspecified, the maximum size or
detected-type authority is missing, ownership cannot be named, a capability has no purpose/expiry,
or there is no answer for provider failure and orphan cleanup. Stop when a proposed proof is only a
filename extension, a public URL, a database row, or a happy-path upload test.

## Proof

| Code | Minimum proof |
|---|---|
| `MEDIA-1` | Integration test proves the database stores metadata/reference while bytes remain in the provider; API projection contains no blob |
| `MEDIA-2` | Fixture tests reject oversized, mismatched, malformed and disallowed content before finalization |
| `MEDIA-3` | Tenant-isolation tests prove another tenant/key/filename cannot read, replace or delete the object |
| `MEDIA-4` | Contract test proves method/key/purpose/expiry constraints and rejects expired, replayed or broad capabilities |
| `MEDIA-5` | Failure/retry/reconciliation test proves no permanent orphan and idempotent delete/finalize behavior |

## Output

```text
bytes:      <provider/stream/staging path>
metadata:   <database record and public projection>
owner:      <tenant/resource identity and check>
capability: <method, key, purpose, constraints and expiry>
lifecycle:  <pending/ready/delete/reconcile states>
situation:  <MEDIA-1 | MEDIA-2 | MEDIA-3 | MEDIA-4 | MEDIA-5>
verdict:    <holds | violates | stop>
reason:     <byte, validation, ownership, capability or lifecycle fact>
proof:      <test or provider evidence>
```

## Scope

This pattern governs runtime file and media byte placement, content safety, tenant ownership,
transfer capabilities and provider-object lifecycle. It does not choose transport routes, database
handles or transaction syntax, source naming, exception wire identity, generic refactoring shape or
test-lane mechanics; those remain `transport`, `data-access`, `naming`, `exception-identity`,
`maintainability` and `testing` respectively.
