// walk-records.mjs - the minimal lawful Work records the stand-in ops of the walk write (validated with `starci runtime validate`): the feature of the authentication product.
export const FEATURE_RECORDS = {
  "br/sign-in/index.yaml": "schema: work/business-rule@1\nid: br.identity.sign-in\ntitle: A person signs in with an email and a password\nstate: todo\nstatements:\n  - A sign-in succeeds only when the pair is known.\n  - A failed sign-in says only that the pair is wrong, never which half.\nauthorityRefs:\n  - \"owner-intent: A person must be able to sign in.\"\nacceptance:\n  - id: ac.identity.sign-in.known-pair-issues-a-session-token\n    given: A registered email and its password\n    when: The pair is submitted to sign-in\n    then:\n      - One live session answers with an opaque token.\n",
  "fr/sign-in/index.yaml": "schema: work/functional-requirement@1\nid: fr.identity.sign-in\ntitle: Sign in\nstate: todo\nactors: [person]\ntrigger: The person submits an email and a password.\nmainFlow:\n  - A live session is issued and returned as an opaque bearer token.\nexceptionFlows:\n  - A wrong pair is refused without naming which half was wrong.\npostconditions:\n  - The token verifies for as long as its TTL lives.\n",
  "sds/session-flow/index.yaml": "schema: work/sds-component@1\nid: sds.identity.session-flow\ntitle: Account and session across sign-up and sign-in\nstate: todo\nresponsibility: >-\n  Holds the account store and the live session: a registration creates an account, a sign-in verifies the pair and\n  issues an opaque session token that other services verify over HTTP.\ninterfaces:\n  - Only the identity HTTP transport writes the account and session tables.\nowners:\n  - {role: module, path: be/src/modules/domain}\nrefs: [br.identity.sign-in, fr.identity.sign-in, contract.identity.session]\ndependsOn: [integration.identity.mail]\nstateMachine:\n  states: [anonymous, signed-in]\n  initial: anonymous\n  terminal: [signed-in]\n  transitions:\n    - id: t-sign-in\n      from: anonymous\n      to: signed-in\n      on: pair-accepted\n      guard: The email and password form a known pair.\n",
  "contract/session/index.yaml": "schema: work/contract@1\nid: contract.identity.session\ntitle: How a caller verifies a session token with the identity service\nstate: todo\nbetween:\n  provider: identity\n  consumer: web\nowner: identity\nsurface:\n  - name: verifySession\n    shape: GET /session -> {person, expiresAt}\n    transport: Plain HTTP/JSON with the bearer token in the Authorization header.\n    guarantee: A live token answers 200 with the person; any other token answers a typed 401.\n    stability: Adding fields to the answer is not breaking; removing one is.\nguarantees:\n  - a 200 means the token is live at that instant.\nconsumerObligations:\n  - the web app treats any non-200 answer as signed out.\nrefs: [fr.identity.sign-in]\nrequiresProof:\n  provider:\n    required: true\n    note: The provider proves a live token verifies and a dead one is refused.\n  consumer:\n    required: true\n    note: The consumer proves it signs the person out on a refusal.\nchange:\n  rev: 1\n  kind: initial\n  at: 2026-10-09T10:00:00.000Z\n  reason: The first contract of the identity service.\n",
  "integration/mail/index.yaml": "schema: work/integration@1\nid: integration.identity.mail\ntitle: A mail provider delivers the sign-up confirmation\nstate: todo\nprovider: mailer\nboundary: The mail provider sends the confirmation message of a registration.\nendpoints:\n  - {name: send, method: POST, path: /v1/send}\ncredential:\n  name: MAILER_API_KEY\n  providedBy: owner\n  custody: identity:mailer-api-key\nsandbox: The provider offers a sandbox key that records messages without delivering them.\nrefs: [fr.identity.sign-in]\nrequiresProof:\n  live:\n    required: true\n    note: A message sent through the real provider sandbox and read back.\nchange:\n  rev: 1\n  kind: initial\n  at: 2026-10-09T10:00:00.000Z\n  reason: The first integration of the identity service.\n",
};

/** The records of the families `families`, as {path under the feature: text}. */
export const recordsOf = (families) => Object.fromEntries(Object.entries(FEATURE_RECORDS).filter(([rel]) => families.includes(rel.split('/')[0])));
