/**
 * The rules that read the project graph: the findings of the architecture machine that sit on a TypeScript file.
 *
 * One graph per lint run: `scripts/hfs/project-graph.mjs` (a byte copy in this package's runtime/) builds the machine's module
 * graph and slot manifest once for the repository, caches it, and each rule below reports the findings of its own codes on
 * the file ESLint is visiting, on the line the machine names. There is no second graph and no second judge: the list of
 * rules and their codes is `LINT_ENFORCERS` of the machine (scripts/hfs/architecture/surface.mjs); `hfs check` keeps the
 * findings that have no TypeScript file to sit on. A graph that cannot be built stops the run with the machine's message.
 */
import { belongsTo, codeOf, LINT_ENFORCERS } from "./runtime/scripts/hfs/architecture/surface.mjs"
import { projectGraph } from "./runtime/scripts/hfs/project-graph.mjs"
import { projectRule } from "./runtime/scripts/hfs/project-rule.mjs"
import { posixPath } from "./runtime/scripts/lib/path-key.mjs"
import { hfsOf } from "./lib/hfs.mjs"
import fs from "node:fs"
import { createRequire } from "node:module"
import path, { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const RUNTIME = join(dirname(fileURLToPath(import.meta.url)), "runtime")
const mine = LINT_ENFORCERS.filter((enforcer) => enforcer.plugins.includes("be"))
const typescript = createRequire(import.meta.url)("typescript")
const supabaseTablesCache = new Map()

/** A TypeScript property name in generated database types. */
const propertyName = (name) => typescript.isIdentifier(name) || typescript.isStringLiteralLike(name) ? name.text : null

/** The members of a named property whose value is an object type literal. */
const objectPropertyMembers = (members, name) => {
    const property = members.find((member) => typescript.isPropertySignature(member) && propertyName(member.name) === name)
    return property?.type && typescript.isTypeLiteralNode(property.type) ? property.type.members : null
}

/**
 * The `Database['public']['Tables']` keys generated by Supabase, cached once for each app root.
 * An absent or unreadable generated contract proves no table, so the existing sql-owner finding remains.
 */
const supabaseTablesOf = (repoRoot) => {
    const appRoot = path.dirname(repoRoot)
    if (supabaseTablesCache.has(appRoot)) return supabaseTablesCache.get(appRoot)
    const result = new Set()
    const file = path.join(appRoot, "supabase", "types", "database.types.ts")
    if (fs.existsSync(file)) {
        const source = typescript.createSourceFile(file, fs.readFileSync(file, "utf8"), typescript.ScriptTarget.Latest, true, typescript.ScriptKind.TS)
        const database = source.statements.find((statement) => typescript.isTypeAliasDeclaration(statement) && statement.name.text === "Database")
        const databaseMembers = database && typescript.isTypeLiteralNode(database.type) ? database.type.members : null
        const publicMembers = databaseMembers ? objectPropertyMembers(databaseMembers, "public") : null
        const tableMembers = publicMembers ? objectPropertyMembers(publicMembers, "Tables") : null
        if (tableMembers) for (const member of tableMembers) {
            if (!typescript.isPropertySignature(member)) continue
            const name = propertyName(member.name)
            if (name) result.add(name.toLowerCase())
        }
    }
    supabaseTablesCache.set(appRoot, result)
    return result
}

/** Whether generated Supabase types replace the missing-TypeORM-entity proof for this finding. */
const provenBySupabase = (hfs, finding) => hfs.ruleParams.schemaAuthority === "supabase"
    && typeof finding.table === "string"
    && finding.message.includes("which no @Entity declares")
    && supabaseTablesOf(hfs.repoRoot).has(finding.table.toLowerCase())

/** One project-graph-backed lint rule, with the edition-specific SQL ownership proof at report time. */
const sqlOwnerRule = (enforcer) => ({
    meta: { type: "problem", docs: { description: enforcer.description }, schema: [], messages: { finding: "{{message}}" } },
    create(context) {
        const hfs = hfsOf(context)
        const rel = posixPath(path.relative(hfs.repoRoot, context.filename))
        if (rel.startsWith("..")) return {}
        const { byFile } = projectGraph({ repoRoot: hfs.repoRoot, runtimeRoot: RUNTIME, injectedTypeScript: context.settings?.starci?.injectedTypeScript?.() })
        const findings = (byFile.get(rel) ?? []).filter((finding) => belongsTo(enforcer, finding) && !provenBySupabase(hfs, finding))
        return {
            Program(node) {
                for (const finding of findings) {
                    const line = Number.isInteger(finding.line) && finding.line >= 1 ? finding.line : 1
                    const column = Number.isInteger(finding.column) && finding.column >= 1 ? finding.column - 1 : 0
                    context.report({ node, loc: { start: { line, column } }, messageId: "finding", data: { message: `[${codeOf(finding)}] ${finding.message}` } })
                }
            },
        }
    },
})

/** The rules this law contributes to the plugin: one per graph enforcer of this profile. */
export const rules = Object.fromEntries(mine.map((enforcer) => [
    enforcer.id,
    enforcer.id === "sql-owner" ? sqlOwnerRule(enforcer) : projectRule({ enforcer, runtimeRoot: RUNTIME, hfsOf }),
]))

/** Every one at error. */
export const recommended = Object.fromEntries(mine.map((e) => [`starci-be/${e.id}`, "error"]))
