// hfs sync: render, verify and write the files an app cannot `extends`.
//
// An app is one repository: its root holds the one package.json (all dependencies, all scripts), the lockfile, the hfs.json of
// kind app, CI, the hooks, the formatter and Sonar configuration and .starciwork; its sides be/ and fe/ hold each side's tool
// configuration. The managed set is read from the slot manifest (knowledge/hfs/slots.yaml): every slot that names `managedBy`
// lists, in its `path`, the whole files sync renders, and `managedBy` names the template directory they are rendered from:
// templates/<scope or common>/<managedBy>/<file path with each leading dot dropped>, the scope being app for a root slot and the
// side (be, fe) for a side slot, whose files land under that side's folder. Two targets are not whole files of a managedBy slot
// and are listed in this module: the marked block of the root .gitignore, and .starciwork/.gitignore, which lives inside the
// .starciwork directory slot. Every file is rendered with the app's hfs.json (both sides and their apps) and, for the Sonar
// exclusions and the one coverage scope (sonar.coverage.exclusions, its complement, and the codecov.yml paths alike), the jest
// preset the app installs for its be side. `--check` compares the sha256 of the rendered content with the
// file on disk and fails on any drift; `--write` rewrites the drifted files. `.gitignore` is the one shared file: only the marked
// block is managed and the app's own lines around it are left alone. The root package.json is managed by its `scripts` block
// only (mode scripts, compared as parsed JSON): the rest of the file (dependencies, npm workspaces of fe/packages/*) is the app's.
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { braceVariants } from '../runtime/scripts/lib/glob.mjs';
import { APP_SCOPE, SIDES, loadSlotManifest, resolveRepoDeclaration } from '../runtime/scripts/lib/hfs-slots.mjs';
import { readDeclaredSonarKey } from './sonar-key.mjs';

export const TEMPLATES_DIR = path.join(import.meta.dirname, '..', 'templates');
export const NODE_MAJOR = 22;
/** The scopes a target is rendered for: the app root, then each side. */
export const SCOPES = Object.freeze([APP_SCOPE, ...SIDES]);
export const BLOCK_BEGIN = '# >>> hfs sync (managed block; do not edit) >>>';
export const BLOCK_END = '# <<< hfs sync <<<';
const HEADER = scope => `# Generated by hfs sync (${scope === APP_SCOPE ? 'app root' : `${scope} side`}). Do not edit: run "npx hfs sync --write".`;

export class SyncError extends Error {
  constructor(code, message) {
    super(`${code}: ${message}`);
    this.code = code;
  }
}

// mode: file = whole file, block = the marked block inside a file the app also writes to, scripts = the `scripts` block of
// package.json. A template that can hold a comment opens with {{header}}; a file whose exact content is specified (JSON, the
// eslint one-liner) has no header.
const MODE_OF_GROUP = Object.freeze({ 'package-scripts': 'scripts' });
const LITERAL_FILE = /^[^*?<>{}[\]]+[^/*?<>{}[\]]$/;

/** The targets no managedBy slot lists as a whole file (see the header of this module); both belong to the app root. */
export const UNLISTED_TARGETS = Object.freeze([
  { path: '.gitignore', template: 'app/gitignore', mode: 'block' },
  { path: '.starciwork/.gitignore', template: 'app/starciwork.gitignore', mode: 'file' },
].map(Object.freeze));

const templateName = (scope, group, file) => `${scope}/${group}/${file.split('/').map(segment => segment.replace(/^\./, '')).join('/')}`;
const onSide = (scope, file) => (scope === APP_SCOPE ? file : `${scope}/${file}`);

/**
 * Every target of `scope` (app, be or fe), its path relative to that scope's folder: the files the manifest's managedBy slots
 * list, then (app root) the unlisted ones. A slot that names managedBy lists literal files only, and each has a template under
 * its scope or under common.
 */
export function targetsOf(scope, { manifest = loadSlotManifest(), hasTemplate = name => fs.existsSync(path.join(TEMPLATES_DIR, name)) } = {}) {
  const listed = [];
  for (const slot of manifest.slots) {
    if (slot.managedBy === undefined || !slot.profiles.includes(scope)) continue;
    for (const file of braceVariants(slot.path)) {
      if (!LITERAL_FILE.test(file)) throw new SyncError('HFS_SYNC_MANIFEST_MANAGED', `slot ${slot.id} names managedBy but its path ${slot.path} is not a list of literal files (${file})`);
      const template = [scope, 'common'].map(dir => templateName(dir, slot.managedBy, file)).find(hasTemplate);
      if (!template) throw new SyncError('HFS_SYNC_TEMPLATE_MISSING', `slot ${slot.id} manages ${file} for ${scope}, but templates/{${scope},common}/${slot.managedBy} has no template for it`);
      listed.push({ path: file, template, mode: MODE_OF_GROUP[slot.managedBy] ?? 'file', slot: slot.id });
    }
  }
  return [...listed, ...(scope === APP_SCOPE ? UNLISTED_TARGETS.map(target => ({ ...target })) : [])];
}

const lf = text => text.replace(/\r\n/g, '\n');
export const hashOf = text => createHash('sha256').update(lf(text)).digest('hex');

/**
 * The hfs.json sync reads: an app declaration valid for the manifest it pins (both sides, their apps, connections, optional slots,
 * reads). Sync never renders configs for a declaration the eslint canons and hfs check would refuse, so a pin bump cannot leave
 * lint unable to start. Answers the resolved app.
 */
export function validateHfs(hfs, manifest = loadSlotManifest()) {
  try {
    return resolveRepoDeclaration(manifest, hfs);
  } catch (error) {
    throw new SyncError('HFS_SYNC_HFS_INVALID', `hfs.json is not a valid app declaration for manifest ${manifest.version}: ${error.message}`);
  }
}

function readBundled(name) {
  return lf(fs.readFileSync(path.join(TEMPLATES_DIR, name), 'utf8'));
}

/** Fill `{{name}}` from vars and expand `{{> partial}}` lines. An unknown name is an error, never an empty string. */
export function render(text, vars, readTemplate = readBundled) {
  const withPartials = text.replace(/^\{\{> ([\w./-]+)\}\}\n/gm, (_, name) => render(readTemplate(name), vars, readTemplate).replace(/\n*$/, '\n'));
  return withPartials.replace(/\{\{([A-Za-z]\w*)\}\}/g, (_, key) => {
    if (!Object.hasOwn(vars, key)) throw new SyncError('HFS_SYNC_TEMPLATE_VARIABLE', `template names {{${key}}}, which sync does not provide`);
    return vars[key];
  });
}

/**
 * What the app's sync reads from the jest preset it installs for its be side: the Sonar exclusions and the coverage sources
 * (`COVERAGE_SOURCES`, the globs jest collects coverage from): { sonarExclusions, coverageSources }.
 */
export async function loadPresets(root) {
  const name = '@starci/jest-preset';
  const require = createRequire(path.join(root, 'package.json'));
  let resolved;
  try {
    resolved = require.resolve(name);
  } catch {
    throw new SyncError('HFS_SYNC_PRESET_MISSING', `${name} is not installed under ${root}; set it to the exact version in knowledge/hfs/canon-pins.yaml and reinstall`);
  }
  const preset = require(resolved);
  return { sonarExclusions: preset.sonarExclusions(), coverageSources: [...preset.COVERAGE_SOURCES] };
}

/** Where the be unit run writes the lcov report (jest `coverageDirectory` coverage under be/, reporter lcov), from the app root. */
export const LCOV_REPORT = 'be/coverage/lcov.info';

/**
 * THE coverage scope of an app, from the app root: the preset's coverage sources on the be side (`be/src/**` + `/*.service.ts`).
 * It is the one source of the codecov.yml status paths and, through coverageExclusions, of Sonar's coverage scope, so the two
 * can never drift; fe/ is outside it (a front end has no tests).
 */
export function coverageScope(presets) {
  const sources = presets?.coverageSources;
  if (!Array.isArray(sources) || !sources.length) throw new SyncError('HFS_SYNC_PRESET_MISSING', '@starci/jest-preset gives no COVERAGE_SOURCES: the coverage scope cannot be rendered');
  return sources.map(glob => `be/${glob}`);
}

const COVERED_SUFFIX = /\*\.([a-z][a-z0-9-]*)\.ts$/;
const asGlob = (text) => String(text).replace(/<[^>]+>/g, '*');

/**
 * Sonar's coverage scope of an app as `sonar.coverage.exclusions` globs: the COMPLEMENT of coverageScope. SonarQube has no
 * coverage inclusions and its globs have no negation, so every executable file that is not a coverage source is excluded:
 *   - every be source role of the slot manifest's closed suffix vocabulary (ruleParams.be.suffixes, R89) other than the
 *     roles the coverage sources name (`service`), as `be/**` + `/*.<role>.ts`;
 *   - every be file name outside that vocabulary a be slot declares (`main.ts`, `index.ts`, `connection.ts`, the migrations,
 *     the test world's files, dto/ and kit/ files), as `be/<slot path>/<name>` with each `<placeholder>` a `*`;
 *   - all of fe/ (a front end has no tests).
 * The result is sorted and has no duplicate. A coverage source that is not `<dir>/**` + `/*.<role>.ts` is refused: its
 * complement cannot be written in Sonar's globs.
 */
export function coverageExclusions(presets, manifest = loadSlotManifest()) {
  const covered = new Set(coverageScope(presets).map(glob => {
    const role = COVERED_SUFFIX.exec(glob)?.[1];
    if (!role) throw new SyncError('HFS_SYNC_COVERAGE_SCOPE', `coverage source ${glob} is not <dir>/**/*.<role>.ts: Sonar's coverage exclusions cannot express its complement`);
    return role;
  }));
  const suffixes = manifest.ruleParams?.be?.suffixes ?? [];
  const isRole = new RegExp(`\\.(?:${suffixes.map(s => s.replace(/[-]/g, '\\-')).join('|')})\\.ts$`);
  const globs = new Set(suffixes.filter(role => !covered.has(role)).map(role => `be/**/*.${role}.ts`));
  for (const slot of manifest.slots) {
    if (!slot.profiles.includes('be') || slot.presence === 'forbidden') continue;
    for (const entry of [...(slot.requires ?? []), ...(slot.allows ?? [])]) {
      if (!/\.ts$/.test(entry) || entry.includes('<role>')) continue;
      for (const name of braceVariants(entry)) {
        if (isRole.test(asGlob(name).replace(/\*/g, 'x'))) continue;
        for (const dir of braceVariants(slot.path)) globs.add(`be/${asGlob(dir)}${asGlob(name)}`.replace(/\/\/+/g, '/'));
      }
    }
  }
  globs.add('fe/**');
  return [...globs].sort();
}

/**
 * The script lines the apps add to the root package.json, each ending with a comma (the template puts them mid-object). Every
 * script runs a side from the app root: a be script from be/ (`cd be && ...`, the folder its tsconfig and jest configuration
 * are relative to), an fe script from fe/. be: `dev:be` runs the one api app from source and restarts it on change (`dev:be:<app>`
 * each, with several), `start:<app>` runs a built api, worker or cli app, `migrate` the migrate app (`migrate:<app>` with several).
 * fe: `dev:fe` runs the one Next app in development (`dev:fe:<app>` each, with several), `start:<app>` serves a built one.
 */
export function appScripts(app) {
  const line = (name, command) => `${JSON.stringify(name)}: ${JSON.stringify(command)},`;
  const be = app.sides.be.apps;
  const fe = app.sides.fe.apps;
  const apis = be.filter(entry => entry.kind === 'api');
  const migrates = be.filter(entry => entry.kind === 'migrate');
  const watch = entry => `cd be && ts-node-dev --respawn -r tsconfig-paths/register apps/${entry.name}/src/main.ts`;
  return [
    ...(apis.length === 1 ? [line('dev:be', watch(apis[0]))] : apis.map(entry => line(`dev:be:${entry.name}`, watch(entry)))),
    ...(fe.length === 1 ? [line('dev:fe', `npm run codegen --silent && cd fe && next dev apps/${fe[0].name}`)] : fe.map(entry => line(`dev:fe:${entry.name}`, `npm run codegen --silent && cd fe && next dev apps/${entry.name}`))),
    ...be.map(entry => line(entry.kind === 'migrate' ? (migrates.length === 1 ? 'migrate' : `migrate:${entry.name}`) : `start:${entry.name}`, `node be/dist/apps/${entry.name}/src/main.js`)),
    ...fe.map(entry => line(`start:${entry.name}`, `cd fe && next start apps/${entry.name}`)),
  ].join('\n    ');
}

/** True when the fe side opts into a workspace package (repo.packages or any fe.package.* slot): the sources then include fe/packages/. */
export const opensPackages = side => (side.optionalSlots ?? []).some(id => id === 'repo.packages' || String(id).startsWith('fe.package.'));

/** The stylesheets of the fe side the CSS canon judges, relative to fe/: every app and every workspace package (slot fe.route, fe.package.*). */
export const STYLE_GLOB = '{apps,packages}/*/src/**/*.css';

/** Every value a template of `scope` can name, derived from hfs.json and the presets. */
export function variables(app, scope, presets, sonarKey, manifest = loadSlotManifest()) {
  const fe = app.sides.fe;
  const packages = opensPackages(fe);
  const feApps = fe.apps.map(entry => `fe/apps/${entry.name}`);
  const feTsconfigs = [...feApps.map(dir => `${dir}/tsconfig.json`), ...(packages ? ['fe/packages/*/tsconfig.json'] : [])];
  return {
    header: HEADER(scope),
    appScripts: appScripts(app),
    buildFe: ['npm run codegen --silent', ...(packages ? ['npm run build --workspaces --if-present'] : []), `cd fe && ${fe.apps.map(entry => `next build apps/${entry.name}`).join(' && ')}`].join(' && '),
    // The fe apps import the workspace packages from their dist/, so the packages are built before the apps are type-checked.
    typecheck: ['npm run codegen --silent', 'tsc -p be/tsconfig.json', ...(packages ? ['npm run build --workspaces --if-present'] : []), ...feTsconfigs.filter(file => !file.includes('*')).map(file => `tsc -p ${file} --noEmit`), ...(packages ? ['npm run typecheck --workspaces --if-present'] : [])].join(' && '),
    nodeMajor: String(NODE_MAJOR),
    sonarKey: sonarKey ?? app.project,
    sonarExclusions: [presets?.sonarExclusions, '**/.next/**', '**/node_modules/**', '**/src/messages/**'].filter(Boolean).join(','),
    sonarSources: ['be/apps', 'be/src', 'fe/apps', ...(packages ? ['fe/packages'] : [])].join(','),
    lcovReport: LCOV_REPORT,
    coverageExclusions: scope === APP_SCOPE ? coverageExclusions(presets, manifest).join(',') : '',
    codecovPaths: scope === APP_SCOPE ? coverageScope(presets).map(glob => `          - ${JSON.stringify(glob)}`).join('\n') : '',
    tsconfigPaths: ['be/tsconfig.json', ...feTsconfigs].join(','),
    styleGlob: STYLE_GLOB,
  };
}

// The scripts of a package.json as one comparable text: a line per script, sorted by name (order is not drift).
const scriptsText = scripts => `${Object.keys(scripts).sort().map(name => `${name}: ${typeof scripts[name] === 'string' ? scripts[name] : JSON.stringify(scripts[name])}`).join('\n')}\n`;

function parseScripts(text) {
  try {
    const { scripts } = JSON.parse(text);
    return scripts && typeof scripts === 'object' && !Array.isArray(scripts) ? scripts : null;
  } catch {
    return null;
  }
}

/**
 * The managed content of every target of the app: [{ path, mode, content, hash, scope }], paths app-relative (a side's targets under
 * its folder); a scripts target also carries `scripts`, the parsed block. `sonarKey` is the key the be side's stack declaration
 * names; without one the key is the project.
 */
export function renderTargets(hfs, presets, { sonarKey, readTemplate = readBundled, manifest = loadSlotManifest() } = {}) {
  const app = validateHfs(hfs, manifest);
  const hasTemplate = name => { try { return readTemplate(name) !== undefined; } catch { return false; } };
  return SCOPES.flatMap(scope => {
    const vars = variables(app, scope, presets, sonarKey, manifest);
    return targetsOf(scope, { manifest, hasTemplate }).map(target => {
      const body = render(readTemplate(target.template), vars, readTemplate);
      const where = onSide(scope, target.path);
      if (target.mode === 'scripts') {
        const scripts = parseScripts(body);
        if (!scripts) throw new SyncError('HFS_SYNC_TEMPLATE_VARIABLE', `the rendered ${target.template} has no scripts object`);
        const content = scriptsText(scripts);
        return { path: where, scope, mode: 'scripts', content, hash: hashOf(content), scripts };
      }
      const managed = target.mode === 'block' ? `${BLOCK_BEGIN}\n${body.replace(/\n*$/, '\n')}${BLOCK_END}\n` : body;
      return { path: where, scope, mode: target.mode, content: managed, hash: hashOf(managed) };
    });
  });
}

// The part of a file sync manages: all of it, the marked block, or the scripts block as text.
function managedPart(mode, text) {
  if (mode === 'file') return text;
  if (mode === 'scripts') {
    const scripts = parseScripts(text);
    return scripts ? scriptsText(scripts) : null;
  }
  const start = text.indexOf(BLOCK_BEGIN);
  const end = text.indexOf(BLOCK_END);
  if (start < 0 || end < start) return null;
  const stop = text.indexOf('\n', end);
  return text.slice(start, stop < 0 ? text.length : stop + 1);
}

function firstDifference(expected, actual) {
  const want = expected.split('\n'), have = actual.split('\n');
  for (let index = 0; index < Math.max(want.length, have.length); index += 1) {
    if (want[index] !== have[index]) return { line: index + 1, expected: want[index] ?? '(end of file)', actual: have[index] ?? '(end of file)' };
  }
  return null;
}

/** Compare every rendered target with the disk: [{ path, status: ok | missing | drift, expectedHash, actualHash?, difference? }]. */
export function checkTargets(root, targets) {
  return targets.map(target => {
    const file = path.join(root, target.path);
    if (!fs.existsSync(file)) return { path: target.path, status: 'missing', expectedHash: target.hash };
    const part = managedPart(target.mode, lf(fs.readFileSync(file, 'utf8')));
    if (part === null) return { path: target.path, status: 'missing', expectedHash: target.hash };
    const actualHash = hashOf(part);
    if (actualHash === target.hash) return { path: target.path, status: 'ok', expectedHash: target.hash, actualHash };
    return { path: target.path, status: 'drift', expectedHash: target.hash, actualHash, difference: firstDifference(target.content, part) };
  });
}

/** Rewrite the missing or drifted targets; returns the paths written. */
export function writeTargets(root, targets) {
  const written = [];
  for (const result of checkTargets(root, targets)) {
    if (result.status === 'ok') continue;
    const target = targets.find(candidate => candidate.path === result.path);
    const file = path.join(root, target.path);
    const existing = fs.existsSync(file) ? lf(fs.readFileSync(file, 'utf8')) : '';
    let next = target.content;
    if (target.mode === 'scripts') {
      let pkg = {};
      if (existing) {
        try { pkg = JSON.parse(existing); } catch { throw new SyncError('HFS_SYNC_HFS_INVALID', `${target.path} is not valid JSON; fix it by hand before sync can set its scripts`); }
      }
      next = `${JSON.stringify({ ...pkg, scripts: target.scripts }, null, 2)}\n`;
    } else if (target.mode === 'block' && existing) {
      const current = managedPart('block', existing);
      next = current === null ? `${target.content}\n${existing}` : existing.replace(current, () => target.content);
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, next);
    written.push(target.path);
  }
  return written;
}

/** The hfs.json object of the app at `root` (validated), or a SyncError. */
export function loadHfs(root) {
  const file = path.join(root, 'hfs.json');
  if (!fs.existsSync(file)) throw new SyncError('HFS_SYNC_HFS_INVALID', `${file} does not exist; hfs sync runs at the app root`);
  let hfs;
  try {
    hfs = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (error) {
    throw new SyncError('HFS_SYNC_HFS_INVALID', `${file} is not valid JSON: ${error.message}`);
  }
  validateHfs(hfs);
  return hfs;
}

/** The rendered targets of the app at `root`: its hfs.json, the Sonar key the be side's stack declaration names, the presets it installs. */
export async function renderRepo(root, { presets, parseYaml } = {}) {
  const hfs = loadHfs(root);
  const sonarKey = await readDeclaredSonarKey(root, { parseYaml, fail: message => { throw new SyncError('HFS_SYNC_SONAR_KEY', message); } });
  return { hfs, targets: renderTargets(hfs, presets ?? await loadPresets(root), { sonarKey }) };
}

/** `hfs sync --check | --write [--root <dir>]` at the app root; returns the exit code (0 clean, 1 drift or error, 2 usage). */
export async function runSync(argv, { cwd = process.cwd(), out = line => process.stdout.write(`${line}\n`), presets, parseYaml } = {}) {
  const check = argv.includes('--check'), write = argv.includes('--write');
  const rootAt = argv.indexOf('--root');
  if ([check, write].filter(Boolean).length !== 1) {
    out('usage: hfs sync (--check | --write) [--root <dir>]');
    return 2;
  }
  const root = rootAt >= 0 ? path.resolve(cwd, argv[rootAt + 1] ?? '') : cwd;
  try {
    const { targets } = await renderRepo(root, { presets, parseYaml });
    if (write) {
      const written = writeTargets(root, targets);
      for (const file of written) out(`wrote ${file}`);
      out(`hfs sync: ${written.length} written, ${targets.length - written.length} already in sync`);
      return 0;
    }
    const results = checkTargets(root, targets);
    const bad = results.filter(item => item.status !== 'ok');
    for (const result of bad) {
      const found = result.actualHash ? `, found ${result.actualHash.slice(0, 12)}` : '';
      const where = result.difference ? ` (line ${result.difference.line}: expected ${JSON.stringify(result.difference.expected)}, found ${JSON.stringify(result.difference.actual)})` : '';
      out(`HFS_SYNC_DRIFT ${result.path}: ${result.status}, expected sha256 ${result.expectedHash.slice(0, 12)}${found}${where}`);
    }
    out(`hfs sync --check: ${results.length - bad.length} of ${results.length} in sync${bad.length ? '; run "npx hfs sync --write"' : ''}`);
    return bad.length ? 1 : 0;
  } catch (error) {
    if (!(error instanceof SyncError)) throw error;
    out(error.message);
    return 1;
  }
}
