// hfs sync: render, verify and write the files a product repository cannot `extends`.
//
// The generated set (target table below) is husky, both GitHub workflows, .gitignore, sonar-project.properties,
// codecov.yml and, for a back end, .starciwork/.gitignore. Every file is rendered from templates/ with the
// repository's hfs.json (profile and apps) and, for the coverage denominators, the same jest/vitest preset the
// repository installs. `--check` compares the sha256 of the rendered content with the file on disk and fails on any
// drift; `--write` rewrites the drifted files. `.gitignore` is the one shared file: only the marked block is managed
// and the repository's own lines around it are left alone.
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { readDeclaredSonarKey } from './sonar-key.mjs';

export const TEMPLATES_DIR = path.join(import.meta.dirname, '..', 'templates');
export const NODE_MAJOR = 22;
export const PROFILES = Object.freeze(['be', 'fe']);
export const BLOCK_BEGIN = '# >>> hfs sync (managed block; do not edit) >>>';
export const BLOCK_END = '# <<< hfs sync <<<';
const HEADER = profile => `# Generated by hfs sync (profile ${profile}). Do not edit: run "npx hfs sync --write".\n`;

export class SyncError extends Error {
  constructor(code, message) {
    super(`${code}: ${message}`);
    this.code = code;
  }
}

// mode: file = whole file, block = the marked block inside a file the repository also writes to.
// header: whether the generated-by comment leads the content (.starciwork/.gitignore is byte-exact instead).
export const TARGETS = Object.freeze([
  { path: '.husky/pre-commit', template: { be: 'be/pre-commit', fe: 'fe/pre-commit' }, mode: 'file', header: true },
  { path: '.husky/pre-push', template: { be: 'common/pre-push', fe: 'common/pre-push' }, mode: 'file', header: true },
  { path: '.github/workflows/ci.yml', template: { be: 'common/ci.yml', fe: 'common/ci.yml' }, mode: 'file', header: true },
  { path: '.github/workflows/e2e.yml', template: { be: 'be/e2e.yml', fe: 'fe/e2e.yml' }, mode: 'file', header: true },
  { path: '.gitignore', template: { be: 'be/gitignore', fe: 'fe/gitignore' }, mode: 'block', header: false },
  { path: 'sonar-project.properties', template: { be: 'be/sonar-project.properties', fe: 'fe/sonar-project.properties' }, mode: 'file', header: true },
  { path: 'codecov.yml', template: { be: 'common/codecov.yml', fe: 'common/codecov.yml' }, mode: 'file', header: true },
  { path: '.starciwork/.gitignore', template: { be: 'be/starciwork.gitignore' }, mode: 'file', header: false },
].map(Object.freeze));

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const lf = text => text.replace(/\r\n/g, '\n');
export const hashOf = text => createHash('sha256').update(lf(text)).digest('hex');

/** The hfs.json shape sync reads: hfs 2, profile, project and a non-empty apps list. */
export function validateHfs(hfs) {
  const bad = message => { throw new SyncError('HFS_SYNC_HFS_INVALID', message); };
  if (!hfs || typeof hfs !== 'object') bad('hfs.json is not an object');
  if (hfs.hfs !== 2) bad('hfs must be 2');
  if (!PROFILES.includes(hfs.profile)) bad(`profile must be one of ${PROFILES.join(', ')}`);
  if (typeof hfs.project !== 'string' || !KEBAB.test(hfs.project)) bad('project must be a kebab-case name');
  if (!Array.isArray(hfs.apps) || hfs.apps.length === 0) bad('apps must list at least one app');
  if (hfs.stacks !== undefined) {
    if (hfs.profile !== 'fe') bad('stacks is a front-end field: a back-end repository owns its own .starcistacks declaration');
    if (typeof hfs.stacks !== 'string' || !hfs.stacks || path.isAbsolute(hfs.stacks)) bad('stacks must be a relative path to the sibling back-end repository that owns .starcistacks');
  }
  const seen = new Set();
  for (const app of hfs.apps) {
    if (!app || typeof app.name !== 'string' || !KEBAB.test(app.name)) bad('every app needs a kebab-case name');
    if (seen.has(app.name)) bad(`app ${app.name} is listed twice`);
    seen.add(app.name);
  }
  return hfs;
}

function readBundled(name) {
  return lf(fs.readFileSync(path.join(TEMPLATES_DIR, name), 'utf8'));
}

/** Fill `{{name}}` from vars and expand `{{> partial}}` lines. An unknown name is an error, never an empty string. */
export function render(text, vars, readTemplate = readBundled) {
  const withPartials = text.replace(/^\{\{> ([\w./-]+)\}\}\n/gm, (_, name) => render(readTemplate(name), vars, readTemplate).replace(/\n*$/, '\n'));
  return withPartials.replace(/\{\{([A-Za-z]\w*)\}\}/g, (_, key) => {
    if (!Object.hasOwn(vars, key)) throw new SyncError('HFS_SYNC_TEMPLATE_VARIABLE', `template names {{${key}}}, which sync does not provide`);
    return vars[key];
  });
}

/** Coverage denominators from the preset the repository installs: { sonarExclusions, sonarCoverageExclusions }. */
export async function loadPresets(root, profile) {
  const name = profile === 'be' ? '@starci/jest-preset' : '@starci/vitest-preset';
  const require = createRequire(path.join(root, 'package.json'));
  let resolved;
  try {
    resolved = require.resolve(name);
  } catch {
    throw new SyncError('HFS_SYNC_PRESET_MISSING', `${name} is not installed under ${root}; set it to the exact version in knowledge/hfs/canon-pins.yaml and reinstall`);
  }
  const preset = profile === 'be' ? require(resolved) : await import(pathToFileURL(resolved).href);
  return { sonarExclusions: preset.sonarExclusions(), sonarCoverageExclusions: preset.sonarCoverageExclusions() };
}

/** Every value a template can name, derived from hfs.json and the presets. */
export function variables(hfs, presets, sonarKey) {
  const globs = [...presets.sonarExclusions.split(','), ...presets.sonarCoverageExclusions.split(',')];
  return {
    profile: hfs.profile,
    nodeMajor: String(NODE_MAJOR),
    sonarKey: sonarKey ?? `${hfs.project}-${hfs.profile === 'be' ? 'backend' : 'fe'}`,
    sonarExclusions: presets.sonarExclusions,
    sonarCoverageExclusions: presets.sonarCoverageExclusions,
    codecovIgnore: globs.map(glob => JSON.stringify(glob)).join('\n  - '),
    tsconfigPaths: hfs.apps.map(app => `apps/${app.name}/tsconfig.json`).join(','),
  };
}

/** The managed content of every target this profile owns: [{ path, mode, content, hash }]. */
/** `sonarKey` is the key the repository's stack declaration names; without one the key is derived from hfs.json. */
export function renderTargets(hfs, presets, { sonarKey, readTemplate = readBundled } = {}) {
  validateHfs(hfs);
  const vars = variables(hfs, presets, sonarKey);
  return TARGETS.filter(target => target.template[hfs.profile]).map(target => {
    const body = render(readTemplate(target.template[hfs.profile]), vars, readTemplate);
    const content = target.header ? HEADER(hfs.profile) + body : body;
    const managed = target.mode === 'block' ? `${BLOCK_BEGIN}\n${content.replace(/\n*$/, '\n')}${BLOCK_END}\n` : content;
    return { path: target.path, mode: target.mode, content: managed, hash: hashOf(managed) };
  });
}

// The part of a file sync manages: all of it, or the marked block.
function managedPart(mode, text) {
  if (mode === 'file') return text;
  const start = text.indexOf(BLOCK_BEGIN);
  const end = text.indexOf(BLOCK_END);
  if (start < 0 || end < start) return null;
  const stop = text.indexOf('\n', end);
  return text.slice(start, stop < 0 ? text.length : stop + 1);
}

function firstDifference(expected, actual) {
  const want = expected.split('\n'), have = actual.split('\n');
  for (let index = 0; index < Math.max(want.length, have.length); index += 1) {
    if (want[index] !== have[index]) return { line: index + 1, expected: want[index] ?? '(end of file)', actual: have[index] ?? '(end of file)' };
  }
  return null;
}

/** Compare every rendered target with the disk: [{ path, status: ok | missing | drift, expectedHash, actualHash?, difference? }]. */
export function checkTargets(root, targets) {
  return targets.map(target => {
    const file = path.join(root, target.path);
    if (!fs.existsSync(file)) return { path: target.path, status: 'missing', expectedHash: target.hash };
    const part = managedPart(target.mode, lf(fs.readFileSync(file, 'utf8')));
    if (part === null) return { path: target.path, status: 'missing', expectedHash: target.hash };
    const actualHash = hashOf(part);
    if (actualHash === target.hash) return { path: target.path, status: 'ok', expectedHash: target.hash, actualHash };
    return { path: target.path, status: 'drift', expectedHash: target.hash, actualHash, difference: firstDifference(target.content, part) };
  });
}

/** Rewrite the missing or drifted targets; returns the paths written. */
export function writeTargets(root, targets) {
  const written = [];
  for (const result of checkTargets(root, targets)) {
    if (result.status === 'ok') continue;
    const target = targets.find(candidate => candidate.path === result.path);
    const file = path.join(root, target.path);
    const existing = fs.existsSync(file) ? lf(fs.readFileSync(file, 'utf8')) : '';
    let next = target.content;
    if (target.mode === 'block' && existing) {
      const current = managedPart('block', existing);
      next = current === null ? `${target.content}\n${existing}` : existing.replace(current, () => target.content);
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, next);
    written.push(target.path);
  }
  return written;
}

export function loadHfs(root) {
  const file = path.join(root, 'hfs.json');
  if (!fs.existsSync(file)) throw new SyncError('HFS_SYNC_HFS_INVALID', `${file} does not exist`);
  try {
    return validateHfs(JSON.parse(fs.readFileSync(file, 'utf8')));
  } catch (error) {
    if (error instanceof SyncError) throw error;
    throw new SyncError('HFS_SYNC_HFS_INVALID', `${file} is not valid JSON: ${error.message}`);
  }
}

/** `hfs sync --check | --write [--root <dir>]`; returns the exit code (0 clean, 1 drift or error, 2 usage). */
export async function runSync(argv, { cwd = process.cwd(), out = line => process.stdout.write(`${line}\n`), presets, parseYaml } = {}) {
  const check = argv.includes('--check'), write = argv.includes('--write'), init = argv.includes('--init');
  const rootAt = argv.indexOf('--root');
  if ([check, write, init].filter(Boolean).length !== 1) {
    out('usage: hfs sync (--check | --write | --init) [--root <dir>]');
    return 2;
  }
  const root = rootAt >= 0 ? path.resolve(cwd, argv[rootAt + 1] ?? '') : cwd;
  try {
    const hfs = loadHfs(root);
    if (init) {
      const { initSkeleton } = await import('./skeleton.mjs');
      const { created, skipped } = initSkeleton(root, hfs);
      for (const file of created) out(`created ${file}`);
      out(`hfs sync --init: ${created.length} created, ${skipped.length} already exist and were left alone`);
      return 0;
    }
    const sonarKey = await readDeclaredSonarKey(root, { parseYaml, stacks: hfs.stacks, fail: message => { throw new SyncError('HFS_SYNC_SONAR_KEY', message); } });
    const targets = renderTargets(hfs, presets ?? await loadPresets(root, hfs.profile), { sonarKey });
    if (write) {
      const written = writeTargets(root, targets);
      for (const file of written) out(`wrote ${file}`);
      out(`hfs sync: ${written.length} written, ${targets.length - written.length} already in sync`);
      return 0;
    }
    const results = checkTargets(root, targets);
    const bad = results.filter(item => item.status !== 'ok');
    for (const result of bad) {
      const found = result.actualHash ? `, found ${result.actualHash.slice(0, 12)}` : '';
      const where = result.difference ? ` (line ${result.difference.line}: expected ${JSON.stringify(result.difference.expected)}, found ${JSON.stringify(result.difference.actual)})` : '';
      out(`HFS_SYNC_DRIFT ${result.path}: ${result.status}, expected sha256 ${result.expectedHash.slice(0, 12)}${found}${where}`);
    }
    out(`hfs sync --check: ${results.length - bad.length} of ${results.length} in sync${bad.length ? '; run "npx hfs sync --write"' : ''}`);
    return bad.length ? 1 : 0;
  } catch (error) {
    if (!(error instanceof SyncError)) throw error;
    out(error.message);
    return 1;
  }
}
