/* Lane v5-5 codemod plan: ui.audit.privacy (components/audit/privacy). */
module.exports = [
    {
        file: "src/components/audit/privacy/component.tsx",
        ops: [
            ["sub", "const { state, refusal, exportRefusal } = props", "const copy = props.copy\n    const { state, refusal, exportRefusal } = props", 1, "copy binding"],
            ["sub", "<Text weight=\"semibold\">Todo app</Text>", "<Text weight=\"semibold\">{copy.brand}</Text>", 2, "shell.brand"],
            ["sub", "<DestinationNav />", "<DestinationNav copy={copy} />", 1, "shell plumbing"],
            ["sub", "<AccountPresence onSignOut={props.onSignOut} />", "<AccountPresence copy={copy} onSignOut={props.onSignOut} />", 1, "shell plumbing"],
            ["sub", "<Text>Alex</Text>", "<Text>{copy.accountName}</Text>", 1, "shell.accountName"],
            ["line", "Sign out", "{copy.signOut}", 1, "shell.signOut"],
            ["sub", "key={destination.label}", "key={destination.key}", 1, "destination keys"],
            ["sub", "isCurrent={destination.label === \"Privacy\"}", "isCurrent={destination.href === CURRENT_DESTINATION_HREF}", 1, "current by route"],
            ["sub", "{destination.label}", "{copy.destinations[destination.key]}", 1, "shell.destinations.*"],
            ["sub", "compactNavigationLabel=\"Primary\"", "compactNavigationLabel={copy.navLabel}", 1, "shell.navPrimary"],
            ["sub", "<div aria-label=\"The privacy screen - request erasure, export data\" className={PRIMARY_COLUMN_CLASS_NAME} role=\"main\">", "<div aria-label={copy.mainLabel} className={PRIMARY_COLUMN_CLASS_NAME} role=\"main\">", 1, "privacy.mainLabel"],
            ["sub", "<nav aria-label=\"Breadcrumb\">", "<nav aria-label={copy.breadcrumbLabel}>", 1, "shell.breadcrumb"],
            ["line", "Settings / Privacy", "{copy.breadcrumb}", 1, "privacy.breadcrumb"],
            ["sub", "<Heading level={1} scale=\"display\">Privacy and your data</Heading>", "<Heading level={1} scale=\"display\">{copy.heading}</Heading>", 1, "privacy.heading"],
            ["sub", "<Text tone=\"muted\">Manage the data linked to your account.</Text>", "<Text tone=\"muted\">{copy.tagline}</Text>", 1, "privacy.tagline"],
            ["sub", "<SurfaceCard ariaLabel=\"Privacy\" composition=\"joined\" frame=\"frameless\">", "<SurfaceCard ariaLabel={copy.cardLabel} composition=\"joined\" frame=\"frameless\">", 1, "privacy.cardLabel"],
            ["sub", "<section aria-label=\"Export your data\" className={FACE_CLASS_NAME}>", "<section aria-label={copy.exportHeading} className={FACE_CLASS_NAME}>", 1, "privacy.exportHeading"],
            ["sub", "<Heading level={2}>Export your data</Heading>", "<Heading level={2}>{copy.exportHeading}</Heading>", 1, "privacy.exportHeading"],
            ["sub", "<Text tone=\"muted\">Get a copy of your personal activity records.</Text>", "<Text tone=\"muted\">{copy.exportTagline}</Text>", 1, "privacy.exportTagline"],
            ["sub", "{state === \"exporting\" ? \"Exporting\u2026\" : \"Export my data\"}", "{state === \"exporting\" ? copy.exporting : copy.exportAction}", 1, "privacy.exporting / exportAction"],
            ["sub", "<section aria-label=\"Request erasure\" className={FACE_CLASS_NAME}>", "<section aria-label={copy.erasureHeading} className={FACE_CLASS_NAME}>", 1, "privacy.erasureHeading"],
            ["sub", "<Heading level={2}>Request erasure</Heading>", "<Heading level={2}>{copy.erasureHeading}</Heading>", 1, "privacy.erasureHeading"],
            ["line", "Remove information that identifies you from the activity log. This cannot be undone", "{copy.erasureTagline}", 1, "privacy.erasureTagline"],
            ["delline", "once completed.", "", 1, "privacy.erasureTagline (continuation)"],
            ["line", "Confirm erasure", "{copy.erasureConfirm}", 1, "privacy.erasureConfirm"],
            ["line", "Cancel", "{copy.erasureCancel}", 1, "privacy.erasureCancel"],
            ["line", "Your erasure request is complete. Information that identifies you has been removed", "{copy.erasureComplete}", 1, "privacy.erasureComplete"],
            ["delline", "from the activity log.", "", 1, "privacy.erasureComplete (continuation)"],
            ["line", "Submitting your erasure request\u2026", "{copy.erasurePending}", 1, "privacy.erasurePending"],
            ["line", "Request erasure", "{copy.erasureAction}", 1, "privacy.erasureAction"],
            ["sub", "href={BACK_TO_TASKS.href}", "href=\"/tasks\"", 1, "tasks route"],
            ["sub", "{BACK_TO_TASKS.label}", "{copy.backToTasks}", 1, "shell.backToTasks"],
            ["sub", "key={link.label}", "key={link.key}", 1, "footer keys"],
            ["sub", "{link.label}", "{copy.legal[link.key]}", 1, "shell.legal.*"],
        ],
    },
    {
        file: "src/components/audit/privacy/index.tsx",
        ops: [
            ["sub", "setExportRefusal(\"You need to sign in again before your data can be exported.\")", "setExportRefusal(t(\"exportSessionEnded\"))", 1, "privacy.exportSessionEnded"],
            ["sub", "setExportRefusal(EXPORT_REFUSAL_MESSAGE)", "setExportRefusal(t(\"exportRefusal\"))", 1, "privacy.exportRefusal"],
            ["sub", "setRefusal(SIGN_IN_AGAIN_MESSAGE)", "setRefusal(t(\"erasureSessionEnded\"))", 1, "privacy.erasureSessionEnded"],
            ["sub", "? SIGN_IN_AGAIN_MESSAGE : ERASURE_REFUSAL_MESSAGE", "? t(\"erasureSessionEnded\") : t(\"erasureRefusal\")", 1, "privacy.erasureSessionEnded / erasureRefusal"],
            ["delline", "const SIGN_IN_AGAIN_MESSAGE = \"You need to sign in again before your erasure request can be submitted.\"", "", 1, "retire const"],
            ["delline", "const ERASURE_REFUSAL_MESSAGE = \"We couldn't submit your erasure request. Try again.\"", "", 1, "retire const"],
            ["delline", "const EXPORT_REFUSAL_MESSAGE = \"We couldn't prepare your export. Try again.\"", "", 1, "retire const"],
        ],
    },
]
